### ISSUE TITLE
Oly Tissue Sample Master sheet

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#100]
Sheet needs attention

https://docs.google.com/spreadsheets/d/1tPvult9e0vqd5sPOTlcQqLXTfIv987rivsQVZj8DGgE/edit#gid=0

New columns - clean up 

and accompanying 'readme' or metadata

**Comment by sr320** [comment]
@jheare What is status on this?

**Comment by jheare** [comment]
The sample spreadsheet has been updated. There is an accompanying readme for this file that can be found [here](https://github.com/jheare/Resilience-Project/blob/master/tissue-sample-description.md).

**Comment by sr320** [comment]
Thanks - but some sample IDs are missing and every sample ID should be unique..

**Comment by jheare** [comment]
Do you want the sample number added to the end of the ID? The IDs I have
are mainly to explain were the samples come from and the sample number
tells you which animal it is.

**Comment by sr320** [comment]
ID should bring us back to specific sample in fridge with wt / size info. appending Sample number if fine

**Comment by jheare** [comment]
Sample ID's have been fixed and have the sample number included in them.
