### ISSUE TITLE
Unlimited Storage on UW Google Drive

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#103]
Should we be considering - or were we aware that we have unlimited Google Drive Storage?

http://www.washington.edu/itconnect/learn/stories/news/unlimited-gdrive/

**Comment by kubu4** [comment]
Ha! I noticed that yesterday, too! Crazy! I had absolutely no idea! I haven't had a chance to check it out further, but I do wonder if there's a max file size...

**Comment by sr320** [comment]
Looks like 5TB

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/Drive_storage_1B1F4704.png)

**Comment by kubu4** [comment]
Whoa!
