### ISSUE TITLE
RNA extraction protocol

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#112]
I was wondering if someone could post an RNA extraction protocol for me. I'd like to get down there sometime to extract RNA from those coral samples. Sam, I think you mentioned doing some corals before - do you have that protocol? I have a protocol from Collin but I figured I should also have a Roberts Lab protocol that might better reflect reagents and equipment in the lab.

**Comment by sr320** [comment]
You should use manufacturers instructions.

**Comment by jldimond** [comment]
So are you saying I should use a kit?

**Comment by sr320** [comment]
@kubu4 might have something special, but we normally just use Tri-reagent, Tri-zol etc. Single solution that has instructions.

**Comment by kubu4** [comment]
RNAzol RT protocol: https://github.com/sr320/LabDocs/blob/master/protocols/Commercial_Protocols/MRC_RNAzol-RT-May-2014.pdf

Follow the total RNA isolation methodology.

I've isolated DNA from corals, but not RNA. If possible, I'd try to track down a mortar and pestle and pulverize them (the corals, not the mortar and pestle) in liquid nitrogen.

**Comment by jldimond** [comment]
Great, thanks - should be able to get a mortar and pestle at Shannon Point. Maybe liquid nitro too.

**Comment by sr320** [comment]
As mentioned in lab meeting - I moved this to gh wiki for current list of protocols - https://github.com/sr320/LabDocs/wiki/Common-Lab-Protocols
