### ISSUE TITLE
NGS databases need updating

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#116]
Recent BS libraries should have better annotation on spreadsheet and do not appear? on Fusion table.

![next_gen_seq_library_database](https://cloud.githubusercontent.com/assets/4442039/8315562/79af54d6-19a6-11e5-866d-983f57d30df3.png)

**Comment by kubu4** [comment]
Fixed annotations and updated Fusion table.

**Comment by sr320** [comment]
I might be missing it but do not see updates on fusion table

**Comment by kubu4** [comment]
The updates added were the additions of the LSU and Emma's OA samples. Those were not previously on there.

Geoduck was not added at the time I closed this issue because we didn't have the sequence data yet. But, we have it now, so I'll be updating it momentarily. :+1:

**Comment by kubu4** [comment]
Updated with geoduck RNAseq.

**Comment by sr320** [comment]
thanks!
