### ISSUE TITLE
qPCR machine might have detection issues

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#118]
Flourescence might be plate dependent?

see 

![jake_heare_research_central](https://cloud.githubusercontent.com/assets/4442039/8316526/8aad4a4e-19ac-11e5-806d-d51529a0deba.png)

**Comment by sr320** [comment]
@jheare go ahead and post image of what actin run looked like.

**Comment by sr320** [comment]
fu
single mix ct spread was ~0.8

**Comment by kubu4** [comment]
Follow up.
[Ran calibration procedure](http://onsnetwork.org/kubu4/2015/06/30/opticon2-calibration/). The calibration appears to not have resolved the issue.

**Comment by sr320** [comment]
Interesting comparison here. - note rep 5 is from opticon 
![screenshot_7_9_15__2_26_pm](http://eagle.fish.washington.edu/cnidarian/skitch/Screenshot_7_9_15__2_38_PM_1B4F216F.png)
