### ISSUE TITLE
[purchasing] Illumina Bisulfite library kits

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#130]
Lets go ahead and purchase kits to make libraries using Illumina protocols.

**Comment by kubu4** [comment]
Kit cost (12 rxns): $960

Additional components required:
FailSafe PCR Enzyme: $110
EZDNA Methylation Kit: $141
AMpure XP Beads: $305
TruSeq PCR Primers: $75

**Comment by sr320** [comment]
This would not include MBD enrichment, correct?

**Comment by sr320** [comment]
And I take it kits are just DNA library kits, so if we wanted to do MBD-seq as opposed MBD-BS-seq or BS-seq, same kits would work?

**Comment by kubu4** [comment]
Does not include MBD enrichment.

Kits are slightly different than standard DNA kits because they have a step to convert the single stranded DNA (resulting from bisulfite treatment) to double-stranded DNA. So, in theory, we could use the kits for other DNA sequencing projects and just skip the step(s) that convert single stranded to double stranded.

**Comment by kubu4** [comment]
Addendum to above post.

I haven't had the time to compare the protocols of the methylation and DNA library kits. It's possible, but unlikely, that the methylation kit combines the single-stranded conversion step with adaptor ligation or something else that would prevent us from using the methylation kit for other types of DNA library prep.

**Comment by kubu4** [comment]
Which budget(s) should I use?

**Comment by sr320** [comment]
Oly- thanks

On Sat, Jul 11, 2015 at 7:44 AM kubu4 <notifications@github.com> wrote:

> Which budget(s) should I use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sr320/LabDocs/issues/130#issuecomment-120626690>.
>
-- 
Steven Roberts
http://faculty.washington.edu/sr320/
