### ISSUE TITLE
[purchasing] RAD library supplies

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#137]
Please put on oly grant...

--- 

Thermo Scientific AlfI: ER1801
NEB T4 DNA ligase, 50 uL: M0202S
NEB 10 mM ATP, 1 mL: P0756S
dNTPs (10 mM each)
NEB Q5 Taq Polymerase, 100 units: M0491S
Qiagen PCR Cleanup kit, 50 rxns : 28104

Oligonucleotide sequences
Adaptor 1
5ILL-NR: CTACACGACGCTCTTCCGATCTNR
Anti-ILL: AGATCGGAAGAGC(InvdT)
Adaptor 2
3ILL-NR: CAGACGTGTGCTCTTCCGATCTNR
ILL-Lib1: AATGATACGGCGACCACCGA 
ILL-Lib2: CAAGCAGAAGACGGCATACGA 
ILL-HT1: AATGATACGGCGACCACCGAGATCTACAC-ATGCAT-ACACTCTTTCCCTACACGACGCTCTTCCGATCT
ILL-HT2:AATGATACGGCGACCACCGAGATCTACAC-CGTACG-ACACTCTTTCCCTACACGACGCTCTTCCGATCT 
ILL-BC1: CAAGCAGAAGACGGCATACGAGAT-CGTGAT-GTGACTGGAGTTCAGACGTGTGCTCTTCCGATC

**Comment by kubu4** [comment]
Ordered. For future reference, those sequences listed above that contain hyphens, the hyphens are demarcating the barcodes. The hyphens need to be removed when ordering.
