### ISSUE TITLE
Order New Normalizing Primers

### ISSUE THREAD

**Issue by jheare** [sr320/LabDocs#143]
Hey Sam,

I put 2 18s ribosomal normalizing primers on the primer database to be ordered. The SRID's are 1697-1700. 

Thanks,
Jake

**Comment by jheare** [comment]
I just put up three more ribosomal primers. One for 28s, 40s, and 60s from the Oly V3 transcriptome. Their SRID numbers are 1701-1706.

**Comment by sr320** [comment]
I would only order 18s - I believe the other ones are actually
differentially expressed as part of translation

**Comment by jheare** [comment]
On genbank, the 18s sequence has a part of a 28s sequence in it. At least if I'm understanding the title of the gene reference correctly. 

>Ostreola conchaphila 18S ribosomal RNA gene, partial sequence; internal transcribed spacer 1, 5.8S >ribosomal RNA gene, and internal transcribed spacer 2, complete sequence; and 28S ribosomal RNA >gene, partial sequence
