### ISSUE TITLE
Google Spreadsheets doesn't retain full revision history

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#148]
Trying to look at some changes in the PrimerDatabase sheet and the revision history only goes back two years. After some Googling, here's what I found: https://productforums.google.com/forum/#!topic/docs/95XCM3FaDgo

Google performs "revision pruning" on old sheets and/or sheets with numerous revisions.

What action should we take, if any, to address this?

**Comment by sr320** [comment]
How about regular CSV to Github- did we not have this close to being
automated at some point?

**Comment by sr320** [comment]
incorporated into #178
