### ISSUE TITLE
Identify common time for Lab Meeting this quarter

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#160]

**Comment by jldimond** [comment]
Most weeks, I plan to be on campus Mondays and Tuesdays and possibly Wednesdays.

**Comment by jheare** [comment]
Before 2 pm M-Th and before 1 pm on Fridays.

**Comment by fenix207** [comment]
Monday and wednesday before 11, Tuesday before 12, and Friday after 1:30

**Comment by grace-ac** [comment]
Mondays, Wednesdays, or Fridays at 10:30 am would work

**Comment by sr320** [comment]
GO with Monday for now,

**Comment by MeganHintz** [comment]
I have class at 11:30 am, so as long as it is before then I can make it.

**Comment by grace-ac** [comment]
Hi Steven! So is the meeting tomorrow? Or will it become Mondays a
different week...?

**Comment by sr320** [comment]
Not tomorrow (since we just had one Friday)
On Sun, Oct 4, 2015 at 5:28 PM grace-ac <notifications@github.com> wrote:

> Hi Steven! So is the meeting tomorrow? Or will it become Mondays a
> different week...?
>
> On Friday, October 2, 2015, Steven Roberts <notifications@github.com>
> wrote:
>
> > GO with Monday for now,
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sr320/LabDocs/issues/160#issuecomment-145129575>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sr320/LabDocs/issues/160#issuecomment-145404956>.
>
-- 
Steven Roberts
http://faculty.washington.edu/sr320/

**Comment by grace-ac** [comment]
oh, ha, of course
