### ISSUE TITLE
Centrifuge what is going on with it?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#162]
September 29, 2015 at 12:02PM<br>
created via Do Button

**Comment by jheare** [comment]
Internal breakers seem fine. Reset them just in case but no change.

Having Jon Wittock check the external power source to see if the 220 is out
of order.

**Comment by sr320** [comment]
Sam- had anyone (Matt) mentioned issues?

On Tue, Sep 29, 2015 at 12:16 PM Jake Heare <notifications@github.com>
wrote:

> Internal breakers seem fine. Reset them just in case but no change.
>
> Having Jon Wittock check the external power source to see if the 220 is out
> of order.
>
>
>
> On Tue, Sep 29, 2015 at 12:02 PM, Steven Roberts <notifications@github.com
> >
> wrote:
>
> > September 29, 2015 at 12:02PM
> >
> > created via Do Button
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sr320/LabDocs/issues/162>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sr320/LabDocs/issues/162#issuecomment-144160615>.
>
-- 
Steven Roberts
http://faculty.washington.edu/sr320/

**Comment by jheare** [comment]
Wittouck is coming over at 2 to help me diagnose the problem.

**Comment by kubu4** [comment]
Rachel (woman working with Matt) emailed me last night mentioning that the centrifuge was tripping the breaker. That was the first I'd heard of any issues.

**Comment by jheare** [comment]
Jon just met with me. Apparently the main breaker in the building keeps
being blown. He's suggesting we check to make sure that the machine isn't
trying to pull more than 30 amps because that's what the breaker is set at.
If so we can have the breaker replaced with a higher strength breaker.

**Comment by jheare** [comment]
Jon just tested the centrifuge a few times. The machine is generating an
E44 drive error. The code suggests calling for service.

**Comment by kubu4** [comment]
I've just put the centrifuge through a few different runs (using the bucket rotor) of differing lengths/temps (t_min=1, t_max=30, temp_min=4, temp_max=30) and have not experienced any issues.
