### ISSUE TITLE
Develop Plan for Oly sample processing

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#163]
We need to develop timeline for completion of project, priorities, and backup plan

**Comment by sr320** [comment]
along those lines - need url for sample spreadsheet

**Comment by jheare** [comment]
Is this the same spreadsheet that I was working on previously? Or is this something for what @kubu4 is working on?

**Comment by sr320** [comment]
@jheare google sheet you created

**Comment by jheare** [comment]
https://docs.google.com/spreadsheets/d/1tPvult9e0vqd5sPOTlcQqLXTfIv987rivsQVZj8DGgE/edit?usp=sharing

**Comment by sr320** [comment]
Katherine - ~100 each her broodstock - target send out November.
Katherine also brought us DNA from SS and Hood Canal, (~50,20).  Will send Fidalgo

Also brought Tissue- SS and Hood Canal (~100 each) 

Everything in -20
