### ISSUE TITLE
Logo for Roberts Lab

### ISSUE THREAD

**Issue by MeganHintz** [sr320/LabDocs#166]
Hello!

Any chance the Roberts Lab has a logo or you would be interested in having one? The Becker Lab has the logo below and I like having a recognizable logo for posters, presentations, and everything! 

![image](https://yt3.ggpht.com/-DGWDnmTwCW8/AAAAAAAAAAI/AAAAAAAAAAA/rARQqCWEZmw/s100-c-k-no/photo.jpg)

**Comment by sr320** [comment]
I think this would be a good idea.

**Comment by kubu4** [comment]
:+1: 
Definitely a fun/neat idea. The Becker Lab even has stickers! Very cool!

**Comment by MeganHintz** [comment]
The possibilities are endless!

**Comment by sr320** [comment]
![img_3440](https://cloud.githubusercontent.com/assets/4442039/10819124/9d388c44-7e03-11e5-9f30-9e100e555989.png)

**Comment by sr320** [comment]
![space - 4](https://cloud.githubusercontent.com/assets/4442039/10819564/046411fc-7e06-11e5-8e6f-fcf88c2fe9cd.png)

**Comment by sr320** [comment]
![space - 4](https://cloud.githubusercontent.com/assets/4442039/10819814/67aa0c7a-7e07-11e5-915f-42429fea609d.png)

**Comment by MeganHintz** [comment]
Oh, I like those! Michelle started sketching some ideas for the logo the other day, I can show you what she drew if you want!

**Comment by kubu4** [comment]
Dang, looking pretty good. I think the logo has to have a double helix in it.

And, @MeganHintz, post pics here so everyone can see.

**Comment by MeganHintz** [comment]
![img_0057](https://cloud.githubusercontent.com/assets/14929070/10825421/31119c9e-7e22-11e5-9e66-7144d4eda4b1.JPG)
![img_0058](https://cloud.githubusercontent.com/assets/14929070/10825423/311ac9a4-7e22-11e5-8c8a-59c910ccb2cf.JPG)
![img_0056](https://cloud.githubusercontent.com/assets/14929070/10825422/311721b4-7e22-11e5-8892-3c690432f284.JPG)

**Comment by kubu4** [comment]
:+1:

**Comment by sr320** [comment]
![2015-10-29 19 44 26](https://cloud.githubusercontent.com/assets/4442039/10846433/02b4048a-7ecd-11e5-9c92-6dce712c2ab4.png)


![2015-10-29 19 56 33](https://cloud.githubusercontent.com/assets/4442039/10846443/0cead212-7ecd-11e5-891f-d207b9ecc6f9.png)

**Comment by sr320** [comment]
See what we are missing out on with no logo : Reason number 104 to work in the #beckerlab. Our holiday lab gift! https://t.co/QRJZpDpCgu

**Comment by kubu4** [comment]
Hot damn! That's pretty tight!

**Comment by sr320** [comment]
![robertslab](https://cloud.githubusercontent.com/assets/4442039/19628550/2af91314-9915-11e6-9c11-4c4dc1428986.png)
