### ISSUE TITLE
Belize trip supplies

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#168]
I'm going to need some reagents and tubes for my Belize trip. Two things I may need help with ordering are the following:

1 L Salt saturated DMSO solution (need approx 500 ml DMSO, 250 g EDTA, and 150 g NaCl)

50 ml conical centrifuge tubes (50)

I haven't checked the lab stock of these items, but I'm guessing my needs would possibly exceed what is available.

My questions are:
1. Can I use what's currently available, or should I get my own?
2. Is there a standard or best source for such items (e.g. Fisher), and how does ordering work if so?
3. Can general lab funds cover these or do I need to cough up my own cash?

TIA :exclamation:

**Comment by kubu4** [comment]
We have sufficient quantities of all those reagents/tubes.

I'll let @sr320 answer the questions.

I'd also keep in mind on how you're going to transport these chemicals, particularly DMSO since it's flammable...

**Comment by jldimond** [comment]
Thanks Sam.
I'll be making a 20% solution of DMSO, so it's mostly water. I've heard this is a good way to go for air travel.

**Comment by jldimond** [comment]
FYI, I decided on salt saturated DMSO based on this paper: http://link.springer.com/article/10.1007%2Fs00338-010-0687-1

**Comment by jldimond** [comment]
I'm also thinking about bringing some temperature loggers down with me. Jake suggested that there were some available (or almost available). Would anyone object to me using these for ~ 1 year?

**Comment by sr320** [comment]
Just make sure all data is backed off first
On Wed, Oct 28, 2015 at 12:03 PM Jay Dimond <notifications@github.com>
wrote:

> I'm also thinking about bringing some temperature loggers down with me.
> Jake suggested that there were some available (or almost available). Would
> anyone object to me using these for ~ 1 year?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sr320/LabDocs/issues/168#issuecomment-151957835>.
>
-- 
Steven Roberts
http://faculty.washington.edu/sr320/

**Comment by MeganHintz** [comment]
I have the temperature logger Jake was using in Fidalgo, I'll get the data off of it tomorrow so you can set it up for your trip. #dontstopBelizing

**Comment by jldimond** [comment]
Thanks @MeganHintz 
#youbetterbelizeit
