### ISSUE TITLE
Determine means for Epigenetic analysis of Katherine's samples

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#177]
We need to get these samples out for sequencing this month.

I am leaning towards MBD-BS-seq / MeDIP-BS-seq but could be convinced otherwise.

Here is what we have 

![DNA](https://www.evernote.com/l/AArLhg56iPlA2bcix01Z-i77Rxn_z5ztb8oB/image.png)

What sequencing facilities will do BS seq or ideally precipitation too..?

**Comment by sr320** [comment]
Here is a list of samples we currently have in [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1anTR7QLB1p_Oyh_hUIWKKHy21sSvVjwTZmdqqxwcpWM/edit?usp=sharing)

**Comment by sr320** [comment]
@kubu4 has MBD underway, with hope to send out samples for BS conversion, library prep, and sequencing.

Targeting downtown :tokyo_tower: ?

**Comment by ksil91** [comment]
Note that for a few SS samples there are an A and B. Most of the B samples were left overnight and had poorer quality when checked on a gel. This is indicated on the sample sheet with a 1(poor)-5(best) rating for the gel. For some the gel quality column is blank because I didn't get a chance to run out all samples, so if HMW DNA is important you may need to check some of them.

**Comment by kubu4** [comment]
Quote from ZymoResearch is ~$15,000.
- 18 samples
- bisulfite
- multiplex libraries
- run multiplex on three separate HiSeq lanes

Breaks down to ~$830/sample.

**Comment by sr320** [comment]
Problem here is 8+ weeks will mean cannot charge to grant...

**Comment by kubu4** [comment]
Yep. Just sharing the info.

I can do the bisulfite treatment and library preps and then have Genewiz do the sequencing (5 - 10 business day turnaround).

**Comment by kubu4** [comment]
Also, I've contacted Zymo to see if they can get things turned around faster and, potentially, provide a guarantee (unlikely they'd ever agree to something like this) they could have the data to us by the end of January.

However, if they CAN get it done before the end of January, would you want to go forward with them?

**Comment by sr320** [comment]
@ksil91 can you remind me what tissue you extracted to obtain this DNA?

**Comment by kubu4** [comment]
Zymo has said they'd guarantee delivery by Jan 31st (assuming the samples pass QC when they receive them). Also, they said they could charge the account prior to data delivery to ensure money is pulled from grant before end of January.

**Comment by sr320** [comment]
Lets decide tomorrow at lab meeting - I actually have a new option that could be excellent and very cheap, Though with risk. @kubu4 can you start hangout 15 minutes before lab meeting and we can discuss in more detail. 

Related-  what quantity of DNA of the 18 samples do we have - was it all MBD'd? 

Also billing in not as a big deal as is getting data. Should have 60 days to bill.

**Comment by kubu4** [comment]
Sure, I can hangout before lab meeting.

All 18 samples were MBD'd.
Recoveries ranged from 250 - 600ng

**Comment by sr320** [comment]
Samples heading to ZYmo
