### ISSUE TITLE
Maybe some day...  "Wishlist"

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#178]
Here is a list of things that would be nice, but currently not a priority
- [x] Join PrimerDatabase and Primer Stocks spreadsheets into a single database
- [ ] Create database of -80C racks
- [ ] Google Spreadsheets doesn't retain full revision history
- [X] Remove stuff from 129
- [ ] Summarize others use of qPCR machine and centrifuge for 2015, 2016
- [X] simple full GitHub repo backup ~to NAS~ - good enough = https://backhub.co/
- [ ] Organize electronics in FTR 230 (rewire)

**Comment by seanb80** [comment]
Not sure if the Github Backup to NAS has been addressed, but I just played with a ruby gem called github-backup, that automates creating clones of GitHub repos associated with a username. Might be worth playing with?

https://github.com/ddollar/github-backup

**Comment by sr320** [comment]
Surely, ideally it would download everything including (issues), but anything would be an improvement

**Comment by seanb80** [comment]
https://docs.google.com/spreadsheets/d/1750PmCaoWynefiLR62sj7FV-ydaapopQMRWsLy2MivM/edit#gid=2137376807

The above is a link to a combined primer database. There are two IDT # columns, one is only populated by a few numbers, as they do not match the other column. I'm unsure of the significance of this, so I left them be. 

Notebook link: http://rpubs.com/seanb80/235047

**Comment by sr320** [comment]
I am going to close this catch all issue as some have been tackled... some might never (or captured in other tasks) Please post new issue if necessary.
