### ISSUE TITLE
Sequencing Katherine's RAD-seq

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#179]
Katherine plans to have libraries ready for sequencing Nov 22.

There will be 4 samples, and we plan to do one lane of each. Each sample has  96 barcodes.

Length is only 36 bp, so **50bp SE** is what we need

What facilities can do this with quick turn around?

**Comment by kubu4** [comment]
A couple options I know off the top of my head:

U of Oregon (experienced with RADseq)
- NextSeq500 (130M reads); no waiting for full flow cells; $1900/sample
- HiSeq2500 (160 - 200M reads); have to wait for full flow cells, but usually fills quickly; $1600/sample

GeneWiz
- HiSeq2500 (160 - 200M reads); should be quick; $1900/sample

**Comment by sr320** [comment]
Also OSU might be an option

http://cgrb.oregonstate.edu/core/illumina-hiseq-3000/illumina-hiseq-3000-service-fees

**Comment by kubu4** [comment]
Called OSU. They require a full chip to initiate a run. SE runs are rare. 50bp PE runs are going "non-stop". Sequencing run only takes a day, so that's an option: $1950/lane

**Comment by sr320** [comment]
Where should we ship- What is the type, cost, and turn around?

**Comment by kubu4** [comment]
Genewiz - HiSeq2500, 50bp SE; $6375; 5 day turnaround.

If this is where we're going, I please need Katherine to email me the list of barcodes and what the labels are on each of the four tubes so I can fill out the sample submission form.

**Comment by sr320** [comment]
@ksil91 can you provide that here? ~

**Comment by sr320** [comment]
@kubu4 So this is @ksil91 4 lanes and 1 of yours?

**Comment by ksil91** [comment]
They also need to be able to do dual index barcoding. I'm making up a spreadsheet now of sample names and labels and will put it here.

**Comment by sr320** [comment]
Not sure what "dual index barcoding" means. I take it if we get 50 bp of data we could demultiplex ourselves?

**Comment by ksil91** [comment]
These aren't inline barcodes (meaning they aren't right next to the insert). During the Illumina run, there are 2 separate index reads that just read the indices and demultiplexes the reads that way. I'm pretty sure all 2500 have the software to do dual index reads, but should just double check.

**Comment by ksil91** [comment]
Oh actually I've given it to you already. The barcode sequences are column B of this sheet https://docs.google.com/spreadsheets/d/1mw23331tl9nfIdA8k9EL3kTSPXu0gAqVovCFrMip1Ac/edit?usp=sharing

**Comment by ksil91** [comment]
The tubes will be labelled "KES-1", "KES-2", "KES-3", and "KES-4"

**Comment by kubu4** [comment]
Actually, @ksil91, could you please fill out their sample submission form? It needs deets about sample volumes, concentrations, etc.

https://docs.google.com/spreadsheets/d/1Y9xbjCndDlqNCkl1lMdsFmHZQ2LVX8pTujvxVw-2phY/edit?usp=sharing

I've already confirmed with Genewiz to have them do the demultiplexing when the data comes off the machine.

**Comment by kubu4** [comment]
@sr320 No, this is just for @ksil91. Genewiz doesn't do any BS-seq (unless we sent them fully prepped Illumina libraries).

**Comment by kubu4** [comment]
@sr320 Oh! I'm an idiot. I see what you're asking. Anyway, no, it's still pricing for just Katherine's. I can certainly have them sequence an additional lane. However, we should discuss how we want to handle those libraries I prepped - there's significant amount of primer dimer present in almost all of them: http://onsnetwork.org/kubu4/2015/11/17/qpcr-oly-rad-seq-library-quantification-2/

**Comment by sr320** [comment]
@kubu4 Assuming @ksil91 will be ready to go next week- let's just hold off on your Rad libraries. Need to get the BS out (different thread :smiley_cat:  #177)

**Comment by ksil91** [comment]
So for that sheet, should I put all 300 samples on there and just indicate which of the 4 pools they will be in? I won't have it filled out until I finish the libraries and quantify but will send it when I do. Also, the sheet only has a column for one barcode- so should I just put both barcode sequences in that column separated by a comma? With dual indices like this, you don't typically do the demultiplexing afterwards as the sequencing software does it for you... I'm just worried that they won't set up the run to do both index reads.

**Comment by kubu4** [comment]
Just list the 4 samples you'll be submitting. You won't be able to list all of the barcodes in each sample on that sheet. I'll be sending them the list of barcodes.

Genewiz does this stuff all the time. They understand the demultiplexing, so you don't have to worry about that.

**Comment by ksil91** [comment]
When going to do the PCR today I realized I ordered the wrong size of Taq, so libraries won't be ready tomorrow. My lab manager will put in an order for the Taq tomorrow so hopefully it'll be here on Wednesday and I can finish them up Wednesday afternoon/Thursday morning. So I guess with the holiday I won't be shipping them until next Monday, unless Genewiz will accept them on a Saturday?

**Comment by ksil91** [comment]
Sorry about that :/

**Comment by kubu4** [comment]
They do not accept shipments on the weekends.

**Comment by sr320** [comment]
So have these been submitted for sequencing?

**Comment by kubu4** [comment]
No. Not sure of @ksil91's status.

**Comment by ksil91** [comment]
Sorry, the qPCR step is taking forever- I can only do 24 samples at a time and each run is 2 hours. I also had to do a few redos that failed. I think I'll just use the Qubit to pool one of the libraries so I can send them out tomorrow morning.

**Comment by ksil91** [comment]
Sample sheet for 1st 3 libraries: https://docs.google.com/spreadsheets/d/1lDF6gWeiqrY4-xlhJ9lmU5_waH9XFQliUAaL2foA-7s/edit?usp=sharing

**Comment by sr320** [comment]
Everything sent out?

**Comment by kubu4** [comment]
I sent our one 2bRAD "test" library.

**Comment by ksil91** [comment]
4th library is done and shipping out today! Sam, I created a new sample sheet for it and will send you the tracking info after I take it to FedEx. There are at least 5 samples across all libraries that didn't work for one reason or another. I'd still like to make 1 or 2 lanes of larvae samples to ship out by January 1 and if so I'll try those samples again, but we'll have to see as I'm going to Texas from Dec. 16-26.
