### ISSUE TITLE
Spec out NAS attachment

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#181]
Can owl take an attachment? we might should consider this for new data coming soon

**Comment by kubu4** [comment]
I was actually thinking about this this weekend, too. 

Yes, it can accept expansion units.

[Synology DX513 5-Bay] (http://www.amazon.com/Synology-Expansion-Increasing-Capacity-DX513/dp/B009EMFXGG/ref=sr_1_1?ie=UTF8&qid=1448301835&sr=8-1&keywords=synology+dx513) (no HDDs) = $550

Supports up to 40TB (5 x 8TB HDD)
