### ISSUE TITLE
PacBio Option for Oly

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#184]
Sequencing data
- ~400Mb (megabases) per "lane" (SMRT Cell)

Costs
- $400 library prep (will be enough for 8 - 20 SMRT Cells)
- $500 for first SMRT Cell
- $400 for each additional SMRT Cell

For the oly sequencing, how much data/coverage do we want?

**Comment by sr320** [comment]
Is there an estimated turn around time for data? I would like to hold off on this and exhaust all options on epigenetics / genetics first.

**Comment by kubu4** [comment]
Turnaround time is 4 -5 weeks.

**Comment by sr320** [comment]
funds are done
