### ISSUE TITLE
Phase 2 - DNA methylation analysis

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#185]
For Phase 2 of DNA Methylation.... plan starts with
From Clam Bay - specifically ones Katherine sent for ~~GBS~~  2bRAD
5 samples from Hood Canal
5 samples from Fidalgo
5 samples from South South

5 samples from Fidalgo site from Fidalgo population  (DNA)
5 samples from Fidalgo site from Fidalgo population  (Tissue)

5 samples (Tissue) from South Sound site from Fidalgo population - Preferably 5 that correspond to the ones sent out for GBS. Noting I think this might all still be in 4C in RNAlater 

---
We want to get these samples to Lotterhos - can take tissue or DNA- need a bit - ~2 ug...
Sam will make BS libraries to complement

**Comment by sr320** [comment]
Links
- [Katherine's sheet](https://docs.google.com/spreadsheets/d/1qrKW9QdtMMrSDHVRHzigEixuh7S8l10ZDySN5R5ZkPM/edit#gid=1279140750)
- [Amended version](https://docs.google.com/spreadsheets/d/1anTR7QLB1p_Oyh_hUIWKKHy21sSvVjwTZmdqqxwcpWM/edit#gid=0)

**Comment by kubu4** [comment]
Are the 15 samples listed here a subset of the Clam Bay or are they different?
"From Clam Bay - specifically ones Katherine sent for 2bRAD
5 samples from Hood Canal
5 samples from Fidalgo
5 samples from South South"

If these are the samples in the spreadsheet she put together ([Silliman-DNA-Samples](https://docs.google.com/spreadsheets/d/1anTR7QLB1p_Oyh_hUIWKKHy21sSvVjwTZmdqqxwcpWM/edit?usp=sharing)), there is no Fidalgo population listed. Additionally, we used these samples for MBD, not 2bRAD. Were they initially intended for 2bRAD or did you mean to type MBD?

**Comment by kubu4** [comment]
What is your vision for sequencing for all of these samples (i.e. how many lanes and how many samples in a lane)?

**Comment by sr320** [comment]
RE samples
Correct - there are no Fidalgo samples on the sheet- though she says she will update as libraries get sent out. On "Katherine's sheet" above- then we can transfer to amended version. We do have the samples.

My understanding is all of these went out for 2bRAD (possibly today) and you took subset for MBD...

**Comment by sr320** [comment]
RE Sequencing ...
Open to suggestion..

**Comment by sr320** [comment]
Lotterhos samples (gigas) arriving tomorrow

1) Mantle tissue samples of C. gigas were collected on 20140705 (source: Pipestem Inlet) by KEL
2) Extraction on 20141028 by VG using Qiagen DNAeasy Blood and Tissue Kit
3) Beadwash on 20150720 by VG using homemade sera-mag speed beads
4) Qubit 3.0 quantification on 20151206 by KEL and the following amounts were sent:

M1: 13 uL of 386 ug/mL
M2: 13.8 uL of 326 ug/mL
M3: 13.15 uL of 380 ug/mL (solution looked cloudy)

**Comment by sr320** [comment]
Samples sent to Katie
sent a total of 15 DNA samples (~2ug of each sample) from C.gigas housed in Clam Bay. The samples were isolated using the E.Z.N.A. Mollusc Kit by a collaborator.

HC1 3
HC3 18
HC2 20
HC2 14
HC2 19

NF2 14
NF2 6
NF2 18
NF2 15
NF2 17

SS2 17A
SS2 19A
SS1 12
SS1 8
SS3 5B

I've also sent a total of 20 C.gigas tissue samples (whole body sub-sample), stored in RNAlater. Tissue weights are unknown. 10 of the samples are from oysters born and raised in Fidalgo Bay. The other 10 are oysters born in Fidalgo Bay and grown in Oyster Bay.

Fidalgo-Fidalgo Tubes:
Fidalgo NF 60 - 69

Fidalgo-Oyster Bay Tubes:
1NF 1 -10 RL

The "RL" label on the second group is just to indicate RNAlater.

**Comment by kubu4** [comment]
Will isolate DNA from 8 oysters each from Fidalgo-Fidalgo & Fidalgo-Oyster Bay samples to make BS-seq libraries.

**Comment by sr320** [comment]
@kubu4 to clarify ...
We do not have DNA from samples mentioned above?  where you
"sent a total of 15 DNA samples (~2ug of each sample) from C.gigas housed in Clam Bay" 

We would want to consider a subset of these for BS..

**Comment by kubu4** [comment]
Yes, we do have those, but when we chatted this week, I was under the impression we weren't going to use those & that's why you wanted me to isolate DNA from 8 Fidalgo-Fidalgo & 8 Fidalgo-Oyster Bay. Sorry for confusion. Let me know which 12 samples you want me to bs treat & make libraries.

**Comment by kubu4** [comment]
To add to the project record, we now have DNA from the following 16 Oly samples from Jake's outplantings :

Fidalgo-Oyster Bay
1NF11-18

Fidalgo-Fidalgo 
2NF1-8

**Comment by sr320** [comment]
For the 12 samples

Select 4 samples from 1NF [gel take 2](http://onsnetwork.org/kubu4/2015/12/17/agarose-gel-oly-gdna-for-bs-seq-libraries-take-two/)
Select 4 samples from 2NF [gel take 2](http://onsnetwork.org/kubu4/2015/12/17/agarose-gel-oly-gdna-for-bs-seq-libraries-take-two/)

Select 2 from [gel take 2](http://onsnetwork.org/kubu4/2015/12/17/agarose-gel-oly-gdna-for-bs-seq-libraries-take-two/) Lotterhos 

M1
M2
M3

Select 2 from the following sent to Katie (do not have to run on gel)
NF2 14
NF2 6
NF2 18
NF2 15
NF2 17

**Comment by kubu4** [comment]
Looks good! Thanks! Will get these going shortly.

**Comment by kubu4** [comment]
Just heard back from Genewiz regarding pricing 50bp SE vs 50bp PE

50bp SE = $1600

50bp PE = $2500

Which shall we go with?

**Comment by sr320** [comment]
SE please

**Comment by kubu4** [comment]
:+1:

**Comment by sr320** [comment]
no we just wait... :clock1130:
