### ISSUE TITLE
Data management plan for Eagle/Owl

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#187]

**Comment by kubu4** [comment]
- Functions/purposes of Eagle vs Owl
- Functions/purposes of directories on Eagle/Owl
- "Active" vs. "Inactive" storage on Eagle/Owl

**Comment by sr320** [comment]
I think I would like to slowly retire Eagle, but document well what is on it....
and  how that is "archived".

And just go forward with Owl? seem reasonable?



Here is the structure of Eagle and a look into a couple of primary directories
![eagle_fish_washington_edu_and_data_management_plan_for_eagle_owl_ _issue__187_ _sr320_labdocs](https://cloud.githubusercontent.com/assets/4442039/12456642/a368ac8c-bf55-11e5-963d-f313ec77d0db.png)


![archive](https://cloud.githubusercontent.com/assets/4442039/12456632/9a1e9664-bf55-11e5-8aa7-b15fb4320da0.png)

web
![web](https://cloud.githubusercontent.com/assets/4442039/12456659/b46c868e-bf55-11e5-8b5a-040ff24dda91.png)

**Comment by kubu4** [comment]
For owl/nightingales, what're thoughts on high-thoughput sequencing data file organization? 

Initially, I think we decided to avoid creating subdirectories within each species directory. However, with the recent 2bRAD data, which generated over 300 files, I created a subdirectory for this project, as it seemed like it would be difficult to sort through the entire set of 300+ files if they were intermingled with all other sequencing files from all other projects.

My question is: Should we created subdirectories that contain project data or should all sequencing files from all projects for a given species exist together within each species folder?

**Comment by sr320** [comment]
Let's make an exception for this data - using date stamp as directory name

**Comment by kubu4** [comment]
Another reason I'm asking is the genome sequencing data from BGI is in. Currently downloading. Only 19 files from each project, but should I create subdirectories in the Oly and Geoduck folders for these as well or just have them amongst the other NGS datasets?

**Comment by sr320** [comment]
Let's just leave in main directory.

**Comment by kubu4** [comment]
Will do, thanks. :+1:

**Comment by sr320** [comment]
Discussed and will move new user directories to owl and leave eagle in current state.

**Comment by kubu4** [comment]
Version control/backup plan for Owl/web

**Comment by sr320** [comment]
moved to #199

**Comment by kubu4** [comment]
Do we have a document that details which directories are being backed up and what the backup destination/service is?

**Comment by sr320** [comment]
Lets create that document 

https://github.com/sr320/LabDocs/wiki/Network-Attached-Storage-Infrastructure
