### ISSUE TITLE
Oly 2bRAD raw data status

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#190]
Where are we in being satisfied with the raw 2bRAD data.

It appears there are 306 files provided by core, with 2 files (5+GB) labelled as _Undetermined_

**Comment by sr320** [comment]
Here is what I got for quick fastqc 

https://github.com/sr320/nb-2016/blob/master/O_lurida/2bRAD-data-check.ipynb

This seems a little concerning...?
![nb-2016_2brad-data-check_ipynb_at_master_ _sr320_nb-2016](https://cloud.githubusercontent.com/assets/4442039/12465029/f1587762-bf80-11e5-9e88-e394ef46d994.png)






h/u @ksil91

**Comment by ksil91** [comment]
Our sequences are only 36 bp long, so we would expect that after 36 bp it would just be sequencing adapters and therefore the quality would go down. I'm assuming that dip in quality scores in the middle is where there restriction cutsite is and therefore the AC/TG color balance was "off". I think this looks good, unless I'm missing something?

**Comment by sr320** [comment]
My concern is at bp 13-15, 22-24, every single sequence has GCA and TGC respectively....

Is this somehow related to protocol?

also bp 2 and 35 are skewed a bit. 

As you indicate the 36+ as AGATCGG... is expected as adaptor..e

**Comment by ksil91** [comment]
The Wang 2012 paper describing the 2bRAD protocol has a figure showing the cutsite for AlfI. Those 2 sections are the restriction cut sites. To reduce the number of fragments we sequence to 1/4 of the cutsites in the genome, the adaptors ligate to a sequence ending in -NR (so any base as bp 1, then A/G at bp 2. On the 5' end its the reverse complement of that. (http://www.nature.com/protocolexchange/protocols/2356#/figures

**Comment by sr320** [comment]
Awesome! thanks :+1:
