### ISSUE TITLE
Discuss upcoming OA purchases

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#192]
We need to determine how to move forward with OA purchases see

https://plus.google.com/u/0/106492099842577316500/posts/1TbperMSXsL

tldr 

We have used
Thermometer:
https://www.fishersci.com/shop/products/fisher-scientific-traceable-digital-thermometers-11/150778

Conductivity:
YSI 63 and are now moving to the following
https://us.vwr.com/store/catalog/product.jsp?catalog_number=23226-505

CRMS:
Tris
Contact co2crms@ucsd.edu for information about availability
was $20 for 250ml, but not sure current price

daily or at least 3 times a week pH calibrations are necessary and the standards are meant to be single use, but if very careful and clean may be able to be used several times.

**Comment by kubu4** [comment]
Spec pH system is from Ocean Optics: http://oceanoptics.com/

However, I don't know all of the components required to set it up. Here are a few:

- CUV-UV-10 (cuvette holder for 10cm quartz cuvettes)
- USB2000+ spectrometer
- SpectraSuite software
- light source
- cables

I'm not sure where the Friedman Lab set up is (still at Manchester?), so I don't have anything to reference for how it's set up. I'll email Ocean Optics and see what they say.

**Comment by sr320** [comment]
At this point I am leaning toward purchasing what @hputnam suggested...

**Comment by sr320** [comment]
@kubu4 can you get information on TRIS CRMS? costs, time frame etc. 

presume can be ProCard purchase..

**Comment by kubu4** [comment]
Cost: $20 - 125mL bottle (more than 10 bottles is special order)
Turnaround: Minimum two weeks to ship after order is received.
ProCard: No credit cards; need PO.

**Comment by sr320** [comment]
My understanding is we will be ordering a lot of these...
Can we set up an "open PO"?

Not sure what special orders mean... 

but maybe for now lets go ahead and get an order placed for 6 bottles...

**Comment by kubu4** [comment]
Tris CRMs are produced in limited quantities. Orders of >10 are "special order" and will require greater processing time to prepare and ship.

**Comment by kubu4** [comment]
Which budget?

**Comment by sr320** [comment]
62-9868

**Comment by kubu4** [comment]
:+1:

**Comment by kubu4** [comment]
Mettler Toledo pH probe: DG115SC (per Holly in today's lab meeting)

**Comment by kubu4** [comment]
CRMs update:

No Tris CRMs currently available. They're getting ready to make a new batch and they won't be available for at <em>least</em> a month. They wouldn't commit to an official ETA, and it sounds like the lab is shorthanded, so it could be longer.

**Comment by sr320** [comment]
I think we might have recipe to make ourselves - I have had several emails
from Rhonda / Hollie and are trying to get material into a github repo..

Hardware wise, can we come up with a list for purchasing (that we can give
to NOAA for purchasing)?

**Comment by kubu4** [comment]
Ordering info:

| VENDOR | DESCRIPTION                                                   | CAT#      | LIST_PRICE |
|--------|---------------------------------------------------------------|-----------|------------|
| FISHER | Traceable Digital Thermometers                                | 15-077    | 650.00     |
| VWR    | VWR Bench/Portable Conductivity Meter                         | 23226-505 | 1425.12    |
| VWR    | DG115-SC Combination pH Electrode, Glass Body, METTLER TOLEDO | 11278-220 | 441.18     |

**Comment by sr320** [comment]
Thanks! I think we also need something for for the pH Electrode to connect to - can we use one of ours?

**Comment by kubu4** [comment]
Don't know. We'll have to ask Hollie.

**Comment by sr320** [comment]
Ordered by Rick - should arrive this week
