### ISSUE TITLE
Centralized project summaries/milestones?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#197]
Create a singular location (e.g. repo in GitHub sr320/LabDocs) to track projects' progressions?

Or, if this already exists, where is it?

Or, create separate repos for each project and use the GitHub Issues tracker as a to-do checklist?

We could potentially set up a default format for each repo's (i.e. project) readme file that has sections like:

- Link to grant proposal and/or experimental design and/or brief description of project goal(s)

- Funding agency

- Organism(s)

- Samples to be collected, including dates/locations/personnel

- Benchwork to be performed, including personnel

- Necessary reagents, tools, etc.

- Expected data types to be collected (upon collection, people can provide storage info, locations, etc)

- Expected data analysis to be performed and personnel (upon completion, people can provide links to data locations)

**Comment by sr320** [comment]
This is a great idea!

I guess I have a hard time identifying "projects"-

**Comment by sr320** [comment]
done

https://github.com/RobertsLab

**Comment by kubu4** [comment]
Reopened for organizational discussion of https://github.com/RobertsLab.

Use the main repo directory for projects/sub info or utilized the GitHub wiki? Or, both? Thoughts on layout(s)?

**Comment by sr320** [comment]
going with wiki, lets develop layout as we kick the tires with the oly repo
