### ISSUE TITLE
Credit Card declined - GENEWIZ invoice # IN140205192148642

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#200]
Appears to be issues with procard - I am going to contact Robin to see if she can pay with Dept card.

I have called Genewiz and provided what I presume to be updated card information.

**Comment by kubu4** [comment]
Can you please forward the email to me? I'm guessing it's more likely that the charge exceeds the single transaction limit for the ProCard. If that's the case, I'll have to initiate a transaction limit increase request via Ariba.

**Comment by sr320** [comment]
Kate is taking care of it. Thanks!
FWIW - it is a $1500, which should not be above limit?

**Comment by kubu4** [comment]
:+1: 

Definitely below the limit (limit = $3500)

**Comment by sr320** [comment]
It has been two weeks and I have not heard anything re this so will close the issue. Underlying issue not known
