### ISSUE TITLE
Purchasing - memory for imac

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#202]
Please purchase 

Crucial 16GB Kit (8GBx2) DDR3L-1600 SODIMM Memory for Mac (CT2K8G3S160BM )

http://www.amazon.com/Crucial-DDR3L-1600-SODIMM-Memory-CT2K8G3S160BM/dp/B008LTBJFW/ref=sr_1_1?ie=UTF8&qid=1458312979&sr=8-1&keywords=imac+memory

**Comment by kubu4** [comment]
Which budget?

**Comment by sr320** [comment]
62-5436
