### ISSUE TITLE
Video Call on epigenetics

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#205]
A student (Nicola Hawes) and advisor want to chat on epigenetics next week

> I am currently doing my PhD research on the effects of environmental change on DNA methylation in a marine invertebrate (a colonial ascidian) and one of my environmental stressors is acidification. I am using high-throughput sequencing analysis and bisulfite sequencing for this project.

She is at the University of Auckland - so will be sometime Monday - Thursday after 2pm....

Let me know if you are interested in joining call and will schedule accordingly..

hu @jldimond @hputnam

**Comment by jldimond** [comment]
I'd be interested but am only available after 4:30 on any of those days... No problem if that won't work for you.

**Comment by sr320** [comment]
Hollie cannot do Tuesdays

**Comment by sr320** [comment]
Confirmed for April 27th at 5pm for those available.

**Comment by jldimond** [comment]
OK I put it on my calendar

**Comment by sr320** [comment]
Will need to push to about 5:15

**Comment by hputnam** [comment]
I have changed it to 5:15 on my calendar. 

Best Wishes,

Hollie 

________________________________
Hollie Putnam
University of Hawaii
Hawaii Institute of Marine Biology
46-007 Lilipuna Rd. 
Kaneohe, HI 96744
Phone: 808-554-1462
Fax: 808-236-7443

http://www.hollieputnam.com

https://www.google.com/calendar/embed?src=hollieputnam%40gmail.com&ctz=Pacific/Honolulu 
________________________________

**Comment by jldimond** [comment]
Roger that. I have to take Julie to catch a bus in town but should be back
by then.

**Comment by sr320** [comment]
Postponing - investigator on other end has death in the family.

**Comment by hputnam** [comment]
sorry to hear that! 

Best Wishes,

Hollie 

________________________________
Hollie Putnam
University of Hawaii
Hawaii Institute of Marine Biology
46-007 Lilipuna Rd. 
Kaneohe, HI 96744
Phone: 808-554-1462
Fax: 808-236-7443

http://www.hollieputnam.com

https://www.google.com/calendar/embed?src=hollieputnam%40gmail.com&ctz=Pacific/Honolulu 
________________________________

**Comment by sr320** [comment]
This is on at 5:30 Pacific today - In the slim chance you guys are available I can add you to the Skype call; just let me know what your Skype username is...

**Comment by hputnam** [comment]
Unfortunately, I have a prior commitment. Looking forward to hearing more about it.

Best Wishes,

Hollie 

________________________________
Hollie Putnam
University of Hawaii
Hawaii Institute of Marine Biology
46-007 Lilipuna Rd. 
Kaneohe, HI 96744
Phone: 808-554-1462
Fax: 808-236-7443

http://www.hollieputnam.com

https://www.google.com/calendar/embed?src=hollieputnam%40gmail.com&ctz=Pacific/Honolulu 
________________________________

**Comment by jldimond** [comment]
Sorry, that won't work tonight.

**Comment by sr320** [comment]
Was an interesting chat ... they are just getting started but doing lots of similar work.

Most interesting was colonial tunicate they are planning on doing genome sequencing and BS-seq with...
