### ISSUE TITLE
Work up of GBS data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#206]
Get some results from Oly GBS data for upcoming report due this month

**Comment by kubu4** [comment]
Initial analysis on subset of individuals, all analyzed as a single population (still waiting on the other analysis to finish that breaks out populations):

28 individuals, 36424 loci, 72251 snps

Separate note: pyRAD vcf file format output is wonky and IGV can't read the header of the file, thus preventing data visualization with IGV.
