### ISSUE TITLE
Release Geoduck Gonad RNA-seq Data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#213]
Review and release data

**Comment by sr320** [comment]
@kubu4 can you post url once this is live?

**Comment by kubu4** [comment]
BioProject: [PRJNA316216](http://www.ncbi.nlm.nih.gov/bioproject/PRJNA316216) - http://www.ncbi.nlm.nih.gov/bioproject/PRJNA316216

Study: [SRP072283](http://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP072283) - http://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP072283

Study (I think this is the link we want): [SRP072283](http://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP072283) - http://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP072283

Female Pool Experiment: [SRX1659865](http://www.ncbi.nlm.nih.gov/sra/SRX1659865) - http://www.ncbi.nlm.nih.gov/sra/SRX1659865

Male Pool Experiment: [SRX1659865](http://www.ncbi.nlm.nih.gov/sra/SRX1659866) - http://www.ncbi.nlm.nih.gov/sra/SRX1659865
