### ISSUE TITLE
Add Geoduck transcriptome to TSA

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#216]
The transcriptome that corresponds to gonad RNA-seq data needs to be added to NCBI TSA-
fasta =
https://github.com/sr320/paper-pano-go/blob/master/data-results/Geoduck-transcriptome-v3.fa.zip

http://www.ncbi.nlm.nih.gov/genbank/tsa/

**Comment by kubu4** [comment]
The TSA submission requirements say that a transcriptome assembly made from multiple organisms should <em>note</em> be submitted. 

Since these were pooled, we can't submit to TSA.
