### ISSUE TITLE
Liquid Nitrogen Dewer

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#217]
Do we have still have our liquid nitrogen dewer? Micah and team might be needing it this summer for sampling.

**Comment by kubu4** [comment]
The little blue one, correct? Last I remember, we had loaned it to the Young Lab for use.

Regardless, I'm not sure it's suited to field sampling, due to its extremely small size...

**Comment by sr320** [comment]
We originally had large tan one... Three feet tall

**Comment by kubu4** [comment]
It's in FRT209. In the back of the lab, under the Mac Mini workstation.

**Comment by sr320** [comment]
Thanks -
Can you also price out a comparable one that might be better suited for car travel. Presume something like Lisa uses?

**Comment by kubu4** [comment]
10L capacity w/shipping container ~ $1700

10L capacity w/o shipping container ~$1000

**Comment by sr320** [comment]
Do you have a recommended dewar similar to what Brent found?

**Comment by kubu4** [comment]
We ordered the one Brent found (dry shipper) on 6/9/2016.

Fisher Cat#: NC0457474. 
Model: CXR100
Capacity: 3.3L
