### ISSUE TITLE
Record Keeping Case Study - Lamprey

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#219]
Rick need know what library prep kits were used on lamprey libraries we submitted. 

Clues:   Individual libraries were constructed and sequenced (36 base bp single end) using the Illumina GAIIx platform (San Diego, CA).

What library kits were used?

**Comment by kubu4** [comment]
We don't have any records in the NGS database of any P.marinus sequencing to reference a date or sequencing facility. Plus, seeing that these were run on the GAIIx suggests that this was done a long time ago; I bet the facility might not even have records on the samples.

Do you happen to have any more info I can go off of to look into this a bit more?

**Comment by kubu4** [comment]
Any chance it's these samples?

![selection_007](https://cloud.githubusercontent.com/assets/4514104/15514262/1bf8456e-219d-11e6-8bf4-72e6a38ad25b.png)

**Comment by sr320** [comment]
Yes-  those are likely it. 

Could also just see if they might be able to provide name of Illumina kits used about 3 years ago...

We should also build / get this information into our ever evolving sequencing workflow.
thanks

**Comment by kubu4** [comment]
They think it was the TruSeq RNA Sample Prep kit.
