### ISSUE TITLE
[purchasing] Hobo Batteries, Dessicant & Pro Software

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#226]
http://www.onsetcomp.com/products/data-loggers/ua-001-64

Please buy batteries (pack 5), dessicant (25)

and Pro Software
http://www.onsetcomp.com/products/software/bhw-pro-dld

	61-0221

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/HOBO_Pendant®_Temperature_Alarm_Data_Logger_64K_1D1088F1.png" alt="HOBO_Pendant®_Temperature_Alarm_Data_Logger_64K_1D1088F1.png"/>

**Comment by kubu4** [comment]
We have an existing license for HOBOware Pro Software. I've added the license to the README.md file in Eagle/Backup/Software/Mac. Will create create README file for Windows folder with this info as well.

Sorry it wasn't in there previously.
