### ISSUE TITLE
Ordering supplies for RAD library prep

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#227]
So I'll be doing my ddRAD and EpiRAD library prep in the Leache Lab the first week of August. I need to order some things from NEB and I assume we have an account. These items should be purchased with funds from the Hall Award, and I believe SAFS holds the purse strings. Any idea how I go about using this award - have you heard anything?

**Comment by sr320** [comment]
I will check; in the meantime you can list out all relevant details needed for ordering supplies here.

**Comment by jldimond** [comment]
Thanks, here are the items I need:

T4 DNA Ligase 
100,000 units	M0202L	$256.00	1	$256.00

HpaII 
10,000 units	R0171L	$249.00	1	$249.00

Phusion® High-Fidelity PCR Master Mix with HF Buffer 
100 reactions (50 µl vol)	M0531S	$175.00	1	$175.00

MspI 
5,000 units	R0106S	$62.00	1	$62.00

PstI-HF® 
10,000 units	R3140S	$62.00	1	$62.00

**Comment by sr320** [comment]
@jldimond -Was the award for $4909?

**Comment by jldimond** [comment]
Yes, that was the amount I requested.

**Comment by sr320** [comment]
@kubu4 - when you get a chance can you order on `65-5164`?

**Comment by jldimond** [comment]
I'd like to add another item from Qiagen:

Cat No./ID: 69504
DNeasy Blood & Tissue Kit (50) $161.00

Thanks!
