### ISSUE TITLE
Potpourri

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#235]
Medley of random stuff that should be hit upon.

- [ ]  status of genomes
- [ ]  CSF
- [ ]  Hollie's arrival
- [ ]  Status of Oly Pop Gen analysis
- [ ]  International Conference on Shellfish Restoration

**Comment by sr320** [comment]
@kubu4 can you confirm which have 2nd version- and url

**Comment by kubu4** [comment]
Sorry, didn't catch this before. Both genomes have 2nd versions:

Geoduck: http://owl.fish.washington.edu/P_generosa_genome_assemblies_BGI/20160512/
Oly: http://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20160512/
