### ISSUE TITLE
[purchasing] Supor 47mm diameter 0.2um filters

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#237]
Looks like taylor filter apparatus  is 47 mm  so could you please order some 0.2um filters (Supor) at that diameter- thanks 
on 63-4279

(unless of course you find some in the lab)

**Comment by kubu4** [comment]
Will 1pk of 100 filters suffice?

**Comment by sr320** [comment]
Sure lets start with that.

**Comment by kubu4** [comment]
Thanks.
