### ISSUE TITLE
Supplies for Taylor Hatchery

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#238]
On Tuesday (July 5) - @emmats will head to hatchery in ucar (61-0221). Assuming @kubu4 is available- he should be able to help @emmats gather up, make the following in the AM.

- For water sampling we need 25% TCA (how much per filter, Brook?)
- I will get small ziplocs from Brook
- 7.5% MgCl2 in ultrapure water
- paraformaldehyde that can be diluted to 4%
- molecular grade ethanol
- 1xPBS
- some extra ultrapure water

**Comment by kubu4** [comment]
@emmats I'll need a rough idea of volumes needed for these reagents...

**Comment by kubu4** [comment]
We do not have any paraformaldehyde. Looks like earliest delivery would be Tuesday (7/5/2016).

**Comment by sr320** [comment]
Seems like Rhonda might have this at hatchery- @emmats can you please
confirm with her?

**Comment by kubu4** [comment]
Looking at the [Oyster Sampling protocol](https://docs.google.com/document/d/1v9c7yEtXZ-eKGE6zFOkY7U1R7dc5mGe5Ru8nCp5INh0/edit), it looks like Rhonda just needs the following:

- ultrapure H2O
- TCA
- PBS

I'm planning on sending @emmats with a carboy of ultrapure H2O, solid TCA, and 1L of 1x PBS. Does anyone have a recommended pH for the 1x PBS? Also, someone should let me know ASAP if 1L of PBS will be insufficient.

I'll also send any of the physical supplies (filters, tubes) if they're waiting for me in the main office.

**Comment by kubu4** [comment]
Also, looks like no one has paraformaldehyde...

**Comment by kubu4** [comment]
@emmats just texted me & says the hatchery visit has been rescheduled for Thursday (7/7/2016).

**Comment by kubu4** [comment]
@emmats will be picking up supplies tomorrow morning for Thursday's trip to the hatchery.

Anyone have desired pH for the 1x PBS?

**Comment by kubu4** [comment]
@emmats informed me that she will now be going to the hatchery on Friday (7/8/2016).

**Comment by sr320** [comment]
Updated list 

_Supplies needed_

- 1. 1L screw cap bottles (or larger) for filtering water
- 2. Tube rack that will fit cryo tubes


Sampling dates
Sunday July 10
Tuesday July 12
Thursday July 14 - Emma and maybe Damon
Saturday July 16
Monday July 18 - maybe Emma
Wednesday July 20 - maybe Emma
Friday July 22
