### ISSUE TITLE
Gff filters

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#239]
Please order 
http://www.sigmaaldrich.com/catalog/product/aldrich/z242519?lang=en&region=US&gclid=CNfYn6zg0M0CFU1rfgodWuwHww

On
610221

**Comment by kubu4** [comment]
That link indicates that this product has been discontinued. I'll look for something similar elsewhere and post link for approval before ordering.

**Comment by sr320** [comment]
Thanks

**Comment by kubu4** [comment]
OK, I found 'em. Same thing - not a substitute, so will order immediately w/o waiting for approval.

They are now cat# WHA1825047

http://www.sigmaaldrich.com/catalog/product/aldrich/wha1825047?lang=en&region=US

**Comment by sr320** [comment]
Great- thanks
