### ISSUE TITLE
RADseq sequencing payment

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#241]
I anticipate having RAD libraries ready to send to UC Berkeley for sequencing on Monday and I'd like to pay for this through the Hall Award. How should I go about this?

**Comment by jldimond** [comment]
Also, in case anyone is interested, here are UC Berkeley sequencing rates. I am planning on 100bp paired-end on the HiSeq 4000. 

[Rates_April2016_GSLFGL.pdf](https://github.com/sr320/LabDocs/files/404483/Rates_April2016_GSLFGL.pdf)

**Comment by sr320** [comment]
award for $4909? If so your budget # is 65-5164, "SAFS HCGR 1"

Maybe credit card

**Comment by jldimond** [comment]
Yes, that's the one.

So if Adam Leache has an account with UC Berkeley, maybe I could just give him that budget info? Or put UC Berkeley in touch with you for credit card?

**Comment by sr320** [comment]
Yes - easiest to just transfer to his account.

**Comment by sr320** [comment]
From Adams email sounds like you need to confer with UC Berkeley and see  if they will take credit cards. If so, they would contact Sam for payment.

**Comment by jldimond** [comment]
@kubu4, do you have a phone number I can put on the sequencing order form? I am entering you as the funds contact. FYI, I am going to have the samples sent out for sequencing with some others in the Leache Lab within the next two weeks. I'll send you the order form once it goes out so you have that information.

**Comment by kubu4** [comment]
2066823273

**Comment by jldimond** [comment]
Thanks

**Comment by jldimond** [comment]
Wondering if someone can offer some advice on read length. If I do 100 bp paired end reads, will that be adequate for getting decent blast hits to coral and symbiont transcriptomes? The one other paper I know of that has done RADseq work with corals used 50 bp reads to map back to transcriptomes, but that seems too low. Is it worth spending the extra $500 to get 150 bp paired end? I have the money but lean towards saving it for the next round of sequencing.

**Comment by sr320** [comment]
Remember even with 400bp reads you might not get mapping to transcriptome
(this is genomic DNA). I would say going from 100bp to 150bp PE is very
unlikely to get you any signifcant increased chance of better mapping to
transcriptome (or genome). If you had a complete genome I might say yes, as
this could help in distinguising duplicated regions.

**Comment by kubu4** [comment]
Additionally, you may even consider dropping the paired end approach. It's good for resolving spatial info, but since you're going genomic to transcriptome, you'll lose most of the benefit of paired end. Single end would save you some cash, too.

**Comment by jldimond** [comment]
Thanks for your thoughts. I am not married to the paired end approach, but considering that this is ddRAD, with paired end reads you are essentially sequencing both sides of a cut site, which effectively doubles the number of tags that you get, right? Also, their turnaround time for single end 100 is longer due to lower demand (not necessarily a good reason to spend more $$, I realize). I was also thinking that I could do 100 bp this time around to help develop a good set of loci, then go to 50 bp for subsequent work.

**Comment by sr320** [comment]
Excellent point - however if we assume we will have a genome one day.....
the PE might pay off.  What is the fragment size of the library?

**Comment by jldimond** [comment]
Fragment size is 500 bp

**Comment by jldimond** [comment]
Keep in mind this is different from traditional RAD...my understanding is that it is easier to build contigs with traditional RAD due to the random shearing on one end of the fragment. With ddRAD the fragment cuts sites for a particular locus should not vary much.

**Comment by sr320** [comment]
I would go PE.

**Comment by jldimond** [comment]
OK, 100PE it is - thanks

**Comment by jldimond** [comment]
Here is the sample submission form. I believe the total should come to around $2424. Samples were shipped out yesterday.

[GSL_Submission_Form_2016_4000_JD001.pdf](https://github.com/sr320/LabDocs/files/420658/GSL_Submission_Form_2016_4000_JD001.pdf)

**Comment by jldimond** [comment]
Got my data! 32GB. I will put it in my folder on Eagle unless you think there is a better place for it.

**Comment by kubu4** [comment]
Nice! Please put the data in the Owl web/nightingales/<species> folder. 

Or, if you happen to have a link for the data, I'm more than happy to do this (since you may not have access to Owl).

**Comment by jldimond** [comment]
OK, I'll forward you the email with all the info - thanks. Once the data is downloaded to Owl, will I be able to work on it remotely?

Did they contact you for payment?

**Comment by sr320** [comment]
@kubu4 so we should be able to point him to a protocol?  

That is.... 
https://github.com/sr320/LabDocs/blob/master/DMPseq.md

This would be a good time to check tires on this document.

**Comment by kubu4** [comment]
@jldimond Yes, you'll be able to work on it remotly - just like Eagle. No, they did not contact me regarding payment.

@sr320 Protocol testing is a good idea (however, I can already tell it needs to be updated to add things like NGS spreadsheet and updating readme files), but we have not granted write access to `nightingales` to anyone other than you and myself.
