### ISSUE TITLE
Reconciling BGI charges

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#243]
@kubu4 according to my records BGI has only charged us for 1 full genome, and 1 half - thus still need to invoice us for $11k. Can you try to see if you come to the same conclusion or do you have different information?

**Comment by kubu4** [comment]
This is correct. When we pushed to have them invoice for the Oly budget (to meet budget closing date), they also inexplicably invoiced for the second part of the project.

Geoduck is still still has outstanding $11k balance.

**Comment by sr320** [comment]
Ok - let's leave this open until we get the final invoice.
