### ISSUE TITLE
Quickly losing free disk space on Eagle

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#245]
Eagle was filling up fast today- got down to ~7GB free. I deleted some backups to give us about 400GB free, but we seem to still be losing free space.

**Comment by kubu4** [comment]
Noticed the space consumption. I killed the notifications (because they were driving me crazy). Haven't had time to look into cause. Will have time tomorrow.

**Comment by sr320** [comment]
As of this AM we are gaining free space back (without me removing anything)
up to 600 GB now

**Comment by kubu4** [comment]
Interesting... I'll glance at this after lunch today.

**Comment by kubu4** [comment]
Couldn't figure anything out. However, I logged in today and noticed that Cloud Sync (the backup service to the unlimited UW Google Drive space) was paused. Possible that space consumption was related to log files or something? I've re-activated Cloud Sync. We'll see if drive space ends up getting consumed again...

**Comment by sr320** [comment]
Thanks - currently 812 GB available.

**Comment by sr320** [comment]
Stable .... closing
