### ISSUE TITLE
Identify Geoduck Hemolymph sample for analysis

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#246]
We have about 60 samples lets get a short list based on stage etc

**Comment by grace-ac** [comment]
I have list of the sampled geoducks, gender, and stage. I can't find which tissue samples have already been used for proteomics.

**Comment by sr320** [comment]
The samples used for proteomics are in these Google Drive Folder
https://drive.google.com/open?id=0B9V_gF766XZAeEthM3k3a2FLOHc

**Comment by sr320** [comment]
Sorry - this url should have all three subdirectories

https://drive.google.com/open?id=0B9V_gF766XZAQUQwT1JXYVdxb1U

**Comment by kubu4** [comment]
I've added this URL to the Wiki page for the "project-geoduck-repro":

https://github.com/RobertsLab/project-geoduck-repro/wiki

There's nothing else there, so I'm not sure if a different means is being used to track progress on this project.

**Comment by grace-ac** [comment]
Here's the list of the hemolymph samples. Any info missing that would be helpful? 
https://docs.google.com/a/uw.edu/spreadsheets/d/1FR7lH_SCV4KeG69HUwOIrYKCB6hprH8q3xa-XW_6VX4/edit?usp=sharing

**Comment by sr320** [comment]
Thanks have added to https://github.com/RobertsLab/project-geoduck-repro

**Comment by kubu4** [comment]
I looked at the spreadsheet Grace put together. I think we should tweak (simplify) the spreadsheet to encompass all geoduck samples collected and indicate which samples (and type) were used for RNAseq and proteomics. Something like:

|ID|Gender|Stage(integer)|Stage(text)|Tissue_proteomics(y/n)|Hemo_proteomics(y/n)|RNAseq(y/n)|Hemolymph(y/n)|
|---|---|---|---|---|---|---|---|

This would make the spreadsheet "machine readable" and a little easier to organize. Could add columns for dates, links to images, etc.

**Comment by sr320** [comment]
but would this not be a new issue? :)
My guess is you were looking for two light flashes.

**Comment by kubu4** [comment]
:+1:

**Comment by kubu4** [comment]
Thinking was hemolymph spreadsheet could be reorganized. How many times has the light flashed now?

**Comment by sr320** [comment]
![screenshot 2016-09-15 at 5 01 48 pm](https://cloud.githubusercontent.com/assets/4442039/18571326/5089976a-7b66-11e6-9d0d-48cedddfeee7.png)

**Comment by sr320** [comment]
➡️  https://github.com/RobertsLab/project-geoduck-repro/issues/5
