### ISSUE TITLE
[purchasing] storage containers for 50ml Falcon tubes

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#247]
Something for 50ml falcon sample storage

63-4279

**Comment by kubu4** [comment]
Do we need more than what we currently have (plastic blue boxes on the shelf in 209 with the microfuge tube boxes)?

**Comment by sr320** [comment]
I do not see any - lots of 15 ml green but no blue...

![snap](http://eagle.fish.washington.edu/cnidarian/skitch/Screenshot_9_6_16__11_37_AM_1D7F4467.png)

**Comment by kubu4** [comment]
Whoa! Thanks for checking.

**Comment by jldimond** [comment]
I have two of the blue ones for my samples...I am done for now but will
need them again in November.
