### ISSUE TITLE
Add Summary of hemolymph samples to notebook

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#248]
@grace-ac - just a reminder to add info on the hemolymph samples (and any other stuff 😺 ) to 

https://genefish.wordpress.com/

**Comment by grace-ac** [comment]
Do i just type in the main box up top and write it like it's a notebook entry? 
![screen shot 2016-09-09 at 1 46 30 pm](https://cloud.githubusercontent.com/assets/14934314/18402399/0369b4dc-7694-11e6-8f0e-ce90eec17717.png)

**Comment by sr320** [comment]
You cannot break anything - so go ahead and try- you can also maybe click
on the pencil in the top right to create a new post.
Just be sure to document what you do each day your in the lab so it does
not pileup.
thanks
