### ISSUE TITLE
Define Purchasing Protocol

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#25]
Define how purchasing is done - going to github?
keeping form? 
I think last week wrong item was purchased because user did not provide part no.

**Comment by kubu4** [comment]
I say move to github.

What was the wrong thing ordered? First I'm hearing of this.

**Comment by sr320** [comment]
Just heard Grace's order was wrong- the fixative product. 
The new order was a fix / stabilize mix (she did not know) so half samples were loss.
or maybe she provided wrong part #?
- via Brent

**Comment by sr320** [comment]
Note the contributing.md is a good place for instructions on issues 

![](http://eagle.fish.washington.edu/cnidarian/skitch/New_Issue_·_sr320_LabDocs_1A5B5B2D.png)


For examples could outline procedures for using issues for purchasing etc.

**Comment by kubu4** [comment]
Ah. I know what this is. This is my fault, but part of the issue was that Qiagen didn't/doesn't carry the part number she listed (it's on their site, but not available for purchase). So, I poked around and thought I ordered the same kit she previously used. Damn.
