### ISSUE TITLE
Decide on Oly paper (transplant) journal

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#250]

**Comment by sr320** [comment]
Lets get this to Axios.....

**Comment by grace-ac** [comment]
This is what Axios looks like when uploading a file:  http://axiosreview.org/get-started/send-us-an-article/ 

Any specific journals? Also, should I put my email down or would you prefer someone else involved with the paper?

**Comment by sr320** [comment]
journals

1 Biological Conservation http://www.journals.elsevier.com/biological-conservation/

2 Aquatic Ecology http://link.springer.com/journal/10452

3 Marine Ecology http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1439-0485

**Comment by grace-ac** [comment]
website wasn't working for a while, but now it is!
@sr320 
should i be submitter and give my email for axios?
do you want it to be double blind?

**Comment by sr320** [comment]
Lets just submit to journal directly 
-
Can you prep for Marine Ecology?

**Comment by grace-ac** [comment]
is there a word doc or google doc somewhere for it? i only have pdf.

**Comment by grace-ac** [comment]
also i have to make an account with marine ecology - my contact info still? do you want to be cc'd?

**Comment by sr320** [comment]
[OluridaSurvey_V7.docx](https://github.com/sr320/LabDocs/files/642942/OluridaSurvey_V7.docx)

**Comment by sr320** [comment]
Your contact info is fine

**Comment by grace-ac** [comment]
link to word document: https://drive.google.com/a/uw.edu/file/d/0B_Kednl1tNImaC1WTGpQRzR5RjA/view?usp=sharing 

this is the edited version for Marine Ecology. Any changes you'd like? I can submit this today.

**Comment by sr320** [comment]
Just change corresponding author to myself, then you can submit.

**Comment by grace-ac** [comment]
okay!

and marine ecology is actually pretty involved. they want:
- running head
- keywords
- author emails, institutions
- if there is funding to report for the submission
- has it been published elsewhere? does PeerJ count?

**Comment by sr320** [comment]
- Olympia oyster population differences
- oyster, reproduction, growth, transplant, temperature
- should be in PeerJ preprint?
- This work was funded by Washington Sea Grant, University of Washington,
pursuant to National Oceanographic and Atmospheric Administration Award No.
NA10OAR4170057 Projects R/LME/N-3. The funders had no role in study design,
data collection and analysis, decision to publish, or preparation of the
manuscript.
- A PrePrint has been posted (PeerJPreprint) - no peer review version has
been published.

On Tue, Dec 13, 2016 at 11:49 AM grace-ac <notifications@github.com> wrote:

okay!

and marine ecology is actually pretty involved. they want:

   - running head
   - keywords
   - author emails, institutions
   - if there is funding to report for the submission
   - has it been published elsewhere? does PeerJ count?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sr320/LabDocs/issues/250#issuecomment-266842007>, or mute
the thread

**Comment by grace-ac** [comment]
done!

**Comment by sr320** [comment]
👍
