### ISSUE TITLE
Login info for Hummingbird and Owl

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#251]
Wondering if someone can tell me what I should use for login and passwords for Hummingbird (and Owl if necessary). Just want to make sure I have this information before I start working on the RAD data. I can't remember if I have an account or not - I think I only have one for Eagle. 

No rush - Thanks!

**Comment by kubu4** [comment]
You can always use the srlab account for Hummingbird, but I'm more than happy to set you up with your own user account. I'll shoot you an email with login info for all this junk.
