### ISSUE TITLE
Oyster sampling at Manchester

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#253]
Day 0 - Sunday
24-48 hour Monday/Tuesday

**Comment by sr320** [comment]
As of now -  we are planning to go for a sampling on Monday 12 at Manchester - This should only take a few hours and Katherine will coordinate with @kubu4. She and Sam will sample.

Then (tentatively) on Monday the 19th- @grace-ac @kubu4 and @sr320 will go out and sample post OA exposure. By this time Katherine will be gone and a detailed protocol in place.

@grace-ac @kubu4 - Are you all available the 19th if this ends up happening?

**Comment by grace-ac** [comment]
Yes

**Comment by kubu4** [comment]
Both Mondays work for me.

**Comment by sr320** [comment]
Standing by to hear from Natalie re the next sampling
