### ISSUE TITLE
No space left on Hummingbird

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#257]
I've had some trouble getting ipyrad to run on Hummingbird, and after trying to install a new environment it became clear that there is essentially zero disk space on the local drive. I'm hoping that this was the root cause of all the issues. I tried emptying the trash and deleting some very old downloads, but this did not free up enough space.

**Comment by kubu4** [comment]
Everything needs to be run in your directory on the toaster external HDD. This includes the iPyrad installation. That should take care of the space issue.

**Comment by kubu4** [comment]
I'll also look into getting rid of some other, obsolete data on Hummingbird when I get back from Manchester, in case iPyrad is using a location on Hummingbird to write some temporary files or something like that.

**Comment by jldimond** [comment]
OK - thank you. I guess I was thinking that I had to run it on the local drive for the sake of speed/efficiency.

**Comment by kubu4** [comment]
You are correct. In this instance, the local external HDD, instead of the server.

**Comment by sr320** [comment]
@jldimond  do note the local drive is partitioned.

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/hummingbird_1D89C349.png)

You can read/write to the `Data` partition, it has about 300 GB free

**Comment by sr320** [comment]
Diving deeper - seemed like the Hummingbird partition was filled up with Andrew's stuff. 

I freed up 50 GB on this partition. - but NO data, personal files should live on this partition. 

This is meant for OS / applications / etc.

**Comment by kubu4** [comment]
Ah! Thanks for that!

**Comment by jldimond** [comment]
Thanks for looking into it. But, just to clarify, I should still install conda/ipyrad onto the toaster HDD?

**Comment by sr320** [comment]
I suggest software goes on Hummingbird os partition - data read write to
toaster/ and if error - problem read/write to Data partition.

**Comment by kubu4** [comment]
Conda is already installed on Hummingbird. To verify, type the following at the Terminal prompt:

```which conda```

See @sr320 comment above for data storage location/priority.
