### ISSUE TITLE
Number drawers & cabinets

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#258]
Print sequential numbers (in large font) and tape to individual cabinet doors and drawers in FTR 209 & 213.

**Comment by kubu4** [comment]
Thanks for numbering, @grace-ac. Now, you're going to want to strangle me. Can you please re-number everything, but with much, much bigger numbers? Sorry...

**Comment by sr320** [comment]
Remember some of us are quite old with poor eyesight :)

**Comment by kubu4** [comment]
Haha! Exactly this! 👍 😿

**Comment by grace-ac** [comment]
Haha! Of course! No problem. After I put them up I thought they might be a bit too small.
