### ISSUE TITLE
Create lab inventory

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#259]
Use numbering system in [Issue 258](https://github.com/sr320/LabDocs/issues/258) to document contents of drawers and cabinets in this Google Sheet: [Roberts Lab Inventory](https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit?usp=sharing).

Please separate multiple items in the "Contents" cells with semi-colons.

**Comment by kubu4** [comment]
Nice work, @grace-ac! Thanks!

Please combine the two separate spreadsheets into a single sheet (and update QR code printouts in both labs). This will simplify searching for stuff (e.g. if someone doesn't know which room something is stored in, opening and searching through two different spreadsheets is tedious).

**Comment by grace-ac** [comment]
Okay all done! Just need to print out two copies of the qr code in the google drive folder i shared with you and we're all set.

**Comment by sr320** [comment]
And the app, so that we can just ask "Alexa, where are the test tubes?"

**Comment by kubu4** [comment]
:+1:

**Comment by grace-ac** [comment]
https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=0

**Comment by sr320** [comment]
also @ https://github.com/sr320/LabDocs/blob/master/Lab_Inventory.csv

**Comment by kubu4** [comment]
With the CSV version on GitHub, should that become the canonical version? Or, is the GitHub CSV "linked" to any changes that happen on the Google Doc?

**Comment by sr320** [comment]
It is not linked...
no strong opinion on canonicalness
