### ISSUE TITLE
Fix and Validate procedure for Sequencing DMP

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#262]
In using https://github.com/sr320/LabDocs/blob/master/DMPseq.md

I have found several issues 
- see https://github.com/hputnam/project_juvenile_geoduck_OA/issues/4

---

I want to find all of our C gigas libraries (data) that were used to study methylation, fairly standard use.

in Google Docs spreadsheet Next Gen Seq Library Database- https://docs.google.com/spreadsheet/ccc?key=0AtV_gF766XZAdHRlUHJMd0k4S2RpdTZqbjFob2NJb2c&usp=sharing

The library type was not always evident.. nor why it was done..

and in the Nightingales Fusion table https://www.google.com/fusiontables/DataSource?docid=13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN#rows:id=1

There should just be one entry per library (where PE can be accessed). Many are in this fashion, but not all. 

---

Here are some things I think should be implemented

for [Sequence Job Submission sheet](https://docs.google.com/spreadsheet/ccc?key=0AtV_gF766XZAdHRlUHJMd0k4S2RpdTZqbjFob2NJb2c&usp=sharing) 
- [ ] add column 1 with sequential numbering so it could be easily sorted and we have simple IDs
- [ ] include in DMP exactly what needs to be added
- [ ] include in DMP acceptable information and format (ie latin? abbreviation?)

for [raw data Nightingales table](https://www.google.com/fusiontables/DataSource?docid=13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN#rows:id=1)
- [x] detail the two stage process (google table to fusion table). 
- [ ] include in DMP procedure / tricks for getting PE data in single row.
- [ ] include in DMP information required / highly recommended.

and
- [ ] Document and implement a GitHub based back up of both tables.

**Comment by kubu4** [comment]
For some clarification before diving in:

Fusion Table - I thought this was to track all data files, not projects. Thus, all PE files have their own lines.

Sequence Job Submission sheet - I thought this was to track projects/libraries and not all the individual data files. 

Otherwise, aren't the two sheets redundant (maybe they should be consolidated into a single database)?

**Comment by sr320** [comment]
Lets discuss, maybe at labmeeting.

But generally I see Fusion table as outward facing - what we would share,
library specific and run specific?

I would say correct on Sequence jobs submission sheet- this should be
library specific.

Re consolidation - that might be a very good option.

**Comment by sr320** [comment]
@seanb80 
Take a look at all this and see what you think....
Maybe we can meet Friday and discuss how to proceed

**Comment by seanb80** [comment]
Interim combined file found [here](https://docs.google.com/spreadsheets/d/1pUMuv_ateGmuwDbr6-7k_C9sFF6hV4MB6AX6oZd4kwQ/edit?usp=sharing)

**Comment by sr320** [comment]
Errors / artifacts in Nightingales sheet?

Missing info, links to incorrect files (why are there links in the first column?) and "JD" files are not O lurida.

![screen capture on 2016-12-28 at 15-21-25](https://cloud.githubusercontent.com/assets/4442039/21533637/834c02ee-cd11-11e6-8339-780d17875f9c.gif)

**Comment by kubu4** [comment]
I think the "links" in the first column are an auto-link attempt by Google Sheets.

Also, @seanb80, I thought you were working in a temp worksheet?

**Comment by seanb80** [comment]
I was, but Steven asked me to merge them today. I tried to retain what new information there was, but now realize that might be more difficult than I initially thought. I might have to remerge them with the changed documents?

**Comment by sr320** [comment]
I told him to go ahead and move - as it was good to go.

Not auto- look closely as gif :) URL does not correlate with file name.

**Comment by seanb80** [comment]
I can't explain why google is attempting to turn things in to hyperlink, in the temp sheet they're not links. I'll work on fixing that.

**Comment by kubu4** [comment]
The merge screwed up a lot of stuff. Any objections to reverting to the pre-merge version?

**Comment by sr320** [comment]
No objections from me.

**Comment by kubu4** [comment]
I've reverted Nightingales Google Sheet back to pre-merge.

Reason: The merged version screwed up row alignments of multiple columns and would've been too time consuming to manually fix.

**Comment by seanb80** [comment]
Once the old version is finished being updated I can rejoin them pretty easily, and will fix the row alignment issues for the end product. I'm pretty sure the alignment issues were caused by the removal of the second file for paired end sets.

**Comment by kubu4** [comment]
I wasn't going to do much updating of the original Nightingales Google Sheet. It just needed a lot of fixing, so I figured it'd be best to get back to where it was before things got wonky. 

Feel free to re-do the merge in your temp file. I'll look it over and if it's good, we can just copy/paste it into the official Nightingales Google Sheet.

**Comment by sr320** [comment]
I guess I am not clear on the "Merge". I thought it the sheet was just
being revised updated in temporary location then cut/paste over the old
sheet.

With primary revisions being a couple of new columns and formatting
regarding paired end libraries...

**Comment by kubu4** [comment]
I also wasn't expecting a merge of any kind. I was in the same thought process as Steven.

**Comment by seanb80** [comment]
I think it's an issue of the method by which the revisions happening. I pulled down a csv copy of the sheet and operated on it locally, but in the intervening time the sheet had changed with new information added inc notebook links, who did extractions, etc. I attempted to preserve that new information, but that didn't work obviously.

**Comment by seanb80** [comment]
Updated main Nightingales spreadsheet once more. Hopefully this time works better!

**Comment by kubu4** [comment]
This looks pretty solid! Thanks so much!

**Comment by kubu4** [comment]
Part of this discussion should also include directory structure. I bring this up because I see that @seanb80 is adding the most recent set of geoduck data from Hollie's Genewiz runs to a sub-directory within the ```owl/nightingales/P_generosa``` folder.

Should all files go directly into the species folder? If not, when are sub-directories warranted?

**Comment by seanb80** [comment]
It should, I did that as a temporary measure for the initial run of my Owl Uploader script. I didn't want to inadvertently mess up existing readme and checksum files. I was planning on moving things in to the species directory/append information to the existing files if script behavior went as expected

**Comment by sr320** [comment]
Correct not going into sub directory

**Comment by sr320** [comment]
I think we are close on this - I will close and lets just create new issues as they arise.
