### ISSUE TITLE
Best option for lab notebooks?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#265]
With a few new students starting, I thought it would be good to reconsider best notebook options..

This might be a contender?
https://github.com/jabranham/github-pages-academic-starter-kit

**Comment by sr320** [comment]
Having played around with it a little more I am thinking what Hollie set up makes sense -
see repo-
https://github.com/sr320/sr320.github.io

seems like `feed.xml` does the trick

**Comment by kubu4** [comment]
Where is that feed.xml file? I don't see any recent commits to your repo? However, the posts definitely show up in my feed reader when I put in the URL...

**Comment by sr320** [comment]
not a file- if you just go to 

https://github.com/sr320/sr320.github.io/feed.xml 

this should work as a feed? not confirmed though

**Comment by kubu4** [comment]
Ah. That link 404s, though. Is that expected? 

However, my feed reader definitely detects site as a feed without the feed.xml addition to the URL. Do other services need the feed.xml addition to the URL?

**Comment by sr320** [comment]
I _think_ ifttt does...

this should open in chrome though https://sr320.github.io/feed.xml  ?

I edited the original url I posted.

**Comment by kubu4** [comment]
Ah! That opens a RSS feed page!

**Comment by sr320** [comment]
For the record this would be what a "notebook" might look like using this new format...

https://sr320.github.io/
https://hputnam.github.io/Putnam_Lab_Notebook/

**Comment by kubu4** [comment]
Backup for offline viewing is VERY fast (I know the notebook is still pretty new, but I think not having the overhead of the WordPress database junk has a pretty decent impact). Here's the command to use to try out offline backup (you'll need the program ```wget``` - not installed by default on OSX. Can install with homebrew, though):

```wget --mirror --convert-links --page-requisites --no-parent -e robots=off --no-check-certificate https://hputnam.github.io/Putnam_Lab_Notebook/```

After download completes, open the ```index.html``` file with your browser and check otu the offline version of the site!

**Comment by sr320** [comment]
now with comments!

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/CoGe_on_Fidalgo_Sibs_–_quarter-shell_–_Staging_for_my_Lab_Notebook_1D918681.png)

**Comment by kubu4** [comment]
Cool! I didn't realize this was built-in!

**Comment by sr320** [comment]
yep - just have to add your Disqus shortname into config file.

**Comment by sr320** [comment]
Will go with 
https://sr320.github.io/

I will try to tighten up mine and see if folks cannot just fork mine- the only disadvantage is searching the code online but I think we can remedy that later (if need be)

and confirmed feed can be used to pipe https://www.evernote.com/l/AAoFgCDiOfBEgpPyUh_d3YH7YB0KbVcgyMY
