### ISSUE TITLE
Some introductory materials

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#268]
With new personnel on boarding (as well as those old hands that have lost your way) here are a few items to tackle in the next few weeks to get familiar with current activities

- [x]  Get a GitHub account
- [ ] [check G+ community](https://plus.google.com/u/0/communities/113620706114893538778) - post questions 
- [ ]  take a look at this [recent chapter on mollusc genomics in aquaculture](https://drive.google.com/a/uw.edu/file/d/0BwVK83sm6XQGSDdRaG5lLXNsaEE/view?usp=sharing)
- [ ]  browse the [text for our bioinformatics class](https://drive.google.com/open?id=0BwVK83sm6XQGWGNZUmlLckdZU1E) (we will go over this in detail later).
- [ ]  learn [Markdown](http://www.markdowntutorial.com/) ; see [also](https://guides.github.com/features/mastering-markdown/)
- [ ]  browse [some notebooks](http://faculty.washington.edu/sr320/?page_id=246)
- [x] **post a comment below (something beyond plain text)**
- [ ] read this [paper on methylation](http://eagle.fish.washington.edu/cnidarian/Briefings%20in%20Functional%20Genomics-2014-Gavery-217-22.pdf)

--- 
⚠️  note some links to Gdrive require using your UW account. 📚 

---

One of the first things to do will be create a lab notebook online. There are a few suitable options we will discuss in lab meeting.

**Comment by yaaminiv** [comment]
![My comment beyond plain text](http://data.whicdn.com/images/80803601/original.jpg)

**Comment by sr320** [comment]
👍

**Comment by jldimond** [comment]
[_Moment of zen_](https://www.youtube.com/watch?v=VoLQEJYA25o)

**Comment by sr320** [comment]
does this work?

<iframe width="560" height="315" src="https://www.youtube.com/embed/VoLQEJYA25o" frameborder="0" allowfullscreen></iframe>

**Comment by kubu4** [comment]
----
DATA
High-throughput Sequencing Data: http://owl.fish.washington.edu/nightingales/

----
COMPUTING
Roberts Lab Computers and printers (roadrunner and hummingbird are the high-powered computers for general use): https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit?usp=sharing

Server (named Owl; I'll set  you up with login info in a bit): https://128.95.149.83:5001/index.cgi

-----
GENERAL LAB

Roberts Lab GitHub: https://github.com/sr320/LabDocs

Purchasing requests (submit as Issue on GitHub; please use Purchasing label): https://github.com/sr320/LabDocs/issues

Shipping/mailing address: Fishery Sciences, 1122 NE Boat St., Rm. 116, Seattle, WA 98105

Roberts Lab GitHub wiki (protocols for RNA isolation, DNAsing, reverse transcription, qPCR): https://github.com/sr320/LabDocs/wiki

Roberts Lab general protocols/recipes: http://genefish.wikispaces.com/protocols

Primer Database: https://docs.google.com/spreadsheets/d/14m2kkFhxcoKWWIGoAD_7VOVsAg9wilME2UcSLqfnqLI/edit?usp=sharing&authkey=CP736rQK

Lab Calendar: https://calendar.google.com/calendar/embed?src=mrc305%40gmail.com&ctz=America/Los_Angeles

----
SAFETY
UW Lab Safety Manual: http://genefish.wikispaces.com/UW_LabSafety

**Comment by sr320** [comment]
![200w](https://cloud.githubusercontent.com/assets/4442039/18725353/d41410aa-7ff4-11e6-8c6d-84be18206fca.gif)

**Comment by Ellior2** [comment]
![Under pressure](https://img.buzzfeed.com/buzzfeed-static/static/enhanced/web03/2012/9/29/22/enhanced-buzz-21809-1348972160-3.jpg?no-auto)

**Comment by MeganHintz** [comment]
![image](https://cloud.githubusercontent.com/assets/14929070/18756235/0181e972-80a4-11e6-8587-742e83901e89.png)

**Comment by sr320** [comment]
Three basics

1) G+ Community (a primary means of communication) Monitor / post stuff / questions @ https://plus.google.com/u/0/communities/113620706114893538778

2) GitHub (a lot is going on here) but for now, just try to at least monitor when you are mentioned or assigned something. This is one core repo - https://github.com/sr320/LabDocs where we will try to centralize "stuff"

3) Lab Calendar - again, just be aware of.
