### ISSUE TITLE
Cnidarian Sequencing

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#27]
Lets get something in this month..

---

In terms of organisms that would be easily accessible, I would suggest either Aiptasia pallida or Anthopleura elegantissima, both anemones. Aiptasia is becoming the lab rat of choice for folks studying the molecular and cell biology of cnidarian-dinoflagellate symbiosis. It's a tropical species that is nearly circumglobal, and is also the bane of the tropical reef aquarium keeper's existence due to it's ability to hitchhike with live rock and spread throughout an aquarium. But these characteristics happen to make it great for biologists who want an easy-to-keep model organism. It's also versatile because it can live without symbionts entirely or be successfully infected with a range of symbiont genotypes, which is generally the exception rather than the rule among symbiotic cnidarians (which has also lead to some criticism regarding its appropriateness as a model for cnidarian symbioses). They could probably be collected for free from an aquarium or an aquarium store; otherwise you can buy them from Gulf Marine Specimen in Florida. The advantage of the latter option is that you could be more certain of their origin.

Anthopleura is also a really interesting anemone because it associates with two entirely different symbionts, and can also live symbiont free. It has a long history as a model organism--going back to the 1960s when it was essentially the first species in which the nutritional role of dinoflagellate symbionts was confirmed. And it's local, easy to keep, and I have some in the sea table at Shannon Point right now. The only downside I see to them is that the coral and symbiosis research communities are less interested in temperate species because, well, they aren't tropical and that's where all the buzz is.

I suppose you could also get some coral material from an online supplier. But they would not provide much taxonomic information (which can be tricky if you only have a fragment) or geographic information, so not ideal. But if you want to wait a few more months, there's a good chance I'll be going to Belize this spring (May or June) and could probably bring back some fixed material. That reminds me that it would be good to talk sometime about preservation methods for my field work to ensure that I get good material for RNAseq and bisulphite sequencing--this will be important to know since field conditions, and even marine lab conditions, are very basic.

What's the overall goal? This may also factor in to which species would be the best...

**Comment by sr320** [comment]
Jay  biringing smaples next week

**Comment by sr320** [comment]
Samples in the fridge

**Comment by sr320** [comment]
Not looking good

**Comment by kubu4** [comment]
They must be on some sort of circadian clock.  They looked really good this morning, but the other afternoon I thought they were toast.

**Comment by jldimond** [comment]
If their tentacles are contracted it's usually not a big deal. Light, water flow, and food are the three main factors that will cause them to expand. If one or more of these cues is insufficient, they will contract to save energy. If this was a long term thing, I would suggest alternating periods of light/dark (night and day), some water motion, and occasional feeding. But for a little while they should be fine as is.

**Comment by jldimond** [comment]
If someone happens to go back in there, you could empty the last bit of seawater in the white bucket into the anemone container (might need to pour some old water out).

**Comment by sr320** [comment]
@jldimond - does anything need to done today (i.e. prep water bath etc) to be ready for anemone experiment / sampling tomorrow?

**Comment by jldimond** [comment]
I wouldn't think anything needs to be done...prepping the water bath can't
take more than a few minutes right?

**Comment by jldimond** [comment]
Here's my notebook post for this:
http://onsnetwork.org/jdimond/2015/02/17/sea-anemone-thermal-stress-experiment/

**Comment by sr320** [comment]
DNA and RNA isolation next week?

**Comment by jldimond** [comment]
Sure--Tuesday? I'll need some hand holding, or at least some very detailed instructions (I think there are some on the wiki?)

**Comment by sr320** [comment]
I would start with DNAzol (to get DNA)
https://tools.lifetechnologies.com/content/sfs/manuals/10503.pdf

Steven Roberts

**Comment by jldimond** [comment]
The animals both died sometime within the past week (though they were not heavily decomposed so it may have been recent). Do you still think it is worthwhile to use the samples given that the stress was probably too intense?

**Comment by sr320** [comment]
yep

Steven Roberts

**Comment by sr320** [comment]
@jldimond - need to get this out the door ASAP as funds run out.

**Comment by jldimond** [comment]
What is the deadline?

**Comment by sr320** [comment]
Need high quality DNA by Monday.

**Comment by jldimond** [comment]
I can work on this on Friday afternoon, and Monday afternoon. Will somone be around then to help me run a gel?

**Comment by jheare** [comment]
I will, if you need some help.

**Comment by jldimond** [comment]
Thanks - it would be good to have someone there to at least show me where things are. Sorry this crept up on me - didn't realize the funds would run out soon.

**Comment by jheare** [comment]
No worries, the system is pretty easy to set up and all the reagents are
close at hand.

**Comment by jldimond** [comment]
FYI - here's what I did on Friday afternoon (summary = very low DNA concentrations):
http://onsnetwork.org/jdimond/2015/04/04/isolation-of-dna-from-anthopleura-elegantissima-samples/

**Comment by sr320** [comment]
Next up - @jldimond will spec DNA to get quantity.

**Comment by jldimond** [comment]
http://onsnetwork.org/jdimond/2015/04/27/dna-quantitation-sea-anemone-thermal-stress-experiment/
