### ISSUE TITLE
Update Crandall Capstone links

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#272]
@grace-ac can you edit 
https://github.com/sr320/LabDocs/blob/master/web/People.md#undergraduates

such that there are links to your specific products from your capstone..

**Comment by grace-ac** [comment]
Updated all but for my notebook. I can't find my old notebook for my capstone - back when it was just the Genefish Wikispace ... :(

**Comment by sr320** [comment]
this one?
http://genefish.wikispaces.com/Grace%27s+Notebook

**Comment by grace-ac** [comment]
yes!!! thank you.
