### ISSUE TITLE
Add classes to Lab Calendar

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#280]
If assignees and Laura (who has not accepted the invitation to be assigned issues) could add your classes to the lab calendar, that would be great.

**Comment by Ellior2** [comment]
I was just going to compile all our names in one listing for shared classes so it doesn't get too cluttered.

**Comment by sr320** [comment]
That would be fine with me. Or could just name class then "R,Y,L" or whatever combo pertains

**Comment by sr320** [comment]
Thanks!
