### ISSUE TITLE
Creating Better Tables 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#282]
As pointed out by @hputnam

In current notebook system, using Jekyll-Now...

---

tables look like 
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/quarter-shell_–_Staging_for_my_Lab_Notebook_1D9DA786.png" alt="quarter-shell_–_Staging_for_my_Lab_Notebook_1D9DA786.png"/>

when in fact if you look at the md file itself it is better...
ie

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Home_·_sr320_course-fish546-2016_Wiki_1D9DA7CA.png" alt="Home_·_sr320_course-fish546-2016_Wiki_1D9DA7CA.png"/>

## trying to fix

Changing the _reset.scss file..

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Update__reset_scss_·_sr320_sr320_github_io_a30b228_1D9DA9C6.png" alt="Update__reset_scss_·_sr320_sr320_github_io_a30b228_1D9DA9C6.png"/>

Now makes it look like

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/phone_–_quarter-shell_–_Staging_for_my_Lab_Notebook_1D9DA9EE.png" alt="phone_–_quarter-shell_–_Staging_for_my_Lab_Notebook_1D9DA9EE.png"/>

Can make it all sorts of pretty (I believe)

see
http://www.w3schools.com/css/css_table.asp

**Comment by hputnam** [comment]
Nice! I now have zebra-striped tables.
