### ISSUE TITLE
Lack of issues feature of Jekyll-now notebooks

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#286]
I am noticing that for our new notebooks that are _forks_ there is no `issues` feature. I was looking to that to ask questions, provide feedback (I think that is something that is important for engagement and collaboration? ) 

@hputnam what do you think?  

Maybe folks could enable [disqus comments as I have](http://disq.us/t/2ddszpp)?

**Comment by yaaminiv** [comment]
I did a quick Google search and found a [solution](http://programmers.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork)!

If you go to the Settings tab in your forked repository, scroll down to Features and check the box for Issues. This creates the issues tab.

**Comment by sr320** [comment]
Awesome - thanks!
