### ISSUE TITLE
Comparing methylRAD to BS - oysters

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#287]
We are collaborating with Katie Lotterhos and comparing DNA methylation approaches. 
She now has some data.

As a reminder, she has these samples:

“Oyster1”-“Oyster3” are C. gigas samples that she sent us

Of the samples we sent her, these were the ones they were able to successfully prepare libraries for:
FID NF-60
FID NF-61
FID NF-62
FID NF-63
FID NF-64
1NF-8
FID NF-66
FID NF-67
FID NF-68
1NF-9
1NF-10
1NF-2
1NF-3
1NF-7
1NF-5
1NF-6

---

I think the first oysters refer to ...

1) Mantle tissue samples of C. gigas were collected on 20140705 (source: Pipestem Inlet) by KEL
2) Extraction on 20141028 by VG using Qiagen DNAeasy Blood and Tissue Kit
3) Beadwash on 20150720 by VG using homemade sera-mag speed beads
4) Qubit 3.0 quantification on 20151206 by KEL and the following amounts were sent:

M1: 13 uL of 386 ug/mL
M2: 13.8 uL of 326 ug/mL
M3: 13.15 uL of 380 ug/mL (solution looked cloudy)

---

And the latter is from what @kubu4 sent her...  ???

I've sent a total of 15 DNA samples (~2ug of each sample) from ~~C.gigas~~ housed in Clam Bay. The samples were isolated using the E.Z.N.A. Mollusc Kit by a collaborator.

HC1 3
HC3 18
HC2 20
HC2 14
HC2 19

NF2 14
NF2 6
NF2 18
NF2 15
NF2 17

SS2 17A
SS2 19A
SS1 12
SS1 8
SS3 5B

I've also sent a total of 20 ~~C.gigas~~ tissue samples (whole body sub-sample), stored in RNAlater. Tissue weights are unknown. 10 of the samples are from oysters born and raised in Fidalgo Bay. The other 10 are oysters born in Fidalgo Bay and grown in Oyster Bay.

Fidalgo-Fidalgo Tubes:
Fidalgo NF 60 - 69

Fidalgo-Oyster Bay Tubes:
1NF 1 -10 RL

The "RL" label on the second group is just to indicate RNAlater.

---

We should probably decide how to best proceed ...

**Comment by sr320** [comment]
We have BS data from the following that might? relate to what KL did.

https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Whole-genome-BSseq-December-2015

1NF11
1NF15
1NF16
1NF17
2NF5
2NF6
2NF7
2NF8

both from Fidalgo - 2 outplanted at Oyster Bay

**Comment by sr320** [comment]
I am confused about KL sample IDs and how they might relate to what we have...

Some of the suffix number match but not prefix numbers.

**Comment by kubu4** [comment]
I'm putting email from KL in here for reference:

---

“Oyster1”-“Oyster3” are C. gigas samples that we sent you (which genome reference are you using?)

Of the samples you sent us, these were the ones we were able to successfully prepare libraries for:
FID NF-60
FID NF-61
FID NF-62
FID NF-63
FID NF-64
1NF-8
FID NF-66
FID NF-67
FID NF-68
1NF-9
1NF-10
1NF-2
1NF-3
1NF-7
1NF-5
1NF-6

**Comment by sr320** [comment]
Also at the top :)

**Comment by kubu4** [comment]
OK, so here's what I've come up with.

We sent her DNA samples AND tissue samples. 

Based on her email, she's saying they were only able to prepare libraries from a subset of the samples we sent them. As it turns out, those successful preps only came from tissue samples.

The DNA samples are what we used for BSseq. We do NOT have any data from the tissue samples we sent to her.

**Comment by sr320** [comment]
I think I would agree.

Next question ...
how does
![l](http://eagle.fish.washington.edu/cnidarian/skitch/Next_Gen_Seq_Library_Database_-_Google_Sheets_1DAD206E.png) 

correspond to what KL did?

and where is the data... (should be easy)

**Comment by kubu4** [comment]
The M2 and M3 samples are here:

http://owl.fish.washington.edu/nightingales/C_gigas/9_GATCAG_L001_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/10_GATCAG_L001_R1_001.fastq.gz

The NF2_6 and NF_18 are here:

http://owl.fish.washington.edu/nightingales/O_lurida/11_GGCTAC_L001_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/O_lurida/12_GGCTAC_L001_R1_001.fastq.gz

They have no relation to what KL did, as far as I can tell. She doesn't say what she did with the M2 & M3 samples she sent to us (guessing these are the same as "“Oyster1”-“Oyster3” are C. gigas samples that we sent you")

**Comment by sr320** [comment]
So the latter need to change directories if they are gigas, which they might not be? I honestly do not know what NF2_6 adn NF_18 are

**Comment by sr320** [comment]
It would appear NF are Ostrea lurida provide by KS

http://onsnetwork.org/kubu4/2015/12/18/bisulfite-treatment-oly-reciprocal-transplant-dna-c-gigas-lotterhos-dna-for-bs-seq/

**Comment by kubu4** [comment]
Correct.

**Comment by kubu4** [comment]
The only gigas samples were the M2 and M3.

**Comment by sr320** [comment]
So nightingales needs updating

A secondary question is 
Are KL Oly libraries siblings of 
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Whole-genome-BSseq-December-2015
?

**Comment by kubu4** [comment]
Nightingales - What needs updating? M2 & M3 are in nightingales/C_gigas and the two NF samples are in nightingales/O_lurida. Or, are you referring to the Fusion Table?

Siblings - Unfortunately, I have no idea on how the Oly samples that Jake and Katherine Silliman relate to each other...

**Comment by sr320** [comment]
Maybe you just updated, but as of 24 minutes ago
https://github.com/sr320/LabDocs/issues/287#issuecomment-252916530

**Comment by kubu4** [comment]
Oh, I see. The Next_Gen_Seq_Library_Database. Will update.

**Comment by sr320** [comment]
FTR there was a typo above

M3 is @ http://owl.fish.washington.edu/nightingales/C_gigas/10_TAGCTT_L001_R1_001.fastq.gz

I guess I am pretty sure..

**Comment by kubu4** [comment]
Thanks for catching that. I'm fixing links in previous post up above.
