### ISSUE TITLE
Consider how to best get tag data online

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#288]
via Andy

Here are some links to the plotting library (bokeh) I was talking about earlier.  I used this library to make an application to easily visualize the data from some sensor testing/QC I have been doing on the tags these past couple of weeks. While it runs locally much like a jupyter notebook, it looks like it is possible to host the apps on the web as well.

Here are the examples on their site - https://demo.bokehplots.com 

Here is some info on the requirements for running one of these servers, 
http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#userguide-server-applications.  I'm not sure if this is something that could be set up easily so people can view it over the web.  It seems there are some special requirements from what ever web host would be used.  

There are some functions that integrate widgets and callbacks in the notebook but I believe they need to be written in javascript while use of the bokeh sever can use callbacks written in python.  That is why I went that route vs the notebook.  I can spend some more time reading the documentation and sort that out though.  At the very least we could use the library to generate some plots that could be embedded to the site that have some degree interactivity.  Here is a quick example of what that might look like (standalone html file) from the sensor QC I have been doing - http://bit.ly/2dBSxE5. This may be the simplest option.

**Comment by sr320** [comment]
see also
https://ajasonowicz.github.io/psat_map/map.html

And for Background:
[2016-10-30-Progress-Report.pdf](https://github.com/sr320/LabDocs/files/564113/2016-10-30-Progress-Report.pdf)

**Comment by seanb80** [comment]
I've read the background information, as well as looked over the Bokeh documentation and example plots. Is there a place I can grab the data from to work on some visualizations? The web hosting stuff will require much more reading/research to see how to do that properly.

**Comment by kubu4** [comment]
@seanb80 - You might consider using [Shiny for R Studio](http://shiny.rstudio.com/) for this project.

**Comment by sr320** [comment]
sample data 
https://github.com/RobertsLab/project-sablefish/tree/master/data

**Comment by sr320** [comment]
@seanb80 do you have something on this? a url?

**Comment by seanb80** [comment]
https://seanb80.shinyapps.io/SablefishDepth/ as it stands. 

There isn't a way I can find to animate the line point by point (like you were drawing it off of the data points) in the shinyapps.io framework. It does however animate by hour
