### ISSUE TITLE
Setting up directories on Owl

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#289]
Directories (and permissions) need to be established for @Ellior2 @yaaminiv and @laurahspencer on `owl/web`.

Also would like to get a general fish546 account that can only read/write to `scaphapoda`.

Instructions on how to access should be placed on wiki
-- start..
https://github.com/sr320/LabDocs/wiki/Lab-Notebook-Best-Practices/_edit#data-management

**Comment by kubu4** [comment]
Users have been created. Suggested folder names for the three new students?

FISH546 folder: ```owl/web/fish546```

Will update instructions a bit today, but will polish them off tomorrow.

**Comment by sr320** [comment]
trochophora
spartina
generosa

thanks!

**Comment by kubu4** [comment]
Thanks!

I've created both a fish546 user account AND a fish546 user group. I suspect just having all people use the single account will be easiest, but figured I'd add the group as an option.

**Comment by sr320** [comment]
Yes I agree - just let everyone use one account and they can set up subdirectories..

**Comment by kubu4** [comment]
I'm assuming folder names are in the order as the student names were listed in the first message (need to assign appropriate permissions to each folder)?

**Comment by sr320** [comment]
Yes please

**Comment by kubu4** [comment]
👍

**Comment by kubu4** [comment]
Why doesn't the Data Management section show up when viewing the wiki? I see it when I go into the editor...

**Comment by sr320** [comment]
FISH546 did not have write access, so I gave them write access to all of web. I could not figure out how to limit to just `web/fish546`
