### ISSUE TITLE
Tubes and such

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#290]
In getting supplies ready for sampling last week here are a few things I think need to be ordered

- 1.5 ml flip cap tubes
- 2 ml screw cap tubes
- cardboard 96 well boxes (ones we use for -80)
- razor blades

**Comment by kubu4** [comment]
Which budget(s)? Total is ~$150.

**Comment by sr320** [comment]
63-4279

**Comment by kubu4** [comment]
👍
