### ISSUE TITLE
ssh connection issues

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#291]
I used ssh to access roadrunner and used the existing mount of owl to web to copy files from owl to roadrunner. I used the nohup command prior to copy and when I went to ssh in to check the progress I was met with this error when I tried to log in:
```hputnam$ ssh srlab@128.95.149.201```
```ssh_exchange_identification: Connection closed by remote host```
any thoughts @kubu4 or @sr320 ?

**Comment by sr320** [comment]
You lost me at nohup....

**Comment by kubu4** [comment]
Doing some Googling, it seems I've run into this issue before - and it doesn't appear to have a concrete, simple solution. I highly suspect I ended up restarting Roadrunner/Hummingbird to "fix" the issue...

**Comment by kubu4** [comment]
To add to my above comment, I get the same message when trying to ssh into Roadrunner.

**Comment by hputnam** [comment]
@kubu4 can I check progress directly on the machine tomorrow before restart?

**Comment by sr320** [comment]
There is no shame in Remote Desktop connections :)

**Comment by kubu4** [comment]
@sr320, can you still Remote Desktop into Roadrunner? 

@hputnam, yes, you can still physically sit at Roadrunner and check your progress. If things are not copying (either done copying or not copying for another reason), then go ahead and physically restart the machine (@sr320 can show you if you need help).

**Comment by hputnam** [comment]
I am not able to log on... just get the spinning rainbow wheel so far.

**Comment by kubu4** [comment]
Well, it seems like the system is locked up... Physical reboot is likely the only way to "fix" it at this point.

**Comment by hputnam** [comment]
system is rebooted, ssh is working.

Now I need to remount owl as follows? /Volumes/web seems to be gone.

mkdir /Volumes/Owl_Putnam
mount_afp -i "afp://hmp6@owl.fish.washington.edu/web/" /Volumes/Owl_Putnam

**Comment by kubu4** [comment]
Hmmm, I'm thinking it's a permissions issue, as I'm able to mount ```owl/web``` using my account. Let me tweak some things and I'll get back to you...

**Comment by kubu4** [comment]
OK, it's all set up! ```owl/web``` is mounted on Roadrunner ```/Volumes/Owl_Putnam```.

**Comment by hputnam** [comment]
Thank you!!
