### ISSUE TITLE
Why does a post not break to read more with Jekyll-now

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#292]
My most recent post did not "break" for the short version where a link to Read More exists.
https://sr320.github.io/

Anyone else run into this or know what might cause this?

**Comment by kubu4** [comment]
Is it possible that empty lines are an issue? I see in the previous post (Oly OA 48hr Sampling Event) you only have single empty lines between paragraphs, but in your most recent post (Analysis of two oyster samples) there are multiple empty lines between paragraphs.

I know having multiple empty lines between paragraphs screws up GitHub wiki displays, so maybe it causes issues with the .io pages, too?

**Comment by sr320** [comment]
Did not appear to be the case..

**Comment by sr320** [comment]
If you scroll down [this] is the post that does not break (along with some others)

**Comment by seanb80** [comment]
Here is the Jekyll documentation that describes how it does post excerpting. 

http://jekyllrb.com/docs/posts/#post-excerpts

If I understand the documentation correctly, Jekyll takes the first paragraph (likely defined by a pair of carriage returns) and turns that into the post excerpt. 

For the post "Fidalgo 8 Old Oyster BS", could you try entering a second carriage return after the "Analysis of eight Fidalgo Olympia Oysters" line? This should convince Jekyll that that is a stand alone paragraph and create a proper excerpt.

**Comment by sr320** [comment]
Thanks but this did not work.
