### ISSUE TITLE
Plan to handle extended power outage?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#295]
The weather predictions for this weekend have me nervous. If power's out for multiple days, we're in trouble.

Not sure if FSH has backup power or not (FTR doesn't - technically it does, but it's inaccessible to us); I'll ask around tomorrow.

However, we should probably get a quick discussion of what we can/will do if power is out. There's the additional issue of the weather being severe enough that many of us may not be able to safely travel to the lab...

**Comment by sr320** [comment]
Not sure we have any options?
What are our biggest concerns?
Depending on the latter maybe we at least inquire with Kate if there is way to plug into the emergency power- we should at least try to get a few long heavy-duty extension cords?
I think we might be out of luck with our -80 as it is 240
I can inquire with Kate/Jon.

**Comment by kubu4** [comment]
Not many options, for sure. Having access to emergency power in FTR would be killer. Maybe Kate/Jon can have facilities unlock the access door on Friday or something?

Biggest concerns are definitely -80C samples.

If you contact Kate/Jon, could you please encourage them to send out a departmental email to address options for everyone?

**Comment by sr320** [comment]
emailed Jon to follow up on options
