### ISSUE TITLE
Roadrunner reconnect and logout

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#296]
I am trying to work in roadrunner under user hollie and it will say "Reconnecting" and then automatically comes back as logged on to srlab.  Would this happen if someone else is also using it, or is there some problem with the remote desktop?

**Comment by sr320** [comment]
I would say quit Remote Desktop and try logging in again. Seems like odd behavior.

**Comment by hputnam** [comment]
Still happening with random frequency. Also doing crazy window resizing when reconnecting.

**Comment by hputnam** [comment]
This is still happening, but with less frequency and @sr320 suggests the resizing is an issue with the display info. It is not stopping me from working remotely.
