### ISSUE TITLE
can't view jupyter notebook in docker

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#297]
I have followed the instructions for jupyter notebook use in a docker container and also downloaded firefox for compatibility. When I call ```jupyter notebook``` I get the following:

```root@7785b6fe19f1:/Users/hollie/Documents/HP_BioInf/Oly_MBD/Notebooks# jupyter notebook```

```[I 20:07:48.555 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret```

```[I 20:07:48.631 NotebookApp] Serving notebooks from local directory: /Users/hollie/Documents/HP_BioInf/Oly_MBD/Notebooks```

```[I 20:07:48.632 NotebookApp] 0 active kernels```

```[I 20:07:48.633 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/```

```[I 20:07:48.634 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).```

```[W 20:07:48.635 NotebookApp] No web browser found: could not locate runnable browser.```

I then ran ```D-128-95-149-201:Oly_MBD hollie$ docker-machine ip``` in another terminal and got back ```192.168.99.103```

I used this address in firefox and got an ```unable to connect``` message.

Any thoughts @kubu4 @sr320

**Comment by kubu4** [comment]
![selection_084](https://cloud.githubusercontent.com/assets/4514104/19413152/8ff63b7a-92da-11e6-81c5-bcf905e9fcee.png)

**Comment by hputnam** [comment]
Sorry I forgot to say  tried that too and same error for all of the following:
192.168.99.103:8888
localhost:8888
192.168.99.103

**Comment by kubu4** [comment]
Are you using Remote Desktop or are you ssh-ing into Roadrunner?

If Remote Desktop, are you using a browser on Roadrunner?

**Comment by hputnam** [comment]
I am using Remote Desktop, with firefox as browser on Roadrunner under user hollie

**Comment by kubu4** [comment]
What command did you use to launch your Docker container?

**Comment by hputnam** [comment]
```docker start 7785b6fe19f1```
```docker attach 7785b6fe19f1```

**Comment by kubu4** [comment]
What was the original command you used to launch your container?

**Comment by hputnam** [comment]
Originally: 
```docker run -p 8787:8787 -p 8888:8888 -v /Users/hollie/Documents/Putnam/Data:/Users/hollie/Documents/HP_BioInf -it 7dc3e9c32189 /bin/bash```

**Comment by hputnam** [comment]
![docker](https://cloud.githubusercontent.com/assets/5198996/19413303/13095f62-92de-11e6-9b61-61d0064e0ddb.jpg)

**Comment by kubu4** [comment]
Leave your container (use Control p, then Control q).

Type: ```docker start 7dc3e9c32189``` and press Enter.
Type: ```docker ps -a``` and press Enter.

Post output of the ```docker ps -a``` command.

**Comment by hputnam** [comment]
![docker_error](https://cloud.githubusercontent.com/assets/5198996/19413362/d449f834-92df-11e6-95de-8194155e5b44.jpg)

**Comment by hputnam** [comment]
Might it be because only safari was installed at the time the container was built and so docker is linked to safari as a web browser and not firefox?

**Comment by kubu4** [comment]
Container named cocky_nobel is now showing that there are ports forwarded, which is what you want.

Now, type: ```docker attach cocky_nobel``` and press Enter

This should put you in the container, but you won't see a command prompt. To get to the prompt, type: ```Control c```

You should now have a command prompt within the container. From here, you should be able to follow the steps to get a Jupyter notebook going and access it in the browser on Roadrunner.

There shouldn't be any issues in regards to which browser you use.

**Comment by hputnam** [comment]
Same issue is persisting

Instructions:
Start Jupyter Notebook (enter this inside the container):

```jupyter notebook```

[I 21:16:49.008 NotebookApp] Serving notebooks from local directory: /Users/hollie/Documents/HP_BioInf/Oly_MBD/Notebooks
[I 21:16:49.009 NotebookApp] 0 active kernels 
[I 21:16:49.010 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 21:16:49.011 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 21:16:49.012 NotebookApp] No web browser found: could not locate runnable browser.

In a separate Terminal window, outside of your container, check the IP address of the Docker machine:

```docker-machine ip```
```192.168.99.103```

Pasted ```192.168.99.103:8888`` into firefox 
got back ```Unable to connect```

**Comment by hputnam** [comment]
Is this thread helpful?
https://github.com/gopherds/gophernotes/issues/6

This works jupyter notebook --ip=0.0.0.0

**Comment by hputnam** [comment]
https://github.com/gopherds/gophernotes/issues/6
![jupyter ip 00](https://cloud.githubusercontent.com/assets/5198996/19413550/424738ec-92e5-11e6-8d04-99033ca93391.jpg)

**Comment by kubu4** [comment]
If that works, then I'd certainly say it's helpful. :)

Out of curiosity, are you running Docker for Mac or Docker Toolbox?

**Comment by hputnam** [comment]
I am using the Docker Quickstart Terminal that was previously installed.

**Comment by kubu4** [comment]
I figured out why this isn't working as described in the lab documentation. The Dockerfile actually has instructions to change the default Jupyter notebook IP to 0.0.0.0. That's this weird command: ```(sed -i '/# c.NotebookApp.ip/c\c.NotebookApp.ip = \x270.0.0.0\x27' /root/.jupyter/jupyter_notebook_config.py)```

That command uses sed to edit the Jupyter config file. It looks for the line that starts with "# c.NotebookApp.ip" and then changes the line to "c.NotebookApp.ip = \x270.0.0.0\x27". The weird \x27 is some crazy representation for single quotes.

However, this command is no longer working and that's why you ended up having to specify the default IP address with the ```jupyter notebook --ip=0.0.0.0```

**Comment by hputnam** [comment]
It seems to be working great now with ```jupyter notebook --ip=0.0.0.0``` Good to know why. Thanks!

**Comment by kubu4** [comment]
I've fixed the Dockerfile so that the lab documentation for this remains accurate (i.e. can use ```jupyter notebook``` to launch Jupyter notebooks. 

For the curious. the problem was caused by a change in the formatting of the Jupyter config file. The formatting used to have a space after the #. It no longer has a space. I changed the sed commands to be more "universal" so that they only look for lines in the config file that match the text (and, effectively, ignore the formatting of the config file).

**Comment by renderit** [comment]
Having the same issue :( 
I did it with `jupyter notebook --ip=0.0.0.0` : I get:
```
[I 19:31:35.329 NotebookApp] Writing notebook server cookie secret to /home/appuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 19:31:35.343 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 19:31:35.349 NotebookApp] Serving notebooks from local directory: /home/appuser/pygdf/notebooks
[I 19:31:35.349 NotebookApp] 0 active kernels
[I 19:31:35.349 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=cc7b5e596cc5aab52a097946da65a33c441e577fe2500966
[I 19:31:35.350 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 19:31:35.350 NotebookApp] No web browser found: could not locate runnable browser.
[C 19:31:35.350 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=cc7b5e596cc5aab52a097946da65a33c441e577fe2500966
```
and when I do a `wget http://localhost:8888/?token=cc7b5e596cc5aab52a097946da65a33c441e577fe2500966` 
I get:
```
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8888... connected.
HTTP request sent, awaiting response...
```
gets stuck above.. 
Any idea why?
