### ISSUE TITLE
java in docker not available?

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#298]
```!fastqc /Users/hollie/Documents/HP_BioInf/Oly_MBD/Data/MBD/20160203_mbdseq/*fastq.gz \
-o /Users/hollie/Documents/HP_BioInf/Oly_MBD/Data/Raw_MBD_QC```

results in 

```Can't exec "java": No such file or directory at /usr/local/bioinformatics/FastQC/fastqc line 277.```

**Comment by kubu4** [comment]
Weird. Java is definitely installed and in the system PATH. You can verify this with the following steps:

Verify Java is present and where it's installed: ```which java```

Should spit out: ```/usr/bin```

Check Java version: ```java -version```

Now, to try fixing your issue, I guess I'd try specifying the Java install location in your fastqc command using ```--java /usr/bin``` in your fastqc command (see the fastqc help file for clarification: ```fastqc --help```

**Comment by hputnam** [comment]
I am not seeing anything when I run ```which java``` and  ```java -version``` gives and error of ```/bin/sh: 1: java: not found```

**Comment by kubu4** [comment]
If that's the case, something went wrong during the image build (either the Java install is implemented in the dockerfile incorrectly or it didn't install when the image was built).

The Docker container (created from the Roberts Lab dockerfile) has Java, so it seems like the Java install is implemented correctly in the dockerfile. However, my container is four months old and the dockerfile has certainly been updated since then.

I'll rebuild and see what happens.

**Comment by hputnam** [comment]
Thanks! Is there a log file from my initial image build that I could look for errors in?

**Comment by kubu4** [comment]
I don't think so. Actually, I think the build will stop if any errors are encountered. 

And, looking at the dockerfile, I think I see the issue. The only Java instructions (JDK) are to add an external package repository, but no instructions follow that to install the JDK from that package repository! Not sure when/why that got changed (sorry!).

Build is still compiling. Will report back when I have info.

**Comment by kubu4** [comment]
I fixed it. Sorry!

Pull the updated dockerfile and re-build your image. Ugh.

**Comment by hputnam** [comment]
Thank you! I am back up and running... may have generated some container clutter I need to ask questions about. but all is working now. 👍

**Comment by tallcuppajoe** [comment]
I'm experiencing the same problem with line 277. In my case, it will work on a set of files, I then change directories to the next set, use arrow-up to call the came command that just worked, and it throws "Bad file number at /c/FastQC/fastqc line 277"
I've been trying again over the day, and then it will work again, with no reinstall or anything else. Very strange.
