### ISSUE TITLE
OlyO samples movement

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#30]
Oyster bay

**Comment by sr320** [comment]
early Feb - still coordinating

**Comment by sr320** [comment]
Waiting on email response

**Comment by jheare** [comment]
I texted Jeremy per Gordon's suggestion. Still no response. Waiting for
Gordon to get back to me.

**Comment by jheare** [comment]
Just talked to Jeremy about moving the samples. We've decided to do it on Friday (2/13) around 12:00 pm. I'm going to try to reserve the SAFS truck for that day so I can bring back the trays we have down there. Otherwise I'll reserve a truck from U-Car.

**Comment by jheare** [comment]
Reserved the SAFS truck for Friday.
