### ISSUE TITLE
MeDIP kits/protoocols

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#301]
What are we using...

**Comment by sr320** [comment]
TruSeq DNA Methylation Library Prep Kit (96 rxns) Cat#: EGMK91396[](url)

**Comment by sr320** [comment]
@kubu4 can you provide the url for the MeDIP protocol @hputnam was referring to?

**Comment by hputnam** [comment]
http://genefish.wikispaces.com/protocols#Protocols-Methylated%20DNA%20Immunoprecipitation%20(MeDIP)

**Comment by hputnam** [comment]
# Antibody
Supplier: Diagenode
Item: MeDIP Antibody (5-methylcytosine (5-mC) monoclonal antibody cl. b)
Cat#: Diagenode C15200006-500

# BS Conversion
Supplier: Zymo
Item: EZ DNA Methylation-Gold™ Kit	
Cat#: Zymo D5005

# Illumina library prep
Supplier: Illumina 
Item: EpiGnome/TruSeq DNA Methylation	
Cat#:  EGMK91396

**Comment by kubu4** [comment]
Thanks @hputnam! I actually had no idea where you got the protocol from! Guess I should've looked at our lab protocols page...  😊

**Comment by sr320** [comment]
If it is a vetted protocol, we should move it over to GitHub..

**Comment by kubu4** [comment]
Have copied it over to the [LabDocs wiki](https://github.com/sr320/LabDocs/wiki/Common-Lab-Protocols)
