### ISSUE TITLE
Install Multiqc and Trinity new version?

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#302]
@kubu4 
Is it possible to install multiqc on roadrunner and hummingbird?
http://multiqc.info/

Can we update Trinity (c2.2.0) on roadrunner and/or hummingbird?
https://github.com/trinityrnaseq/trinityrnaseq/releases

**Comment by kubu4** [comment]
Both are now in Dockerfile - have not tested Docker image build yet.

Currently having difficulty getting Trinity to compile directly on Roadrunner (exits with: ```clang: error: unsupported option '-fopenmp'```).

**Comment by kubu4** [comment]
Docker image builds successfully. 

Trinity test run fails because it can't find bowtie. Figuring out how to resolve this...

**Comment by kubu4** [comment]
Trinity test completes successfully.

Resolution to previous issue was Trinity specifically requires bowtie-1. Bowtie-2 was already part of the Dockerfile, but that's too good for Trinity I guess...

**Comment by hputnam** [comment]
Thank you!
