### ISSUE TITLE
Manchester Hatchery Plan 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#304]
@laurahspencer We need to have a full plan for the any hatchery work by Nov 2. 

Of course do this somewhere on GitHub.. In your labnotebook repo is fine.

**Comment by laurahspencer** [comment]
Check out my draft research plan on my [latest notebook post](https://laurahspencer.github.io/LabNotebook/Oyster-Gonad-Research-Plan-Draft/).  This is very much a draft/ideal plan, and I look forward to discussing/refining it this week.
