### ISSUE TITLE
Update New Grad Student Bios

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#305]
Please update (actually add) bios and photos
at
https://github.com/sr320/LabDocs/blob/master/web/People.md

This is what is online at 
http://faculty.washington.edu/sr320/?page_id=505

**Comment by yaaminiv** [comment]
added + created a pull request.

**Comment by laurahspencer** [comment]
Edited/committed the bio page with my info.

**Comment by sr320** [comment]
Thanks!
