### ISSUE TITLE
Photos from Big Beef Creek?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#309]
@kubu4 you have some pics from Big Beef Creek? where might there be?

And related is there some central place we can dump photos that would be automatically curated?
I am pretty sure Google does this ie I can type oyster and voila 🐚

**Comment by kubu4** [comment]
Here's a link: https://goo.gl/photos/AqNuXMoMRzKPsVis9

I also sent you a link to an additional album.

Google Photos (and now Amazon) does automatic curation. In fact, that's how I found the album above. I searched for "big beef creek" and it pulled up the album.

**Comment by kubu4** [comment]
Also, I think there are a bunch in the "Bioindicator" album on our Flickr account: https://www.flickr.com/photos/35623250@N04/albums/72157619107872733

Although, they'll be harder to sift through since that album is a compilation of all the sites Mac was visiting.
