### ISSUE TITLE
Get BGI quote for RAD libraries 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#31]

**Comment by sr320** [comment]
@kubu4 will follow up

**Comment by kubu4** [comment]
Current pricing is below.  Awaiting response on "bulk" (i.e. 96 samples for RAD-seq) pricing and clarification on what "GBS" is (item e):

a) Genome re-sequencing: $170 per library construction, $90 per GB clean data.
b) RAD-seq: $140 per library, $200 per GB clean data.
c) Bisulfite seq: $400 per library, $120 per GB clean data.
d) RNA-seq: $250 per library, $100 per GB clean data.
e) GBS: $4000 for 96 samples, including library, sequencing, and analysis.

**Comment by kubu4** [comment]
Pricing from Epigentek:

BS-Seq:
- $75 project initiation fee
- $350 bisulfite library prep
- $20 library quant
- $15 Bioanalyzer QC
- $1850 Illumina sequencing
