### ISSUE TITLE
Oly MBD BS Sample and Site Info

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#311]
@sr320 @kubu4 

I am trying to piece together the background on the Oly MBD samples. I have tried to follow the threads between Sam and Katherine's notebooks... sorry if I missed this info somewhere.

* Are there any data of collection and holding coordinates?  
* Are there any physical data for the sites (e.g., temp, pH, salinity, DO)?

* Where are the 2bRAD data from each of these samples? 
* Has Katherine already analyzed these?

**Comment by sr320** [comment]
Do you know about 
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki

We do have physical data ...

**Comment by hputnam** [comment]
Thanks!

I have been looking here, but think maybe sometimes the same name is within the seq name and sometimes not.... just wanted to grab the right ones.
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/2bRAD-Sequencing-December-2015

**Comment by hputnam** [comment]
I am gathering info from Wiki and Jake's paper. Will look forward to chatting with Katherine.
