### ISSUE TITLE
Wishlist- script for simple posts to github

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#312]
I wish there was a super simple way (simple script) where I could type a _phrase_ that would be a title to a md file and said file would automatically be named: YYYY-MM-DD-_phrase_.md and the header would be

```
---
layout: post
title: _phrase_
date: 'YYYY-MM-DD'
---
```

I could edit (nano would be fine)...

then that file would automatically be pushed to GitHub.

🎁 for most elegant solution 🎆

**Comment by kubu4** [comment]
Would you settle for a two-step process for the phrase?

1. Start script
2. Enter phrase

**Comment by sr320** [comment]
Yes

**Comment by kubu4** [comment]
Here you go: https://github.com/kubu4/Scripts/blob/master/bash/jekyll_header.sh

To use:
1. Copy file to repo.
2. Change to the directory with the ```jekyll_header.sh```
3. Run the script: ```. jekyll_header.sh```
4. Enter your phrase when prompted.
5. File will be created and uploaded to GitHub.

**Comment by kubu4** [comment]
Step 5 above will prompt you for your GitHub username and password if you don't have GitHub SSH authentication keys configured for your computer.

**Comment by kubu4** [comment]
I was just re-reading your initial post.

You want to edit the file after file creation, before pushing to GitHub, correct? 

Seems obvious now (yes, you'd like to edit before going to GitHub), but I interpreted that differently when I initially read it.

**Comment by kubu4** [comment]
I have added the ability to edit the post (using nano) prior to all the GitHub stuff.

**Comment by kubu4** [comment]
Ugh. I posted the above commented before pushing the changes to GitHub. The updated script is now available.

**Comment by sr320** [comment]
Very slick!

This only thing I cannot figure out is how the title has _ _ around it. I realize that is what I asked for....
But do not want those in the end.

https://sr320.github.io/test4/

**Comment by kubu4** [comment]
Removed the underscores. Have pushed changes the script changes to GitHub.

**Comment by sr320** [comment]
🎁 
That was worth a Dot.. Go ahead and order three. 75-1266

The next test will be if I can just talk to the Dot and post to my notebook!

**Comment by kubu4** [comment]
Awwww yeah! :smiley_cat:

**Comment by kubu4** [comment]
Color preferences? Figured I'd get two of one color and one of the other color...

**Comment by sr320** [comment]
I will take a white one
