### ISSUE TITLE
Hyak node

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#313]
Lets go ahead and get a Hyak node..

Looks like they are getting ready to deploy new infrastructure.

@kubu4 can you see what our options are and how to proceed?

**Comment by kubu4** [comment]
How much RAM? Options and pricing (they may have smaller options, but I'm only finding these three options):

128 - $4892

256 - $5382

512 - $6503

**Comment by sr320** [comment]
I say 512..

**Comment by kubu4** [comment]
Which budget(s) should I use for this?

**Comment by sr320** [comment]
Before that, just to confirm will we get new hardware gear and what does
that look like CPU wise?

**Comment by kubu4** [comment]
This is confirmed on the details page:

https://itconnect.uw.edu/service/shared-scalable-compute-cluster-for-research-hyak/

The top part indicates that "...please be aware that you cannot purchase new Classic Hyak nodes..."

**Comment by sr320** [comment]
61-0221 - 3000
63-4279 - 1503
65-2861 - 2000
