### ISSUE TITLE
Proteomics Meeting - Developing Timeline

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#314]
There are several proteomics projects that need to get going and I would like to schedule a meeting with the Emma and Brook to come up with a game plan.

Please indicate your availability @ http://whenisgood.net/krhtxkd
so I can get something scheduled. 

thanks

**Comment by Ellior2** [comment]
Can you try and give me as much of a heads up as possible on our meeting time? I have been working from home occasionally on Mondays and Wednesdays when I don't have class to eliminate a 3hr roundtrip commute. So I'll need a couple hours to get to campus if I am not already there. Thanks!

**Comment by sr320** [comment]
We will be meet 9am Wednesday Nov 2 - it is on the calendar.

**Comment by sr320** [comment]
Sure- should decide tomorrow - but you can always call into meetings if you
need to..
Thanks
