### ISSUE TITLE
Roadrunner Connection?

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#315]
@kubu4 I am not able to access roadrunner remotely. Can you tell if it is down, or is it i just a connection issue for screen sharing? I am getting the following error.

> Unable to communicate with “128.95.149.201”.  Make sure the remote computer is available and the firewall is not blocking screen sharing.

**Comment by hputnam** [comment]
The connection is back!

**Comment by hputnam** [comment]
Have not been able to access roadrunner remotely the last 2 days. Any suggestions?  I checked it yesterday and it is on and functioning.

```Unable to communicate with “128.95.149.201”.  Make sure the remote computer is available and the firewall is not blocking screen sharing.```

**Comment by kubu4** [comment]
It is on, but it does not seem to be functioning (pinwheel). I was going to post to G+ about potentially restarting...

**Comment by sr320** [comment]
Would just restart - you guys are the only ones using...

**Comment by hputnam** [comment]
roadrunner is frozen again. Is it ok to force restart? @kubu4

**Comment by kubu4** [comment]
It's always OK to restart if it's frozen. Thanks for checking, though!

**Comment by hputnam** [comment]
Thanks!!

**Comment by kubu4** [comment]
This is the likely source of the constant Roadrunner problems (Exit code 8):

![20161107_roadrunner_first_aid](https://cloud.githubusercontent.com/assets/4514104/20076651/2110f17a-a4ee-11e6-9957-b0722aa7d605.png)

@seanb80 - Please see if you can resolve. Try the following options:

1. Boot in Safe Mode and then run First Aid.
 
  If that doesn't fix that exit code:

2. Boot in Recovery Mode and then run First Aid

 If that doesn't fix that exit code:

3. Boot in Single User mode and run ```fsck``` (search internet for full instructions).
