### ISSUE TITLE
Integrative Environmental Physiology

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#316]
@sr320 

I've started looking ahead to plan my classwork at UW over the next couple years as my availability is limited. I saw that you are teaching Integrative Environmental Physiology in Spring 2017. Just wondering if you would consider offering it in the fall as well because I would love to take it!

**Comment by sr320** [comment]
It is unlikely given the larger curriculum. But I have had students take the course remotely in the past.

**Comment by Ellior2** [comment]
Great, I'll probably do that. Thanks
