### ISSUE TITLE
Develop Schematic of Entirety of Oly Oyster Samples

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#317]
Eventually digital, but might want to start with whiteboard.

**Comment by grace-ac** [comment]
Excellent! I will be in 9-1p tomorrow. Will you be around to explain this to me?

**Comment by grace-ac** [comment]
I'll be in tomorrow 9am-3p so we can talk about this then if you like! But for now I'll prioritize the proteomic paper until we talk.

**Comment by sr320** [comment]
Oly big picture -
Want to develop a schematic - likely Google Figure, that outlines entirety of Oly work / samples
Starts with 
1) https://peerj.com/preprints/704/

-
offspring were used by Katherine 

and here is a master sheet 
https://github.com/sr320/LabDocs/blob/master/OlyO_Master.tsv

-
Start by reading the paper and diagraming on white board experiment / time / samples.

**Comment by grace-ac** [comment]
Is there a specific white board I should use/ one that I can erase to use?

**Comment by sr320** [comment]
Can erase all- let's meet at 11 with Emma re paper

**Comment by grace-ac** [comment]
okay!

**Comment by grace-ac** [comment]
@kubu4 @sr320 is there white board spray anywhere? I've looked around and haven't seen any.

**Comment by kubu4** [comment]
Best possibilities:

FTR213: shelf on big white board, on stainless steel table

FTR209: below white board, above printer

**Comment by grace-ac** [comment]
Thanks!!! however no luck!

**Comment by grace-ac** [comment]
Never mind steven found some! @kubu4 all good

**Comment by sr320** [comment]
Here is one data sheet
https://github.com/sr320/LabDocs/blob/master/OlyO_Master.tsv

**Comment by sr320** [comment]
we seem to have a lot 
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Comprehensive-Data-Descriptor

**Comment by grace-ac** [comment]
okay i think i'm understanding things a bit better. that last file you sent is really helpful! i'll be in tomorrow to try to sketch it out on the white board. we had a little house water/plumbing situation today which is why i didn't make it to lab!

**Comment by grace-ac** [comment]
here's what i did last fri https://docs.google.com/a/uw.edu/drawings/d/1xRNhsCgDO093FKyItvsMwl07NQQMTRQwHffvbVYB4IY/edit?usp=sharing 

literally made it in 10-ish minutes, so it's a draft. there's a link to the data for katherine's Fidalgo bay out plant oysters. any other links that would be helpful to add? any other info?

still unsure where the oyster bay samples that were brought to UW in autumn 2015 are.
