### ISSUE TITLE
Docker and Jupyter Crash

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#318]
Jupyter would not save and crashed. 
Docker crashed

I updated to the new Dockerfile.bio

opened Virtual box
opened docker terminal

>docker is configured to use the default machine with IP 192.168.99.101
For help getting started, check out the docs at https://docs.docker.com

Entered command:
```D-128-95-149-201:~ hollie$ eval "$(docker-machine env default)"```

Got following error:
>Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": x509: certificate signed by unknown authority
>You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

any thoughts @kubu4 ?

**Comment by kubu4** [comment]
Run the command they tell you to in that error message. Replace [name] with default.

**Comment by hputnam** [comment]
Thanks! I tried that first, but was too scared to say Y because it said 
>Warning: this is irreversible.

Rebuilding from new docker file now.
