### ISSUE TITLE
Want: Online Mind Mapping Software 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#319]
It would be great to have software where we could visually represent large projects and click through to see data.

Any ideas?

**Comment by laurahspencer** [comment]
This probably isn't what you're looking for, but have you heard of [Tableau](http://www.tableau.com/)? Commonly used in the business world to visualize data.

**Comment by sr320** [comment]
Coggle is an option

https://coggle.it/diagram/WBFmAenTnO1HUqMM

**Comment by sr320** [comment]
Actually it might be as simple as a Google Drawing

https://docs.google.com/drawings/d/1IFP72os7LPJBRW3lBxnUZ9nQiZzw5pya2cbeSIRqE0c/edit?usp=sharing

**Comment by jldimond** [comment]
https://www.mindmup.com/

**Comment by sr320** [comment]
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/iThoughtsX__mindmap__on_the_Mac_App_Store_1DC234DF.png" alt="iThoughtsX__mindmap__on_the_Mac_App_Store_1DC234DF.png"/>

**Comment by sr320** [comment]
Thanks! That is worth exploring

**Comment by sr320** [comment]
I think we explored the visual concept years ago with NGS and svgs of
animals @kubu4
