### ISSUE TITLE
Create Bibliography for Geoduck Gonad Proteomics Paper

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#321]
found at 

https://docs.google.com/document/d/11zGFXFa4ODBjBVRXOH3-ly2NQ7w3LrrpGce4w31PflA/edit

**Comment by grace-ac** [comment]
Added most of the citations to a literature cited using paper pile. They are not in the correct format yet - I'm trying to figure out what the Journal of Proteomics citation style is called. But it's super easy to change between citation styles, so it will be quick and easy once I figure out the style name.

**Comment by grace-ac** [comment]
Ah, it's literally just called "American Chemical Society".
