### ISSUE TITLE
Skyline version control?

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#322]
@emmats 

I found this Skyline [tutorial](https://skyline.gs.washington.edu/labkey/_webdav/home/software/Skyline/%40files/tutorials/GroupedStudies1-3_1.pdf) and I am starting to play around with our oyster data and identify truncated peaks. I am very concerned about making unwanted or irreversible changes to the data. How do you manage version control in Skyline? I know we will always have our raw files stashed away, but how do you document every step of the way? Is it possible to go back to previous versions, or do you just have to go back and undo everything you have done if you decide it wasn't right?

**Comment by sr320** [comment]
Excellent question
