### ISSUE TITLE
Get Geoduck Paper Supplemental Files to GitHub

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#323]
There are a bunch of files 
linked out 
in
https://docs.google.com/document/d/11zGFXFa4ODBjBVRXOH3-ly2NQ7w3LrrpGce4w31PflA/edit

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Geoduck_Protein_Expression_-_Google_Docs_1DC24BDF.png" alt="Geoduck_Protein_Expression_-_Google_Docs_1DC24BDF.png"/>

can you please get all of these into 

https://github.com/sr320/paper-Geoduck-proteomic/tree/master/Supplemental-files

Some are already there... 

thanks!

**Comment by grace-ac** [comment]
It says uploads are disabled and that it requires push access to this repository.. this is ringing some bells from when I did git and github stuff at the software carpentry thing, so i have been trying to figure out how to do this. not sure if there is an easier way!

**Comment by sr320** [comment]
added to repo

**Comment by grace-ac** [comment]
@sr320 i'm making the ReadMe file for this. is it ok to just use the descriptors of each file that are in the paper?

**Comment by sr320** [comment]
Yes

**Comment by grace-ac** [comment]
Okay! it is made. i tried adding it to github... and it's there, but doesn't show up at the bottom. instead it shows up as a link to my google doc. https://github.com/sr320/paper-Geoduck-proteomic/tree/master/Supplemental-files

**Comment by grace-ac** [comment]
also the .txt files for S8-SRM-data and for _Enrichment-input were not working. the supporting information says that you can have .xlsx for spreadsheets, so i converted them to .xlsx. they have multiple tabs in the spreadsheet which is why it said it couldn't support .txt format when i tried.
