### ISSUE TITLE
Improving Genomes 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#329]
Talking with folks over at NOAA- sounds like UW Genome has X-10 and we should be doing overlapping read libraries with this machine. This coupled with what we have, and likely PacBio, might get us where we need to be. 

@kubu4 can you see what services they provide (Nickerson Lab). the desire is they would make the libraries along with sequencing. Pretty sure this is same core with PacBio -so try to get details on this also.

**Comment by kubu4** [comment]
[Nickerson Lab](http://nwgc.gs.washington.edu/) provides the following:

![screenshot 2016-11-03 07 58 04](https://cloud.githubusercontent.com/assets/4514104/19971121/5e10d636-a19b-11e6-93be-23ce356933d7.png)

Not entirely sure the X10 (HiSeq X) platform provides us with any real benefit over HiSeq4000. It seems like X10 is geared towards really high-throughput sequencing (e.g. sequencing many individuals in different populations). [Illumina platform comparison tool](http://www.illumina.com/systems/sequencing-platform-comparison.html) suggests we use NextSeq or HiSeq:

![screenshot 2016-11-03 08 17 56](https://cloud.githubusercontent.com/assets/4514104/19972044/25314d0c-a19e-11e6-9715-fdee8aa38e71.png)



Thinking a bit more about this, is the reasoning for using the X10 to address the "overlapping read libraries?" I'm not entirely sure what this means. Make multiple libraries from the same sample to try to get overlapping reads?

[PacBio facility](https://pacbio.gs.washington.edu/) has some startling recommendations for <em>de novo</em> and/or gap-filling sequencing. The suggestion is to use <em>at least</em> 30 - 40 SMRT cells. Each SMRT cell costs $337!!! I'll contact them to get their thoughts on our project, as well as a quote. Here's a screen cap of sequencing recommendations, dependent on project type:

![screenshot 2016-11-03 08 17 01](https://cloud.githubusercontent.com/assets/4514104/19971970/e980e68c-a19d-11e6-8ec8-82da32a02bbe.png)

**Comment by sr320** [comment]
via Sam
Genewiz - 9k

**Comment by kubu4** [comment]
To clarify @sr320's comment above. That number references issue #310 and is solely for assembly services - does not include any additional sequencing.

**Comment by kubu4** [comment]
Official quote from [UW PacBio facility](https://pacbio.gs.washington.edu/) for sequencing a _single_ species (using 10 SMRT cells - possible we could need more):

Cost: $4000
Turnaround: 8 weeks

**Comment by kubu4** [comment]
Pricing from [Northwest Genomics Center(i.e. Nickerson Lab)](http://nwgc.gs.washington.edu/):

"Project costs": $336
Library prep: $62

HiSeq 4000:
PE75: $2,102 per lane

PE150: $3,749 per lane


HiSeq X
PE150: $1,230 per lane

**Comment by sr320** [comment]
@kubu4 to clarify-
in conversation with PacBio fac, you told them what we had and that (10 SMRT cells) is what they suggested based on current our status?

**Comment by kubu4** [comment]
Correct. 

However, the gap-filling I described was based on a much smaller genome size (500Mb). I had forgotten that the BGI documentation provided kmer-based genome size estimates.

**Comment by sr320** [comment]
Lets go ahead and do 10 SMRT cells for Ostrea lurida....
