### ISSUE TITLE
ID Transposable Elements in Oly Genome

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#330]
Use RepeatMasker to ID transposable elements in Oly Genome-
Genome file : https://github.com/sr320/student-fish546-2016/blob/master/data/Ostrea_lurida-Scaff-30k.fa?raw=true

Be sure to fully document all aspects of the effort including software installation etc.

**Comment by seanb80** [comment]
Will do!

**Comment by seanb80** [comment]
I've begun installation of the RepeatMasker program, but one of the dependencies required are a set of libraries from girinst.org, which requires an approved login/password to download. I've begun the approval process (I believe someone just has to bless that I'm from an academic institution) but they say this process can take 1-2 days. Will continue as soon as I get this approval back.

**Comment by seanb80** [comment]
Results from a RepeatMasker run with _Crassostrea _gigas__ as the comparison species. Setting up a lab notebook where I will walk through the install, and the various pitfalls now.
[RepeatMasker.zip](https://github.com/sr320/LabDocs/files/572327/RepeatMasker.zip)

**Comment by hputnam** [comment]
@seanb80 could you run again on the 10k file? Thanks!
https://raw.githubusercontent.com/sr320/student-fish546-2016/master/analyses/Olyv6_blastn-Scaff-10k.gff

**Comment by seanb80** [comment]
Repeat Masker requires a fasta file input, so should I use the gigas genome as the reference genome for converting the .gff file to .fa? I was planning on either using bedtools or GFF utilities to do this (I think they do what I intend them to do?). 

 I looked in the student-fish546-2016 repo and it looks like there are only 30k and 40k .fa files, owl had nothing that looked right either.

Thanks!

**Comment by sr320** [comment]
@hputnam likely dropped in the wrong url 😸 

What she is requesting is if you can run repeatmasker on...
 http://owl.fish.washington.edu/halfshell/working-directory/16-10-24/Ostrea_lurida-Scaff-10k.fa

**Comment by hputnam** [comment]
Yes, sorry!!

**Comment by seanb80** [comment]
done. uploaded to 

http://owl.fish.washington.edu/scaphapoda/Sean/Oly%20Transposon/oly-10k-RM.zip

**Comment by sr320** [comment]
Thanks -
Can you rerun with gff output?
http://eagle.fish.washington.edu/cnidarian/skitch/untitled_text_1DD61743.png

Also when you document in your notebook can you include input commands and any stderr output...

**Comment by seanb80** [comment]
Will do!

**Comment by seanb80** [comment]
re-run and uploaded

http://owl.fish.washington.edu/scaphapoda/Sean/Oly%20Transposon/Oly_10k_gff.zip

**Comment by sr320** [comment]
Thanks! 
I am aggregating canonical tracks 
 http://owl.fish.washington.edu/halfshell/index.php?dir=2016-11-oly-annotation%2F

@seanb80 's RM track is 
http://owl.fish.washington.edu/halfshell/2016-11-oly-annotation/RM-sb-Ostrea_lurida-Scaff-10k.fa.out.gff

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/sr320’s_iMac_1DD68F33.png" alt="sr320’s_iMac_1DD68F33.png"/>
