### ISSUE TITLE
Can I take the dry shipper with me to Belize?

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#331]
If yes, I would ideally want to fill it on Tuesday right before I go.

**Comment by jldimond** [comment]
Related: Sam may have mentioned that I am requesting some RNAlater; there is none in stock.

**Comment by sr320** [comment]
I have no objection

**Comment by hputnam** [comment]
I would recommend filling it over 1-2 days before you leave to give it enough time to become fully saturated.  I usually fill, wait for 1-2 hours and refill. Then I repeat this over 1-2 days to make sure the shipper is fully charged. Then I do a final fill just before i leave campus and pour out any remaining liquid on the ground just before the airport or transport. @kubu4 may have an idea of the total time this size should hold a charge.

**Comment by jldimond** [comment]
Thanks for the tip. I also have an email out to the station manager re: filling in Belize. Ideally I would fill it upon arrival and departure.

**Comment by jldimond** [comment]
Oh and Sam already looked up the charge hold time and it is 21 days static, 16 days dynamic. Just on the edge of my time frame.

**Comment by kubu4** [comment]
@jldimond only 16 days static, 11 days dynamic.
