### ISSUE TITLE
Purchasing Reagents

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#332]
Proteinase K

Item: Protein A/G PLUS-Agarose Beads
Cat # sc-2003
Quantity: 2
https://www.scbt.com/scbt/product/protein-a-g-plus-agarose

TE pH 8.0 
500ml bottle
for example https://www.fishersci.com/shop/products/tris-edta-1x-solution-ph-8-0-molecular-biology-fisher-bioreagents-3/p-29171#?keyword=TE+ph+8

Sodium Acetate pH 5.2
https://www.fishersci.com/shop/products/fermentas-3m-ph-5-2-sodium-acetate-solution/ferr1181#?keyword=3M+sodium+acetate

**Comment by sr320** [comment]
62-9868
