### ISSUE TITLE
Schedule oyster sampling at Manchester

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#335]
November 07, 2016 at 09:54AM<br>
created via Do Button

**Comment by sr320** [comment]
Please indicate your availability to assist with sampling Katherine's oysters

http://whenisgood.net/4k8azcy

[*](http://whenisgood.net/4k8azcy/results/zimyqbp)

**Comment by sr320** [comment]
Nov 21

**Comment by grace-ac** [comment]
There's a chance I'll be put on the schedule for the restaurant. I'll know by next Friday at the latest, so I may be able to join!
