### ISSUE TITLE
Convert remaining Xserve blades (slave nodes) to current OS X

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#337]
Larger capacity HDDs have been ordered. Wait to perform conversion until new HDDs arrive.

**Comment by sr320** [comment]
For clarification that is 1 node?

**Comment by kubu4** [comment]
Should be two nodes (1 & 3).

**Comment by sr320** [comment]
one of which is roadrunner?

**Comment by kubu4** [comment]
I've think Hummingbird is node 2 and Roadrunner is node 4.

**Comment by sr320** [comment]
My bad - so we wiped "Node 4" - what the Seeb lab had set up? Vision and memory - shot.

**Comment by kubu4** [comment]
Memory not shot! Roadrunner is on node 3 (just checked my notebook). 

Regardless, plan would be to change remaining two nodes (node 4 and whatever number the remaining node is).

**Comment by kubu4** [comment]
@seanb80 - New hard drives are in. I have placed them by the keyboard for Roadrunner.

I have also installed a monitor switch to allow switching between the three nodes (Hummingbird has its own monitor).

A USB switch will be here Monday to allow easy switching of the keyboard/mouse between the nodes. As such, I'd wait until next week to bother with any of this.

I have labeled the nodes with their new names (and current node number): ostrich (node 004) and emu (node 002).

Here is my notebook on converting node 003 (roadrunner) from Xserve to OS X: http://onsnetwork.org/kubu4/2016/05/31/computer-setup-cluster-node003-conversion/

The quick summary of the procedure is this (Note: you'll need a "toaster" to use an external HDD; see if @sr320 has an extra lying around)

1. Clone the existing HDDs in node 002 and 004 to an external HDD (use the 6GB HDD that's on top of the cluster). You should be able to do this using Disk Utility. Once complete, write on the HDD with marker indicating its contents. Please do not discard this HDD.

2. Reformat the HDDs in node 002 and 004 with the Xserve installation disc. I've put a CD case containing the Xserve install disc on top of the cluster. This is needed is to disassociate the hardware from the "cluster" configuration. Otherwise, just popping a new HDD in with a new OS won't work.

3. Install Mountain Lion on each of the new HDDs. You'll have to connect the HDDs to a Mac, using a "toaster". The link to the Mountain Lion installation disc is here:

https://eagle.fish.washington.edu:5001/sharing/MOAnaGr0z

I think you can figure out the password needed to download it. If you can't get it to work, just let me know.

4. Remove old HDDs from nodes 002 and 004. Put a piece of tape on them indicating that it is permissible to overwrite them with the date and your initials.

5. Remove the HDD from Roadrunner. Run a SMRT test (this can be done sometime in the future - doesn't require immediate attention). If it fails, see if the drive is eligible for warranty replacement. If it passes, please perform a clean reformatting of the drive.

6. Put new HDDs (running Mountain Lion) in the three nodes. Name the computers appropriately (emu, ostrich, roadrunner). Establish the usual ```srlab``` user account on each.

7. Upgrade each to the newest OS (Sierra).

**Comment by kubu4** [comment]
Actually, don't proceed with anything until I've double-checked some things on Monday. I'll post in this thread to provide the green light.

**Comment by seanb80** [comment]
I will wait till Monday.

**Comment by seanb80** [comment]
Roadrunner, Ostrich, and Emu are all currently online. They all are running the current El Capitan build of OS X (10.11.6) and have SSH enabled. IP addresses have been added to the Roberts Lab Computing Resources sheet.

**Comment by hputnam** [comment]
How do I access these? I am not  able to connect via screen sharing using the IPs for roadrunner
emu or ostrich.

**Comment by kubu4** [comment]
Access via srlab user account or create your own user account.

**Comment by hputnam** [comment]
@kubu4 does this need to be done on site first, or should I be able to connect remotely either way?

**Comment by kubu4** [comment]
Assuming @seanb80 enabled remote screen sharing in the System Preferences, you should be able to login via the srlab account (using Screen Sharing) and create a new user account.

**Comment by hputnam** [comment]
Thanks! I'll check remote screen sharing tomorrow.

**Comment by seanb80** [comment]
I checked accessibility via SSH, let me try to get screen sharing to work real quick.

**Comment by seanb80** [comment]
Fixed.
