### ISSUE TITLE
Narrow down # of samples

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#338]
We've decided to narrow down the number of samples we want to run because we want to be conservative in our use of funds and resources considering we will probably try to redo this experiment in a couple months. I threw together a quick graph (sorry if it's messy but hopefully you get the idea) that includes 2 things:

1) Percent of live oysters at Day 17 (orange): this is based on the number of seed I actually sold on Day 17 (I considered them healthy enough to sell to customers). It is a rough estimate- I have yet to do the microscope work to assess actual mortality. I calculated percent survival based on original 1 million per silo.

2) Mean weighted screen size on Day 17 (grey): essentially an indication of how big the oysters were based on the screens I used to screen them on Day 17 and volume counts.

A Few considerations: I think prioritizing Day 0- 11 would be best, I don't think we will gain much more by looking at samples post day 11 as Day 0-11 is that critical time frame where we normally see high mortality- and we didn't.

The standpipe fell on Conical #8 on the first day so they were sprayed with seawater all night but not submerged -we saw the highest mortality in this conical for this treatment.

Do we want to just pick 3 conicals to assess from each treatment? We could throw out #8, but I am not sure what we would throw out for the 23C side. 

If we do this we could literally cut our sample numbers in half. I'm thinking roughly 30, which we might be able to do in one extraction session.

![image](https://cloud.githubusercontent.com/assets/20071030/20147720/1f9a5bf8-a65e-11e6-9342-30300e6de4db.png)

**Comment by Ellior2** [comment]
Also, I met with @kubu4 today about ordering chemicals that we will need. My goal for the weekend is to figure out how much of each chemical is required/sample so we can order appropriate amounts.

**Comment by sr320** [comment]
Will determine Friday 9:30

**Comment by sr320** [comment]
Going with 
tank 2, 3, 7 
22 samples - 3* 7 times + day 1 pool
