### ISSUE TITLE
LabDocs organization

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#339]
Example: @grace-ac generated the lab inventory QR code.

Where should this be stored? I directed her to just put the image file in the LabDocs top directory because I couldn't think of a better place for it.

However, this may not be worth putting any thought into, since I don't think anyone else uses LabDocs actively (i.e. isn't making changes to files in the repo). So, an issue of this nature may only arise very rarely...

**Comment by sr320** [comment]
create `img` for image files as the are somewhat uniq
