### ISSUE TITLE
Chemical ordering for protein extraction

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#340]
BCA assay kit -1L

https://www.thermofisher.com/order/catalog/product/23225

**Comment by sr320** [comment]
61-0221 <https://ucs.admin.uw.edu/MyFD/UWNetID/BudgetList.aspx#>

**Comment by Ellior2** [comment]
You want me to order it through Myfinancial.desktop? I navigated to the ASTRA page where I need a budget code or organization code...?

**Comment by sr320** [comment]
Just let Sam order this...

**Comment by Ellior2** [comment]
Things we need to order:

ApoA1 (not sure which to select- @emmats )
http://www.sigmaaldrich.com/catalog/search?interface=Product%20Name&term=APOA1&N=220003048&focus=product&lang=en&region=US&sort=DISPLAY_ATTRIBUTE

Endoproteinase Lys-C from Lysobacter enzymogenes (P3428-1VL)
http://www.sigmaaldrich.com/catalog/product/sigma/p3428?lang=en&region=US

Formic acid (F0507-500ML)
http://www.sigmaaldrich.com/catalog/product/sigald/f0507?lang=en&region=US

IAA  (I1149-5G)
http://www.sigmaaldrich.com/catalog/product/sigma/i1149?lang=en&region=US

Trypsin (T8658-1VL)
http://www.sigmaaldrich.com/catalog/product/sigma/t8658?lang=en&region=US

HPLC methanol (A452-1)
https://www.fishersci.com/shop/products/methanol-hplc-fisher-chemical-6/p-216129

pH test strips (WU-05546-42)
http://www.coleparmer.com/Product/Hach_pH_Paper_Test_Strips_0_to_14_pH_Range_100_Strips_Pk/WU-05546-42?referred_id=778&utm_source=bing&utm_medium=cpc&utm_campaign=Shopping+Campaign+-+BSC+-+Converters&utm_term=1100007790297&utm_content=pH+Meters+%26+Water+Quality+Products

Spin-columns?

**Comment by emmats** [comment]
Don't worry about the ApoA1. You do not need it. Note that it is optional in the protocol. 

We get our LysC from Wako Chemicals. Catalog # 125-02543. See my lab note book entry: https://www.evernote.com/l/APLW_DUL5xlOpJ7K76iizBxTd0A0VRktU0U

If there is a HPLC grade formic acid available, you want that one.

Sam @kubu4  has ordered trypsin for us before so just make sure it's the same one and you'll be fine.

Spin columns are from the nest group. You want macrospin (see table on the protocol). Sam has also ordered these before.

**Comment by Ellior2** [comment]
@emmats what formic acid did you buy? We ended up ordering a 50% solution because it was the only one from Sigma that was HPLC.

Also Sam, here is the TCEP.

http://www.sigmaaldrich.com/catalog/product/aldrich/c4706?lang=en&region=US

C4706-2G

**Comment by emmats** [comment]
I have a 50 mL bottle of formic acid from fisher scientific. It says "optima LC/MS" on it. Catalog number A117-50 https://www.fishersci.com/shop/products/formic-acid-optima-lc-ms-grade-fisher-chemical-5/p-3795381

**Comment by emmats** [comment]
Also, that appears to be the same TCEP we have.
