### ISSUE TITLE
Replace cluster UPS batteries

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#342]
@seanb80 - Please put the old battery sleds in the boxes I showed you. Move old batteries to the FSH copy room and leave in the designated battery recycling area.

**Comment by seanb80** [comment]
The upper UPS (Connected to Roadrunner/Ostrich/Emu) battery has been replaced. The lower (head node/hummingbird) will be replaced once hummingbird can be shut down.

**Comment by sr320** [comment]
thanks
