### ISSUE TITLE
Determine Directory Structure for Birds

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#343]
For the three "new" computers  (and considering hummingbird) I would like to decide on how directory structure should be set up...

Each has 1.9 TB drive..

Computer |  IP | RAM 
-------------|-------|--------
roadrunner | 128.95.149.201	|  48GB DDR3
emu | 128.95.149.143	|  12GB DDR3
ostrich | 128.95.149.197	|  48GB DDR3
hummingbird | 128.95.149.71	|  24GB DDR3

I would like to follow the model we have for `genefish` and assume a Mac user experience with bioinformatics programs in a [Shared user directory](https://cloud.githubusercontent.com/assets/4442039/20347342/725c96f6-abb5-11e6-8f99-ffdea3960b29.jpg). This would be a common directory that all users could access. Likewise have a shared "data" directory where common data files could be accessed (ie blast databases).

I am open to other suggestions. I am not opposed to docker, per se, but want access apps the old fashion way. I presume there is room for both modes.

Somewhat related we should consider programs and use of the computers... 
roadrunner and ostrich should get priority for assembly (hi mem jobs).
blast jobs should go to emu ...

**Comment by kubu4** [comment]
On the memory front, we could also upgrade memory for Emu & Hummingbird... However, with Hyak coming online in a few months, I'm not certain it's worth putting more money into these computers.

**Comment by kubu4** [comment]
On regards

**Comment by kubu4** [comment]
Sorry, finger hit close button on a bouncy bus ride!

**Comment by kubu4** [comment]
As far as shared programs go, I'll show @seanb80 how Giles set it up on Hummingbird. We should put together a list of desired programs to be installed.

**Comment by sr320** [comment]
This implies that approach is preferred over what I suggested?

**Comment by kubu4** [comment]
Sorry, didn't see the link when on the bus this morning.

Eh, they're both the same, but different. 😄 

Using that ```Shared``` account in ```/Users``` should be fine.

**Comment by kubu4** [comment]
Quick Mac question - Does adding programs to the ```/Applications``` directory make them available for all users?
