### ISSUE TITLE
Install Trinity on ostrich

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#344]
https://github.com/trinityrnaseq/trinityrnaseq/wiki

**Comment by seanb80** [comment]
I have Trinity on the srlab account, but can't share it with other users. It looks like the steven, sam, and Hollie accounts are admins, so if one of you can turn on file sharing, I should be able to share it between accounts.

**Comment by kubu4** [comment]
Did you install it in ```/Users/Shared```, per #343 ?

**Comment by kubu4** [comment]
Also, do you have a notebook entry that we can view that documents the install?

**Comment by sr320** [comment]
@seanb80 done? 
see also #354

**Comment by seanb80** [comment]
Is done, the Lab_software.md from the repo was updated also, but not the wiki. Will fix that now.

I was unsure of updating the software on Hummingbird, do we want to leave the software versions as they stand for those currently using it?

**Comment by sr320** [comment]
Lets leave hummingbird as is. thanks
