### ISSUE TITLE
docker errors on Mac

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#345]
I have been trying to get docker to work on roadrunner and ostrich based on the docker website recommendations for mac. This is different then the docker quickstart terminal. When trying to open the application I get the following error:

![docker_error_junk](https://cloud.githubusercontent.com/assets/5198996/20357806/3fe2eaf8-abde-11e6-9707-381c0d9b960a.jpg)

When I run the suggested test ```sysctl kern.hv_support```  it comes back ```kern.hv_support: 0``` which means it does not supports the Hypervisor Framework docker requires.  Is there a work around this, or is it possible to install the docker file content directly?

**Comment by seanb80** [comment]
I believe the workaround will be to use the older docker toolbox instead of docker for mac. I'll look around to see if there is any other option.

**Comment by sr320** [comment]
Another workaround is not use docker :)

**Comment by hputnam** [comment]
I am pretty sure this is my last docker effort.... it seems to hate me.

**Comment by kubu4** [comment]
> This is different then the docker quickstart terminal.

Why aren't you using Docker Toolbox (and, in turn, Docker Quickstart Terminal)?

Also, I too, thought you were done using Docker.

**Comment by hputnam** [comment]
From their website it seemed they were recommending the new mac app. I also tried the instructions for docker toolbox but did not find the actual download file.  It seemed docker would have been the fastest way to get all software back on the computer if it had worked directly from install.  I am happy not to use it and to try to direct install the contents of the Dockerfile.bio on roadrunner if that is possible.

**Comment by kubu4** [comment]
Using Docker is the fastest means by which to implement that software on the newly formatted computers. 

Docker Toolbox is already installed on Roadrunner and should be accessible from your user account.

As far as installing software independently on Roadrunner, please see Issue #343 . We need to confirm an installation location. 

Additionally, the installation commands should be added to a script file that can be used to perform the installation quickly/easily on all other machines.

**Comment by kubu4** [comment]
However, you are more than welcome to install software on your user account!

**Comment by sr320** [comment]
I believe in this instance the issue has been resolved by running straight...

**Comment by hputnam** [comment]
Yes, I think I am up and running! Thanks all!
