### ISSUE TITLE
Reinstall OS X on Emu

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#346]
Emu is showing flashing question mark folder when booting.

**Comment by sr320** [comment]
Does it make sense to just install linux one, maybe Emu?

**Comment by kubu4** [comment]
Installing Linux on Macs is a pain (and sometimes not possible) - that's why I set up that Dockerfile (creates a virtual Linux environment).

However, Sean could set up a virtual Linux (Ubuntu) machine on Emu. This would be similar to using Docker (possibly less complicated for the end user to use).

**Comment by sr320** [comment]
Ok- think you already told me that :)  - proceeding with OSX is good.

**Comment by seanb80** [comment]
Strange, I SSHed and Screen shared in the night before. Will get it fixed though!

**Comment by kubu4** [comment]
Yep, I even used it. Rebooted after installing updates and now not working.. M

**Comment by seanb80** [comment]
Installed Ubuntu 16.04.1. Both SSH and VNC should be enabled if anyone is interested in playing. The IP changed, so check the Roberts Lab Computing Resources spreadsheet for update.

**Comment by kubu4** [comment]
Assuming srlab and password is login?

**Comment by seanb80** [comment]
Yup!
