### ISSUE TITLE
Logistics for Monday @ Manchester

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#350]
Hi Team- I'll plan on catching the 7:50am ferry from Fauntleroy on Monday, and will catch a ride with PSRF to the hatchery, so I'll get there around 8:30am.  Let me know if I need to bring anything - I'm about to leave the office and I assume ya'll have the material transport figured out, but if needed I could pick things up over the weekend.

**Comment by hputnam** [comment]
Grace and I were thinking to catch the 8:45 direct ferry and could give you and Sam a ride then. If it sounds like it is better for everyone to take the 7:50, we can reassess our time of departure.

**Comment by kubu4** [comment]
You may wish to remove your phone number from your post, as it's publicly viewable. 

I'll catch the same ferry, but am unsure about logistics getting from the ferry to Manchester.

**Comment by kubu4** [comment]
Sorry, Hollie's post beat mine. I'll hitch a ride with her & Grace. Just tell me which ferry to be on. Thanks!

**Comment by laurahspencer** [comment]
Great- I'll plan on catching a ride with you guys @ 8:45am.  Just let me know if plans change See you on the ferry!

**Comment by kubu4** [comment]
8:45am ferry confirmed. See you then!
