### ISSUE TITLE
Create Labdocs wiki page that list all software installed on birds

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#354]
November 23, 2016 at 05:05PM<br>
created via Do Button

**Comment by kubu4** [comment]
Copied [Lab_Software.md
](https://github.com/sr320/LabDocs/blob/9073dc7caf2dcf40e7739fc7ce9d922b28468dc3/Lab_Software.md) to [wiki page](https://github.com/sr320/LabDocs/wiki/Lab-Software),

Has Hummingbird, but needs other birds.
