### ISSUE TITLE
Any tips for making tables in Jekyll blog posts?

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#355]
I am having trouble making tables in my blog posts using Jekyll. It shows up like this [see microplate arrangement](https://ellior2.github.io/BCA-assay/) even though the tables renders nicely in [my GitHub post](https://github.com/Ellior2/Ellior2.github.io/blob/master/_posts/2016-11-22-BCA-assay.md)

Am I missing something in my _config.yml file?

@hputnam I see that you made it work in several of yours but when I look at your raw GitHub posts they have the same format as my tables.

**Comment by sr320** [comment]
pretty sure it is this file that needs edit

 _reset.scss

see
https://github.com/hputnam/Putnam_Lab_Notebook/commit/94877317c8d846c7b51037799a11be6226a18ebc
