### ISSUE TITLE
Enzyme Order Request

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#356]
MSPI
Supplier: NEB 
Cat#: R0106L
25,000 units	20,000 units/ml
Quantity: 1

NEBuffer2
Supplier: NEB 
Cat#: B7002S	
5 ml	10X
Quantity: 1

62-9868

**Comment by kubu4** [comment]
These came in today.

I put them in the door of the -20C in 209, with all the Illumina kit stuff. They're in baggies.

**Comment by hputnam** [comment]
Thanks @kubu4
