### ISSUE TITLE
Complete RRF Final Report

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#358]
see http://www.washington.edu/research/main.php?page=rrfGuidelines2010

@grace-ac - could you draft - 

indicate what details you need 

proposal is in the markdown file re other issue.

**Comment by grace-ac** [comment]
From Issue #349, yes ? Which RRF proposal... the geoduck one?

**Comment by sr320** [comment]
yes

**Comment by grace-ac** [comment]
link to draft in progress: https://docs.google.com/a/uw.edu/document/d/1IHOzc0J4iiReIR1oyyUZko6ViFM5h6OL8hidMY4CWks/edit?usp=sharing

**Comment by sr320** [comment]
@sr320 is finishing up and submitting soon
