### ISSUE TITLE
Determine options for repair/replacement of sonicator

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#361]

**Comment by seanb80** [comment]
Contacted UW Scientific Instruments and Fisher Scientific for repair estimates/timelines. Will update. 

I looked up tip prices online and they seem to run between 350.00-550.00 per tip, so maybe Rhonda's idea of borrowing one from Genome Sciences for testing may be a good idea. Do we have someone to talk to about that (Emma?)

**Comment by seanb80** [comment]
No luck on trying Emma's sonicator tip. Apparently there are different shank diameters on the tips, and the shank for our sonicator is larger than that for Emma's. Still waiting for UW/Fisher to respond.

**Comment by seanb80** [comment]
Just heard back from the UW Scientific Instruments guy. Charges 108.00/hr, figures 1.0 hours for diagnostics, and repair will vary from there. No word back from Fisher Scientific yet.

**Comment by seanb80** [comment]
Update from the Scientific Instruments guy:

He cannot say for sure, but he is pretty sure that it's a cracked transducer crystal in the sonicating head part. I asked if it was possible to find a replacement head, and he said that the head and the power supply are tuned together, and are not interchangeable between machines.

He will call someone he knows at Branson (the mfg) tomorrow to inquire about flat rate repair, or exchange, but it's not sounding hopeful for a cheap repair.

New Sonicators of a similar wattage are ~$3500.00

ex. https://www.fishersci.com/shop/products/fisher-scientific-model-120-sonic-dismembrator-4/p-3974654

**Comment by seanb80** [comment]
Got email back from the SI guy. The manufacturer believes it's a problem caused by tip degradation (cavitation slowly wears metal off of the tip, changing the frequency with which the tip resonates) and suggests replacing the tip. 

New tips are around 400.00, which is considerably cheaper than a new machine, but not a guaranteed fix.

**Comment by sr320** [comment]
Let's purchase a new tip-
Can you provide ordering info?

**Comment by Ellior2** [comment]
Does he know that I heard a popping noise?

**Comment by seanb80** [comment]
Tip Order info-

Part number: 1091221065R

Fisher URL: https://www.fishersci.com/shop/products/branson-ultrasonics-microtips-sonifiers-slpe-slpt-150e-150t-4/p-3665707

The fisher site is significantly more expensive than most of the random biotech websites that also come up googling the part number, but I know little of their reliability. 

As far as the pop, did it sound like it came from the sonicator head, or the power supply? He was in the power supply and said the visible capacitors and transistors looked good.

**Comment by Ellior2** [comment]
It's hard to know where it came from, I thought it came from the main unit...

Do you know what brand Emma's lab uses? Their setup seems super durable. They even turn it on without liquid- no problemo.

**Comment by sr320** [comment]
@seanb80 that exact part number is not listed. The is one that lack the R....
Are you sure that is the correct one?

**Comment by seanb80** [comment]
The part number is per the SI guy, I will email him back to ensure that is
right.

**Comment by seanb80** [comment]
Heard back from SI, the R may or may not signify anything. Here is an
updated link for the part that has the full correct part number from
Grainger.

https://www.grainger.com/product/41V336??cm_mmc=Affiliate-_-Lab%20Supplies-_-%7Bsubid%7D-_-productfeed&avad=196442_fd13ad7b

**Comment by sr320** [comment]
order request #381

**Comment by seanb80** [comment]
Got the new tip in, same issue so it looks like replacement is our only avenue now. 

Sam said he would look in to returning the tip to Grainger, hopefully we'll get lucky there.
