### ISSUE TITLE
Add info to Software wiki page

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#362]
Add details of where software is installed on (directory)
https://github.com/sr320/LabDocs/wiki/Lab-Software

and include in Path such that user would just have to type command.

I presume samtools is installed as it is a dependency?

**Comment by seanb80** [comment]
Updated with links for the new birds (Ostrich and Roadrunner), Hummingbird will take a bit more hunting

**Comment by kubu4** [comment]
/user/local/bioinformatics

**Comment by kubu4** [comment]
Sorry.

/usr/local/bioinformatics

**Comment by sr320** [comment]
But to clarify - can I just type `trinity` to launch the program?

**Comment by laurahspencer** [comment]
Related: I'm trying to run various programs on Genefish (Jupyter Notebook, Bowtie2). Is it OK for me to install programs on that computer if they aren't already on it? E.g. Genefish has Bowtie, but not Bowtie2 (as far as I can tell). When installing, I presume I should install in the Shared -> Apps directory?

**Comment by sr320** [comment]
Yes & yes

**Comment by seanb80** [comment]
Everything has been added to /etc/paths and should work across users from any directory.
