### ISSUE TITLE
Trypsin Purchasing Reqeust

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#364]
@kubu4, could you order Tripsin for protein extractions that @yaaminiv & I are starting late next week? I believe this is what you ordered before?:

Trypsin (T8658-1VL)
http://www.sigmaaldrich.com/catalog/product/sigma/t8658?lang=en&region=US

**Comment by kubu4** [comment]
Which budget(s)?

**Comment by laurahspencer** [comment]
I'm not sure - @sr320 is there a budget number for the DNR project?

**Comment by sr320** [comment]
63-4279 <https://ucs.admin.uw.edu/MyFD/UWNetID/BudgetList.aspx#>

**Comment by kubu4** [comment]
That is not the trypsin I ordered for Rhonda. 

Would you like me to order the product listed above, or order the one that Rhonda used?

**Comment by laurahspencer** [comment]
The one you ordered for Rhonda, please.  Thank you!

**Comment by kubu4** [comment]
Will do. Thanks for clarifying.
