### ISSUE TITLE
Purchasing request: HOBO temp. loggers

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#365]
@sr320 @kubu4 
As discussed in last week's lab meeting we'd like **4 HOBO loggers** ordered for the Manchester Oly experiment nearly underway.  Hollie suggested the following:

HOBO U22 Series, "Affordable temperature monitoring for fresh or salt water":
http://www.onsetcomp.com/products/data-loggers/u22-001

Thanks!

**Comment by kubu4** [comment]
Which budget(s)?

**Comment by laurahspencer** [comment]
@sr320 here's a better question: is there a list of projects+budget numbers that I should reference for purchasing?

**Comment by sr320** [comment]
normally I will provide budget ...
in this case..  63-4279
<https://ucs.admin.uw.edu/MyFD/UWNetID/BudgetList.aspx#>
