### ISSUE TITLE
Instruments available in SAFS for protein extractions 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#366]
@kubu4 I'm drafting an email to Emma & Brook to arrange use of the below instruments in their Genome Science lab for @yaaminiv and my protein extractions.  I remember from our lab meeting some discussion of us using other SAFS labs - could you let me know who in SAFS has any of the below items? 

* Sonicator
* Speed vaccuum @ 4degC 
* Plate reader 
* De-salter 

Thanks!

**Comment by sr320** [comment]
Just inquire with Brook and Emma if you can use theirs..

**Comment by kubu4** [comment]
@emmats - When you have a sec, can you please provide details about your SpeedVac? Specifically, is it refrigerated or does it just have a cooled vapor trap? Thanks for your help!

**Comment by emmats** [comment]
From Genn in the MacCoss lab: We have the Refrigerated Centrivap Concentrator (Model 7310021), the Centrivap Cold Trap, Vacuum Pump and the Strobe Light. Manual attached.
[LabConco NewCentriVap Manual.pdf](https://github.com/sr320/LabDocs/files/664602/LabConco.NewCentriVap.Manual.pdf)
