### ISSUE TITLE
MS autosampler vials

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#369]
@kubu4 Please order more MS autosampler vials. I guess they are not longer included in the price of the MS rental. We ended up taking a full unopened box and so we will need to replace it. I will bring back the remainder of the box I am using.

[MSCERT5000-33TR](https://www.thermofisher.com/order/catalog/product/CERT4000-993)

It's also listed on the [protocol](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) 😉

**Comment by laurahspencer** [comment]
@kubu4 do you know where these are being stored in the lab? I don't see them listed on the inventory, or in the lab ...

**Comment by kubu4** [comment]
FTR 209. Cabinet 50. 

See row 51 of [Roberts Lab Inventory](https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=0)
