### ISSUE TITLE
New OlyO RAD libraries

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#37]

**Comment by sr320** [comment]
New DNA - post BS; maybe go with BGI

**Comment by sr320** [comment]
New DNA extractions this week

**Comment by sr320** [comment]
@jheare so "fresh samples" have degraded DNA? or ?

**Comment by jheare** [comment]
Looks like it. I'm running the other half of the samples today. Though I
doubt they'll look much better. I'm not aware of what would be causing the
degradation as everything was processed quickly.

**Comment by sr320** [comment]
Isolate DNA from a subset of samples with DNAzol - this should yield better HMW DNA.

**Comment by sr320** [comment]
![image](https://cloud.githubusercontent.com/assets/4442039/6315083/9963c9ca-b9ab-11e4-8d41-cbf82836e915.png)

**Comment by sr320** [comment]
![image](https://cloud.githubusercontent.com/assets/4442039/6315096/f84a9676-b9ab-11e4-96fc-0b56f3807207.png)
