### ISSUE TITLE
Create Word version of Geoduck Proteomics paper

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#371]
for bioarxiv

**Comment by grace-ac** [comment]
I have one, just waiting on some citations from emma!

**Comment by grace-ac** [comment]
reminder for @sr320 to read discussion before submission anywhere

**Comment by sr320** [comment]
You have link to the word version?

**Comment by grace-ac** [comment]
https://drive.google.com/file/d/0B_Kednl1tNImbl9JakRCR3k1ZnM/view?usp=sharing

**Comment by sr320** [comment]
revised
[Timmins-Schiffman-biorxiv-v1.docx](https://github.com/sr320/LabDocs/files/646818/Timmins-Schiffman-biorxiv-v1.docx)

**Comment by sr320** [comment]
new url to use for supplemental files

https://github.com/sr320/supp-geoduck-proteomics
