### ISSUE TITLE
Directory permissions on Owl?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#372]
We've had two recent incidents (Katherine and Sean) of people accidentally moving files that shouldn't be moved. 

Should we consider "locking" down specific directories to minimize accidental changes to "permanent" directories?

**Comment by sr320** [comment]
Ideally everyone would only have write access to their web directory, and
maybe a general one.... ie whale.
And then can give access to folks as necessary- ie nightingales.

**Comment by sr320** [comment]
Oddly it appears @seanb80 did not have access to nightingales but all other directories in web. 
He was able to remedy this on linux, but in the web interface I could not figure out.

**Comment by kubu4** [comment]
@seanb80 - How did you resolve this issue?

**Comment by kubu4** [comment]
That behavior was expected. I locked down the nightingales folder after Katherine and Sean had those issues.

In regards to viewing permissions via the web interface, there are two different places (at least) to manage permissions. The first, which is the most obvious one, is via Control Panel > User menu:

![selection_012](https://cloud.githubusercontent.com/assets/4514104/21811105/3b91746a-d703-11e6-8ad5-fbdb4298288d.png)


The second method is folder permissions viewed in File Station and then right-clicking and selecting "Properties" for a given folder:

![selection_013](https://cloud.githubusercontent.com/assets/4514104/21811141/5d9d178a-d703-11e6-89fd-a96f50ddade8.png)


The above images show that Sean has permissions to Read/Write to the web folder, but when we look at permissions for the nightingales folder, the only group that has Read/Write permission is the Admin group (which Sean is not a part of). These group permissions supercede individual Read/Write permissions set at the user level.

**Comment by seanb80** [comment]
I believed I had fixed it by resetting folder permissions via chmod +777 /owl/folder/ but apparently this was not a permanent solution as my uploaded script failed after a single file with a permission denied error. 

It's still possible for me to upload files to nightingales, it just requires a sudo prefix for each file.

**Comment by kubu4** [comment]
Interesting. In my mind, you shouldn't be able to sudo around the permissions settings on Owl. I wonder how this works... You're an admin on Emu, but a "regular" user on Owl. It's surprising you can utilize sudo to overcome permission settings on a different Linux system.

**Comment by kubu4** [comment]
@seanb80 - You're now in the admin group on Owl. So, you should have no issues reading/writing to any folders.
