### ISSUE TITLE
Starting tissue amount for MS?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#373]
What is the recommended starting amount of tissue for the protocol?

https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md

We would like to conserve upcoming samples as much as possible.

**Comment by emmats** [comment]
If you start with tissue about the size of your pinky nail, you will have more than enough. I extracted single copepods this summer and they yielded barely enough protein.

**Comment by sr320** [comment]
So half a pinky nail is enough? Copepods (is that like a piece of rice?) or microscopic?

**Comment by emmats** [comment]
half of a pinky nail is enough
copepods are approximately a grain of short-grain rice :)
