### ISSUE TITLE
Purchasing Request: 48gb RAM for EMU

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#374]
Can we order 48gb of ram for Emu? This SKU has been ordered in the past.

https://eshop.macsales.com/item/OWC/85MP3S4M48GK/

Thanks!

I can't check the slot population without cracking the blade, but in the old RAM box there's 6x 2gb sticks from the last blade that was upgraded, so I would imagine that Emu is in a similar state and requires a full replacement to max. Can open the blade to verify if need be.

**Comment by kubu4** [comment]
Is this intended to ask @sr320 for approval or is this intended for me to proceed with the purchase?

Also, will need budget number(s), please.

**Comment by kubu4** [comment]
If we proceed with this, here's my [notebook entry](http://onsnetwork.org/kubu4/2016/06/09/ram-upgrade-roadrunner-apple-xserve-to-48gb-ram/) on the Roadrunner upgrade. The most helpful aspect of the post is the image with my finger pointing to a lever; this lever needs to be pushed down (I think on both sides) to release the blade from the rack.

**Comment by sr320** [comment]
proceed with 61-0221

**Comment by kubu4** [comment]
After this comes in, I'd recommend transferring the current Emu RAM to Hummingbird.

**Comment by kubu4** [comment]
@seanb80 - What did you end up doing with the leftover RAM? Did you add it to Hummingbird?

**Comment by seanb80** [comment]
I did not. I put it with the other ram in the conference room. I can add it to hummingbird tomorrow if you like.

**Comment by kubu4** [comment]
[Yes please.](https://github.com/sr320/LabDocs/issues/374#issuecomment-265556177)

Thanks!
