### ISSUE TITLE
Blank "sample" for protein extraction necessary?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#375]
@emmats do you recommend preparing a "blank" sample in our protein extraction process? It doesn't look like Rhonda did this, nor is it listed in the protocol, but perhaps it would be helpful?

**Comment by emmats** [comment]
I never do it, but of course there is value to it. We do have a collaborator who did blank extractions, but the mass spec is so time-intensive that we chose not to analyze them.

**Comment by kubu4** [comment]
I spoke to @laurahspencer and @yaaminiv about this. I recommended they run a blank (i.e. negative control).
