### ISSUE TITLE
Lyophilizing tissue samples

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#376]
I guess @laurahspencer and I missed the fact that we would need to lyophilize our gill tissue samples. We would need to homogenize in liquid nitrogen or with a tissue mill before sonication.

@emmats & @sr320: any suggestion on how to go about this/where to get the equipment from?

Also @emmats: At what point in the [protocol](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) with samples need to be lyophilized?

**Comment by sr320** [comment]
Will just use 1.5 ml tubes and corresponding pestels.
