### ISSUE TITLE
Generate Plot showing CpG o/e and GO slim for Geoduck transcriptome

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#377]
For annotated contigs, generate a plot reminiscent of 

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/DNA_methylation_patterns_provide_insight_into_epigenetic_regulation_in_the_Pacific_oyster__Crassostrea_gigas____BMC_Genomics___Full_Text_1DF9C6ED.png" alt="DNA_methylation_patterns_provide_insight_into_epigenetic_regulation_in_the_Pacific_oyster__Crassostrea_gigas____BMC_Genomics___Full_Text_1DF9C6ED.png"/>

or 

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/onlinelibrary_wiley_com_doi_10_1111_mec_13414_epdf_1DF9C710.png" alt="onlinelibrary_wiley_com_doi_10_1111_mec_13414_epdf_1DF9C710.png"/>

----

CpG o/e (and more @ 
https://github.com/sr320/paper-pano-go/raw/master/data-results/Geoduck-transcriptome_v3_bigtable_v08.tab

-- 
corresponding go-slim bin...
[GOslim-bin.txt](https://github.com/sr320/LabDocs/files/640062/GOslim-bin.txt)

---
hints
- https://github.com/sr320/course-btea/blob/master/day-5/02-Piura-CpG.ipynb
- https://github.com/sr320/course-fish546-2015/blob/35f95be9d5f7429e82f6862a20bd62afb64733bd/notebooks/Jay-CpG.ipynb

**Comment by seanb80** [comment]
Plot like the first:

![rplot02](https://cloud.githubusercontent.com/assets/10619258/21061726/652a7728-be02-11e6-9934-eeb209aa7d9f.png)

Notebook here, though I'm experiencing a rendering bug with R Notebook, so this is a previous version without the N values attached to the labels. It gets the spirit however: 

http://rpubs.com/seanb80/234128

**Comment by sr320** [comment]
Awesome! 

Is there a way to plot where we see all data points? something like

http://zevross.com/blog/wp-content/uploads/2014/08/image50sm.png

**Comment by seanb80** [comment]
I'll try to add a strip chart on top of it, though I think the forest plot
is a unique object, so it may have to be rebuilt.

**Comment by seanb80** [comment]
Here's an updated graph. 

![ordered cpg](https://cloud.githubusercontent.com/assets/10619258/21154195/567a5eaa-c122-11e6-850e-1bec2882502f.png)
