### ISSUE TITLE
Git push timing out with fatal error

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#378]
I'm trying to push my git commits to GitHub, which include a few large files, and I receive the following error: 

![git push error](https://github.com/laurahspencer/LabNotebook/blob/master/images/Snip20161208_2.png?raw=true) 

Perhaps the files are too big; I found a possible solution [online](https://confluence.atlassian.com/bitbucketserverkb/git-push-fails-fatal-the-remote-end-hung-up-unexpectedly-779171796.html)  that has me editing the config file to increase buffering capacity via: 

Increase the Git buffer size to the largest individual file size of your repo:
`git config --global http.postBuffer 157286400`

Anyone else run into this issue?

**Comment by sr320** [comment]
One work around and possible troubleshooting activity would be to use GitHub Desktop and see if that works.

**Comment by kubu4** [comment]
Out of curiosity, what do you consider "large" files? Also, have you
checked your remote repo and verified that the push command actually failed
to copy your commits?

**Comment by laurahspencer** [comment]
Large file: 16.6 GB
I did check my remote repo, and yes the committed files aren't showing up there.

**Comment by sr320** [comment]
files have to be less than 100MB

**Comment by laurahspencer** [comment]
Wow - ok, that is likely the issue then.

**Comment by sr320** [comment]
Yes you will have to have ignore that file when syncing
