### ISSUE TITLE
Oyster seed morphology 

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#379]
### 2016 Oyster Seed Morphology Samples

Thank you Grace for helping me with my oyster seed experiment!

- There are 4 replicates per treatment for this experiment:
1, 2, 3, and 4 are from 23C 
7, 8, 9, and 10 are from 29C

- You only need to look at 2, 3, and 9 for now because that is what we are doing proteomics on.

- We are hoping to get morphology information (or development stage) via size measurements as well as survival information from these oysters.

- Everything is preserved in 70% ethanol so be careful the labels don’t wipe off.

- If you want more information about the experiment see the [wiki](https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/2016-Oyster-Seed-experiment-23C-vs.-29C)

- Please save the remaining samples.

- Take photos if you can. 

__2ml crytobes__
1. I have taken one sample everyother day from each of the replicates throughout the experiment. Please measure 3 sets of 100 from each sample. Also document live/dead.

__10ml testubes__
	
2. These are from the very last day of the experiment. Each tube within a bundle contains a certain size class within that replicate. Again, please measure 3 sets of 100 from each sample and document live/dead.

3. Can you also do volumetric counts on the largest size (4000-5000) from each of these replicates? At the hatchery I estimate how many oysters I have by screening them by size. Because we have done most of the counts in previous years, I can say for example, in 1ml I have 2000 oysters in the screen size range of 710-1000 microns. However, I do not have these volume counts for the largest (4000-5000 microns) size which is where we will tend to see a lot of variation among replicates with regard to #of oysters per ml. Try using a small 5 or 10ml graduated cylinder. Ideally you would want to count about 100 so use an approximate volume that would allow you to count 3 replicates of 100 per sample. Perhaps you can tie this in with step 2 for efficiency.

__Here is an example of the volume counts I have already for the other sizes__

| Lower   screen size | Upper screen   size | Number of   seed/mL |
|---------------------|---------------------|---------------------|
| 450                 | 710                 | 3577                |
| 710                 | 1000                | 2000                |
| 1000                | 1320                | 846                 |
| 1320                | 1600                | 328                 |
| 1600                | 2000                | 200                 |
| 2000                | 2380                | 95                  |
| 2380                | 3000                | 47                  |
| 3000                | 4000                | 32                  |

Please let me know if you have any questions! THANK YOU!!

**Comment by Ellior2** [comment]
I realize this is probably going to be pretty time intensive. Let's do 3 sets of 50 instead and see what level of variability we are getting. Also (stating the obvious), make sure to get a representative sample from the tube- the smaller ones sink to the bottom and the dead shells seem to sit on top. Do you guys have any voice recognition software that would make this faster?

**Comment by grace-ac** [comment]
Okay! I should be able to get started on this process next Wednesday. I just need to find a dissecting scope and a 10ml graduated cylinder ( @kubu4 ?)

**Comment by sr320** [comment]
Grace - you are suppose to know where everything is! You realize Sam is
just going to send you a link to your spreadsheet :)

**Comment by grace-ac** [comment]
haha i know! I just haven't found a 10ml anywhere and didn't know if there was a secret stash...

**Comment by kubu4** [comment]
I'm fairly certain we don't have either of those items. 

It's possible a dissecting scope was taken (and left) at Manchester? Friedman Lab has one you can use, but it'll have to stay in the Friedman Lab. Also, Jon Wittouck might be able to loan us a SAFS Instructional dissecting scope...

Alternative to 10mL graduated cylinder would be to use a 10mL serological pipette.

**Comment by kubu4** [comment]
Although, now that I've read through the above protocol, it's not clear to me what the purpose of the graduated cylinder is. It doesn't seem like it's actually being used to measure anything. Is that correct? If all you need is a vessel to hold 10mL, you can use a 15mL (or 50mL) conical tube, or a small beaker...

**Comment by grace-ac** [comment]
Yeah, I think Rhonda was just thinking that 10ml might be more user friendly.

**Comment by Ellior2** [comment]
For step #3, we will need some way to measure volumes of the 4mm to 5mm oysters. I need a conversion (like I have for the other sizes in the tables) that will allow me to calculate the number of oysters I have based on the size and volume I measured. For example, for the 3mm to 4mm seed I already know there are 32 oysters/ml, so I am guessing in the 4mm to 5mm range there might be like ~15 oysters/ml (?). But to get a good estimate, we might want to measure out say 7ml and count how many oysters there are (hoping to count at least 100). And do this three times. A graduated cylinder or small beaker in my mind was a good way to do this, but I am open to other options. Keep in mind these oysters are about 5mm so they will not fit in a pipette.

**Comment by grace-ac** [comment]
Emailed Jon asking about a dissecting scope for next week - so if there's one available, this will begin next week!

**Comment by grace-ac** [comment]
Here's what I've started: https://drive.google.com/open?id=0B_Kednl1tNImbEwwdW1kYUFxbjA

Images folder is where I'll put all the labeled images used for ImageJ.
The spreadsheet has a tab for the 10ml tube measurements. A tab for raw image J output which I have to use to reorganize measurements. A tab for the cryotubes.

I'm not used to looking at oysters, so I'm trying to be extra careful about making sure I am measuring the lengths and widths correctly, as many are oddly shaped.

**Comment by Ellior2** [comment]
Looking good Grace! Thank you!!

**Comment by grace-ac** [comment]
Here's some summary info on what I have so far. 

For the mortality... I only used the oysters that I measured. And I only measured those that I could clearly distinguish their shape. There were often large clumps of oyster seed that were too difficult to accurately measure, so I skipped them. I don't think the mortality method I did is truly representative. 

![screen shot 2017-03-13 at 9 09 47 pm](https://cloud.githubusercontent.com/assets/14934314/23885604/84b3fc4e-0831-11e7-8a02-68178a7cece5.png)

**Comment by grace-ac** [comment]
The above table is in the google spreadsheet that I have shared previously. Here's the [link](https://docs.google.com/a/uw.edu/spreadsheets/d/1PS_-GUlnSuXMcfpp3Z91tiusy2YLXJKn022I17Y8Xes/edit?usp=sharing).

**Comment by Ellior2** [comment]
Thanks grace- what you did is just fine. I know how challenging it is to measure these guys and draw that line between dead and alive. What matters for us at the production level is the number of single live oyster seed that we get from a group and I think we get that from your counts. We usually try to get rid of clusters if we are able to screen them out early on.

**Comment by Ellior2** [comment]
Did you by chance check to see how many 4000um screen size seed fit into say 7ml? All I have in my experiment notes is the volume of seed I have for that size class because I don't have a conversion yet for the 4mm.

**Comment by grace-ac** [comment]
I haven't' done that yet, sorry! I can easily do that when I'm in tomorrow.

**Comment by Ellior2** [comment]
Cool! I really appreciate it Grace!! Thank you!

**Comment by grace-ac** [comment]
For 7ml, I did three counts. 133, 166, 165. 
Average = 154. 154/7 = 22 seed/ml at 4000+µm.

**Comment by Ellior2** [comment]
Perfect, thank you!

**Comment by sr320** [comment]
Lets hold on this until we can chat with @Ellior2 on the end goal and confirm approach is correct.

**Comment by Ellior2** [comment]
@grace-ac did you do a % survival for the 710-1000's?

**Comment by grace-ac** [comment]
@Ellior2  No, because I was told to pause the project until Steven was able to speak with you more about it.

**Comment by Ellior2** [comment]
Ok, well you have done over 95% of the morphology analysis. If you were to get survival estimates on the 710-1000s then I would have the full picture of survival- which would be really helpful @sr320 . I really appreciate everything you have done Grace!

**Comment by sr320** [comment]
Go ahead and do that if you understand what Rhonda is asking-

Can we talk via phone at 2pm tomorrow about this?

**Comment by Ellior2** [comment]
Me? Yes. Grace's numbers so far have really helped in getting a more accurate representation of survival. Not including the 710-1000's I am calculating:

Silo 2-23C: 3.1% survival ( I estimated 2% earlier)
Silo 3-23C: 6.6% survival (I estimated 10% earlier)
Silo 9-29C: 18.1% survival (I estimated 10% earlier)

My earlier estimates were just based on # of seed (both alive and dead) that held on at least a 1800um screen which obviously was not accurate. It really helps to count # of live oysters in each size class. If you just try to take one homogenized sample of all the seed to assess you will end up getting really high variability due to such different sizes with the smaller ones having high mortality.

**Comment by grace-ac** [comment]
@Ellior2 : Updated summary data
![screen shot 2017-04-11 at 12 19 23 pm](https://cloud.githubusercontent.com/assets/14934314/24926657/4006e89a-1eb1-11e7-95e3-9024b2e3511b.png)

**Comment by Ellior2** [comment]
The summary table above looks a little fishy. The mean size of Silo 2 2380-3000's are tiny. I will go through the whole document and make sure all the formulas are correct. I can take it from here though, thanks Grace! You have helped immensely.
