### ISSUE TITLE
Katie Capstone Paper

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#38]

**Comment by sr320** [comment]
Introduction past due.

**Comment by sr320** [comment]
Waiting on url

**Comment by sr320** [comment]
What can we do with this?

https://docs.google.com/document/d/1hdy7NU7wLdXbA-_BqhF9dyfrD-TWqfrz2c7Yj0DRE_Y/edit?usp=sharing

**Comment by sr320** [comment]
Made some minor revisions to intro -

NOTE there are no RESULTS, so the value in lacking - there are good methods

**Comment by jheare** [comment]
Here's Katie's results from a [word doc](http://genefish.wikispaces.com/file/view/Oly%20anesthesia%20data.docx/507850388/Oly%20anesthesia%20data.docx) she hosted on her notebook. I think these are the final results she gave.

**Comment by jheare** [comment]
Here's her raw data from [April 11th 2013](http://genefish.wikispaces.com/file/view/4-11-13.xlsx/435600190/4-11-13.xlsx) and [May 14th 2013](http://genefish.wikispaces.com/file/view/05-14-13.xlsx/435600210/05-14-13.xlsx). I'm pretty sure you can mess with this for statistical analysis.
