### ISSUE TITLE
Install Proteomics Software on Emu

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#380]
Does not have to be Emu - but my guess is Linux is best for these three proteomics packages that we need for data analysis

1) http://comet-ms.sourceforge.net/

2 ) http://tools.proteomecenter.org/wiki/index.php?title=Software:TPP#Mac_OSX

3) http://abacustpp.sourceforge.net/

**Comment by seanb80** [comment]
Update on this. Comet and Abacus installed, I'm having numerous issues with TPP stemming from some issues with a library called Boost. I'm currently trying some workarounds, but not having much luck.

**Comment by sr320** [comment]
It is fine if TPP is on a Mac- It seems to not be officially supported but there are third-party intructions

**Comment by seanb80** [comment]
Everything is now installed and operational on Emu.

http://rpubs.com/seanb80/234188

**Comment by sr320** [comment]
Thanks!
