### ISSUE TITLE
Purchase new Sonicator Tip

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#381]
https://www.grainger.com/product/41V336??cm_mmc=Affiliate-_-Lab%20Supplies-_-%7Bsubid%7D-_-productfeed&avad=196442_fd13ad7b

Budget: 63-4279

**Comment by kubu4** [comment]
Sonicator tip has arrived. Have placed on top of sonicator control unit.

**Comment by laurahspencer** [comment]
Sean - can you remember if the sonicator is now functional?

**Comment by kubu4** [comment]
Re-closing issue, as this was purchased already.

See Issue #361 for info on sonicator.

**Comment by seanb80** [comment]
It is not functional, it wasn't the tip that was broken but something in the transducer that necessitates replacement of the entire device.

**Comment by laurahspencer** [comment]
Thanks y'all!
