### ISSUE TITLE
TA samples on Friedman Titrator

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#382]
In pursuing the option of using the Friedman lab titrator - there are a few question....

1) How many samples are there to run?

2) Do we have CRMs?

**Comment by hputnam** [comment]
There are ~102 from the juvenile experiment.

There are ~38  from trial 2 of the larval experiment.

We do not have Dickson CRMS or Dickson acid, but can place an order prior to running samples, or to replace materials as necessary
