### ISSUE TITLE
Screen Sharing not connecting to Roadrunner @ login, unless Roadrunner is awake

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#383]
I'm trying to connect to Roadrunner via Screen Sharing and the connection continually drops, is extremely slow to respond, making it not possible to use.  This happens from both my house and the lab. However, just now I sat down to Roadrunner, logged on, and then Screen Sharing on my computer worked well.  Anyone have ideas as to why Screen Sharing doesn't connect when Roadrunner is asleep? 

Thanks!

**Comment by sr320** [comment]
If you connect, and it is just slow, that is either a network issue, or
roadrunner issue (cpu / ram used; would be same experience as if you sat in
front of).

If in fact it does not connect when asleep, do not let it go to sleep

**Comment by kubu4** [comment]
@laurahspencer - Here's how to disable sleeping: https://support.apple.com/kb/PH21695?locale=en_US

If you need/want help with this, let me know.

**Comment by laurahspencer** [comment]
Looks like I need the admin credentials to change Energy Saver options, as
the user login credentials aren't sufficient...

Thanks!

**Comment by sr320** [comment]
I changed it so it does not sleep.

**Comment by laurahspencer** [comment]
Thanks! I'll see if that changes things
