### ISSUE TITLE
Amazon business account?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#384]
I know we discussed before, but I think this might make purchasing easier?

**Comment by kubu4** [comment]
Yes and no. 

Yes - No ProCard reconcilation.

No - Free, 2-day shipping is limited to orders >$50.

**Comment by sr320** [comment]
But what about actual purchasing - anyone could purchase thus skipping steps such that someone else has to go back in and add to cart?

**Comment by kubu4** [comment]
Good question! Let me check. Last I heard, it was supposed to get tied to eProcurement (once it was fully operational). So, that would mean ordering would be the same as it is now.

**Comment by kubu4** [comment]
Looks like I was wrong about ProCard!

UW Amazon Business FAQ: https://f2.washington.edu/fm/ps/sites/default/files/Resources/charts/Amazon%20Business%20FAQ.pdf

Still requires use of ProCard (which would still require reconciliation at the end of each month) and Amazon Business is still not an option via eProcurement.

However, you can enable multiple Amazon Business users under a single "group" (i.e. account). So, multiple people could place orders...
