### ISSUE TITLE
analyzing DDA data from the mass spec

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#388]
Here are general guidelines for analysis of data dependent acquisition acquired mass spectra (or, shotgun proteomics). @Ellior2 will be following these steps, Laura and Yaamini will be doing something slightly different and should see notes on DIA analysis.
1. Search files against a protein sequence database using Comet. 
You will need: 

- Comet installed and an appropriate comet.params file

- Your raw experimental files (excluding blanks and QCs) in one directory

- a protein sequence fasta file that you expect is a good match to your acquired data

I usually soft link my files to a specific search directory (link -s). The comet.params file must be in the same directory. Make sure your parameters reflect the type of data you have and that the database path is correct. More details can be found on the UWPR website. It is good practice to include a decoy search.
If searching all files in the directory, you can simply type: runCometQ *.raw

---
2. Calculate statistics associated with peptide and protein IDs using the Trans Proteomic Pipeline (Peptide and Protein Prophet). 
What you will need:

- TPP installed

- pep.xml search results from Comet
I usually run TPP in the same directory as my Comet searches. You need to run it on each file individually, but each analysis is relatively fast.
I use a p-value cut-off for my peptide probability of 0.9, but this can be changed depending on what you want.
For each file, run: xinteract -p0.9 -OAp -dDECOY_ -N[file name without pep.xml] file name.pep.xml

3. ABACUS will correlate protein inferences across your sample files so that a single protein will be associated with each peptide.
You will need:

- ABACUS installed

- interact -....pep.xml files from TPP

- An Abacus parameters file
Details can be found on the UWPR tools page. Once ABACUS runs, you will have a .tsv file with all your files joined together and corresponding spectral counts and normalized spectral abundance factor (NSAF), which will be your proxy for protein abundance.

**Comment by laurahspencer** [comment]
Thanks, Emma. 

So, to confirm @yaaminiv and I will be doing DIA analysis on our samples. We see that this includes the extra optional digestion step:

"For DIA analyses: Add ApoA1 to each sample (dilute 1.1 µl 2200 ng/µl stock in 48.9 µl of 50mM NH4HCO3 to make 50 ng/µl) to make 1:300 ratio of ApoA1:total protein. For 100 µg total protein in a sample, add 333 ng of ApoA1 by adding 6.7 µl of 60 ng/µl ApoA1 solution."

Since we are working with 30ug instead of 100ug, we will add 2.2ul of the prepared 60 ng/µl ApoA1 solution. Let us know if we've misinterpreted anything.

**Comment by emmats** [comment]
If you have the ApoA1, it does not hurt to include it. Thanks for catching that - I forgot! And, yes, you should adjust to your different protein amount.

**Comment by yaaminiv** [comment]
We checked the -20º in the lab and the MerLab freezer for ApoA1 and couldn't find it! @kubu4 do you know if we have this? If not, we'll just proceed without it

**Comment by emmats** [comment]
Don't worry about it too much. You'll be fine without it.

**Comment by sr320** [comment]
@Ellior2 - where did you keep the ApoA1? I looked in the Restriction Enzyme box.. did not see it

**Comment by laurahspencer** [comment]
FYI @sr320 Rhonda did not use ApoA1 in her digestion

**Comment by Ellior2** [comment]
I did not use ApoA1. Emma said I didn't need it for DDA. I did not order it. If they want to use it, they probably have to borrow some from Emma, but it sounds like its not necessary

**Comment by sr320** [comment]
Gotcha- So based on my investigation, We never had that, as it was never ordered. Seems moot? but if anyone will need it, it needs to be ordered.

**Comment by emmats** [comment]
Right. But I think we cover part of the purpose of ApoA1 by adding the PRTC QC peptide mix pre-MS analysis. That will be ordered, I believe.

**Comment by seanb80** [comment]
So I'm playing with the software for this and have a quick question. You guys reference a runCometQ command, but the installation from http://comet-ms.sourceforge.net only has a comet.exe executable. Is this an in house script, or is there a better source for comet that has this. Tried googling for runCometQ and the only results are a few UWPR pages and a couple of Steven's Geoduck things.

Thanks!

**Comment by emmats** [comment]
All I know is that Comet is installed on our cluster and all I need to do is navigate to my search directory and type runCometQ. Sorry I can't be more help. Feel free to contact Jimmy (engj@uw.edu).

**Comment by sr320** [comment]
Moved to wiki
https://github.com/sr320/LabDocs/wiki/DDA-data-Analyses
