### ISSUE TITLE
analyzing DIA data from the mass spec

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#389]
This is the workflow that @Ellior2 is following for OOSP and that @laurahspencer and @yaaminiv will be following for their data. I think it is a little less intuitive than the DDA pipeline, but I will try to explain it.
1. Using PECAN, create a peptide spectral library from your data. PECAN correlates your acquired peptide spectra to a database of known sequences and creates a library of proteins and peptides that you detected in your experiment.
You will need:

- PECAN installed

- raw data files converted to mzML using MSConvert

- the peptides you want to find in your data - this can be all the peptides in the proteome, in which case you will need to in silico tryptic digest your proteome. The peptide list should be tab delimited with protein name and peptide sequence. Be sure to include your QC peptides.

- a background proteome - tab delimited file with protein name and peptide sequence. May be the same file as your peptide list.

- an estimate of the memory needed - I always just ask Sonia, who sits behind me, but I will ask her how to derive a valid estimate

- mzML file path list: I create this using nano in my directory and it is just a list of the path to each mzML that you will include in your analysis.

- peptide path file: create using nano; file path to your peptide list

- isolation scheme: create using nano; list of DIA precursor isolation windows. This will be experiment dependent. You will need to look at your method file to figure this out.

Sonia has instructions here: https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe, but honestly, I had a hard time following them. I gave her suggestions for edits, but I'm not sure if she included them. Below is the command I run for Pecan.

pecanpie -o [directory to create] -b [background proteome.txt] -n [blib file name] --isolationSchemeType BOARDER --pecanMemRequest [Gb] [mzML file path list name] [peptide file path name] [isolation scheme file name] --fido --jointPercolator

This step will be fast, but is just setting up the real pecan run. Navigate to your newly created directory and run pecan: ./run_search.sh

Pecan takes a while to run, especially if you are looking for all possible peptides in your proteome.

2. Get protein and peptide abundance information from Skyline.
You will need:

- Skyline (preferably Skyline daily, but you need to get permission to download it)

- your .blib file from pecan

- your fasta proteome, including QC protein sequence
You should already have instructions on how to use Skyline. You will put all your data in Skyline and export the peak area integration values (your proxy for peptide/protein abundance). You are relying on Skyline to pick the correct peaks across all samples. I would check how well Skyline is doing by 1) ensuring that all your QC peptides are chosen correctly and 2) ensuring that a certain number (10? 20? 100?) of your peptides were chosen correctly across all samples. From this information you can derive an estimated error rate for Skyline.
You export your peak areas in a csv file.

3. Normalize your peak areas for experimental peptides/proteins by peak areas of your QCs.
I do this by calculating the coefficients of variation for all my QC peptides across all samples. Since the same amount of QC was spiked into each sample, peak areas should be the same. I then select the QC peptides with CV<10 and I normalize all experimental peak areas by the average of those QC peak areas. You will then have a normalized dataset to analyze.

**Comment by sr320** [comment]
Moved to wiki 
https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses
