### ISSUE TITLE
Proteomics data for testing TPP/Pecan install

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#391]
Do we had some proteomics data somewhere for testing TPP and pecan installs?

 Both have numerous dependencies and I was hoping to run a test case to ensure proper functionality.

**Comment by sr320** [comment]
👍 see https://github.com/RobertsLab/project-pacific.oyster-larvae/issues/12

Fill free to create issues in that repo to inquire about details of data-

Related I am developing data management plan for proteomics
