### ISSUE TITLE
Close out BGI Genome Projects

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#392]
- [x] Indicate we would like the partial refund option
- [ ] Obtain complete details on what was carried out as reports are not clear / inaccurate. In a manner suitable for publication
- [x] Obtain validated version of all raw data.

**Comment by kubu4** [comment]
Turns out, all of the FASTQ files we've received from them are all identical - only the names differ. Verified by checking md5 and they all match.

**Comment by sr320** [comment]
So one raw file is corrupt on their end?

**Comment by kubu4** [comment]
I finally figured it out! The two original "corrupt" files are actually incomplete downloads! That's why checksums don't match AND why they cannot be unzipped/FASTQC'd!

**Comment by sr320** [comment]
Replace the incomplete, naming as others.
I guess I do not really care about other locations on owl, only
nightingales and the corresponding sheet that describes the files and
libraries.

**Comment by kubu4** [comment]
Here's the info Frank (BGI rep) provided me with (he attached a bunch of screenshots; sorry). I think most of it my just be taken from the project report PDF...

![image004](https://cloud.githubusercontent.com/assets/4514104/22073477/4a534b74-dd5a-11e6-82d0-7d1ebcb66380.png)
![image005](https://cloud.githubusercontent.com/assets/4514104/22073484/4c81337a-dd5a-11e6-8b05-02d3b6031df6.png)
![image006](https://cloud.githubusercontent.com/assets/4514104/22073491/4e931250-dd5a-11e6-895d-578c3588a4bc.png)
![image007](https://cloud.githubusercontent.com/assets/4514104/22073496/50710d7a-dd5a-11e6-8c3e-1c572b10908e.png)
![image003 1](https://cloud.githubusercontent.com/assets/4514104/22073499/524c8b7e-dd5a-11e6-8d96-9459c7953064.png)

1).data filter: filter reads with adapter

                     filter reads with small size

                     filter reads with >2% base is N

                     filter reads with many low quality(<30) bases

2).kmer : software: kmerfreq 1.0 

              Genome Size=K-mer_num/Peak_depth

3).simulate_heterozygosis : software readsim 2.2

                                        parameter: false ratio: 0.001/0.0015/0.002

                                                         repeat ratio:0.15/0.3/0.5/0.7

                                                         hybrid ratio:0.005/0.01/0.015/0.02

4).assembly: software : SOAPdenovo_v2.01

5).GC_depth: inhouse program

6).close gaps: software: krskgf 1.19 / GapCloser_v1.12

2. We used the script below to generate the fa file.

 

SOAPdenovo_v2.01 pregraph -s lib.cfg -d 1 -K * -o out.prefix >pregraph.log

SOAPdenovo_v2.01 contig -D 1 -M 2 -g out.prefix >contig.log

SOAPdenovo_v2.01 map -s lib.cfg -g out.prefix >map.log

SOAPdenovo_v2.01 scaff -g out.prefix -F >scaff.log

**Comment by sr320** [comment]
So what is the resulting fasta file of the genome?

I have become confused on their two data dumps to us in 2016.

**Comment by kubu4** [comment]
The resulting FASTA file is [Ostrea_lurida.scafSeq](http://owl.fish.washington.edu/O_lurida_genome_assemblies_BGI/20160512/Ostrea_lurida.scafSeq)

**Comment by sr320** [comment]
That is what I thought, but then what is 
scaffold.fa.fill ?

**Comment by kubu4** [comment]
That's the initial assembly using only the small insert libraries. You'll notice that there's a TON of missing sequence (i.e. NNNNNNN) in that FASTA file because it hadn't been combined with the large insert libraries (which hadn't been sequenced when they produced that initial assembly).
