### ISSUE TITLE
Lab supplies order

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#393]
Pipette tips
* 10µl Cat 24-401
* 200µl Cat 24-412

96 well Plate seals
Excel Science Alumaseal II 
Cat AF100

I also used up all the Zymo Methylation Gold kits, but not sure we need these until specifically wants them

**Comment by kubu4** [comment]
@sr320 which budget(s)?

**Comment by sr320** [comment]
62-9868

**Comment by kubu4** [comment]
Ordered different plate seals. See [purchasing log](https://docs.google.com/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8/edit#gid=0) for deets.
