### ISSUE TITLE
Run mixture model analyses on Geoduck CpG o/e values

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#395]
ie ![model](http://onlinelibrary.wiley.com/store/10.1111/mec.13414/asset/image_n/mec13414-fig-0001.png?v=1&t=iws3i8p7&s=cb891ac246069bb8778e47f1461b3b1d277474f6)

as described in
http://onlinelibrary.wiley.com/doi/10.1111/mec.13414/full

essentially want to test to see if there is a bimodal pattern

**Comment by seanb80** [comment]
http://rpubs.com/seanb80/235847

Mixture Model, plus histograms we talked about.
