### ISSUE TITLE
Program Hobos for Temp logging

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#398]
Set up the 4 loggers to record temperature (in a syncronized manner ie make sure clocks are synced)

Software:
existing license for HOBOware Pro Software. license to the README.md file in Eagle/Backup/Software/Mac

**Comment by kubu4** [comment]
License info is already in README.md file.

**Comment by seanb80** [comment]
4 loggers are currently set up to log temperature every 30 minutes, starting at 11:00:00 today. They are all synched to the system clock on my laptop, so that should result in logging at the same time.

**Comment by laurahspencer** [comment]
Thanks for programming! I will plan on taking the loggers out to Manchester on Thursday before I head out of town for the Holiday week. Where are they being stored in the lab?

**Comment by sr320** [comment]
I will take them out tomorrow...

**Comment by kubu4** [comment]
Even though @sr320 is taking them out tomorrow, you can find them in lab by looking at the [Roberts Lab Inventory](https://github.com/sr320/LabDocs/wiki/Lab-Inventory)

**Comment by laurahspencer** [comment]
Thanks @sr320 for taking the HOBOs out; if plans change and you need me to do it tomorrow I can in the morning.
