### ISSUE TITLE
Printer set-up?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#40]
Are there any instructions online on how to set-up the Brother Printer? 

I tried the IP method and only got blank pages..

**Comment by kubu4** [comment]
Ugh.  You might need the driver(s):

http://support.brother.com/g/b/downloadtop.aspx?c=us_ot&lang=en&prod=mfc7460dn_all

**Comment by sr320** [comment]
No luck - just blanks

Steven Roberts

**Comment by sr320** [comment]
Ok then went in and changed software selection and it worked!
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Printer_Software_and_Add__and_Printer_set-up__·_Issue__40_·_sr320_LabDocs_1A7AFD1A.png" alt="Printer_Software_and_Add__and_Printer_set-up__·_Issue__40_·_sr320_LabDocs_1A7AFD1A.png"/>

**Comment by laurahspencer** [comment]
Just used this to set up my computer on the printer. Very helpful.
