### ISSUE TITLE
ID best shelving system for -20

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#401]

**Comment by kubu4** [comment]
@grace-ac found these: https://www.amazon.com/gp/product/B014E30YX6/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=A31WC3UU6P8H6Z

Some drawers are good, but I think we also should get some steel box organizers. They make shorter versions that will fit in the -20C. Downside is that they are so friggin' expensive (~$75 - $125)...

**Comment by grace-ac** [comment]
These are about same size as drawers we already have if you don't like the idea of stacking the smaller ones in the link in above comment.

https://www.amazon.com/Sterilite-23018006-Quart-Stacking-Drawer/dp/B007UTRJ1M/ref=sr_1_1?s=home-garden&ie=UTF8&qid=1483480421&sr=1-1&keywords=sterilite+16+qt+stacking+drawer

**Comment by sr320** [comment]
Please post new issue to purchase t
Three of Sterlites, tagged purchasing.
