### ISSUE TITLE
New Monitor for Xserve

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#403]
Talked to Steven about ordering a new monitor for the Xserve setup. He OK'd it, and should follow with a budget number.

[Here](https://www.amazon.com/ViewSonic-VA2855SMH-1080p-Monitor-HDMI/dp/B00NM76PXY/ref=sr_1_21?s=pc&ie=UTF8&qid=1482858569&sr=1-21&keywords=monitor&refinements=p_n_size_browse-bin%3A3547807011) is a monitor that would work, but if we've ordered a different type or brand in the past that would work too!

**Comment by sr320** [comment]
Looks good to me.
61-0221
