### ISSUE TITLE
Rhonda's attempt at DDA analysis

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#405]
I successfully logged into Emu. Baby steps.

Is comet installed? This tells me otherwise...
![image](https://cloud.githubusercontent.com/assets/20071030/21527864/1d9f32aa-cce3-11e6-81fa-bfab464383f4.png)

I'm also trying to access my raw files from the owl server. I am not sure why, but I am unable to see them on my local computer. It's saying I have no shared folders now... And how would I access them from Emu?

**Comment by sr320** [comment]
Awesome! #winning 

Comet is installed.
see 
https://github.com/sr320/LabDocs/wiki/Lab-Software#computer-emu

**Comment by sr320** [comment]
re access owl via Emu - I will let @seanb80 provide the answer..


re access on your computer.. you would need to provide details on exactly what you are doing and the failure point, in a manner we could reproduce.

**Comment by kubu4** [comment]
A few things I noticed:

- Emu software location is not listed in $PATH (within srlab account). So, just typing something like "comet" will not work. @seanb80 , when you have a sec, could you please add ```/home/shared/``` to the system $PATH for srlab?

- Comet is a Windows executable (comet.exe). This won't run on Linux (even though there's a "linux.exe" program? Very weird...

**Comment by sr320** [comment]
Yes getting software in $PATH would be helpful..

@seanb80 has run Comet on Emu... see http://rpubs.com/seanb80/237863

**Comment by kubu4** [comment]
Ah! You have to run WINE (a Windows emulator). Maybe we should have a specific protocol written up on how to use Comet?

**Comment by Ellior2** [comment]
As far as accessing raw files from Owl...

After I login, I click on the folder like I have done everytime in the past and there is nothing to show.

![image](https://cloud.githubusercontent.com/assets/20071030/21528684/28931dce-cce9-11e6-8f8a-c1e1f6ffbde4.png)

**Comment by sr320** [comment]
@Ellior2 Thanks!
Ok I just went into owl and fixed it. Same thing happend to @seanb80.
Maybe related to the last update... but check now.. you should be able to see `web`.

**Comment by seanb80** [comment]
Mounting owl on Emu:

`sudo mount.cifs //owl.fish.washington.edu ~/local/directory/for/mounting -o user=username,nounix,sec=ntlmssp`

The local directory for mounting has to be created prior to trying to mount via 

`mkdir directoryname`

Comet is a linux native program, it's ReAdW that requires wine to run. 

I'll add /home/shared to the path, and update the Lab software wiki to include actual executable names, since they can be non-intuitive.

Let me know if you need any more help!

**Comment by seanb80** [comment]
Ok, Everything should be pathed properly. Also, I had to create a shell script for Abacus, since it's just a java runtime file as opposed to a straight executable. The syntax is as follows.

`abacus /path/to/your/params/file` and should work from anywhere, allowing Abacus to have 16g of ram, though this can be changed if we find it to be a limiting factor.

**Comment by kubu4** [comment]
Generally, you have to set up a "tunnel" into a remote computer, run Jupyter notebook on that remote computer, and then you can use Jupyter in your browser (and it will actually be running on the remote computer). See here for more info: https://github.com/sr320/LabDocs/blob/master/code/jupyter.md

You'll have to scroll down a bit (see Run IPython on a remote computer section).

**Comment by kubu4** [comment]
Quick rundown of steps would be:

1. Open two Terminal windows.
2. On one of the Terminal windows, SSH into your desired remote computer.
3. On the second Terminal window, use SSH to create a tunnel into the same remote computer.
4. On your first Terminal window, launch Jupyter notebook using the "--no-browser" argument.
5. Open a web browser on your computer and enter "localhost:8888" as the URL.

**Comment by kubu4** [comment]
Also to note when using Jupyter notebooks, you can close your browser and the commands

**Comment by kubu4** [comment]
Closed accidentally! Sorry!

**Comment by sr320** [comment]
@Ellior2 If it were me, I would just make sure I could get everything to run at the plain command-line before jumping into Jupyter via tunnel..

**Comment by Ellior2** [comment]
LOL definitely keep this one open. Might compete with the number of comments in my last issue!

I got it to work. I am using a jupyter notebook on Emu.

**Comment by sr320** [comment]
Great!  But thinking ahead to those future persons searching issues.. it
might be best to post issue on specific problem/issue that can be
addressed/closed. Opening new ones. ie

Problem accessing shared files on owl
How to run Jupyter on remote machine
What software is installed on machine?
Mounting owl via linux.

Note: most of these are not directly related to DDA analysis.
...

**Comment by kubu4** [comment]
Also, please be sure to describe how your problem was resolved...

So, on that note, how did you get Jupyter notebooks running with Emu?

**Comment by Ellior2** [comment]
@kubu4 Well I documented what I did in a markdown cell in Jupyter notebook on Emu, but I need to get that on GitHub. Hmmm... Here it is for now... 

To ssh into ipython notebook on Emu:

1) I opened a Git Bash terminal locally and entered 
`ssh -N -L localhost:8000:localhost:7000 srlab@128.95.149.195` to login into Emu linux machine

2) I was prompted for the password and entered it

3) Terminal is active but it won't return any command prompt. You have created a tunnel into Emu

To start ipython on Emu

4) Open a new Git Bash terminal, but keep the first one open.

5) Enter `ssh srlab@128.95.149.195`

6) Input password

7) Enter `ipython notebook --no-browser --port=7000`

Now you are remotely logged into Emu and have started ipython without the browser.

8) Open a browser locally and enter localhost:8000

9) This will open Jupyter in your browser on the Emu machine. It will prompt you for the token which you can find in the second Git Bash terminal you opened.

Thanks @sr320 I will start posting separate issues.

**Comment by kubu4** [comment]
Thanks! You probably could have just linked to that notebook, or said "I followed the instructions in the link Sam posted above". :)

**Comment by sr320** [comment]
and with that.... 📕
