### ISSUE TITLE
Supp files proteomics paper

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#406]
The new Readme file is up to date and matches order of references in paper.

Next:
- Make Table 2 from paper into a supp file (S8)
- Rename files according to readme text

And then hopefully we'll be all done with it!!

**Comment by grace-ac** [comment]
noooow it's up to date - forgot to do the pull request.

**Comment by sr320** [comment]
Table 2? can you add that here?

**Comment by grace-ac** [comment]
Emma says she wants it as a .csv

Table 2. GO biological processes enriched in proteins that were differentially abundant between stages within a sex (e.g. early- vs. mid-stage female) or between sexes within a stage (e.g LF vs. LM). Only the most specific GO terms in the GO hierarchy are listed. No terms are listed when a comparison was not made.

[S8_GOterms_table.xlsx](https://github.com/sr320/LabDocs/files/676314/S8_GOterms_table.xlsx)

**Comment by sr320** [comment]
I believed this has been fixed.
Please confirm: https://github.com/sr320/supp-geoduck-proteomics

**Comment by grace-ac** [comment]
okay, i fixed the readme one last time. you just have to change S5 and S6 names in the file list to match the readme and it will all be good!

my fault on not catching the mis-numbered S5 and S6.

**Comment by sr320** [comment]
think I got it?

**Comment by grace-ac** [comment]
yes!

**Comment by sr320** [comment]
🎆
