### ISSUE TITLE
Mounting Owl from Emu error 22

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#407]
@seanb80 I am having difficulty mounting Owl from Emu

![image](https://cloud.githubusercontent.com/assets/20071030/21533780/16490bd6-cd13-11e6-95fc-3df971b387d7.png)

What am I missing?

**Comment by seanb80** [comment]
Ah! When the permissions got changed, we may have only gotten permissions to access the /web directory. I just tried it and got the same error when using the //bare owl.fish.washington.edu, but it mounted when I used //owl.fish.washington.edu/web 

Let me know if that doesn't work.

**Comment by Ellior2** [comment]
That works, thank you

**Comment by kubu4** [comment]
Are you getting the same error message as when you originally opened this issue?

**Comment by Ellior2** [comment]
Hmmm.... 
![image](https://cloud.githubusercontent.com/assets/20071030/22661684/26853378-ec5b-11e6-92aa-db8b707bf5d9.png)

Well I thought I successfully mounted, but when I opened the directory I created for it, I don't see anything

**Comment by Ellior2** [comment]
Oops haha

![image](https://cloud.githubusercontent.com/assets/20071030/22661742/5e1572bc-ec5b-11e6-877a-a1e15af1b1a9.png)

**Comment by seanb80** [comment]
So I just hopped on Emu and used `the code below to successfully mount Owl.
Might try that?

   - sudo mount -t cifs -o username=USERNAME //owl.fish.washington.edu/web
   ~/Documents/owl/

**Comment by Ellior2** [comment]
My goal is to get a file off of Emu on my local computer. I thought maybe I could try these steps to copy a local file from Emu and put it on Owl. I'm trying to get my Abacus_output.tsv file.

**Comment by sr320** [comment]
Post a new issue with what you are trying to do- where the file is etc- and
someone will get it for you

**Comment by seanb80** [comment]
If you're just trying to copy a file from Emu to Owl, you can use scp via

`scp filename owlusername@owlIPaddress:/directory/you/want`

**Comment by Ellior2** [comment]
Thank you Sean!

**Comment by kubu4** [comment]
This issue was not resolved. Reopening.

**Comment by sr320** [comment]
Lets call it incorrectly unopened.. 

@Ellior2 no longer needs it resolved....
primary issue (getting file) solved be @seanb80 

with bonus https://github.com/sr320/LabDocs/issues/469#issuecomment-277782949
