### ISSUE TITLE
File conversion from .raw to .mzXML

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#408]
@seanb80 I am getting this error during the file conversion step.

[notebook](http://localhost:8000/notebooks/Documents/rhonda/000-Remotelogin_filechange.ipynb)

Sorry for the millions of questions, still a command-line newb.

**Comment by seanb80** [comment]
Your notebook link is to the localhost version, 
So I can't access it.

**Comment by sr320** [comment]
Note that notebook URL is just a local URL. No one else can see. Have to
post to Github and grab URL.

**Comment by Ellior2** [comment]
I was curious about that... How should I do that from Emu?

**Comment by sr320** [comment]
Well, simple workaround - export notebook to different format. Upload,
Or screen shot,
Or just include input code and error.

Maybe post new issue on how to use github on emu.

**Comment by Ellior2** [comment]
Ok for now here are some screenshots. Soon I'll work on using GitHub on Emu

Just so you can see that the file exists in my path...

![image](https://cloud.githubusercontent.com/assets/20071030/21534657/2ac5af86-cd1f-11e6-8e58-19fc2ea9a9e2.png)

Now to convert files...
![image](https://cloud.githubusercontent.com/assets/20071030/21534659/39e02bc2-cd1f-11e6-898e-1dd7c847c3f9.png)

**Comment by seanb80** [comment]
That is very strange. That's literally the file I worked on yesterday. 

Just got on the bus, let me get my computer out and I'll see if I can figure it out.

**Comment by sr320** [comment]
Tough one.
I think @seanb80 has run this file..
http://rpubs.com/seanb80/237863

My only guess is maybe a permissions issue. but @seanb80 should be able to tell you what the problem is.

**Comment by sr320** [comment]
Sample 

Not

sample

?

**Comment by sr320** [comment]
Always good to copy file name in error and then  ls :)

**Comment by sr320** [comment]
#offissue 
But those spaces in file names are killing me 👎

**Comment by seanb80** [comment]
So, this may be an odd interaction with trying to use an emulated application via path, but I get that error when I try to run ReAdW in any directory other than `/home/shared/ReAdW/`, but when I do run it in that directory, it works. It will take a little more experimentation to fix, but for now if you switch to `/home/shared/ReAdW` and run 

`WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe ~/Documents/ProteomicsTest/20161205_sample_1.raw ~/Documents/ProteomicsTest/20161205_sample_1.mzXML` 

for example, it should work. Or at least it did for me just now on Emu, logged in to the srlab account.

**Comment by Ellior2** [comment]
@sr320 Good catch. I did need to capitalize the S. This got me a little farther but it still didn't create the file.

![image](https://cloud.githubusercontent.com/assets/20071030/21534936/490dca7e-cd23-11e6-9e3d-fd30ad73e204.png)

![image](https://cloud.githubusercontent.com/assets/20071030/21534942/65969fb8-cd23-11e6-9544-7af029620fe5.png)

P.S. I did not name those files with spaces.

**Comment by seanb80** [comment]
Is the rhonda2016oyster your mounted copy of owl? 

If so, you might want to try saving the .mzXML file somewhere locally on Emu and working with it there. If nothing else, having the files local would speed up the process immensely.

**Comment by Ellior2** [comment]
Yes it is and here is a better image of the whole command. I'll try saving locally to Emu.

![image](https://cloud.githubusercontent.com/assets/20071030/21535057/d57e6d50-cd24-11e6-92e4-0b01c4f1e8e6.png)

**Comment by sr320** [comment]
Sounds like this issue is still open ? still cannot get to RAW converted?

**Comment by Ellior2** [comment]
I'm going to work on it after work today or in the next couple days. Keep you posted.

**Comment by Ellior2** [comment]
Ok I got it to work by saving locally to Emu! This is probably a no-brainer for you guys but I want to convert all of the files at once using this code and wildcards in my input file name:
`!WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe ~/Documents/rhonda2016oyster/trochophora/C_gigas_proteome2016/20161205_Sample_***.raw ~/Documents/rhonda/20161205_Sample_***.mzXML`

I also just tried: 
`!WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe ~/Documents/rhonda2016oyster/trochophora/C_gigas_proteome2016/*.raw ~/Documents/rhonda/*.mzXML`

but I get errors. How can I transfer the names from my input files to my output files but run everything at once?

**Comment by sr320** [comment]
Great question- I would use loops or xargs. Both are in textbook from class
. Not sure how these work on this platform - will defer to Sean for first
stab at this.

Also what are errors?

**Comment by seanb80** [comment]
Can you post your error messages?

I'm going to spitball here and try to answer the question anyway. But I think it's because wildcard don't work great for making output files. 

You're essentially saying "name my output file sample_everything.mzxml. It works for input files because you have a restricted space you're operating in, you're telling the program "put everything that matches .raw from this directory" in to readw. 

I use an R script where I pull all of the file names in a directory using list.files() and then build the output file names from that. I'm sure something similar is available for Python as well. 

If you need help setting up the script let me know.

**Comment by Ellior2** [comment]
If you open up this thread on your computer you should be able to see the screenshot I put into my earlier post. Here it is again and you can see my whole code in the cell. 
![image](https://cloud.githubusercontent.com/assets/20071030/21628957/b59b7844-d1d8-11e6-9e98-7d3025384845.png)

I looked into using the `find . -name ""20161205_Sample_***.raw"" | xargs ` command but I don't know how to insert the 
`!WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe` after it. All of the examples I see online and in my text just use really simple commands like rm. I can't have any backslashes in my unix filename which means I need to be in the working directory of the `home/shared/reAdW` to run the file conversion program. Hmmm...

![image](https://cloud.githubusercontent.com/assets/20071030/21630402/adc7d7ea-d1e5-11e6-9586-53544ebd5154.png)
![image](https://cloud.githubusercontent.com/assets/20071030/21630363/502c9120-d1e5-11e6-8172-2a0ae60ff291.png)
![image](https://cloud.githubusercontent.com/assets/20071030/21630498/922ce916-d1e6-11e6-9c56-2f661268282c.png)

**Comment by kubu4** [comment]
What error messages are you getting? :wink:

In the shell, I would do the following:
```
for file in ~/Documents/rhonda2016oyster/trochophora/C_gigas_proteome2016/20161205_Sample_*.raw
do
no_path=${file##*/}
no_ext=${no_path%.raw}
WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe "$file" ~/Documents/rhonda/"$no_ext".mzXML
done
```

**Comment by Ellior2** [comment]
YAY!! Thank you Sam!!

**Comment by kubu4** [comment]
Here's a small tidbit for future reference. When using the shell and wildcards (*), you only need a single wildcard character. The asterisk expands to match 0 or more instances of any characters. Using multiple asterisks in this situation has no effect.

---
Too-much-information-note: An asterisk in the shell behaves differently than when it is used in a regular expression! In the shell, the use of the asterisk in the "wildcard" fashion is called "globbing." 

In a regular expression, the asterisk matches 0 or more instances of the preceding character. It will not expand to match multiple characters, as it does when it is "globbed" in the shell. This is an instance when you might use multiple asterisks in succession when trying to match a pattern.

Finally, to add to the confusion, you can tell shell programs to utilize regular expressions, in which case, the asterisk would be interpreted in the regular expression and would not be "globbed" (i.e. expanded to match any/all characters).
