### ISSUE TITLE
Save Geoduck RRBS data to Owl

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#411]
The first lane of Geoduck RRBS data is ready for download.

Host name:         ftp2.genewiz.com
Port number:     22

Steven and I have username and password for download.

**Comment by kubu4** [comment]
Will initiate download and MD5 checksum verification shortly. Will post here when download and checksum verification is complete (as well as in my [notebook](http://onsnetwork.org/kubu4/)).

**Comment by kubu4** [comment]
Heads up, there will be a bit of a delay on this. No MD5 checksums provided by Genewiz. Have already sent them email requesting that checksums be provided.

**Comment by kubu4** [comment]
MD5s have been checked and look good:

[notebook entry](http://onsnetwork.org/kubu4/2016/12/30/data-management-geoduck-rrbs-data-integrity-verification/)
