### ISSUE TITLE
Power Outage at FTR

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#414]
Just wanted to give everyone a heads up that the power is currently out in FTR. I got ahold of the front office in FSH and they've gotten ahold of the Facilities people, but currently it is a mystery as to whats going on. 

I'll keep an eye on the -80s if this ends up being a longer term thing. On a lighter note, those new UPS batteries seem to be working!

**Comment by sr320** [comment]
Thanks- do keep us posted- I am out at Manchester today

**Comment by seanb80** [comment]
Looks like the power is back! Hopefully it's just a hiccup.
