### ISSUE TITLE
Purchase Request: PTRC for DNR samples on Mass Spec

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#417]
@yaaminiv & I need Peptide Retention Time Calibration Mixture to add to our samples slotted to go on the Mass Spec starting 1/17.  @kubu4 could you please order #88320 from https://www.thermofisher.com/order/catalog/product/88320, which is 50µL of a 0.5pmol/µL mixture (need 375 fmol/sample).

**Comment by sr320** [comment]
Budget 63-4279

**Comment by kubu4** [comment]
This came in today. Bottom shelf of -80C:

![img_20170111_135852](https://cloud.githubusercontent.com/assets/4514104/21868248/cd781966-d806-11e6-90a0-94067bccaf14.jpg)
