### ISSUE TITLE
Abacus ram limits

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#419]
I made an [Abacus parameters file](https://raw.githubusercontent.com/Ellior2/Fish-546-Bioinformatics/master/analyses/DDA_2016/Abacus_parameters.txt) and ran the last step in @seanb80 's [workflow](http://rpubs.com/seanb80/237863) and it seemed to time out (hasn't made any progress in a couple hours). 
![image](https://cloud.githubusercontent.com/assets/20071030/21753035/547c8792-d598-11e6-8440-7796fc3a04f2.png)

I'm wondering if Sean's comment earlier is why..?
![image](https://cloud.githubusercontent.com/assets/20071030/21753026/24e44a88-d598-11e6-846d-b0c8a0dae26d.png)

**Comment by sr320** [comment]
Can you run the command `top` on emu to see if it is still "running"?

**Comment by sr320** [comment]
Actually I think the power is out on campus now...

**Comment by Ellior2** [comment]
Yeah I am having trouble logging in, even after a reboot
![image](https://cloud.githubusercontent.com/assets/20071030/21753188/367337e2-d59c-11e6-94c9-a2b9a4e9457a.png)

**Comment by seanb80** [comment]
Emu is back up now.
