### ISSUE TITLE
What is Emu doing?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#422]
What is the simplest way for one to remotely determine what Emu is doing. ie What processes are using RAM/CPU, user etc?

**Comment by seanb80** [comment]
from the command line typing `htop` opens up a process list and memory and CPU usage.

**Comment by seanb80** [comment]
![16bsmapinstances](https://cloud.githubusercontent.com/assets/10619258/21788208/2f96fd8c-d682-11e6-9937-599484a49416.png)
This is an example of the output of `htop`
