### ISSUE TITLE
Proteomics Submission

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#425]
Link for making JPR submission account: https://acs.manuscriptcentral.com/acs

Person who submits has to either be corresponding author, OR a non-author submitting on behalf of others.

@sr320 is corresponding author. Emma says " I am also happy to be corresponding author for the purpose of manuscript submission, even though he will be on the manuscript itself. Whatever he wants to do!"

Link to FINAL PAPER VERSION: https://drive.google.com/open?id=0B_Kednl1tNImQ0RhTmhnYlBMM3c

**Comment by grace-ac** [comment]
Link to cover letter: https://drive.google.com/open?id=0B_Kednl1tNImaXFTelNrZWV2b2M
COVER LETTER NEEDS: Check on highlighted information for accuracy @sr320

**Comment by sr320** [comment]
Cover letter looks good- I am fine with Emma submitting

**Comment by grace-ac** [comment]
Great! Just sent everything to Emma!
