### ISSUE TITLE
Ship Oly Samples to Katherine

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#426]
wondering if you could ship the adult oly tissue samples from the OA experiment this week or next? As long as you send it out overnight on a Mon-Tues-Wed it should be fine. Just send me a tracking number. Thanks!

Shipping Address:

Cathy Pfister
Zoology 401A
1101 E. 57th St.
Chicago, IL 60637

@sr320 has billing info

**Comment by grace-ac** [comment]
@kubu4 Hey Sam! What do you suggest we do?

There are 8 boxes of samples (those square plastic boxes) that are in -80 and there are 2 boxes of samples that are in ethanol in the fridge.

**Comment by kubu4** [comment]
Ship frozen samples on dry ice. Ship samples in EtOH at RT. EtOH samples will require special packaging and labeling that I have to sign off on.

**Comment by grace-ac** [comment]
Sweet! Okay, thanks!

And I can just fit them into a styrofoam box, yes? Where do I get dry ice? Do I then have to take it to the main office? I've never shipped anything from here before - will probably have a lot of questions for you...

**Comment by sr320** [comment]
Once you get it figured out - maybe create a page on Github with the
procedure- presuming it is not already there.

**Comment by grace-ac** [comment]
@kubu4 I have to leave today at 2 for doctor appointments, but I can come by tomorrow early afternoon to do this if you're around to direct me!

**Comment by kubu4** [comment]
Tomorrow will work for me.
