### ISSUE TITLE
Help Axios test System with Proteomics paper

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#427]
@grace-ac Can you try to submit http://biorxiv.org/content/early/2016/12/28/094615
to Axios through bioRxiv? 

They will not review but just need some to try to test the system.

In theory you do it here.
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Author_Area_1E2729E9.png" alt="Author_Area_1E2729E9.png"/>

**Comment by grace-ac** [comment]
yes! it seems easy! 

I should upload the final version of the paper to biorxiv before doing that?

**Comment by sr320** [comment]
No - just go ahead and do it - it is just a test, they are not reviewing -
post some screen shots here if it works
Thanks

**Comment by grace-ac** [comment]
It worked!
I just selected Axios Review from a drop-down menu. Then was asked if I was sure of the action, and then it was done! 
![screen shot 2017-01-13 at 10 37 09 am](https://cloud.githubusercontent.com/assets/14934314/21941216/8fbdfe70-d97c-11e6-9850-b242659b0032.png)

**Comment by sr320** [comment]
Before you clicked did your screen look just like mine above (with 0 in Submit link etc)?

Can you go back to that screen and take a shot?

**Comment by grace-ac** [comment]
![screen shot 2017-01-13 at 12 34 22 pm](https://cloud.githubusercontent.com/assets/14934314/21944761/b17d3a20-d98c-11e6-9114-d09d9e4d9d69.png)

**Comment by grace-ac** [comment]
That's what it looked like ^
Then I just clicked on the "Submit bioRxiv Preprint to a Journal...." where it brought me to a drop-down menu with a list of the journals/review services that you can submit to directly from bioRxiv
