### ISSUE TITLE
Next steps in DDA analyses

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#429]
@emmats I have my Abacus_output.tsv file. Hooray!

Now I look for differentially abundant proteins using QSpec?

**Comment by emmats** [comment]
Yes, you can put your data into qspec. Make sure you use spectral counts and not NSAF! Also, make sure you don't have any spaces in your file name. Qspec is really picky.
This is also when you can start looking at the bigger trends in your data by doing NMDS and things like that.
