### ISSUE TITLE
Problems with Owl?

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#430]
I think I'm running into the same problem @Ellior2 referenced here: https://github.com/sr320/LabDocs/issues/405

I need to access her trochophora folder in Owl, but when I log in I can't see the web folder. Any tips?

![screen shot 2017-01-15 at 11 30 04 am](https://cloud.githubusercontent.com/assets/22335838/21968125/29c12a7c-db46-11e6-99e0-c66b5327e57c.png)

**Comment by kubu4** [comment]
You can access @Ellior2 folder from here: http://owl.fish.washington.edu/trochophora/

However, that doesn't resolve the issue about no "web" folder access. I'll work on that and post an update here when it's fixed.

**Comment by yaaminiv** [comment]
thanks @kubu4!

**Comment by kubu4** [comment]
For posterity, the issue about no ```web``` folder access was resolved in Issue #435 .
