### ISSUE TITLE
RE Proteomics MSMS sample collection and storage

### ISSUE THREAD

**Issue by hputnam** [sr320/LabDocs#432]
Is there a recommended sampling and storage portion for this protocol?
https://github.com/sr320/LabDocs/blob/82c0f06869baa574a85479f24b7421aa1b76d5ca/protocols/ProteinprepforMSMS.md

I am interested in the potential to store coral samples from remote locations in RNAlater.
E.g., http://onlinelibrary.wiley.com.offcampus.lib.washington.edu/doi/10.1002/pmic.201100328/full

@emmats do you have concerns about RNAlater?

**Comment by emmats** [comment]
I'm glad you found that article! I had read that RNAlater works for microbes, but I was curious about multicellular organisms. It sounds like RNAlater may even be a better choice than snap freezing, although I would want to look at the methods of some of the other papers more closely.

I'm curious about the temperature at which the samples were stored after being preserved in RNAlater. They don't specify in this article, but I am going to check out the other ones. 

I would also like to use a better MS technology to assess protein identifications. We are able to identify thousands of proteins with the machines we use, so I'd like to make sure the robustness of identification holds up with both preservation methods.  This may be a good thing to discuss with Brook and @sr320 to see if we can do a simple experiment with different tissue preservation methods and make sure our pipeline yields the results we expect if we use RNAlater.

**Comment by emmats** [comment]
I did a bit of poking around and I found this article especially convincing: http://www.sciencedirect.com/science/article/pii/S2212968515300222

Note that in most of the RNAlater protocols, after letting the tissue stew in the RNAlater for 24 hours they are stored at -80C. Sometimes -20C. I'm guessing that would be difficult in a field situation as well.

**Comment by hputnam** [comment]
Thanks @emmats This is actually feasible in Moorea and what I had them do for the last samples collected (https://hputnam.github.io/Putnam_Lab_Notebook/Sample_Collection_RNALater/). They were then transported on dry ice, so in theory should be good samples for proteomics. I will likely not be able to get samples for snap frozen RNALater comparison until April when I travel with a dry shipper, but would be super interested in collaborating on a comparison!

**Comment by emmats** [comment]
The comparison would probably be easier to do with relatively unimportant tissue in the lab, but I will definitely keep you in the loop. Based on that paper I found, though, it does seem that RNAlater preservation still allows for the same number of protein IDs as snap freezing, even with a high mass accuracy instrument that will be detecting proteins across the abundance spectrum. Given those findings, I'm not sure if it is even necessary to investigate this further, but I will see how the PIs feel.

**Comment by hputnam** [comment]
Sounds good, Thanks!
