### ISSUE TITLE
viewing pep and prot.xml files

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#434]
Can someone please move one of Rhonda's pep.xml files to Owl just so I can try to open it in a web browser? Thanks @yaaminiv @kubu4

**Comment by yaaminiv** [comment]
@kubu4 just tried uploading a file to Owl but I get the following error

![screen shot 2017-01-17 at 3 13 56 pm](https://cloud.githubusercontent.com/assets/22335838/22044077/a2981e74-dcc7-11e6-8bd3-b5c86dc368ac.png)


Could I please have the proper privileges 😄

**Comment by kubu4** [comment]
@yaaminiv - Which folder are you trying to upload to? You should be trying to upload to your folder, as that's the only folder you have permission to work in.

**Comment by kubu4** [comment]
As a reminder, per Issue #289, your folder is "spartina".

**Comment by yaaminiv** [comment]
Just tried "spartina" and got the same error message

![screen shot 2017-01-17 at 3 19 50 pm](https://cloud.githubusercontent.com/assets/22335838/22044232/71a6bffe-dcc8-11e6-87c6-2fca63daf351.png)

**Comment by yaaminiv** [comment]
@emmats Just uploaded a pep.xml file into the spartina folder
