### ISSUE TITLE
Owl permissions issue - unable to write to user folder

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#435]
@yaaminiv cannot write to her spartina folder, as demo'd in Issue #434 .

@yaaminiv , can you please post the user name you're using to log in to Owl?

**Comment by yaaminiv** [comment]
My username is "yaaminiv"

**Comment by kubu4** [comment]
OK, this is fixed. Sorry for the hassle and confusion! Please log out of Owl and log back in to make sure the changes take effect on your end.

**Comment by kubu4** [comment]
Putting this here for posterity.

Had previously (all in the Synology web interface):
- created user group "srlab" for all lab members to be part of
- set permissions for srlab group to read access only for the ```web``` directory and all subdirectories
- set individual users as owners for their specific web folder (e.g. Yaamini was the owner of the ```spartina``` folder)

For some reason, the group permissions (read only) took priority over owner and prevented anyone in the srlab group from writing to folders, even if they were the owners of said folder.

To resolve the issue:
- changed srlab group permissions for the ```web``` folder to read/write.

However, this means everyone can currently write to any web folder...
