### ISSUE TITLE
reading pep.xml files in Emu

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#436]
@emmats contacted a collaborator down at UWPR to help me view and manipulate my pep.xml files in Emu itself. I've taken screenshots of his advice, but it's way over my head and I can use some assistance. Any thoughts @kubu4 or @seanb80?

![screen shot 2017-01-17 at 3 29 01 pm](https://cloud.githubusercontent.com/assets/22335838/22044562/332cb4a2-dcca-11e6-9c6f-34aea49ab462.png)

![screen shot 2017-01-17 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/22335838/22044560/33294ba0-dcca-11e6-900e-56e241e3f4b9.png)

![screen shot 2017-01-17 at 3 29 18 pm](https://cloud.githubusercontent.com/assets/22335838/22044561/332b16ec-dcca-11e6-83ba-0b5893fd84eb.png)

**Comment by kubu4** [comment]
@seanb80, could possibly use one of those old computers to install/run LAMP (I think you already converted one to Ubuntu) to function as an Apache web server that we can mess with without occupying Emu resources?

**Comment by yaaminiv** [comment]
I reread some of the instructions and it seems like I should be able to run a script created by the collaborator to convert my pep.xml files to .txt files and then read them open them in R/excel...I'm going to try playing around with that when I'm out of class and will keep you updated

**Comment by kubu4** [comment]
Note: Unless you're physically sitting at Emu, you won't be able to open the files with a spreadsheet program (Linux would use LibreCalc instead of Excel).

**Comment by seanb80** [comment]
Sorry it took so long to get back. 

TPP is installed and currently running on Emu, so it can be accessed using Emu's IP of 128.95.149.195.

It shouldn't be terribly resource intensive, but I can set something up tomorrow on one of those two old boxes if need be.

**Comment by yaaminiv** [comment]
@kubu4 I'm assuming I can scp to my local machine though?

And just to clarify: the script should solve my immediate problem of needing to view, interpret and manipulate the pep.xml files. Everything else pertains to being able to view pep.xml and prot.xml files in an interactive manner similar to what Emma uses.

For now, I'm just going to try and convert files so I can use them and worry about interactively viewing the files later....?

**Comment by kubu4** [comment]
Yes, you can always scp files from Emu to your own computer.

> And just to clarify: the script should solve my immediate problem of needing to view, interpret and manipulate the pep.xml files.

Admittedly, this is a little vague. You can view, interpret, and manipulate a XML file at any time. Try it out. Use the ```head``` command to view the first 10 lines of the XML file. It's just a text file with a different format than you're used to seeing. Since I don't really know what you want to do with the data in that file, it's hard to answer the question.

But, with all of that said, a tab-delimited file will be easier to view and manipulate (although, I'm sure R has some packages for importing XML files...), since it will be stripped of the XML formatting stuff.

**Comment by yaaminiv** [comment]
Sorry for the vague explanation! I'm trying to figure it out in my head as well. Basically, I want to take the information in the files and make a histogram with them, and I figured the easiest way to do this was to manipulate the data in R.

I'm having some trouble using scp to copy the pepxml2txt script from my computer to emu. I used the following code:

`scp /Users/yaaminivenkataraman/Downloads/pepxml2txt srlab@128.95.149.195:/home/srlab/Documents/rhonda/`

And got the following error:

`/Users/yaaminivenkataraman/Downloads/pepxml2txt: No such file or directory`

The file is in my Downloads folder and this is the path to the file that terminal gave me, so I'm stumped.

**Comment by emmats** [comment]
there is no extension on the file? An easy way to check your directory path is to use tab to autocomplete the file name to make sure you are pointing to the right thing.

**Comment by kubu4** [comment]
Please post the above  problems about copying files in Issue #431 and reopen Issue #431.

**Comment by kubu4** [comment]
As far as using R to make some histograms, you should be able to do this on your own computer. You already have the file(s) on your computer that you want to convert with the ```pepxm2txt```. Follow the instructions provided in that email, but don't SSH; you don't need to since you've already copied the XML file to your own computer. 

It may be easier for me to help in person. Let me know if/when you're available and I can come down.

**Comment by yaaminiv** [comment]
@kubu4 Just tried that and it didn't seem to work

![untitled](https://cloud.githubusercontent.com/assets/22335838/22074269/a53044fa-dd5c-11e6-9d5b-661873ab6f30.png)


I'll be in the office in about 15/20 minutes.

**Comment by seanb80** [comment]
We may be able to get around the whole pepxml2txt problem by using the TPP install in Emu.

to use the Pep XML viewer the fellow from UWPR mentioned you can go to 

`http://http://128.95.149.195/tpp/cgi-bin/PepXMLViewer.cgi`

which should render a webpage that looks like

<img width="1294" alt="screen shot 2017-01-18 at 9 24 03 am" src="https://cloud.githubusercontent.com/assets/10619258/22075202/e7590206-dd5f-11e6-96e3-5add410286e3.png">

You'll type in the absolute (full) path to the file, for example

`/home/srlab/Documents/rhonda/interact-20161205_sample_8A.pep.xml`

which gives you

<img width="1211" alt="screen shot 2017-01-18 at 9 27 36 am" src="https://cloud.githubusercontent.com/assets/10619258/22075308/65b21c78-dd60-11e6-9fe5-edce8e5f72d5.png">

Is this what you're wanting?

**Comment by yaaminiv** [comment]
@seanb80 yes! would I have to be physically sitting at emu to do this?

**Comment by seanb80** [comment]
Nope, just type that Url in to your web browser and it should work. Those screenshots are from my laptop, not Emu.

Also, fixed the URL! Didn't need two http://s

**Comment by yaaminiv** [comment]
it works! thank you for all of the help @kubu4 and @seanb80 and sorry about all of the confusion!
