### ISSUE TITLE
NanoPure broken

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#437]
Error Code 4: Requires calibration using NIST calibration module

Calibration module ([E896X5](https://www.fishersci.com/shop/products/barnstead-nanopure-accessories-consumables/0903516?searchHijack=true&searchTerm=0903516&searchType=RAPID) is ~$230.

**Comment by sr320** [comment]
Please purchase on 61-0221

**Comment by kubu4** [comment]
Purchased. 

Lead time is ~ 40 days.
