### ISSUE TITLE
exporting files from TPP viewer

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#438]
New problem: I'm able to view the spreadsheet and add an m/z column, but I can't export the spreadsheet (see https://github.com/sr320/LabDocs/issues/436)

I tried exporting the file as a spreadsheet and got this error

![screen shot 2017-01-18 at 9 43 41 am](https://cloud.githubusercontent.com/assets/22335838/22075882/a2f99820-dd62-11e6-9840-ca1e37f92261.png)

Tried `ssh` into emu to see if I could find the file, but it isn't there

![untitled](https://cloud.githubusercontent.com/assets/22335838/22075931/caac98cc-dd62-11e6-89dc-a6a2f051200d.png)

Could this be solved by physically sitting at emu, exporting the spreadsheets and using `scp` to transfer the files to my machine?

**Comment by seanb80** [comment]
Let me check, I'll get back with you in a moment.

**Comment by kubu4** [comment]
This is likely a problem we won't be able to solve. It seems like once the "Export Spreadsheet" button is pressed (it's in the "Other Actions" tab), you can't even use the "Update Page" button any more, as pressing that button also generates the same error message...

**Comment by seanb80** [comment]
Don't have a fix, but do have a workaround from the command line

`/usr/tpp_install/tpp/cgi-bin/PepXMLViewer.cgi -B exportSpreadsheet 1 -I path/to/your/xml/file` will output the .xls. 

The xls looks like: 

![xls](https://cloud.githubusercontent.com/assets/10619258/22076939/08b53abc-dd67-11e6-8f65-ebaa17821323.png)

**Comment by seanb80** [comment]
Oops! To clarify more. That would be in a terminal window connected via ssh to Emu.

**Comment by yaaminiv** [comment]
Hmm...is there a way to also add the m/z column before exporting?

**Comment by seanb80** [comment]
`/usr/tpp_install/tpp/cgi-bin/PepXMLViewer.cgi -C Pprobability,Gspectrum,Sexpect,Gions,Gpeptide,GMZratio,Gcalc_neutral_pep_mass,Gprotein -B exportSpreadsheet 1 -I /path/to/xml/file/

Note: The Protein column may extend multiple columns over if there are multiple options there, so the spreadsheet won't be nice and square. If you like, you can drop the Gprotein from the -C argument list and it won't output that.

**Comment by yaaminiv** [comment]
🎉 thanks @seanb80!

![untitled](https://cloud.githubusercontent.com/assets/22335838/22079148/a09312ac-dd6f-11e6-98e3-b68cc336a1a3.png)

**Comment by yaaminiv** [comment]
To recap for posterity:

If you have `pep.xml` files on Emu and need to export the spreadsheet as an `.xls` through TPP viewer, use the following code

`/usr/tpp_install/tpp/cgi-bin/PepXMLViewer.cgi -C Pprobability,Gspectrum,Sexpect,Gions,Gpeptide,GMZratio,Gcalc_neutral_pep_mass,Gprotein -B exportSpreadsheet 1 -I /path/to/pep.xml/file`
