### ISSUE TITLE
Preparation for 1/25 Manchester sampling

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#439]
We're planning on sampling 20-30 *C. gigas* specimens on Wednesday at Manchester! From my understanding, we'll need the following:

1. Prelabelled screwcap tubes for each tissue sample. We want gill, mantle and muscle samples from each oyster.
2. Equipment to shuck/extract samples
3. Ethanol and dry ice

Since you've done this before I hope you know what I'm referring to! If not, let me know (or ask @laurahspencer since she knows a lot more than I do). If you can have everything collected by Tuesday so we can look it over before we head out, that would be awesome!

**Comment by grace-ac** [comment]
Awesome! Do you have an idea of how many C. gigas will be sampled? @yaaminiv

**Comment by yaaminiv** [comment]
@grace-ac My bad for not making it clear: 20-30!

**Comment by grace-ac** [comment]
Oh! for some reason i took that to be 20-30 ˚C... makes sense now!! thanks

**Comment by grace-ac** [comment]
@yaaminiv @laurahspencer do you want collection tubes with ethanol like previous sample days? and/or some ethanol in supply box? 

last time it was ctenidia (gill) in ethanol in addition to just the ctenidia tissue samples.

**Comment by grace-ac** [comment]
@sr320 what would you suggest? collection tubes containing ethanol similar to what was done for katherine's project?

**Comment by sr320** [comment]
Yes - tubes with ethanol - thanks!

**Comment by grace-ac** [comment]
should getting dry ice wait until tomorrow morning before you all leave? if yes, i think @kubu4 will have to be the one to get it... everything else is ready for the collection day in a box in FTR 213

**Comment by yaaminiv** [comment]
@grace-ac what Laura and I did in the past was get dry ice and then store it in a cooler in the -80ºC until we needed it. If you could do that, that would be great! If not, we can get it tomorrow.

**Comment by sr320** [comment]
I think it would be fine to get today and store in -80....

**Comment by grace-ac** [comment]
dry ice is in blue cooler in -80 room. rest of supplies in cardboard box in FTR 213 with a list of supply box contents on top.
