### ISSUE TITLE
2015 larval samples in Washington?

### ISSUE THREAD

**Issue by ksil91** [sr320/LabDocs#442]
I was organizing my samples and noticed a set of larvae samples from 07-2015 that are missing. I took some to Washington this summer in case I had time to make libraries with them, so it's possible I left them in the UW lab. Looking at the handy pics [here](https://drive.google.com/drive/u/1/folders/0B_Kednl1tNImZENNWklNVExocHM), I'm particularly interested in the "Redos" Silliman box. Can you let me know if it is still there, and possibly snap me a top down pic of the tubes in it? 

Not super high priority, would just like to make sure I know where things are.

**Comment by grace-ac** [comment]
Contents of "Redos" Silliman box

![img_1572](https://cloud.githubusercontent.com/assets/14934314/22269315/b9c9e3ac-e23f-11e6-88c9-9d5fe81c0a6e.JPG)
![img_1571](https://cloud.githubusercontent.com/assets/14934314/22269316/b9d3ea28-e23f-11e6-9dad-d78ca456bebf.JPG)

**Comment by grace-ac** [comment]
All boxes in those pictures are still in the -20 by the way, @ksil91 !

**Comment by ksil91** [comment]
Nope, those are newly settled spat from the end of the 2015 experiment and not crucially important. Thanks!
