### ISSUE TITLE
Tissue Fixing/histology kits for oysters

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#443]

**Comment by sr320** [comment]
We need to have these ordered (or confirmed we have supplies in the lab) ASAP for sampling Oly and Gigas at Manchester before Feb 8

**Comment by grace-ac** [comment]
locate/purchase. I'll look around today to see if I can find any leftover from my capstone!!

**Comment by grace-ac** [comment]
I found:
6 50ml Tissue FIX containers
 - Each container can fit 4 histology cassettes
6 Tissue Stabilizer bottles
 - Add ethanol to get final volume of 500ml 

Not sure how many samples will be taken.

**Comment by laurahspencer** [comment]
Thanks Grace!  Do you know how many different samples 1 cassette can hold?  I want to sample between 20-30 animals, and hoping to do so this Saturday the 4th.

**Comment by grace-ac** [comment]
@laurahspencer it depends on how large the samples are, but each cassette is separated into four quadrants (see pic). So, you could potentially do four small tissue pieces. However, since I believe these will be made into histology, you'll want to make sure you can tell the individuals apart. Unless you're sampling different types of tissue from one individual, then it should be no problem.  
![img_1602](https://cloud.githubusercontent.com/assets/14934314/22435459/f6e38b78-e6d4-11e6-8587-1ccb7865b1e0.JPG)

Since I was sampling geoduck gonad, I took larger samples and used one cassette per sample. The largest tissue size a cassette can hold is 4x15x15mm.

**Comment by laurahspencer** [comment]
Grace - I see you're coming in today.  Do you have a few minutes sometime between 10:30-12:30 to discuss the use of these kits?

**Comment by grace-ac** [comment]
Definitely! @laurahspencer
