### ISSUE TITLE
Clear, defined plan for OA experiment 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#445]
By Feb 2 - we need a simple plan for what I will be asking PSRF to do from Feb 8 - ?? End of OA treatment...

**Comment by laurahspencer** [comment]
@yaaminiv & @sr320 here are my thoughts on the Manchester setup; what am I missing?

**OA System Needs **Now** 1/29/2017** 
 * Water pumps re-installed on OA system and tested  
 * Run bleach water through system to clean out all pipes  
 * 2 algae dosing pumps installed & tested
 * Hose connectors replaced with valves (for culture tank connections), so we can turn off/on while cleaning, etc.  
 * Likely: One more hole punched into treatment pipes for another culture tank connection (with valve). There are currently 3 per side; I expect we’ll need at least 4 per side (Laura needs 1-3/side, Yaamini needs [_how many?_])  
 * Confirm enough sock filters for the system; we need 3-6 each of 10um and 5 um; I expect they’ll need to be changed every ~1-2 weeks (cleaned more frequently), depending on the flow rate.  
 * Close the holes that were punched in the culture tanks.  
 * Test the mixing valve; we’ll need to slowly increase temperature in all tanks for spawning, so best to test that now 
 * I expect we will not aerate the tanks, as this would likely mess up the chemistry. But, will the animas be okay w/o aeration; will high flow rate suffice?  
 * Perhaps order/install flow meters:  
    * King Instrument Company, P/N 75302125C06: $148 per flow meter, not including shipping (from [Instrumart.com](https://www.instrumart.com/products/10153/king-instrument-7520-7530-series-rotameter)); would need at least 4; could possibly size down?:  
![flow meter](https://github.com/laurahspencer/LabNotebook/blob/master/images/Snip20170129_7.png?raw=true)  

**OA System Needs, during trial:** 
  * Clean oysters & tanks 1x/week 
 * Feed daily & clean algae header tank as needed 
 * Spray down sock filters, every other day-ish 
 * Replace filters, 1x/week 
 * Keep record of weird occurrences
 * Take water chemistry samples 2x/week 
    * 1L  grab samples, measure T, S & pH (mV) with handheld probes  
    * Discrete water samples dosed with HgCl, 2 per treatment & culture tank (12 total)  

**I propose that we spend 1 day/week (Wed, Sat or Sun) @ Manchester cleaning tanks, checking the system, taking samples, scoping it out.  That leaves daily feeding/cleaning maintenance to PSRF, and water chemistry samples 1x/week.**

Question: As suggested, on the 2nd day of treatment we could sample chemistry every hour to assess diurnal variation. A major caveat is that we are not allowed to stay overnight using HgCl w/o a NOAA employee present (we ran into this issue last year).  Would it be worthwhile to use the hand-held probes for the 24hr period, or can we instead review the Durafet continuous data to see if we need to vary our discrete sampling time?

**Comment by yaaminiv** [comment]
I'm still working out the kinks in my project so I'll update the numbers soon. Seems like everything we thought about at Manchester is on this list.

**Comment by sr320** [comment]
To clarify / simplify what I will ask PSRF to do for the OA experiment..

Feed daily & clean algae header tank as needed
Replace filters as needed. 
Keep record of weird occurrences
Take water chemistry samples 1x/week (Pick Day)
     1L grab samples, measure T, S & pH (mV) with handheld probes (each tank)
     Discrete water samples dosed with HgCl, (2 per tank)

--

**Comment by yaaminiv** [comment]
Update: I'll have at least four tanks, maybe six if the gigas are too big. So more holes punched into treatment pipes.

**Comment by laurahspencer** [comment]
**This is what I think we need to talk to PSRF about tomorrow:**  

_System Setup_
  * We plan to sample oysters on Saturday, arriving ~9:30am; will we have access to the hatchery & Rick's building (to get to -80?)  
  * Need pumps installed prior to Saturday, so we can fire up the OA system for testing
  * We would like another hole punched on each culture tank pipe (there are 3 now, need 4); can they add these for us?  
  * We would like to install flowmeters on each culture tank connection. We've ordered one of the King flowmeters that ya'll use on the larval tanks to test it out; will these work on this system?  
  * We will need 5 x 10um and 5um filters each.  Do we have these?
  * We understand there are 2 algae dosing pumps to use.  

_System Maintenance_
  * Feed daily & clean algae header tank as needed  
  * Clean filters as needed.  
  * Keep record of weird occurrences  
  * Take water chemistry samples 1x/week (Pick Day)  
    * 1L grab samples, measure T, S & pH (mV) with handheld probes (each tank)  
    * Discrete water samples dosed with HgCl, (2 per tank)

**Comment by laurahspencer** [comment]
Update: due to the HgCl use we cannot sample on the weekends, since no NOAA staff is consistently going to be on site. Instead, we will do water chemistry sampling every Wednesday. 

Spoke with Ryan yesterday; PSRF will do a weekly water chem. sampling either on Monday or Friday, depending on their schedule/capacity.  We need to provide them with data sheets, and should pre-label some bottles.
