### ISSUE TITLE
Box of PAXgene Tissue FIX Containers (50ml)

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#449]
Steven needs to "ok" pricing. 

![img_1574 2](https://cloud.githubusercontent.com/assets/14934314/22384223/3dde0aee-e482-11e6-9ac3-9b38e58c7bc4.JPG)

**Comment by sr320** [comment]
@grace-ac what is the price? (such tat I can approve)

**Comment by grace-ac** [comment]
$298.68 for a box

**Comment by sr320** [comment]
Please order two boxes 
on 
62-9868
