### ISSUE TITLE
Nightingales geoduck data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#451]
Correct ID for geoduck libraries on nightingales
https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0

also include info onto what differently libraries are - likely a single URL

**Comment by seanb80** [comment]
I'm not 100% sure what we should use for library IDs for these samples. Do we want to use a combination of title and Index number from https://hputnam.github.io/Putnam_Lab_Notebook/Geoduck-RRBS-Library-Prep-part-3/ or some other system?

**Comment by kubu4** [comment]
I believe a "lane" (as indicated on Hollie's page you linked) constitutes a library in this instance.

**Comment by kubu4** [comment]
Actually, ignore me. Wait for response from @sr320. Sorry for the clutter!

**Comment by kubu4** [comment]
Defining what a "library" is will/should impact Library ID numbering for past and future samples. 

I guess, technically, a library is an individual sample that gets a unique seqencing barcode. If that's the definition we use, then we need to update Nightingales to reflect unique Library IDs for individuals that were sequenced.

For example, in the Next Gen Library Database, I made Library IDs for each pool Katherine had sequenced:

![next_gen_seq_library_database_-_google_sheets](https://cloud.githubusercontent.com/assets/4514104/22438919/90e305ac-e6e2-11e6-9df8-0f72be1a206c.png)


However, in Nightingales, those different pools all have the same Library ID:

![nightingales_-_google_sheets](https://cloud.githubusercontent.com/assets/4514104/22438943/a3bc2f0a-e6e2-11e6-9d10-d2517ed3d78b.png)


Even my initial Library ID assignment would be incorrect if we categorize each individual sample with a unique sequencing barcode as a library.

**Comment by kubu4** [comment]
After speaking with @sr320, each entry on Nightingales (i.e. each row) should have a unique Library ID. Primary reasoning is that if a library is resequenced, it will get its own row with links to the corresponding sequencing file(s). 

However, it will have the same library name, since the source library that was sequenced will be the same. This allows us to distinguish between sequencing runs, but also identify all data files associated with a given library.

**Comment by seanb80** [comment]
Updated the Nightingales spreadsheet with the correct Library Names and links to the sample prep URL and experiment repo URL.

![screenshot_2017-02-02_08-54-58](https://cloud.githubusercontent.com/assets/10619258/22559279/78c21586-e925-11e6-8c39-0f8d0ac1398c.png)
