### ISSUE TITLE
Clean up owl P_generosa

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#452]
Files in owl do not seem to match nightingales - there is 106 - only 50 entries in spreadsheet.

What is RRBS2? @eaDIR ?

**Comment by kubu4** [comment]
@eaDIR is a weird thing with Synology and certain network connection types (can't remember what the deal is, but I've looked it up before). I think the @eaDIR directories can be deleted.

**Comment by sr320** [comment]
there appears to be some major PE file discrepancies 

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Index_of__nightingales_P_generosa_1E3D567A.png" alt="Index_of__nightingales_P_generosa_1E3D567A.png"/>

**Comment by kubu4** [comment]
Where is the wiki for this geoduck project? I'd like to see the QC reports from Genewiz.

**Comment by sr320** [comment]
The repo - https://github.com/hputnam/project_juvenile_geoduck_OA

I think we need to start incorporating QC reports into nightingales

**Comment by kubu4** [comment]
Thanks!

**Comment by seanb80** [comment]
All of the files in P_generosa now match those delivered by Genewiz on the hard drive, also removed the RRBS2 directory.

http://rpubs.com/seanb80/246600

**Comment by sr320** [comment]
Thanks
