### ISSUE TITLE
Equipment for 2/4 Manchester Sampling

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#455]
As promised, here's what we need for Saturday:

-Tubes with ethanol to sample 20-30 olys
-Histology kits for 20-30 olys and 20-30 gigas
-Chisel and hammer to sample gigas
-Dry ice

@laurahspencer did I miss anything?

**Comment by grace-ac** [comment]
@yaaminiv would you like me to label the ethanol tubes with a specific oly tissue type? otherwise i'll just say that they're Olys and have ethanol.

**Comment by yaaminiv** [comment]
@grace-ac Whatever you did for the gigas will be fine! Or just whatever makes sense. Not sure what the consensus was after you discussed histology sampling with @laurahspencer

**Comment by grace-ac** [comment]
okay great! also @laurahspencer and @yaaminiv I can label the histology cassettes for you once you guys get an idea of what kinds of tissue you'll be sampling :) that way you won't have to worry about doing it out there. but i'll make sure to put a histology pen in the supply box either way.

**Comment by kubu4** [comment]
I highly recommend labeling cassettes with pencil...

**Comment by yaaminiv** [comment]
@grace-ac i'm sampling gill, mantle and gonad! pretty sure @laurahspencer is doing the same thing

**Comment by grace-ac** [comment]
@yaaminiv so you'll be putting those three tissue types in one cassette, yes? of a total of 20-30 individuals

**Comment by sr320** [comment]
No - only gonads will be fixed.

**Comment by yaaminiv** [comment]
To clarify:

-histology cassettes for gonads
-sampling tubes for gill and mantle ?

**Comment by sr320** [comment]
Yes

**Comment by laurahspencer** [comment]
@kubu4 or @grace-ac do you know if we have or have access to histology marking ink?

**Comment by kubu4** [comment]
Need clarification on this? Do you mean a marker?

If you mean a marker, yes, the lab markers are good for histology. Note, they do require some drying time for them the writing to become chemically resistant (5 -10mins). However, in all instances where histology is involved, I recommend using a pencil if at all possible...

**Comment by laurahspencer** [comment]
No, I am referring to ink that you apply to a tissue sample; Brent
suggested marking one sample with ink if putting a bunch in one cassette,
for reference.

**Comment by kubu4** [comment]
Nope, we don't have that.

**Comment by sr320** [comment]
Might be worth confirming what Brent means in terms of ink on tissue- never
heard of this.

**Comment by laurahspencer** [comment]
Here's an example product: http://bradleyproducts.com/ 

The use in this situation would be to mark a particular tissue in a cassette with multiple samples, thus when the results come back there's no confusion as to the orientation of the cassette when processed. We can discuss it tomorrow- this website says that ink can be applied to preserved tissues.

"Applications: ...  
  * Permanently mark tissue for orienting and for other tissue marking applications.  
  * Process multiple specimens in a single tissue cassette.  
  * Tissue Dye appropriate for both fresh and frozen tissue processing."

**Comment by sr320** [comment]
Cool - please post new issue to purchase.

**Comment by yaaminiv** [comment]
@grace-ac would you mind throwing in some extra ziplocs/some sort of packaging equipment so we can group everything for sampled organism in one place? thanks 😊

**Comment by laurahspencer** [comment]
@grace-ac my sampling scheme has grown considerably. Here's what I need, but **please** don't feel required to do it all yourself.  As much as you have time/the will to prepare would be great, and I'll finish things up tomorrow afternoon (at ~4:30pm); just let me know where you left off. 

In the below labeling scheme:
 * SN. NF, HL & K are all different populations (as you know)
 * 6 & 10 correspond to temperature treatments
 * M = Mantle
 * C = Ctenidia
 * A = Adductor
 * the # sign =  sample 1 through 15 or 9, depending

I also would like to to have enough cassettes for up to 110 tissues; they are small, so I will be putting several in the same cassette, possibly 6-8(?). **That means I need ~19 cassettes total.**

| # Tubes Needed | Labeling Scheme  |
|----------------|------------------|
| 15             | SN-6-M-#       |
| 15             | SN-6-C-#       |
| 15             | SN-6-A-#       |
| 15             | SN-10-M-#      |
| 15             | SN-10-C-#      |
| 15             | SN-10-A-#      |
| 15             | NF-6-M-#       |
| 15             | NF-6-C-#       |
| 15             | NF-6-A-#       |
| 15             | NF-10-M-#      |
| 15             | NF-10-C-#      |
| 15             | NF-10-A-#      |
| 9              | HL-6-M-#       |
| 9              | HL-6-C-#       |
| 9              | HL-6-A-#       |
| 9              | HL-10-M-#      |
| 9              | HL-10-C-#      |
| 9              | HL-10-A-#      |
| 15             | K-6-M-#        |
| 15             | K-6-C-#        |
| 15             | K-6-A-#        |
| 15             | K-10-M-#       |
| 15             | K-10-C-#       |
| 15             | K-10-A-#       |
| Total tubes needed = 324 |

**Comment by sr320** [comment]
Reminder.
Lets be sure to have Dry Ice, and Ethanol so we can sample.

And plenty of extra tubes (screw cap), markers, and supplies to dissect oysters.

Also we should check to see if more histology fixative is here.

**Comment by grace-ac** [comment]
@sr320 the only screw cap tubes left are cryotubes. is that okay? i can make a purchasing issue for more non-cryotube screw caps for future.

**Comment by grace-ac** [comment]
@laurahspencer would a large plastic bin that's a little larger than the cooler from last time fit in your car?

**Comment by laurahspencer** [comment]
Shouldn't be a problem. it will be going in a classmate's car, which is a hatchback.

Thanks!

**Comment by grace-ac** [comment]
@laurahspencer all tubes labeled. Didn't get to histology cassettes, but all histology supplies are in the box along with extra cassettes and foam pads. 

There is a box of dry ice in the container as well, labeled. 

the large container in FTR 213 is for Manchester. It has a lid and wheels on one end, Hopefully it'll fit in the car!

I am heading out, but if there are any questions as to what is in the box, I'll be able to respond to emails!

**Comment by grace-ac** [comment]
Also, the other histology fixative containers did not arrive today, so there are just the six containers (24 cassettes total)

**Comment by MeganHintz** [comment]
So, I don't think the bin is going to fit in my car. Should I see if
Lindsey can drive?

**Comment by laurahspencer** [comment]
I'll text her now

**Comment by laurahspencer** [comment]
Ideas of things to bring for next time: sharper, more slender shucking knife, 1 more small cooler for organizing/transporting tubes on dry ice, more precise tweezers, calipers, figure out best way to label histology cassettes. @yaaminiv anything to add?

**Comment by yaaminiv** [comment]
- cryo-labels
- extra scissors, tweezers, scalpels, shucking knives (preferably with a sharper or serrated edge for the gigas)
- tongs/something to move tubes in and out of the dry ice bath (or in and out of the pantyhose)
- VWR markers for histology cassettes
- print datasheets on waterproof papers

**Comment by sr320** [comment]
Please create issues to purchase

- shucking knives
- precise tweezers
- calipers
- cryolables
- histology markers

**Comment by kubu4** [comment]
We have histology markers, btw...
