### ISSUE TITLE
Printer Toner

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#456]

**Comment by sr320** [comment]
62-9868

**Comment by kubu4** [comment]
@sr320, may I please have a budget number to use when you have a sec?

Cost: $53.00

**Comment by sr320** [comment]
See prior comment https://github.com/sr320/LabDocs/issues/456#issuecomment-276224126 :)

**Comment by kubu4** [comment]
Ha! Simultaneous posts (that was a super quick response, btw)! Thanks!
