### ISSUE TITLE
Manuscript for Peer Review? 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#458]
@sr320: @Ellior2, @yaaminiv and I all have an assignment and "homework" for our Proposal Writing class:

_Assignment, due this Monday:_
**1) Find an article and do a comprehensive peer-review of it.** Steven, it would be interesting to use a manuscript that you are reviewing currently; do you have one?  If not, we can use one that has already been published. 

_Suggested homework, no due date:_
1) Talk with your advisor about the peer-review process and their past experiences
2) Ask to see the peer-reviews of a paper and the response letter by your advisor
3) Shadow your advisor during a peer-review assessment
4) Peer-review a manuscript of a lab mate or advisor prior to submission
5) Ask your advisor to recommend you as a referee, and ask for feedback

Perhaps we can all work through the peer review homework together this spring?

**Comment by yaaminiv** [comment]
I second the idea of working on peer reviews during the spring! Maybe even incorporating it into Pubathon somehow...?

**Comment by kubu4** [comment]
This actually used to be a component of pub-a-thon in years past and is one of the reason everyone's manuscripts & references have to be available for comments...

**Comment by sr320** [comment]
Sounds good - but when you say Spring - you mean it needs to be done by March 10? End of Winter Quarter?

**Comment by laurahspencer** [comment]
The "homework" is a suggested list of things to do- it's not mandatory for the class, so there is no due date.  It's something that would be interesting to do, so perhaps we could do it sometime during Spring Quarter, and possibly connect it to pub-a-thon as Sam suggests.

**Comment by sr320** [comment]
Great! we can certainly do this during Pub-a-thon

**Comment by laurahspencer** [comment]
I forgot to reiterate: we do have to review a manuscript or published article by this Monday.  It was suggested that we could review a manuscript that you're currently reviewing for a journal, if you have one.

**Comment by sr320** [comment]
I can get you one today

**Comment by laurahspencer** [comment]
@sr320 if this is still on the table, there's still time!  If not, no problem we ca use a published article.

**Comment by sr320** [comment]
Stop by my office at noon?

**Comment by Ellior2** [comment]
Can you email me one Steven? Or I'll find one already published? Thanks.

**Comment by sr320** [comment]
Talked with @laurahspencer 
Here are few papers I have reviews for - they are published

Evolutionary Transition of Promoter and Gene Body DNA Methylation across Invertebrate-Vertebrate Boundary 10.1093/molbev/msv345

Transcriptome of American Oysters, Crassostrea virginica, in Response to Bacterial Challenge: Insights into Potential Mechanisms of Disease Resistance 10.1371/journal.pone.0105097

Bimodal signatures of germline methylation are linked with gene expression plasticity in the coral Acropora millepora

Transcriptomic Resources for the Rocky Intertidal Blue Mussel Mytilus edulis from the Gulf of Maine
http://www.bioone.org/doi/abs/10.2983/035.035.0218
