### ISSUE TITLE
Init Molecular Ecology paper repo

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#46]

**Comment by sr320** [comment]
Waiting on @jldimond

**Comment by jldimond** [comment]
Happy to start creating a repo--maybe we can talk more about it tomorrow?

**Comment by sr320** [comment]
How about Authorea with github backend?

**Comment by jldimond** [comment]
OK...I just checked out Authorea, sounds great. But it sounds like it automatically has Git version control...what do you mean by a Git "backend"?

**Comment by sr320** [comment]
Just meant setting this up
https://www.authorea.com/users/3/articles/17235/_show_article

(and make me collab on repo)

**Comment by sr320** [comment]
https://www.authorea.com/users/16716/articles/18248/_show_article
