### ISSUE TITLE
Purchasing- Algae Paste

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#462]
February 02, 2017 at 10:36AM<br>
created via Do Button

**Comment by sr320** [comment]
@laurahspencer can you provide details

**Comment by laurahspencer** [comment]
http://reedmariculture.com/product_instant_algae_shellfish_diet_1800.php

Regarding purchase size, I think they order the 10L size, but the quart size should be enough to supplement the next 6 weeks.

**Comment by sr320** [comment]
One Quart on 62-9868

**Comment by kubu4** [comment]
This is in the 4C in 209 (top shelf).
