### ISSUE TITLE
Purchasing Cartridges (filters) for Manchester

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#463]
February 02, 2017 at 10:37AM<br>
created via Do Button

**Comment by sr320** [comment]
@laurahspencer Can you provide details?

**Comment by laurahspencer** [comment]
Yes- TBD!

**Comment by sr320** [comment]
Will need 2O, 5, and 1s

**Comment by sr320** [comment]
61-0221

**Comment by laurahspencer** [comment]
Order from Harrington Plastics:

~6 x [1 micron 20" WB-20-1W](https://store.hipco.com/viewProduct?rlProdNum=WB-20-1W)
~6 x [5 micron 20" WB-20-5W](https://store.hipco.com/viewProduct?rlProdNum=WB-20-5W)
~6 x [20 micron 20" WB-20-20W](https://store.hipco.com/viewProduct?rlProdNum=WB-20-20W)

**Comment by sr320** [comment]
Please order 20 of each

**Comment by kubu4** [comment]
These came in on Thursday. I put them under the steel dissecting table in 213.
