### ISSUE TITLE
Purchasing - Histology Ink

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#464]
Please purchase a small bottle of histology ink; this seems like a good place to purchase: http://bradleyproducts.com/products/1-oz-tissue-dyes/

- 1 oz bottle is plenty
- How about blue or green? 

Thanks!

**Comment by sr320** [comment]
61-0221

**Comment by kubu4** [comment]
Ordered Cat#NC9513663 from Fisher.
