### ISSUE TITLE
Purchasing - tubing for algal pumps

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#465]
@laurahspencer @yaaminiv 

we also need to purchase tubing for algal pumps.. hard plastic
Can you guys provide details here...

**Comment by laurahspencer** [comment]
Yep- we need to get the specs tomorrow. @yaaminiv don't let me forget.

**Comment by laurahspencer** [comment]
Pretty sure this is what we need: 

[0.250"ID x 0.375"OD x 0.062" Wall Kuri Tec® Series 220 Low Density Food Grade Tubing, Polyethylene, Natural, 500' Coil Item # 220-0662X500](https://store.hipco.com/viewProduct?rlProdNum=220-0662X500) from Harrington. Max we'll need is 20 ft

![algae dosing pump tubing](https://github.com/laurahspencer/O.lurida_Stress/blob/master/Images/2017-02-04_AlgaeDosingPumpsTubing.JPG?raw=true)

**Comment by sr320** [comment]
Please put on 
61-0221

**Comment by laurahspencer** [comment]
FYI I did plug the algae tanks in yesterday and turned them on for a second without any of the plumbing components- they work.

**Comment by kubu4** [comment]
Purchased 100' coil instead of 500'.
