### ISSUE TITLE
2 ml screw cap tubes 

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#466]
not cryotubes.

we have none, so please order a lot. 

used for putting samples in baths, and the snap cap tubes pop open.

**Comment by sr320** [comment]
61-0221

**Comment by kubu4** [comment]
Need caps, too, I assume?

**Comment by grace-ac** [comment]
@kubu4  yes! sorry i forgot that they are separate purchases.

**Comment by kubu4** [comment]
@sr320 total number of tubes? 2000 tubes?

**Comment by sr320** [comment]
Yes please
