### ISSUE TITLE
Github desktop

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#468]
Anyone else having issues with GitHub Desktop today? I tried to open it and got this message. I tried to redownload it from the website and got the same error message....

![image](https://cloud.githubusercontent.com/assets/20071030/22653772/5756779e-ec3f-11e6-8ff3-9a378e1f3a48.png)

**Comment by sr320** [comment]
Have had something similar on Mac - Might try deleting GitHub application
on your computer before redownloading...
Of course there is always the Web workaround if appropriate for what you
are doing.

**Comment by Ellior2** [comment]
Restored to previous state. Thanks
