### ISSUE TITLE
Help getting a file off Emu

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#469]
Can someone please email me a file from Emu? 

Here is the path:
~/Documents/rhonda/ABACUS_output.tsv

rhondae@taylorshellfish.com

**Comment by seanb80** [comment]
I'l email it to you as soon as I finish downloading it, but for future reference, this code will work to copy a file from Emu, to my local machine. Change user name and directories as needed.

`scp sean@128.95.149.26:/home/srlab/Documents/rhonda/ABACUS_output.tsv ~/Documents/ABACUS_output.tsv
