### ISSUE TITLE
Image shortcuts, and Images orientation

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#470]
Anyone have a workaround for posting an image to GitHub issues, without having to upload to a repo?  Say, if I have an image on my computer/email, and don't want to go through the process of adding to a Repo. I tried attaching it in an email reply to an issue, which didn't work. 

Also, anyone else have this issue?: every time I upload an image to a repo the orientation is off. I have to go back to the original image on my computer, flip it 90deg and back, then resave it, and commit those changes. Then, and only then, will the orientation be correct on GitHub.

**Comment by sr320** [comment]
I can tell you markdown will not work via email...
Not sure about attachments...

could always just email url.
Not sure orientation should ever really be a concern in a github issue
conversation...
