### ISSUE TITLE
inputs for PECAN

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#472]
Looked at the [DIA wiki](https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses). Not sure where I can find the following inputs:

- in silico tryptic digest your proteome
 - I'm assuming I can use this for my background list as well? Would I just need to append the QC peptides for the peptides I want to find, but not for the background proteome?
- list of QC peptides ( @emmats ?)

I'm also confused about the Isolation windows. I read Sonia's tutorial but just to clarify: I would need to go into each file and identify the start and end of the m/z range used?

**Comment by emmats** [comment]
I use the PNL protein digestion simulator: https://omics.pnl.gov/software/protein-digestion-simulator

That should be your background list and, yes, you should append your QC peptides. I am emailing the QC protein sequence for PRTC so you can just add it to your fasta and include it in the digestion (github won't let me attach it). I have your isolation windows. I will send them to you and @laurahspencer

**Comment by sr320** [comment]
As we get a better picture of the protocol, please update DIA wiki
accordingly...

**Comment by laurahspencer** [comment]
OK, @emmats & @yaaminiv, I am nearly primed to run Pecan using the below commands. Emma- do you have suggestions on the amount of memory needed?. Also - should the -b input (Background proteome file) be my digested .tab, or undigested .fasta? Can't tell from either guidance docs.:

```
pecanpie -o ~/srlab/Documents/Laura/DNR_geoduck/Pecan_2017-02-20_geoduck
-b 2017-02-19_Geoduck-database4pecan.tabular 
-n DNR_geoduck_SpLibrary.blib --isolationSchemeType TARGET -w isolationWindowWidth 
--pecanMemRequest [??Gb] 
~/srlab/Documents/Laura/DNR_geoduck/DNR_Geoduck_mzMLpath.txt 
~/srlab/Documents/Laura/DNR_geoduck/DNR_Geoduck_DatabasePath.txt 
~/srlab/Documents/Laura/DNR_geoduck/DNR_Geoduck_IsolationScheme.txt 
--fido --jointPercolator
```

Where: 
  * Directory to create = `Pecan_2017-02-20_geoduck`
  * Background proteome.txt file = `2017-02-19_Geoduck-database4pecan.tabular`; _**this is my digested peptide file with the PRTC sequence added. Is this correct? Or, should I be using the undigested protein fasta file instead?**_  
  * blib spectral library output file name =  `DNR_geoduck_SpLibrary.blib`  
  * --isolationSchemeType =  `TARGET`, b/c my isolation scheme file contains 1 column, which I assume represents the center of the precursor isolation window  
  * --pecanMemRequest = ???, _**I need guidance on the # Gb**_  
  * mzML file path list name = `DNR_Geoduck_mzMLpath.txt`, which is simply a list of all my mzML files
  * peptide file path name = `DNR_Geoduck_DatabasePath.txt`, which is a .txt file with only 1 file path listed; it's the digested protein fasta file with PRTC appended - same as my backgroud proteome file. 
  * isolation scheme file name = `DNR_Geoduck_IsolationScheme.txt` - a simple txt file with one column of numbers between ~450-850.
  * Other = : `--fido --jointPercolator`

**Comment by emmats** [comment]
amount of memory:  ummmm, try 16? pecan will suggest the amount of memory it thinks you need if you just put something down. I always accept its suggestion.
background proteome: it should be a txt list of protein name and peptide from your digested peptide file. It will not accept a fasta.
You don't need to put ".blib" at the end of the file name - I always forget this and end up with .blib.blib files.
Give it a try with the isolation scheme as target and we'll see if it works. I'm a little fuzzy on this part. If it doesn't work, that will be our most likely culprit and I will dig into it further for you.
Good luck! I'm working sporadically tomorrow since we are finishing up potty training, but I will be generally available. I'll be in the lab the rest of the week.

**Comment by laurahspencer** [comment]
Ok - tried running the script (with minor changes based on your suggestions), and it looks like it's not recognizing the -b [backgroundproteome.txt] override of the -s [species] input: 

![pecan issue](https://github.com/laurahspencer/LabNotebook/blob/master/images/2017-02-21_Pecan-issue-background.png?raw=true)

Any suggestions?

**Comment by seanb80** [comment]
Looking at the documentation for PECAN, it looks like we need to add the name of the reference proteome to that config file, Do you have the name and a location on Emu for the file?

**Comment by emmats** [comment]
@seanb80 I have never had to do this. It is not necessary to add to the config file if you are providing a background proteome with -b. For some reason, it does look like it thinks Laura is using a -s argument as well. I'm not sure why this is. I will email Sonia and ask.

@laurahspencer - I actually think your isolation scheme is "boarder". I will get back on this in a few minutes. Let me figure it out.

**Comment by laurahspencer** [comment]
Yeah - According to this [Pecan Tutorial](https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe) the -b input overwrites the standard species databases (ecoli/yeast/mouse/human).

**Comment by emmats** [comment]
What is the format of your background proteome? Here is an example of one that worked...

Protein_Name	Sequence
P00000	SSAAPPPPPR
P00000	SSAAPPPPPRGISNEGQNASIK
P00000	GISNEGQNASIK
P00000	GISNEGQNASIKHVLTSIGEK
P00000	HVLTSIGEK
P00000	HVLTSIGEKDIPVPKPK
P00000	DIPVPKPK
P00000	DIPVPKPKIGDYAGIK
P00000	IGDYAGIK

**Comment by laurahspencer** [comment]
![screenshot background proteome](https://github.com/laurahspencer/LabNotebook/blob/master/images/Screenshot_2017-02-21_12-45-20.png?raw=true)

**Comment by laurahspencer** [comment]
Is it possibly because it's a .tabular file type?

**Comment by emmats** [comment]
It can't hurt to save it as .txt and see if that fixes it. I also know that Sonia sometimes messes around with pecan a little bit to improve it and there are unintended consequences. I'll let you know what she says, but she may not get back today since she is in Boston now.

Your isolation windows should be "boarder" following the format below. @yaaminiv should make sure hers are similarly formatted. Let me know if this doesn't make sense.
<img width="438" alt="screen shot 2017-02-21 at 12 48 14 pm" src="https://cloud.githubusercontent.com/assets/4564812/23184370/5cd8abc8-f834-11e6-8b36-7a5a30e20d3f.png">

**Comment by seanb80** [comment]
It might also be a character delimiting thing? Your .tabular may be tab-delimited, and it's expecting a white-space delimited file? Just an idea.

**Comment by laurahspencer** [comment]
I'll give the .txt format a try, then will try the tab/character change. Thanks for the help!

Also, @emmats you kindly provided us with the isolation scheme files, which only have 1 column (snapshot of mine is below) - I assume you pulled this data from a Lumos method file - so I should go back to the methods file and pull data in precursor windows/ranges? 

![isolation scheme](https://github.com/laurahspencer/LabNotebook/blob/master/images/Screenshot_2017-02-21_12-54-07.png?raw=true)

**Comment by emmats** [comment]
You should just have to move the numbers around. I think every two numbers represent the borders of your isolation windows. You will notice that the numbers starting in row 42 match the numbers in the screen shot I sent you (which is how this list was generated in Skyline). So your windows are:
455-465
465-475
475-485....
450-460
460-470...

But with the exact decimal places that I was too lazy to type out :) Does that make sense?

**Comment by laurahspencer** [comment]
So the windows should look like this?
Also, just to confirm, they're supposed to run from 455-855, then restart @ line 41 from 450-850? 

![isolation scheme ranges](https://github.com/laurahspencer/LabNotebook/blob/master/images/Screenshot_2017-02-21_13-14-56.png?raw=true)

**Comment by emmats** [comment]
Yes. They are overlapping windows with a 5 m/z offset. That is supposed to get better coverage/peptide resolution.

**Comment by laurahspencer** [comment]
FYI: I tried converting to .txt, played around with the file paths, and also converted from tab to character spaces in the database file (used `expand` command), and continued getting the same error.

**Comment by emmats** [comment]
This is what Sonia says:
The path to the file is incorrect as stated in the last line
"Please confirm the file path in ...."

If you wish to have pecanpie to provide some species db by default, put them under /your/dir/path and change the corresponding address in the config file to /your/dir/path
