### ISSUE TITLE
Wine error

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#474]
following https://github.com/sr320/LabDocs/issues/394

here is what I get just trying to run comet.
```
steven@emu:~/bioinfo/020917$ wine /home/shared/comet/comet.2016012.wine32.exe
wine: cannot find '/home/shared/comet/comet.2016012.wine32.exe'
```

@seanb80 what I am doing wrong? permissions issue?

**Comment by seanb80** [comment]
I apologize! it's win32.exe, not wine. Typo on my part. 

`wine /home/shared/comet/comet.2016012.win32.exe \
-Pcomet.params.high-low \
-Dgigas-proteome.fasta \
*.raw
`

**Comment by sr320** [comment]
typo 👎  😄  ?
cut-paste 
thanks
