### ISSUE TITLE
Still Wining 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#475]
Going the conversion route I still am having `wine` issues.

```
steven@emu:~/bioinfo/020917$ for file in *.raw;     do     no_path=${file##*/};     no_ext=${no_path%.raw};     WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe "$file" "$no_ext".mzXML;     done
wine: cannot find L"C:\\windows\\system32\\ReAdW.2016010.msfilereader.exe"
steven@emu:~/bioinfo/020917$ Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
```

and hangs...

**Comment by kubu4** [comment]
Try specifying full path to ```ReAdW.2016010.msfilereader.exe```

**Comment by seanb80** [comment]
I updated the /etc/environment path to include everything. I believe after logging out of your user account and logging back in it should work.

Previously, I'd just been adding paths to individual user accounts, this should be global.

**Comment by sr320** [comment]
@kubu4 full path is?

@seanb80 exited, quit terminal, relogged in....

```
steven@emu:~/bioinfo/020917$ for file in *.raw;     do     no_path=${file##*/};     no_ext=${no_path%.raw};     WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe "$file" "$no_ext".mzXML;     done
wine: cannot find L"C:\\windows\\system32\\ReAdW.2016010.msfilereader.exe"
steven@emu:~/bioinfo/020917$ Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
```
still hanging

**Comment by kubu4** [comment]
I don't know. Full path is wherever that program is saved. I've never used it, so can't provide any help on locating it.

**Comment by kubu4** [comment]
Found it! (I used: ```which ReAdW.2016010.msfilereader.exe```). It's here: ```/home/shared/ReAdW/ReAdW.2016010.msfilereader.exe```

**Comment by sr320** [comment]
no luck

```
steven@emu:~/bioinfo/020917$ for file in *.raw
>     do
>     no_path=${file##*/}
>     no_ext=${no_path%.raw}
>     WINEPREFIX=~/.wine32 wine /home/shared/ReAdW/ReAdW.2016010.msfilereader.exe "$file" "$no_ext".mzXML
>     done
err:module:import_dll Library mfc100.dll (which is needed by L"Z:\\home\\shared\\ReAdW\\ReAdW.2016010.msfilereader.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\shared\\ReAdW\\ReAdW.2016010.msfilereader.exe" failed, status c0000135
steven@emu:~/bioinfo/020917$ Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window

```

**Comment by seanb80** [comment]
I think it's an SSH issue, but am not sure, looking at it now.

**Comment by kubu4** [comment]
To get rid of the display error messages, edit the ```/etc/ssh/sshd_config``` file so that X11 forwarding is ```yes```. This needs to be done on your local computer (it's already set to ```yes``` on Emu). Be sure to uncomment the line, in that config file. You may need to restart Terminal for the change to take effect.

The other library stuff is the real issue, though...

**Comment by seanb80** [comment]
It's a permission issue apparently. Am working on fixing it now. 

Learned a valuable lesson though, never run anything involved with wine as sudo! It sets the owner to things as root, and finding everything that's been set as such is difficult.

**Comment by seanb80** [comment]
I believe I have it working now. Am testing a file and will write something up on Genefish once I'm sure.

**Comment by seanb80** [comment]
Ok. I'm 99.9% sure it works. I just converted a file on Steven's Emu account, and it completed. 

![readw2](https://cloud.githubusercontent.com/assets/10619258/22800943/e57eb75c-eebf-11e6-8ce7-bc616e184fb1.png)

I'll write up an overview of what went wrong, and how to fix it in the future. I'm also going to look into if it's possible to create a shared wine environment that everyone can use, as opposed to re-creating the environment for each new user account.

**Comment by sr320** [comment]
Believe this works!

Lets have everyone else use srlab account so this does not have to be fixed for all..

I presume this also means I could use windows version of comet and not convert?

```
steven@emu:~/bioinfo/020917$ WINEPREFIX=~/.wine32 ReAdW.2016010.msfilereader.exe \
> 20161205_Sample_1.raw \
> test-SR.mzXML
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
fixme:thread:GetThreadPreferredUILanguages 52, 0x33fafc, 0x33fc74 0x33fb04
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
ReAdW 2016.1.0(build Jun 21 2016 11:13:06)
Xcalibur interface initialized (5).
(Thermo lib opened file 20161205_Sample_1.raw)
file version is 66, interface version is 2.0 or greater
file should contain scan numbers 1 through 109165
(got computer name: emu)
Calculating sha1-sum of mzXML
--done (mzXML sha1):8ff1de9bb5ca369cce98859a506c3d166b56076a

steven@emu:~/bioinfo/020917$ head test-SR.mzXML 
<?xml version="1.0" encoding="ISO-8859-1"?>
<mzXML xmlns="http://sashimi.sourceforge.net/schema_revision/mzXML_3.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://sashimi.sourceforge.net/schema_revision/mzXML_3.1 http://sashimi.sourceforge.net/schema_revision/mzXML_3.1/mzXML_idx_3.1.xsd" >
 <msRun scanCount="109165" startTime="PT0.0281661S" endTime="PT8399.64S" >
  <parentFile fileName="20161205_Sample_1.raw" fileType="RAWData" fileSha1="9959094e2ae1c93e0439425418921b9df1c80000" />
  <msInstrument>
   <msManufacturer category="msManufacturer" value="Thermo" />
   <msModel category="msModel" value="Orbitrap Fusion Lumos" />
   <msIonisation category="msIonisation" value="NSI" />
```


It appears the loop command @kubu4 has on the wiki does not work...

```
steven@emu:~/bioinfo/020917$ for file in *.raw
>     do
>     no_path=${file##*/}
>     no_ext=${no_path%.raw}
>     WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe "$file" "$no_ext".mzXML
>     done
wine: cannot find L"C:\\windows\\system32\\ReAdW.2016010.msfilereader.exe"
steven@emu:~/bioinfo/020917$ Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
```

I am going cross our for now so others do not go down this path..

**Comment by seanb80** [comment]
Yes, you should be able to use the win32 version of Comet to skip the conversion step.

**Comment by sr320** [comment]
I think I am now... thanks!

**Comment by kubu4** [comment]
Whoa! Just realized that the difference with the "for loop" and the working "one-liner" is the inclusion of ```wine``` after ```WINEPREFIX=~/.wine32```! Removing that ```wine``` from the for loop version makes it work.

Was that the issue all along? Having that extra ```wine``` in the code?

I've udpated the wiki with the functioning for loop code, although it might not be needed any more, since it appears that comet is working...

**Comment by seanb80** [comment]
Interesting. I just tested running things without the `wine` part, and they seem to work. Apparently the `WINEPREFIX=~/.wine32` part is enough?
