### ISSUE TITLE
Install MSconvert on Emu for DIA analyses

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#478]
Now that @seanb80 is an expert on wine..

I think we need to install the windows version of MSconvert in order to convert "vendor" formats. (Not sure what this means). There is Linux version.
http://proteowizard.sourceforge.net/downloads.shtml

Note it is part of a larger software package..

Big picture is I am trying to get .raw files ready for Pecan...

https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses

**Comment by kubu4** [comment]
Who knew the proteomics field relied on Windows so heavily??!! Crazy.

**Comment by seanb80** [comment]
Sadists, all of them. Should I try to get skyline working as well, since it will be the next step after pecan I believe?

**Comment by sr320** [comment]
I suppose...

Or we could just bail on this whole proteomics thing.

Actually I think Skyline is a Windows GUI- so everyone is in their own.
