### ISSUE TITLE
Connecting to Hummingbird

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#481]
Hi - For some reason I cannot remote connect to Hummingbird. I wonder if it is on? Is it possible for someone with remote boot privileges to boot up Hummingbird if it is indeed turned off? 
Thanks

**Comment by sr320** [comment]
It is online - note the IP address has changed to 128.94.149.36

**Comment by jldimond** [comment]
OK - I replaced the old IP address with the new one but it still am not able to connect...

**Comment by jldimond** [comment]
But, I am at work on a WWU wireless connection, so maybe there is a firewall preventing connection?

**Comment by jldimond** [comment]
Will try again when I'm back home.

**Comment by sr320** [comment]
There is no firewall.
I successfully screen shared with my account and srlab.

**Comment by jldimond** [comment]
Yes but I think the WWU wireless network may be preventing VNC: http://www.wwu.edu/depts/admcs/Remote_Access_Info.shtml

**Comment by sr320** [comment]
gotcha - I thought you meant on UW side..

**Comment by jldimond** [comment]
OK, I got it - I checked on the IP address and there was a slight discrepancy between the IP address you sent above (128.95.149.36 not 128.94.149.36).

**Comment by kubu4** [comment]
For reference, IP addresses for all computers are listed here: https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit#gid=0
