### ISSUE TITLE
Laura attempting .raw to .mzXML conversion 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#482]
I'm doing the same conversion from .raw to .mzXML that Rhonda worked on recently. I'm sitting in front of Emu, using the following script that Sam provided in Issue #408:
```
for file in ~/Documents/Laura/DNR_geoduck/2017_January_23_envtstress_*.raw  
do  
no_path=${file##*/}  
no_ext=${no_path%.raw}  
WINEPREFIX=~/.wine32 wine ReAdW.2016010.msfilereader.exe "file" ~/Documents/Laura/DNR_geoduck/Converted/"$no_ext".mzXML  
done
```
(my files are saved locally on Emu)

I'm encountering these errors: 

![error](https://github.com/laurahspencer/LabNotebook/blob/master/images/Screenshot%20from%202017-02-12%2013-00-31.png?raw=true)

Am I using WINE correctly?

**Comment by laurahspencer** [comment]
I just moved to the /home/shared/ReAdW/ directory and tried again with the same script, and got these errors:

![error2](https://github.com/laurahspencer/LabNotebook/blob/master/images/Screenshot%20from%202017-02-12%2013-18-55.png?raw=true)

(The "file: path not found" error and subsequent description is repeated many times, presumably for each of my .raw files)

**Comment by sr320** [comment]
If we step back a minute - my understanding you are doing the DIA workflow ...
https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses
not the DDA workflow?

**Comment by laurahspencer** [comment]
Yes, this is correct.

**Comment by sr320** [comment]
So there in no  .raw to .mzXML in the DIA workflow...

**Comment by laurahspencer** [comment]
Ah - I'm converting to .mzML, not .mzXML

**Comment by laurahspencer** [comment]
So - I now see that I need to use MSConvert for this step (not the ReAdW program); and from the status of Issue #478 it appears that it is still in the process of being installed. Correct?

**Comment by sr320** [comment]
unfortunately.... yes.
This issue is that it is Windows software.

**Comment by laurahspencer** [comment]
Ok - thanks for the help!
