### ISSUE TITLE
Purchasing: netting for oyster bags 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#484]
We need some plastic netting for our Manchester experiment.  Let's get some tubular nets from Norplex Inc., called "shellfish packaging" on their [site](http://www.norplexinc.com/aquaculture/).  

It'd be great to get 2 colors: red & blue.  This isn't necessary, however.   I only need ~40 feet now, so I'm guessing the minimum order will work.

**Comment by kubu4** [comment]
Please provide link(s) and/or product numbers.

Also, please use GitHub "Labels" feature to indicate purchasing needs (see the right side of the screen - click on "Labels" and you'll be presented with a bunch of options to choose from).

**Comment by laurahspencer** [comment]
Here's [the website](http://www.norplexinc.com/aquaculture/)

The Norplex Inc. website doesn't include any product numbers, unfortunately. Would you like to call them to get the product details, or would you prefer that I do it? 

Thanks for the tip on the labeling scheme!

**Comment by kubu4** [comment]
Please contact them to get purchasing info and provide the info here.

I'll place the order using the info you provide. 

A bit of a pain, I know, but saves me time and guesswork, particularly not knowing exactly what size netting (diameter, hole size, unit length, etc) you need/want.

**Comment by laurahspencer** [comment]
No prob - will provide later today.

**Comment by laurahspencer** [comment]
FYI I called and left a message with their "weaving guys" today. I was told that he'll hopefully get back to me tomorrow.

**Comment by laurahspencer** [comment]
I think these will work fine: http://a.co/6DvIP4X

Please order: 
1 pack of 100
Teal

**Comment by kubu4** [comment]
This arrived today.
