### ISSUE TITLE
http://owl.fish.washington.edu/spartina permission

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#485]
We cannot see anything at
http://owl.fish.washington.edu/spartina

**Comment by kubu4** [comment]
Fixed. Checked all the boxes in the Properties screen for this folder (matches other folders that are accessible). This is how it was before:

![selection_091](https://cloud.githubusercontent.com/assets/4514104/22984425/289397ee-f35a-11e6-92be-91553f0477e0.png)

**Comment by sr320** [comment]
Thanks!
