### ISSUE TITLE
MsConvert Settings do not Match Example

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#486]
In running MsConvert- the option to not appear consistent with what is provided by the "evernote" example on the Wiki.

http://d.pr/i/JPrV

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Screen_Capture_on_2017-02-15_at_06-49-26_gif_•_Droplr_1E54A7FD.png" alt="Screen_Capture_on_2017-02-15_at_06-49-26_gif_•_Droplr_1E54A7FD.png"/>

Is the selection correct for the type of analysis?

**Comment by emmats** [comment]
I guess MSConvert was updated? Is that the closest option you could find to what Sonia had in her instructions? I can email her or ask around to see if that is what we should use.

**Comment by sr320** [comment]
In my limited ability - I would say this is the closest, but could you please confirm this is the right setting?

**Comment by emmats** [comment]
The choice that you have highlighted is the same as the one Sonia indicates in her tutorial.

**Comment by sr320** [comment]
thanks

**Comment by sr320** [comment]
And I presume the correct setting for Laura's and Yaamini's data?

**Comment by emmats** [comment]
yes
