### ISSUE TITLE
Sequencing larvae of Laura's G2 oysters

### ISSUE THREAD

**Issue by ksil91** [sr320/LabDocs#488]
I'm preparing a 2bRAD library with larval samples, mostly with the intent of seeing how well it works and how many samples can fit on one lane considering coverage. Also sequencing oysters involved in the growth experiment. I have DNA samples from the larvae in Summer 2015 that were then added to cultch and grew up to become Laura's South Sound G2 oysters that she's using in her experiment. Any interest in me sequencing these particular larvae? Need to know in the next couple of days.

**Comment by sr320** [comment]
Yes- there is interest.

**Comment by laurahspencer** [comment]
Agreed, definite interest!
