### ISSUE TITLE
Purchase low water alarms

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#490]
Please purchase three of

High or Low water alarm https://www.amazon.com/dp/B001B4VO36/ref=cm_sw_r_cp_api_MJKPybZ9J0HTW

**Comment by sr320** [comment]
61-0221

**Comment by sr320** [comment]
I think only one was ordered, not three?

**Comment by kubu4** [comment]
You are correct. Doh! I misread "three" as "these". Ordering more now...

**Comment by kubu4** [comment]
And, of course, they only have 1 left in stock. 😞

**Comment by kubu4** [comment]
Never mind! I "gamed" the system! Two more have been ordered and they will arrive tomorrow.
