### ISSUE TITLE
TA Samples from OA @ Manchester

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#491]
@sr320, @yaaminiv & @seanb80 

I am bringing the first round of water chem. samples (2.17.2017 @ 8am) from Manchester back to the lab. Sean - do you have TA analysis in Olympia scheduled yet? It'd be great to get these in the queue.

Also, Ryan told me that he is no longer comfortable committing to weekly water samples; he hadn't realized/remembered the time commitment (~1hr) due to the calibration curve and measurements via handheld probes.  Steven, I asked him to send you a note about it - not sure if he has yet. I ran out this morning before class to sample; I'll see how it goes in terms of getting to class on time (unlikely!). I'll plan on doing so next week too, unless we can figure out another solution.

**Comment by sr320** [comment]
They are queued.

**Comment by laurahspencer** [comment]
Excellent.  There are 16.

**Comment by sr320** [comment]
Queue will likely move faster once we have some proteomics data to show DNR
:)

**Comment by seanb80** [comment]
Good news! We don't even have to bribe them with proteomics data. I emailed Micah this morning again, and he got back to me quickly. I'm scheduled to pick up my pass and run through a couple of samples which should leave me relatively autonomous after that!

I'll make a new issue to determine what sample subset I should bring down with me.

**Comment by sr320** [comment]
Thanks Sean!
But note I did follow up his email promising some exciting proteomics data
coming down the pipe, in order to keep the momentum going.
