### ISSUE TITLE
TA subsample selection

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#493]
I heard from Micah today! 

I should be scheduled to meet with him next Wednesday to get my guest pass and run through some samples, which means I need to bring them down with me today most likely. 

@sr320 or @hputnam which should I bring, or should I just grab a few and deal with the sub-sampling later when we bring the bulk down?

**Comment by sr320** [comment]
I will let @hputnam decide

**Comment by seanb80** [comment]
I'm leaving soon and so I grabbed 6 bottles from the blue tub, triple bagged them, and put paper towels in each bag. Hopefully this is ok?

the bottles are:
| Bottle # | Tank # | Date          |
|----------|--------|---------------|
| 121      | 3      | 17 March 2016 |
| 125      | 5      | 17 March 2016 |
| 133      | 13     | 17 March 2016 |
| 147      | 2      | 19 March 2016 |
| 148      | 2      | 19 March 2016 |
| 167      | 16     | 19 March 2016 |

**Comment by hputnam** [comment]
Those are good samples to start with. They are from the larval project and have duplicates, so are good training.

Here is the list for the juvenile project. There is no need to do duplicate tanks from the same day. The header tanks are low priority. 

https://github.com/hputnam/project_juvenile_geoduck_OA/blob/master/Setup_Notes/SW_Chem_Sample_List_juvenile.csv

**Comment by seanb80** [comment]
Good news and bad news. 

The good: I got my access badge and now can get in to the lab and also have run a number of CRM samples through the titrator and feel comfortable about using it (Will write a Wiki page on the process). 

The bad: The titrator hadn't been used in a while, and is apparently a little temperamental. None of the samples I ran were within reasonable proximity to each other (ex. the last three I ran were 2140, 2480, and 2212, with a target of 2230). 

I'll follow up further with Micah regarding the variation, and hopefully we can get that fixed and I'll get to grinding all the samples out.

**Comment by hputnam** [comment]
This is common if the titrator hasn't been used for a while. It is good to run several junk seawater samples first, then maybe 2 CRMs and then samples after you are happy with CRMS. I am happy to look over any protocol and see if I can see anywhere to improve.  The most common issue when not run for a while is usually bubbles in the lines.  They can be hard to see and have major impacts on the TA.  How is the pH probe performing (e.g., slope and zero point when calibrated)?
