### ISSUE TITLE
Emu srlab frozen via gui

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#494]
I'm sitting in front of Emu and the File Explorer crashed, now the entire interface is frozen.  The mouse moves around, but nothing responds when I click.  I'm able to log in via ssh, so I think the file explorer is the issue.  Anyone have an idea how to get it back up and running?  I need to use a gui program, so cannot do everything via ssh. 

Here's a snapshot of Emu via `top`: 

![top](https://github.com/laurahspencer/LabNotebook/blob/master/images/Snip20170219_1.png?raw=true)

Thanks!

**Comment by sr320** [comment]
Restart is ok - but what GUI are you trying to run?

**Comment by seanb80** [comment]
For future reference you can open up a terminal window, type `xkill`, which changes your cursor to an X, you can then click any window you want to kill, and it goes away!

**Comment by laurahspencer** [comment]
Cool - it's rebooted, thanks for the response!
I was doing a rerun of Protein Digestion Simulator program.
