### ISSUE TITLE
Add R script to DMP

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#496]
Please add the R script for handling high-throughput sequencing data to [https://github.com/sr320/LabDocs/tree/master/code/script-box](https://github.com/sr320/LabDocs/tree/master/code/script-box). Please update corresponding readme file w/brief description of script functionality.

Please add instructions on how to run this script to the [DMP](https://github.com/sr320/LabDocs/blob/master/DMPseq.md).

**Comment by seanb80** [comment]
Updated!
