### ISSUE TITLE
Purchasing: glass bottles for TA sampling 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#497]
We need more glass bottles for water/TA samples out at Manchester. In looking through old issues and the purchasing log I don't see purchasing history.  Anyone know where the bottles that are currently out there came from?  I think they are 125mL.

**Comment by kubu4** [comment]
Please add "purchasing" label to this issue.

I don't know what type of bottle we use. I don't recall ever ordering bottles specifically for TA sampling.

**Comment by hputnam** [comment]
We bought several cases previously and stored them under the stairs going up to Rick's lab. You may want to check there before reordering.

Bottle information:

Specialty Bottles:
http://www.specialtybottle.com/

Bottle Type:
4 oz Clear Boston Round Glass Bottle with Black Cap

Item ID Code:
BRF4

**Comment by laurahspencer** [comment]
Thanks Hollie! 

Sam, I'll get back to you on this one.

**Comment by laurahspencer** [comment]
Confirmed that the big boxes of bottles have already been used (by PSRF in Natalie's project this summer). So, we need more. Please order:

4 oz Clear Boston Round Glass Bottle with Black Cap
http://www.specialtybottle.com/glass-bottles/clear-boston-rounds/4oz-brf4
ID Code: BRF4, Closure: 24/400
2 cases (128 bottles per case)

**Comment by sr320** [comment]
61-0221

**Comment by kubu4** [comment]
These have arrived. I've put them under the steel dissecting table in 213.
