### ISSUE TITLE
Pecan/Grid Engine error

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#498]
I've got pecanpie working, but when I try to actually execute `run_search.sh` that's created, I get the error:

`Unable to run job: unknown resource "mem_requested".
Exiting.
`
for each pecan call in the script. Some googling suggests that this is due to pecan not using the mem_requested argument passed by Grid Engine. 

@emmats is this something you've seen before perhaps? I'll keep plugging away, but any assistance would be appreciated!

**Comment by emmats** [comment]
I've never had that issue before. If you want to ask Sonia, her email is sonia810@uw.edu.

**Comment by sr320** [comment]
Can you post the shell script?

**Comment by seanb80** [comment]
The overall shell script is: [run_search.txt](https://github.com/sr320/LabDocs/files/800461/run_search.txt)

which then references a bunch of .job files, such as [pecan_2017_January_23_envtstress_blank1.txt](https://github.com/sr320/LabDocs/files/800462/pecan_2017_January_23_envtstress_blank1.txt)

I believe I have everything working, I just went through and removed the `mem_requested` argument in each line of the `run_search.sh` as well as fixed an issue with pecanpie not properly referencing the config file for locating the pecan binary.

**Comment by seanb80** [comment]
Heard back from Sonia, 

Apparently mem_requested is an argument in Grid Engine itself which, depending on the version, can also be entitled mem_free. We apparently have the mem_free version. This requires a re-compile of pecan, which I will do when the current run is done.
