### ISSUE TITLE
Set-up and Deploy new Hobos at Manchester

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#499]
The new hobos came in last week - please set-up and deploy Wednesday

**Comment by hputnam** [comment]
Don't forget to synchronize deployment time and frequency!  Also you may want to do a cross calibration for at least 24h prior to deployment.

**Comment by laurahspencer** [comment]
Thanks for the tips! I'm soaking them all overnight in the same water, so we can see how the temps differ. 

They're programmed and ready to go. We'll take them out tomorrow and put them in the tanks.
