### ISSUE TITLE
Linux box

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#50]
Twice today software installs failed which I think would have worked on Linux- painless means to see if this is viable option going forward?

Maybe dual boot genefish? Or greenbird?

**Comment by kubu4** [comment]
Another possible option: Install Linux (dual boot or convert entirely to Linux) on an extra cluster node.

**Comment by sr320** [comment]
Anyone have an Ubuntu DVD? I burned 2 and cannot seem to get to install.

**Comment by jheare** [comment]
I've done it with a flash drive and it worked pretty well.

**Comment by jldimond** [comment]
I have it on a flash drive and could bring in on Tuesday

**Comment by sr320** [comment]
If I could try a flash drive that would be great

Steven Roberts
