### ISSUE TITLE
Inventory / Clean out room 213 Shelf

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#502]
Kits at left at entryway.

**Comment by grace-ac** [comment]
Submitted forms to get the hazardous chemicals picked up. If all was done correctly, the chemicals will be picked up within 2-4 weeks.

**Comment by grace-ac** [comment]
added current inventory to tab in Roberts Lab Inventory: https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit?usp=sharing 

If there's any more useful information you'd like me to add to spreadsheet about the kits, I can easily do that.
