### ISSUE TITLE
Identifying Box 2 Oly samples

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#506]
Picture of the few boxes that are labeled: 
![img_2022](https://cloud.githubusercontent.com/assets/14934314/23562455/599f8952-fff7-11e6-86d3-70072d161fcf.JPG)

**Comment by grace-ac** [comment]
When I come back this afternoon I will search through to try and find spreadsheets of what these might be. I can also start working on a true master sheet of all Oly samples if I can't find one. The one that I have seen in the past doesn't seem to be an exhaustive list as it appears to only include samples from one year.

**Comment by grace-ac** [comment]
Looking for wild from fidalgo (NF)

**Comment by sr320** [comment]
Somewhere there should be some text associated with the analysis Katie did.
Will check with Brent
