### ISSUE TITLE
DIA analysis wiki updates

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#507]
I've updated the [DIA analysis wiki](https://github.com/sr320/LabDocs/wiki/DIA-Data-Analyses) with the steps @laurahspencer and I used to run PECAN. There is one step that I couldn't elaborate on, which was how @seanb80 configured the species before we ran `pecanpie`.

@sr320 + @emmats , I'd appreciate your feedback whenever you're free!

**Comment by sr320** [comment]
I edited to try to better isolate steps. Review to make sure nothing was missed. @seanb80 can update pecan steps next week when he is in..

**Comment by emmats** [comment]
Looks good to me. FYI: I am on vacation and the wifi here is unusable. I'm working off my phone as best as possible.
