### ISSUE TITLE
PECAN run 1 finished...now what?

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#508]
The run with only 5 oyster samples I started yesterday seems to have created .blib file I wanted.

![pecan-run-1-complete](https://cloud.githubusercontent.com/assets/22335838/23580360/1a772398-00b5-11e7-978e-e6a4708a8e2b.png)

@emmats, is the only way for me to check whether or not this was successful is to open it in Skyline?I just want to know if I can use the same [code](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/2017-02-28-DIA-Analysis-PECAN.ipynb) to run more samples in the meantime.

**Comment by sr320** [comment]
Skyline is next

**Comment by yaaminiv** [comment]
actually... @seanb80 actually thinks there was a problem with the mzML files.

https://genefish.wordpress.com/2017/03/04/pecan-on-roadrunner-isnt-working-correctly/

**Comment by kubu4** [comment]
Sean's post mentions Pecolator, but I don't see that as a step in the DIA wiki. Is that a sub-process of PECAN?

**Comment by seanb80** [comment]
Percolator is part of the pecan workflow. It goes Pecan -> Percolator -> Pecan2blib "seamlessly" via pecanpie.

**Comment by sr320** [comment]
@yaaminiv I would recommend re converting the raw files in the event this ends up being the problem and/or start getting familiar with skyline

**Comment by kubu4** [comment]
In regards to @sr320's post, who ran the steps leading up to PECAN (i.e. which notebook can I look at to view those previous steps)?

**Comment by sr320** [comment]
Yes, everything done should be documented in notebooks in a manner someone
else could reproduce.

**Comment by yaaminiv** [comment]
my notebook is here: https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/2017-02-28-DIA-Analysis-PECAN.ipynb

percolator is one of the arguments for PECAN (it's in the code on the wiki)

**Comment by sr320** [comment]
Be sure to add to you lab notebook- minimally a link and blurb. That is
where we will be looking for it.

**Comment by sr320** [comment]
I would also compare what @laurahspencer used as input for pecan and see how this compares with your files

**Comment by kubu4** [comment]
I was looking at your notebook and noticed a few things. Any chance any of these are causing the issue that Sean noticed?

- There is no output from the ```head```, nor ```tail``` commands when viewing the results of the tryptic digest (Combined-gigas-QC.txt). This suggests the file is empty.

- Same goes for your isolation scheme file (2017-03-03-isolation-windows.csv)

- Your ```pecanpie``` command was never run.

**Comment by kubu4** [comment]
Your isolation scheme option in your ```pecanpie``` command has a typo: BOARDER.

It should be BORDER.

That typo can be directly attributed to the [Evernote Tutorial](https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe), which has the incorrect BOARDER. The [official PECAN tutorial](https://bitbucket.org/maccosslab/pecan/src/31750509f5c44348d61b2bfb5c52d9ea37d64a17/docs/PECANTutorial_v0.9.9.pdf?fileviewer=file-view-default)(you'll have to click on the "view raw" link on that page to view the PDF), indicates in multiple locations that it should be spelled BORDER.

**Comment by kubu4** [comment]
Is there any info on the raw conversion and/or the ```msconvert``` config file that was used? Also, the [Evernote Tutorial](https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe) indicates that the ```msconvert``` GUI cannot be used for raw conversion under some conditions. Do you know whether or not your files fall under the conditions mentioned that would require command line conversion?

**Comment by kubu4** [comment]
Update: You can ignore my [previous post](https://github.com/sr320/LabDocs/issues/508#issuecomment-284202971); I looked at the actual files on Roadrunner (they seem OK) and I see in your screen cap that the ```pecanpie``` command was actually run.

**Comment by yaaminiv** [comment]
After talking with Sam, here's my game plan:

1. Try using "BORDER" instead of "BOARDER" for the isolation scheme.
*Just tried this and it gave me an error. Looks like you do need to use the typo to run the command correctly.* 

2. Reconvert 1 mzML file in the command line ([see Evernote tutorial](https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe)) and see what happens when I run `pecanpie`
@sr320 is it possible for me to do this on Roadrunner, or do I need another computer?

3. Try just uploading the .blib file I have now to Skyline (once we get instructions.......)

4. @laurahspencer and I used the exact same steps. @seanb80, did her output also have the same problem mine did? It wouldn't make sense for my files to need command line conversion and hers not to since we both used the Lumos and have the exact same file formats.

**Comment by sr320** [comment]
Re #2 - Please refer to the GitHub wiki regarding what step you are
referring to.

**Comment by yaaminiv** [comment]
I'm referring to [Step 1](https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses#step-1-convert-raw-files-with-msconvert)

**Comment by sr320** [comment]
That is a Windows GUI program. This would be run on a Windows machine.

**Comment by kubu4** [comment]
@sr320 - The tutorial suggests that the GUI cannot be used:

> 
>STEP 2: Convert RAW to mzML
>***************************************
>** Data from Orbitrap Fusion (Lumos) instruments:
>Proteowizard GUI cannot correctly convert the raw files to mzML when SIM scans are used for MS1 (which is probably always). You have to convert the raw files to mzMLs using proteowizard commend line. 
>msconvert.exe -c msconvert-SIMMS1.config raw_files
>

**Comment by sr320** [comment]
#FFS 
No way - we have a clear confirmation from @emmats here:
https://github.com/sr320/LabDocs/issues/486

However seems like as good as step as any to redo based on that statement.

**Comment by yaaminiv** [comment]
Alright, I'll proceed with using MSConvert in the command line to reconvert a single .mzML file while concurrently examining the .blib file I have to see what's going on.
