### ISSUE TITLE
Qspec input file considering experimental design

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#509]
@emmats @kubu4 @sr320 

I'm having a hard time figuring out how I should input my data in Qspec as I don't have as simple of an experimental design. I have more than two sampling days and I have more than two groups I would like to compare.

My experimental design is as follows. Steven, Brent and I decided to run 22 samples out of the 65 we had so we don't really have biological reps (at least that performed similarly). My 23C Silo 2 had poor survival while 23C Silo 3 had high survival- even though these were my biological replicates. My 29C Silo 9 had high survival (similar to Silo 3). This is why I want to treat these as three separate groups sampled at 7 different times. I think it's also important to look at the progression of protein expression through time, which I feel like we would lose by considering all my sampling days within each group as "replicates". From what Emma said in [Issue 492](https://github.com/sr320/LabDocs/issues/492) it sounds like Qspec groups all the 0s and compares it to all of the 1s. I feel like we will lose a lot of information this way. The other option would be running Qspec a bajillion times with all the different combinations.

Here are the samples I have. Number in the parenthesis is the sample number. I have technical replicates for each sample which are labeled with an "A" following the sample number.

Day 1: pooled larvae (1)

Day 3: 23C Silo 2 (3), 23C Silo 3 (4), 29C Silo 9 (8)

Day 5: 23C Silo 2 (11), 23C Silo 3 (12), 29C Silo 9 (16)

Day 7: 23C Silo 2 (19), 23C Silo 3 (20), 29C Silo 9 (24)

Day 9: 23C Silo 2 (27), 23C Silo 3 (28), 29C Silo 9 (32)

Day 11: 23C Silo 2 (35), 23C Silo 3 (36), 29C Silo 9 (40)

Day 13: 23C Silo 2 (43), 23C Silo 3 (44), 29C Silo 9 (48)

Day 15: 23C Silo 2 (51), 23C Silo 3 (52), 29C Silo 9 (56)

See the [wiki](https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/2016-Oyster-Seed-experiment-23C-vs.-29C) for more info.

For the first Qspec run I could compare Silo 2 to Silo 3, considering all the sample days as replicates. 

Perhaps for the first run my 0 columns (for Silo 2) could be:
1, 1A, 3, 3A, 11, 11A, 19, 19A, 27, 27A, 35, 35A, 43, 43A, 51, 51A

And my 1 columns (for Silo 3) could be:
1, 1A, 4, 4A, 12, 12A, 20, 20A, 28, 28A, 36, 36A, 44, 44A, 52, 52A

And then run it two more times to compare Silo 2 to Silo 9 and Silo 3 to Silo 9.

**Comment by sr320** [comment]
Good question -
And I presume you are doing this but you should examine the Abacus output outside of Qspec.
Excel, R - NMDS etc. 
for others here is the file: https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417NSAF.tsv
See https://plus.google.com/u/0/106492099842577316500/posts/7gUDrcDw9AD
and Emma Geoduck paper for context and NDMS code etc....

To answer your question here.. What you suggest is fine - but  doing NMDS on all data is important, not only to determine if reps are consistent but to ID samples to compare with QSpec

**Comment by emmats** [comment]
Let me know if you need any more input from me. I agree with Steven that looking at the overall data structure first may help guide your qspec choices.
