### ISSUE TITLE
NMDS using Vegan Package in R

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#510]
Can someone provide more details on how to execute non-metric multidimensional scaling on the abacus output file? Am I using the values in the normalized spectral abundance factor [NSAF](https://raw.githubusercontent.com/sr320/nb-2017/master/C_gigas/data/ABACUS_output021417NSAF.tsv) column for the NMDS? I am not an R expert yet- I downloaded the vegan package and have been reading [Emma's geoduck paper](http://biorxiv.org/content/biorxiv/early/2016/12/28/094615.full.pdf) to learn about the process but it provides little detail on how accomplish this (at least for a novice like me). 

From Emma's paper
"Non-metric multidimensional scaling analysis (NMDS) was used to determine the similarity of technical replicates [Supporting Information 3](https://github.com/sr320/supp-geoduck-proteomics/blob/master/S3-technical-reps.pdf) using the vegan package in R v.3.2.3. NMDS was performed on log-transformed data using a Bray-Curtis dissimilarity matrix. As technical replicates clustered closely together and showed less variability than biological replicates [Supporting Information 4](https://github.com/sr320/supp-geoduck-proteomics/blob/master/S4-tech-vs-bio-reps-DDA.pdf), spectral counts were averaged across each sample (n=18)."

Carrying out an NMDS analysis will inform decisions on how to input our QSPEC sample data. If we find that the technical replicates cluster closely or even the different sampling dates cluster closely within each group then perhaps we can try to input the data as suggested in [Issue 509](https://github.com/sr320/LabDocs/issues/509)

Anyone have any good resources to learn about it? I found [this](https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/) which has been sort of helpful, but I guess I need a little more guidance.

**Comment by sr320** [comment]
A good place to start is simply trying to recreate Emma's NMDS from the paper.
See wiki for links
https://github.com/sr320/LabDocs/wiki/DDA-data-Analyses#5-nmds

to repo
https://github.com/sr320/supp-geoduck-proteomics

You should be able to take her starting data file, use her R code, and recreate NMDS. (A good way to learn)

**Comment by sr320** [comment]
Might also have a look at https://cran.r-project.org/web/packages/vegan/vignettes/intro-vegan.pdf

**Comment by seanb80** [comment]
This is also a good walkthrough of NMDS. https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/

**Comment by Ellior2** [comment]
I used the documentation of NMDS from [wiki](https://github.com/sr320/LabDocs/wiki/DDA-data-Analyses#5-nmds), @emmats [R code](https://github.com/sr320/supp-geoduck-proteomics/blob/master/R-code/geoduck-gonad-nmds.R), and her [data](https://github.com/sr320/supp-geoduck-proteomics/blob/master/data/Detected-geoduck-proteins.csv) as a guide for own analysis. [See notebook](https://ellior2.github.io/NMDS-analysis/)

I am trying to first determine how similar my technical replicates are. At first I started using the [Abacus file](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/DDA_2016/ABACUS_NUMSPECSTOT.csv) with the columns "_NUMSPECSTOT" and then realized I think I need to be doing it with the "_ADJNSAF" addendum instead so I made this [file](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/DDA_2016/Abacus_ADJNSAF.csv). In the [wiki](https://github.com/sr320/LabDocs/wiki/DDA-data-Analyses#5-nmds) it says:

"NMDS: Technical replicates should be examined. Example might be available using this R code see line 68. Original table here. For NMDS, heat maps, etc: the ADJNSAF data column should be used."

But is the first step calculating the coefficient of variation between technical replicates? And in doing this first step, am I using the "_ADJNSAF" column? In Emma's data she used in the R code the columns say "tot spectra sample ID".

This is my box plot using the "ADJNSAF" columns.... seems messy and I need to fix the y-axis.
![image](https://cloud.githubusercontent.com/assets/20071030/23827615/018d322a-066c-11e7-9d39-5b2e43279c73.png)

**Comment by emmats** [comment]
Why are you making a box plot? I do not usually calculate CV for DDA data. I only do it for SRM. 

You can use either nsaf or spec counts for the nmds at this stage. Your final nmds will be with nsaf.

**Comment by Ellior2** [comment]
@emmats 
This is copied from [your R code](https://github.com/sr320/supp-geoduck-proteomics/blob/master/R-code/geoduck-gonad-nmds.R):

#NMDS of all bio and tech reps as individual points   
#log(X+1) transform data    
reps.t<-t(gd.reps)   
reps.tra<-(reps.t+1)   
reps.tra<-data.trans(reps.tra, method='log', plot=F)

I installed the following packages: Raster, Vegan, RColorBrewer

Is "data.trans" a function of one of these packages? It is not recognized when I run it in R.

This is [my R Code](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/DDA_2016/NMDS.R)

**Comment by emmats** [comment]
data.trans is in the biostats package, which you need to load as a source file. I believe I gave it to you previously, but here is the help file. I can't attach the R source file in github so I will email it to you. I also recently sent it to Laura and Yaamini.
[biostats help.pdf](https://github.com/sr320/LabDocs/files/855597/biostats.help.pdf)

**Comment by kubu4** [comment]
@emmats - What modification(s) to [your R code](https://github.com/sr320/supp-geoduck-proteomics/blob/master/R-code/geoduck-gonad-nmds.R) would you make in order to source/load the Biostats Package (i.e. can you post it here and/or update [your R code](https://github.com/sr320/supp-geoduck-proteomics/blob/master/R-code/geoduck-gonad-nmds.R))?

**Comment by emmats** [comment]
The second line says "load libraries for biostats and vegan". So at that point, I would load the biostats library through file -> source file and then I would select the biostats.R file.

**Comment by kubu4** [comment]
So, is there a way to do this in your R code instead of using the R Studio GUI?

**Comment by emmats** [comment]
This is the best way I have found of doing it. When I do command-shift-O on my computer (shortcut for loading a source file) it makes R freeze and crash 99% of the time.

**Comment by emmats** [comment]
R code has been edited to reflect adding a source file.

**Comment by Ellior2** [comment]
Wowza!! This is really cool!
![image](https://cloud.githubusercontent.com/assets/20071030/24220958/99f69f74-0f09-11e7-8612-dd7ef8e3f74e.png)

Not sure if you can see it all that well but sample numbers correspond to this list [here](https://ellior2.github.io/NMDS-analysis/). I will work on making a less-ugly visual, but I was just too excited to not share. Here is my [R code](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/DDA_2016/NMDS.R)

**Comment by Ellior2** [comment]
Wow and those outliers there to the right are from Silo 2 (23C) at Day 11 and Day 13 which is the one where we saw very high mortality! I think we are on to something! Super interesting.
