### ISSUE TITLE
Getting Familiar with Skyline for DIA Analysis

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#511]
I'm reading through this [Skyline DIA tutorial](https://skyline.ms/wiki/home/software/Skyline/page.view?name=tutorial_dia). @emmats, the tutorial shows how to work with .raw files (e.g. see snapshot from pg. 24 below). Do you have any Evernote entries, or other resources, showing the workflow using Pecan's output .blib files?

![image](https://cloud.githubusercontent.com/assets/17264765/23592708/f0b4be2a-01b9-11e7-84b6-b4bd32f700e8.png)

**Comment by sr320** [comment]
Presume you have looked at
https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses#skyline

**Comment by laurahspencer** [comment]
Yes; I'm curious if there are more Pecan-specific steps outlined somewhere - if documentation exists it would be helpful to be able to take a look at the post Pecan-specific workflow. If not, that's okay too. 

![image](https://cloud.githubusercontent.com/assets/17264765/23593055/8d17f04e-01be-11e7-89da-ec963c43c258.png)

Side-note: GitHub now supports simply pasting an image into this text box - it uploads the file to the cloud!

**Comment by kubu4** [comment]
Out of curiosity, have you tried importing a .blib file into Skyline and see what happens?

**Comment by emmats** [comment]
There are tutorials on the skyline website that are not pecan specific but should be helpful all the same. I believe there is a PowerPoint supplemental file for the geoduck paper that may be useful here. @sr320 can point you towards that. I have some long and messy notebook entries that I can share if necessary.

**Comment by laurahspencer** [comment]
We know about the tutorials/webinar of tutorials online, but the PowerPoint and your notebook entries would both be great to see, if possible.  Emma - are they accessible online somewhere? Would it be possible for you to send us links?  Thanks!

**Comment by sr320** [comment]
Here is info including slidedeck https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/MS-Tutorial

@laurahspencer it would be good to be very specific in your issue. 
For instance - "I opened up pecan output in Skyline, here is what it looks like.. I do not know what to do next"
