### ISSUE TITLE
Add mac mini to Lab Software wiki

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#513]
And add instructions to boot into Windows (via Bootcamp).

**Comment by seanb80** [comment]
All software added and updated on the Lab Wiki. Still trying to figure out how to get bootcamp to reliably behave with a wireless keyboard.

**Comment by sr320** [comment]
Do not worry about wireless keyboard that is why I have wired keyboard hooked up. Plus new windows machine will reduce reliance on that  machine for windows
