### ISSUE TITLE
Install/test Linux package of MSconvert?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#516]
Going to throw this out there as an option to reduce reliance on Windows. There's a Linux package that runs MSconvert: [libpwiz-tools](http://manpages.ubuntu.com/manpages/trusty/man1/msconvert.1.html)

That link is just the overview/usage of the program. Should be able to download/install using:

```sudo apt-get install libpwiz-tools```

**Comment by seanb80** [comment]
I was pretty sure I'd tried this before, but tested it again to be sure. It's not an MSConvert issue, it's an issue where Thermo only produced the .DLL files to convert their proprietary .raw format to .mzML for Windows

<img width="750" alt="screen shot 2017-03-07 at 11 46 03 am" src="https://cloud.githubusercontent.com/assets/10619258/23674786/f5c931fc-032b-11e7-990b-651e03f0df6c.png">
