### ISSUE TITLE
Update on pecan progress, and example logs

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#517]
FYI I was finally able to get onto Emu today - see my latest notebook entry for details: https://laurahspencer.github.io/LabNotebook/Pecan-Status/

I viewed some Pecan and Percolator logs, and checked on the progress. Bad news is that there is still a long queue, and there is a recently generated error in a few Percolator logs. 

Anyone have any insight into the Percolator error that was generated (see lab notebook entry)?

Also, it looks like 1-2 data files are being processed / day.  Progress is very slow.  I don't want to interrupt it, but perhaps it's worthwhile for me to run Pecan on just 1 or 2 files using Roadrunner to get some data to work with this week ... ?

**Comment by sr320** [comment]
Will decide tomorrow AM if we want to restart with smaller subset.

Keeping in mind others time who might be able to assist. 
If there is an error message needs attention, put that message in the issue (as markdown not image).
