### ISSUE TITLE
Purchase a PC Desktop

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#519]
Lets purchase a desktop

I will suggest 
https://www.amazon.com/dp/B011ZB45LM/ref=cm_sw_r_cp_api_pOLNybD8SRQYK
```
Number of Processors Supported:1 / Number of Processors Installed:1 / Processor Manufacturer:Intel / Processor Type:Xeon
Processor Core:Quad-core (4 Core) / Processor Speed:3.20 GHz / Maximum Turbo Speed:3.60 GHz / Cache:8 MB
64-bit Processing:Yes / Hyper-Threading:No / Chipset Manufacturer:Intel / Chipset Model:C226
Maximum Memory:32 GB / Memory Technology:DDR3 SDRAM / Memory Standard:DDR3-1600/PC3-12800 / Number of Total Memory Slots:4
Hard Drive Interface:Serial ATA / Hard Drive RPM:7200 / Optical Drive Type:No / Controller Type:Serial ATA
```

But open to suggestions

**Comment by kubu4** [comment]
This is the same as above, but comes with a 1TB HDD (it's unclear if the one @sr320 linked above comes with a HDD) and 8GB of RAM:

[https://www.amazon.com/Dell-Flagship-PowerEdge-E3-1225-Operating/dp/B01LKQJCBK/ref=pd_sbs_147_3?_encoding=UTF8&pd_rd_i=B01LKQJCBK&pd_rd_r=RSVR54CNZKST5DQQKZA2&pd_rd_w=g9AKQ&pd_rd_wg=Y59HO&psc=1&refRID=RSVR54CNZKST5DQQKZA2](https://www.amazon.com/Dell-Flagship-PowerEdge-E3-1225-Operating/dp/B01LKQJCBK/ref=pd_sbs_147_3?_encoding=UTF8&pd_rd_i=B01LKQJCBK&pd_rd_r=RSVR54CNZKST5DQQKZA2&pd_rd_w=g9AKQ&pd_rd_wg=Y59HO&psc=1&refRID=RSVR54CNZKST5DQQKZA2)

**Comment by kubu4** [comment]
Never mind my comment about being unclear if @sr320's choice comes w/HDD; it does.

**Comment by kubu4** [comment]
I vote we just go ahead and go with @sr320's suggestion and spend additional $170 to add 16GB RAM.

**Comment by seanb80** [comment]
We could go with an older dual CPU precision workstation with a ton of memory. Something like below. Would just need a hard drive of sufficient size, which we may have lying around?

https://www.amazon.com/gp/aw/d/B00T509QAG/ref=mp_s_a_1_4?ie=UTF8&qid=1488993781&sr=1-4&refinements=p_n_feature_five_browse-bin%3A13580787011&pi=AC_SX236_SY340_QL65&keywords=dell+precision+workstation+tower+dual+xeon&dpPl=1&dpID=41aZCPT2YsL&ref=plSrch

**Comment by seanb80** [comment]
Oops. I meant the below link, app won't let me edit however. 

https://www.amazon.com/gp/aw/d/B00T502T3W/ref=mp_s_a_1_6?ie=UTF8&qid=1488993781&sr=1-6&refinements=p_n_feature_five_browse-bin%3A13580787011&pi=AC_SX236_SY340_QL65&keywords=dell+precision+workstation+tower+dual+xeon&dpPl=1&dpID=41aZCPT2YsL&ref=plSrch

**Comment by kubu4** [comment]
I like @seanb80's suggestion.

**Comment by kubu4** [comment]
We used to get computers from Surplus... 😄

**Comment by sr320** [comment]
Show me a new dual CPU precision workstation with a ton of memory.

**Comment by seanb80** [comment]
<img width="704" alt="screen shot 2017-03-08 at 12 16 45 pm" src="https://cloud.githubusercontent.com/assets/10619258/23722177/51cc8ce2-03f9-11e7-84e2-d26b5b52e7f2.png">

Gives us 2x 8-core Xeon CPUs, 64gb ram, and 2tb HDD.

**Comment by sr320** [comment]
Please purchase 
https://www.amazon.com/gp/aw/d/B00T502T3W/ref=mp_s_a_1_6?ie=UTF8&qid=1488993781&sr=1-6&refinements=p_n_feature_five_browse-bin%3A13580787011&pi=AC_SX236_SY340_QL65&keywords=dell+precision+workstation+tower+dual+xeon&dpPl=1&dpID=41aZCPT2YsL&ref=plSrch

on 63-4279
