### ISSUE TITLE
Run one of Laura's Samples on Roadrunner

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#521]
To see if a similar error message arises.

**Comment by laurahspencer** [comment]
Sean- in heading to Manchester and unable to update the input files necessary for this test run. Could you? Isolation scheme and database files should be same, but the path .txt files need updating.

**Comment by seanb80** [comment]
I can! Working on it now. Will update soon.

**Comment by seanb80** [comment]
Ok, update: It works. Sort of.

 It looks like the no MS2 scans error is a little more nuanced than originally thought. When it says no MS2 scans what it really means is "No MS2 scans at the given M/Z ratio window". 

Laura's data produced the same error when I used 405-410 as the window. I opened it up to 510-615 and it seems to be working happily.

Will check with Yaamini's data  now.

**Comment by laurahspencer** [comment]
Thank for running this and for the update @seanb80! For posterity, here's sean's [reasoning](https://genefish.wordpress.com/2017/03/08/proteomics-pt-3/) for using the specified 510-615 M/Z ratio window.

**Comment by seanb80** [comment]
Just a heads up. Pecan finished running. It took 10 hours to finish the three concurrent windows of a single sample. Will get the blib processed and uploaded asap.

**Comment by yaaminiv** [comment]
Some notes for posterity/so I don't have to figure it out again in the future. First, `pecanpie` adds a -Q argument to the percolator command. That doesn't exist in the current release build, so it will need to be removed.

Secondly, and this will likely not be as much of an issue when we get to real data sets, percolator has some requirements for the ability to detect directionality in the training data set it chooses. This requires some number of true positives to be detectable in the subset it chooses as training data. The three windows of one sample wasn't enough using the stock FDR level of 0.01, so I had to change that to 0.10. The error/documentation isn't particularly intuitive and the current implementation requires both the -F and -t flags to be set to 0.10 per [https://github.com/percolator/percolator/issues/179](this issue).

upshot of it all, percolator is finished and pecan2blib is going through now!

**Comment by seanb80** [comment]
Hah! Apparently Yaamini left herself logged in to Roadrunner on Github, oops! That's really me.

**Comment by seanb80** [comment]
Results of the 3 window, 1 sample run here. in blib format. 

[Geoduck-test.blib.zip](https://github.com/sr320/LabDocs/files/831979/Geoduck-test.blib.zip)

**Comment by sr320** [comment]
Thanks!
