### ISSUE TITLE
Rhonda's thesis- Take 3

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#522]
Benoit and I were just talking and think we will have surplus larvae coming up next week or week after that we can use for my thesis settlement experiment. 

I think all I will need are 
- 3 boxes of 0.7 Glass Microfiber Filters Gf/F Diameter 47mm CAT No. 1825-047 Qty:100 (https://www.amazon.com/Whatman-1825-047-Microfiber-Binder-Diameter/dp/B00394FCEI/ref=sr_1_2?ie=UTF8&qid=1489014158&sr=8-2&keywords=glass+microfiber+filters+whatman+GF%2FF) or 
(https://www.coleparmer.com/i/whatman-1825-047-gf-f-glass-microfiber-filters-0-7um-4-7cm-100-box/0664891)
-1 box of 0.22 Millipore Type GPWP filters 47mm Qty:100
(https://www.emdmillipore.com/US/en/product/Millipore-Express-PLUS-Membrane-Filter,-polyethersulfone,-Hydrophilic,-0.22%C2%A0%C2%B5m,-47%C2%A0mm,MM_NF-GPWP04700)
- Gallon of etOH
- Nanopure
- TCA
- 1L- pH7.5 PBS

I will get liquid nitrogen- can I use a budget number for this? We have a dewar.

**Comment by sr320** [comment]
sure 61-0221

We should discuss a game plan sometime soon..

**Comment by Ellior2** [comment]
Yes I agree. Are you available via phone tomorrow? My internet capabilities right now are pretty limited for anything like a google hangouts. I'd like to get these filters ordered ASAP, as they may take a week or more to get here. I think you guys have TCA and reagents for the PBS on hand...

**Comment by Ellior2** [comment]
On second thought, I am probably just going to buy the liquid nitrogen at Airgas in Bremerton, so not sure how I can use your budget number.

**Comment by sr320** [comment]
For LN - you pay for then get reimbursed from grant

**Comment by kubu4** [comment]
To clarify, the only things needed for purchasing are the two sets of filters?

**Comment by Ellior2** [comment]
We are looking into more sizes of filters and a new filtering device (which may end up accommodating different diameter filters). We would like to be able to capture potential orchitophyrid ciliates which according to this paper by Elston et al. 1999, are anywhere from 25-50um.

http://www.sciencedirect.com.offcampus.lib.washington.edu/science/article/pii/S0044848698005122

**Comment by kubu4** [comment]
To clarify, the only things needed for purchasing from the list you provided are the two sets of filters?

**Comment by Ellior2** [comment]
As far as our third filter goes: I found a [membrane filter](http://www.gelifesciences.com/webapp/wcs/stores/servlet/catalog/en/GELifeSciences-us/products/AlternativeProductStructure_21483/28414920) with a pore size of 12um. This could be our top filter to catch potential ciliates, then we will go through the 0.7um to remove other stuff before retaining bacteria on the 0.22um filter. I could fix and keep all 3 filters...

I think you guys ordered a whole new bottle of TCA last summer at the lab. If that is unused, and we are still able to make 1L of PBS then we should be good on reagents.

**Comment by sr320** [comment]
I would contact Millipore first to confirm best hardware before purchasing
filters, size might change?

**Comment by Ellior2** [comment]
The one I sent earlier via email: https://www.emdmillipore.com/US/en/product/In-Line-Filter-Holder,MM_NF-C258#overview is still the same 47mm diameter sizes we have been using. These are the biggest diameter filters I have seen and should be the most effective as they allow a bigger surface area to prevent clogging. But I agree with holding off on purchasing filters until we know what type of device we will have. Millipore technical assistance is only available M-F. I will call Monday.

**Comment by kubu4** [comment]
The filters listed in the first post have already been ordered...
