### ISSUE TITLE
Generate new Pecan input (oysters)

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#523]
Provide revised Pecan input for the 5 samples 
Attach here (or URL)

See https://github.com/sr320/LabDocs/issues/520 
https://github.com/sr320/LabDocs/issues/520#issuecomment-285205648
Make sure proteome is digested.

@seanb80 will run Pecan on said files Thursday

**Comment by yaaminiv** [comment]
Will do! I have the digested proteome, but I did not use that in my analysis last time. However, I did not take screenshots of this process. Should I redigest my proteome and take screenshots for reproducibility purposes, or should I just proceed?

**Comment by yaaminiv** [comment]
Everything should be ready to go now. I removed extraneous columns from the digested proteome file I had and used the isolation scheme Emma provided. I did not modify this isolation scheme at all. It was already properly formatted and sent as a .csv.

[Lab notebook entry (for reference)](https://yaaminiv.github.io/PECAN-Update-4/)

Everything for the analysis can be found in [this folder in OWL](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_3_20170308/).

It is also fully set up in Roadrunner. The folder with my inputs is "DNR_PECAN_Run_3_20170308" in the Documents directory.

![screenshot from 2017-03-08 22-55-43](https://cloud.githubusercontent.com/assets/22335838/23739301/bdb7baae-0452-11e7-86bd-ef623da15729.png)

[digested background proteome](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_3_20170308/Combined-digested-edited-gigas-QC_Mass400to6000.tabular)
[mzML file path list](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_3_20170308/2017-03-08-mzML-file-path-list.txt)
[background peptides path list](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_3_20170308/2017-03-08-background-peptides-path-list.txt)
[isolation windows](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_3_20170308/2017-03-03-isolation-windows.csv)
