### ISSUE TITLE
Calibrate NanoPure

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#529]
NIST calibration module is in 213 drawer 47.

NanoPure manual is in 213 drawer 49.

**Comment by seanb80** [comment]
So I finished the calibration, but it still returns the same "Error 4", requesting calibration with the NIST module. According to tech support, this model doesn't have specific errors for failed PC Boards, and so likely it's a failed main or meter board. 

There is no good way to test which one it is beyond buying a new board (at a cost of 800/ea) and seeing if replacement fixes the problem. 

The FSH hike for nanowire water will have to continue.
