### ISSUE TITLE
Swinnex filters

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#532]
I made this set up today. There is only one in-line Swinnex filter holder in this photo but once we get them all in I will be able to connect them directly together. I will work on making another set up so we can filter two samples at a time. This is going to be so efficient! The 4" PVC will hold 4L.

![image](https://cloud.githubusercontent.com/assets/20071030/23972503/48889fb8-098f-11e7-8242-4a64192caeb6.png)

Can we order these [Swinnex filter holders](https://www.emdmillipore.com/US/en/product/Support-filtre-Swinnex%2C-47%C2%A0mm,MM_NF-SX0004700) directly to the hatchery? I called Millipore and they verified that it comes in a pack of 8.

Can we also order one pack of these filters to the hatchery?http://www.gelifesciences.com/webapp/wcs/stores/servlet/catalog/en/GELifeSciences-us/products/AlternativeProductStructure_21483/28414920

Thanks Sam!

**Comment by kubu4** [comment]
Before I order the GE filters, just wanted to provide a heads up that estimated delivery is 4/24/2017. 

Please confirm whether or not you'd still like me to order them.

**Comment by sr320** [comment]
My guess is they are needed sooner.

61-0221

**Comment by kubu4** [comment]
Agreed.

**Comment by kubu4** [comment]
Wait! Are the Swinnex filter holders intended to be used with the GE filters? Or with the filters that were delivered this week?

If the former, should I wait to order the Swinnex filters?

What say you @Ellior2 ?  :)

**Comment by Ellior2** [comment]
The swinnex filter holders will hold all three filter types. The two that your ordered last week and the GE ones listed in this issue.

**Comment by kubu4** [comment]
So, should I place the order for the Swinnex filter holders?

What about the GE filters?

**Comment by Ellior2** [comment]
Wow 4/24 is a ways out! I'll look at some other sources. How soon is the delivery date on the swinnex filter holders?

**Comment by kubu4** [comment]
Swinnex - ~3/20/2017

**Comment by Ellior2** [comment]
Ok let's definitely order the swinnex filter holders and I'll look into other suppliers of the GE filters. Thanks!

**Comment by Ellior2** [comment]
Here are some other options but I'm not sure about the best material the filter should be made of for DNA extraction.

Here is a 10um pore size filter made of nylon:https://scientificfilters.com/store/nylon-membrane-filters-sf14756?gclid=CKnqh4zj2dICFRBEfgodooAFSg

Here is an 8um pore size filter made of polyester: http://www.sterlitech.com/polyester-membrane-filter-pet8047100.html

Here is a 5um pore size filter made of polyvinylidene fluoride: http://www.emdmillipore.com/US/en/product/Durapore-Membranfilter,MM_NF-C7631?ReferrerURL=https%3A%2F%2Fwww.google.com%2F#specifications

The choices are overwhelming. Do you have any thoughts steven? Should we get Brooke's input?

**Comment by Ellior2** [comment]
Can we please order one pack of these to the hatchery? http://www.emdmillipore.com/US/en/product/Durapore-Membran%2C-PVDF%2C-hydrophil%2C-5%2C0%C2%A0%C2%B5m%2C-47%C2%A0mm%2C-wei%C3%9F%2C-Netz,MM_NF-SVWG04700

**Comment by kubu4** [comment]
@Ellior2 - Quick reminder. For all items shipped directly to the hatchery, please sign and date the packing slips. Please return them to me as soon as possible, as I am required to submit them for budget reconciliation. Thanks!
