### ISSUE TITLE
Something amiss with C virginica NGS data 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#533]
Looking at virginica data I found a fault in the DMP

https://github.com/sr320/LabDocs/wiki/Data-Management#ngs-data-management-plan

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Nightingales_-_Google_Sheets_and_nightingales_1E7AD99F.png" alt="Nightingales_-_Google_Sheets_and_nightingales_1E7AD99F.png"/>

6 lines in sheet but lots of files - 
readme explains a bit, but DMP needs to address this (and not clear why two files per library if SE)

**Comment by kubu4** [comment]
There are multiple files per library because the sequencing facility provided them this way. I'm guessing the output files were split based on size (~1.5GB). So, if a particular library yielded more than 1.5GB of data, then the data was written to multiple files.

**Comment by kubu4** [comment]
I updated Nightingales to include the additional files for the demultiplexed set (e.g. 2112_lane1_ATCACG_L001_R1_001
2112_lane1_ATCACG_L001_R1_002
2112_lane1_ATCACG_L001_R1_003)

@seanb80 - Can you please at the "NoIndex" files to Nightingales when you have the chance?

**Comment by seanb80** [comment]
Added.
