### ISSUE TITLE
RM 213 Hazardous Waste Pickup today

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#534]
Raymond from E.H.&S. would like to stop by this afternoon to RM 213 to pick up the hazardous waste boxes. 

Will someone be around to give him access to rm 213? 

I babysit all day Thursdays so I won't be around.

The boxes are on the bench and have labels on top stating that they are hazardous waste ready for pick up.

**Comment by kubu4** [comment]
If you can get him to commit to a time before 4PM, I can meet him over there at the set time.

**Comment by kubu4** [comment]
Actually, I have lab meeting from 2:30 - 3:30. Can't meet him during that time.

**Comment by grace-ac** [comment]
Ok, he just said he'll be able to be there by 2p. He'll be in marine
sciences at 1:30.

**Comment by sr320** [comment]
I am here - I will make sure 213 is open by 1:30 
thanks

**Comment by kubu4** [comment]
Thanks.
