### ISSUE TITLE
Skyline course July 24-28

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#536]
Just got this announcement- looks interesting. Anyone else interested in taking this summer course? @yaaminiv @laurahspencer 

@sr320 @emmats Are we going to do DIA for the 2017 experiment? I guess it probably depends on what we find with 2015/2016 info. DIA does require quite a bit more funding right? Steven do you know of funding opportunities for this course? 

From email:
 
Dear Skyline Users,
The Skyline Team and our invited instructors are pleased to announce the fourth University of Washington Targeted Proteomics Course on July 24 - 28, 2017 in Seattle, WA. The course schedule will address a range of targeted techniques using SRM, PRM, data independent acquisition (DIA/SWATH) and MS1 filtering, and topics like system suitability, plasma proteomics, statistical methods for designing and analyzing these experiments and, of course, learning to use Skyline software more effectively in your research.
The instructor list includes researchers and software developers with a wealth of combined experience in targeted and quantitative proteomics, and both using and creating Skyline to meet the needs of this research approach.  
Space is limited.  However, all applications submitted by the deadline of April 14, 2017 will be considered equally on the merits of the application.
Don't miss this opportunity. 99% of all 450+ participants worldwide have said they would recommend a weeklong course in targeted proteomics to their peers.
We hope you will join us.
Brendan MacLean, 
Skyline Project Lead 
Register Now! 
When: July 24 - 28, 2017
Where: Foege Building, University of Washington, Seattle
    (Meet at 9am Monday between Foege South and North)  (map) 
Cost: $400 academic, $900 industry
Apply by: April 14, 2017
Pay by: May 17, 2017
Participants: 30
Room & Board: Not included. 
Related Links: 
Course Schedule 
Instructor List

**Comment by sr320** [comment]
Sure - if it is relevant- I can put it on a grant.

**Comment by Ellior2** [comment]
Cool, yeah its probably only worth it if we are doing DIA for 2017.
