### ISSUE TITLE
Translation of Oyster proteomic File names

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#537]
Where would I find a key for the proteomic file names?

ie `2017_January_23_envtstress_oyster23.raw` 

Location, eel grass ?

**Comment by yaaminiv** [comment]
Having some trouble accessing any owl links so let's see if I can do this from memory...

[This](http://owl.fish.washington.edu/spartina/January_2017_DNR_Raw_Data/2017_January_23.csv) should be the link to the .csv file that maps sample numbers with the labelling scheme used to identify sample locations/eelgrass (i.e. links oyster23 with a sample ID)

And [here's my notebook entry](https://yaaminiv.github.io/First-Day/) with a list of sample IDs with the location/eelgrass condition.

I intend to condense all of the information into one spreadsheet once I can access owl links! Is there a problem accessing owl when you're not on a UW network?

**Comment by kubu4** [comment]
See pinned Google Plus post.

**Comment by yaaminiv** [comment]
Gotcha, I'll update this issue once owl is back online!

Yaamini Venkataraman
Graduate Student, Roberts Lab
School of Aquatic and Fishery Sciences
University of Washington, Seattle 98105
(408) 504-3603 | yaaminiv@uw.edu
