### ISSUE TITLE
Reagents for Coral Methylome assays

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#539]
We will be running ~ 60 coral samples in a similar manner that we did for last year for the NSF proposal. I believe @kubu4 did this based on @hputnam 's methods.? Elisa Method.

What do we need to run 60 samples, presuming we do not already have reagents..

**Comment by kubu4** [comment]
Is DNA already extracted?

**Comment by sr320** [comment]
I want to say yes we can ask them to send DNA, but I can confirm. Last time
did you start with DNA?

**Comment by kubu4** [comment]
Yes. We received DNA last time.

**Comment by kubu4** [comment]
For methylation quantification, we'll need:

2 x [MethylFlash Methylated DNA 5-mC Quantification Kit (Colorimetric) P-1034-96](http://www.epigentek.com/catalog/methylflash-methylated-dna-quantification-kit-colorimetric-p-2094.html?currency=USD&height=190&width=500&border=1&modal=true&random=1490049507422): $540 ea

**Comment by hputnam** [comment]
I would caution against this if they still contain symbionts.

**Comment by sr320** [comment]
Hold on a purchase until I confirm some stuff

**Comment by sr320** [comment]
Please go ahead and order 

2x P-1034-96 

On
65-2861

**Comment by sr320** [comment]
@kubu4 has this been ordered?

**Comment by kubu4** [comment]
No. I must've missed this! Will submit tonight... Sorry.

**Comment by sr320** [comment]
No rush - just thought you might have missed the go head...

**Comment by kubu4** [comment]
Definitely missed it. Doh!
