### ISSUE TITLE
Owl web directory will not render in browser

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#540]
I am still old schooling with index.php (not sure if this is related) but 
http://owl.fish.washington.edu/halfshell/

does not render my file links

**Comment by kubu4** [comment]
Removed index.php file and added .htaccess file. Directory listing now viewable for ```halfshelll```.

If you want to utilize PHP, I think it might be fixable. Currently using PHP 7.0; previous version was 5.4. Version change possible cause for breaking index.php functionality?

**Comment by sr320** [comment]
Thanks!
