### ISSUE TITLE
Gathering lab supplies for Taylor Hatchery

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#541]
Brent says he will be at UW on Monday 27th and then the hatchery on the 28th. I was wondering if I could have some help gathering up some supplies so he can bring them over next Tuesday.

~ 1 gallon etOH
~ 5 gallons of Nanopure
- TCA bottle from fridge
- 1L of PBS pH 7.5
- Any filters they may have arrived to the lab. I know Sam started sending them directly to the hatchery, but am not sure where the first filter purchase was sent to.

I really appreciate it. Thank you

**Comment by kubu4** [comment]
Look here for filter location: [Roberts Lab Inventory](https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit?usp=sharing)

Will you be here tomorrow? I could help you then.

**Comment by sr320** [comment]
Etoh - 190 proof ?

We have no Nanopure water (system is down)

TCA - which fridge? what are we looking for (size bottle?

PBS (where?)

**Comment by kubu4** [comment]
Nanopure can be filled in FSH 235. @seanb80 or I can show you.

We don't keep PBS. Will need to be made up.

**Comment by Ellior2** [comment]
Trichloroacetic Acid (TCA) is in Room 209 in refrigerator. It's a small bottle containing 100g. It was ordered 6/30/2016: https://cspc.admin.uw.edu/mychem/uwnetid/inventory/Inventory.aspx?Context=619995

Molecular grade etOH, 190 proof.

Sam made us the PBS last time. If it's a huge hassle, I can make a trip out there to make it. It'll probably have to be on a weekend.

**Comment by sr320** [comment]
We will not do TCA this year as per Brook- thus do not need. 

I would say 200 proof not 190 then

**Comment by Ellior2** [comment]
Will ethanol be used to preserve filters?

**Comment by sr320** [comment]
I do not think so, did you use it last year?

**Comment by Ellior2** [comment]
No, we used TCA. But the fact that now recommend 200 proof instead of 190 led me to believe I would use ethanol to preserve the filters instead...

**Comment by sr320** [comment]
I recommended 200 because in your response you indicated Molecular Grade,
(actually our 190 nor 200 is MG).
IF you asked for EtoH to dissolved TCA, then you no longer need EtoH.

**Comment by Ellior2** [comment]
Ok, it probably doesn't matter what grade now. I still need ethanol for sanitation purposes and for preserving oysters for microscopy.

**Comment by sr320** [comment]
Filters
PBS (thanks @kubu4)
Nanopure water ( 👍 @kubu4 )
And a big jug of EtOH are in the lab under the webcam.

**Comment by Ellior2** [comment]
Thank you all!!
