### ISSUE TITLE
Intermediate files from DDA pipeline

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#542]
@seanb80 I'm looking for the intermediate files from the last run you did for the 2016 P. oyster DDA pipeline or the command line output that might lead us to believe there was an error. We are seeing large discrepancies between our technical replicates and Emma thinks it's possible there could have been an error in the process of file merging. Can you please help me out with this? Thank you!

Please see https://github.com/sr320/LabDocs/issues/530

**Comment by seanb80** [comment]
I am in the process of uploading them to /scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates but there's ~100gb of files, so it will take a little bit. The process that was followed is outlined [http://rpubs.com/seanb80/237863](here) but I believe that I just ran the final Abacus step on Steven's /bioinfo/021417/ files. 

The Abacus code I used was `java -Xmx16g -jar /home/shared/abacus/abacus.jar -p ~/Documents/ProteomicsTest/Abacus-01.param`

If anything needs to be re-ran let me know and I can get it started.

**Comment by seanb80** [comment]
your files have arrived!

[http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/]()
