### ISSUE TITLE
identify c. gigas proteins with relevant go terms

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#545]
@sr320 here is the spreadsheet:

https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_Preliminary_Analyses_20170321/all-proteins-go-terms/skyline-proteins-go-terms.tabular

**Comment by sr320** [comment]
which column is coefficient of variation?

**Comment by yaaminiv** [comment]
ah i knew I forgot to do something...will do ASAP.

**Comment by sr320** [comment]
no prob
here is a  short list..
https://github.com/sr320/nb-2017/blob/master/C_gigas/analyses/YV-stress-short-list.tab

can you get cov for these.

**Comment by yaaminiv** [comment]
can do 👍

**Comment by yaaminiv** [comment]
/Users/yaamini/Documents/project-oyster-oa/analyses/DNR_Preliminary_Analyses_20170321/short-list-analysis/coefficient-of-variance-stress-short-list.txt

**Comment by yaaminiv** [comment]
https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_Preliminary_Analyses_20170321/short-list-analysis/coefficient-of-variance-stress-short-list.txt

**Comment by yaaminiv** [comment]
created REVIGO plots using the coefficient of variation and p-values from DAVID.

cv:
![cv](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_Preliminary_Analyses_20170321/short-list-analysis/REVIGO/coefficient-of-variation-biological-processes.png)

p-values:
![pvalues](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_Preliminary_Analyses_20170321/short-list-analysis/REVIGO/p-value-biological-processes.png)

left the windows open on chrome on genefish in case you wanted to check it out

**Comment by sr320** [comment]
I still think a list would be good and add variety
https://github.com/sr320/LabDocs/issues/545#issuecomment-288586988
