### ISSUE TITLE
Can't login to Owl

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#546]
![image](https://cloud.githubusercontent.com/assets/20071030/24261177/610a07be-0fb3-11e7-99a3-9b09ef100a20.png)

My password no longer works.

**Comment by Ellior2** [comment]
sorry! Just realized it's down!

**Comment by sr320** [comment]
Actually is not completely down, we just have loss credential info. 

@kubu4 can you set up an account for Rhonda?

Note you can access w/o creds @ http://owl.fish.washington.edu/trochophora/

**Comment by kubu4** [comment]
This is on the agenda for today.

@Ellior2 - Before I can do this, I please need to unblock the IP address from which you were trying to login from. Can you please post your IP address? You can figure out your IP bey Googling "what's my IP?"

**Comment by Ellior2** [comment]
Here is the one I am at right now: 70.199.147.144

However, it blocked me last night when I was at my house. I can update later with my home IP address

**Comment by kubu4** [comment]
Thanks.

That IP is unblocked.

You should receive an email with a new password. The system should require you to create a different password than the one sent in the email.
