### ISSUE TITLE
Add software to new Windows computer (woodpecker)

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#547]
All requests below are for the ```srlab``` account.

Please install various proteomics software on Windows computer (hopefully you know what the list of software is?).

Please install Microsoft Office (Word and Excel) on Windows computer (available from UW IT Software).

Please update [Lab Software wiki](https://github.com/sr320/LabDocs/wiki/Lab-Software) to reflect any software additions.

**Comment by seanb80** [comment]
Installed Office, Skyline, Proteowizard, and Protein Digestion Simulator.

**Comment by yaaminiv** [comment]
Could we also get MSConvert on Woodpecker as well? If it's already there, it's not on the wiki!

**Comment by seanb80** [comment]
MSConvert comes packaged in Proteowizard so technically it's in the wiki, though I'm not sure how you want to deal with the special version you have now, or where it's installed.

**Comment by yaaminiv** [comment]
It's in the oystertest folder, but I was going to move it into the ProteoWizard folder once we figured out if it works or not.
