### ISSUE TITLE
Can't log in to Owl web portal: Failed 2-step verification setup wizard

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#548]
Trying to log in to Owl with the new credentials brings up a 2-Step Verification Setup Wizard and after hitting next I get an "Operation Failed" error. Is there a way around this?

<img width="666" alt="screen shot 2017-03-24 at 8 50 10 am" src="https://cloud.githubusercontent.com/assets/10619258/24302162/fa1522e8-106e-11e7-92cf-e8e24da947bc.png">

<img width="656" alt="screen shot 2017-03-24 at 8 50 18 am" src="https://cloud.githubusercontent.com/assets/10619258/24302177/ff82fe6c-106e-11e7-8f23-d921fbd83061.png">

**Comment by kubu4** [comment]
Removed 2-factor requirement. You should be able to login.
