### ISSUE TITLE
Set up owl account for Kaitlyn

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#549]
Please set up an account for @kaitlynrm 
her email krmitch7@uw.edu

with a home directory inside `scaphopoda`

@kaitlynrm - see https://github.com/sr320/LabDocs/wiki/Data-Management#daily-data-on-owl
regarding access and use

**Comment by kubu4** [comment]
@kaitlynrm - You're all set up! You should have received an email from Owl (the server) with a username/password. You'll have to change that password when you first login.

Let me know if you run into any issues (or, just post a GitHub issue!).

**Comment by kaitlynrm** [comment]
Perfect, thank you! I got the email and will post an issue if I have any problems (or possibly questions).
