### ISSUE TITLE
Genewiz RNAseq methods

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#55]
@kubu4 - could you add proper language for methods for Claire's RNA-seq samples - i.e. kit name 

https://github.com/sr320/paper-Temp-stress/blob/authorea/methods-rna.md

**Comment by kubu4** [comment]
Will contact GeneWiz for info.

That link 404's.
Is this the correct one?

https://github.com/sr320/paper-Temp-stress/blob/authorea/methods-rna2.md

**Comment by sr320** [comment]
thanks - yep 
these authorea branches are killing me -

Should also be at https://www.authorea.com/users/3858/articles/18000/master/file/methods-rna2.md
