### ISSUE TITLE
Develop April / May Plan for Manchester

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#552]
Please develop a draft plan for the oysters over the next couple of months, with a particular emphasis on hatchery resources (i.e. space, effort)
I am planning to go over this at the Hatchery meeting on Wednesday.

Please drop URL below. Thanks

**Comment by laurahspencer** [comment]
Started a draft to begin getting down rough timeline/thoughts. Please add/update as you see fit: https://docs.google.com/a/uw.edu/document/d/1W13BF8ufEXkbLFZM5VK62OU_kx9HxbFHnwo14s5kaQc/edit?usp=sharing
