### ISSUE TITLE
Ethanol resistant tube labels

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#553]
Please purchase enough labels for at least 520 tubes, need by Friday so Grace can apply them, and bring out to Manchester on Saturday.

**Comment by kubu4** [comment]
@seanb80 - Could you please post the spreadsheet template you used in the Friedman Lab for printing on these labels (VWR Cat# 89097-572)?

**Comment by seanb80** [comment]
I'm trying to figure out how to get word to export a custom label template for use by others, but for now, here are the settings required to duplicate that template using the Word Template Wizard. 

<img width="408" alt="screen shot 2017-04-04 at 10 21 52 am" src="https://cloud.githubusercontent.com/assets/10619258/24670051/7aeadfce-1921-11e7-8b4b-446175d1885e.png">

**Comment by laurahspencer** [comment]
Sam - do you anticipate these arriving in time to use on Friday?

**Comment by kubu4** [comment]
Estimated delivery is today.

**Comment by kubu4** [comment]
@grace-ac - Be sure to print a test sheet on regular paper to verify that the print layout is correct.
