### ISSUE TITLE
Microscope cell phone adapter

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#556]
If we're staying with cell phones for the camera, [this](https://www.amazon.com/Gosky-Universal-Phone-Adapter-Mount/dp/B013D2ULO6/ref=sr_1_1?ie=UTF8&qid=1491326269&sr=8-1&keywords=cellphone+microscope+adapter) seems like a good option. It allows for the cell phone camera to rest directly on the eyepiece and looks like it'd be able to get a full picture. Compatible with all cell phones as it is adjustable. 

My problem with the snap zoom is that the camera on my cell phone (iPhone 5 without the case) never got close enough to the eyepiece, so the image looks like this: 
![17690819_10154436843035814_583770966_n](https://cloud.githubusercontent.com/assets/14934314/24670624/a12d0098-1923-11e7-988c-8715d5d4779d.jpg)
Which is why when I did all the microscope image-capturing, I chose to hold the camera myself.

**Comment by sr320** [comment]
Go ahead submit issue to order a few options including the one you link to .
