### ISSUE TITLE
Microscope cell phone adapter options

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#557]
Best-seller on Amazon. $20: https://www.amazon.com/Gosky-Universal-Phone-Adapter-Mount/dp/B013D2ULO6/ref=sr_1_1?ie=UTF8&qid=1491326269&sr=8-1&keywords=cellphone+microscope+adapter

Another design $9: https://www.amazon.com/WinnerEco-Cellphone-Telescope-Monoculars-Microscope/dp/B01LCP59AM/ref=sr_1_3?ie=UTF8&qid=1491334097&sr=8-3&keywords=cellphone+microscope+adapter

All the rest of the top sellers are the same design as the Gosky Universal Phone Adapter (top link)

@kubu4 also mentioned that Friedman lab has microscope(s?) with permanently mounted cameras that are a potential option as well.

**Comment by Ellior2** [comment]
I have the first one you posted here. It works pretty well but takes several minutes to get it situated just right. Once you have it properly mounted though its good to go. I use it with my IPhone6.
