### ISSUE TITLE
Order: fine nose tweezers

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#558]
Please purchase 2 of these [fine nose tweezers from Amazon](https://www.amazon.com/Splinter-4-5-Inch-Serrated-Stainless-Precision/dp/B00HB53JEG/ref=sr_1_20?dd=sPRtUokNJ5KQL-r1Lb2P4Q%2C%2C&ddc_refnmnt=pfod&ie=UTF8&qid=1491347313&sr=8-20&keywords=fine+forceps&refinements=p_97%3A11292772011) for use at the Hatchery this Saturday. Prime 1-day shipping should be available.

**Comment by sr320** [comment]
61-0221

**Comment by laurahspencer** [comment]
Thank you!!!

**Comment by kubu4** [comment]
Bad news. These are the forceps we received:

![img_20170406_134319](https://cloud.githubusercontent.com/assets/4514104/24774862/7047c870-1acf-11e7-9fa9-46ae69a79581.jpg)

Oddly, the info on the tag matches exactly what is listed on Amazon. However, the contents clearly don't match the description. I'll be returning them.

**Comment by sr320** [comment]
I would say stick to fisher / VWR etc for that kind of stuff
We should have nice tweezers somewhere

**Comment by kubu4** [comment]
Agree with your first point, but not enough turnaround time was available.

Also agree with your second point, but when they get taken out to the field (or hatcheries), they frequently "disappear" forever...

**Comment by laurahspencer** [comment]
We have lots of tweezers at Manchester but they are not fine-nosed; Sam I
sent you an email with a photo of a pair that's PSRF has that work great.
Whats the issue with the ones that arrived?

**Comment by laurahspencer** [comment]
Oh- it's that they are enormous?

**Comment by sr320** [comment]
Where are tweezers in the lab (did not see on inventory sheet)?

**Comment by kubu4** [comment]
209 7 (search for forceps)

**Comment by laurahspencer** [comment]
This was a blessing in disguise! We will use these extremely long forceps to flash freeze tubes in dry ice/ethanol bath whilst keeping our fingers out of harms way.  I took them!
