### ISSUE TITLE
Oly PacBio DMP suggestions?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#559]
Currently, each SMRT cell has a data folder associated with it. We ran 10 SMRT cells worth of sequencing. Each SMRT cell folder contains 20 sub-directories and 127 files; most of it is metadata related to the sequencing. 

However, there are a few .h5 files for each SMRT cell and a ```filtered_subreads.fastq``` file for each SMRT cell. These are likely the types of files that we would link to in the DMP.

The directory structure currently is: ```owl/nightingales/O_lurida/20170323_pacbio/SMRT_cell_data_folder_n```

Should we consider moving the .h5 and/or the fastq files out of this subdirectory into ```owl/nightingales/O_lurida/``` to be consistent with the DMP?

OR

Should we leave the directories as they are and point to those files types in their current locations?

**Comment by kubu4** [comment]
@seanb80 provided this link on Google Plus last week and I'm putting it here for posterity: [https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Data-files-you-received-from-your-service-provider](https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Data-files-you-received-from-your-service-provider)

After some brief discussion, @seanb80 suggested that all ```.h5``` and ```.fastq``` files are the "core" sequence data files that are used/needed for analsyis.

Maybe we should just add those file types to the DMP?

**Comment by sr320** [comment]
I take it this is resolved?
