### ISSUE TITLE
Download SRA data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#560]
Download C gigas SRA data that is methylation related- not from our own lab.
Download to your directory in Scaphapoda

**Comment by grace-ac** [comment]
@seanb80 did it and showed me the process! thank you Sean! 

[Folder](http://eagle.fish.washington.edu/scaphapoda/index.php?dir=Grace%2FSRA+Data+-+C.+gigas+methylation%2F)

**Comment by kubu4** [comment]
It would be helpful if the process was detailed in your notebook.

**Comment by seanb80** [comment]
http://rpubs.com/seanb80/267942 Grace gets to make the notebook post though!

**Comment by kubu4** [comment]
@seanb80 - Why did you put this data on Eagle?

**Comment by seanb80** [comment]
Because grace said to put it in her directory there.

**Comment by grace-ac** [comment]
Because i was told to put it there :)

**Comment by kubu4** [comment]
On Eagle?

I believe you, but the reason I questioned it is Eagle hasn't been used for any active projects in a very long time (because it's nearly full, as @seanb80 noticed). So, I was surprised to see new data going there.

**Comment by grace-ac** [comment]
Yup! That's the only place I am aware of that has a folder of mine in
scaphapoda!

**Comment by sr320** [comment]
Grace said owl/scaphapoda is for newbs, she has legacy status:)

**Comment by yaaminiv** [comment]
Just looking at the folder, there seems to be only one .fastq file (SRR5085013). Was there a problem downloading the other files?

**Comment by grace-ac** [comment]
@seanb80 ?

**Comment by seanb80** [comment]
Hmm, there may have been! I will look in to it tomorrow morning. I tried to
be clever and download then zip files to deal with the limited space, but
that may not have worked.

**Comment by yaaminiv** [comment]
No worries! Also, I tried searching "SRR46473" in the SRA database but it said "No items found"...?

**Comment by grace-ac** [comment]
I think it's supposed to be "SRR546473" https://www.ncbi.nlm.nih.gov/sra/SRX180561[accn]

**Comment by grace-ac** [comment]
I think these are the four data sets we were trying to download...? "SRR546473" is the second on the list.
https://www.ncbi.nlm.nih.gov/sra?term=SRP015008

**Comment by yaaminiv** [comment]
script to download additional datasets: https://github.com/RobertsLab/paper-gigas-metaanalysis/blob/master/scripts/2017-19-04-Downloading-SRA-Data.R

**Comment by kubu4** [comment]
@seanb80 - It might be a good idea to add an update to your original Rpub, so that someone doesn't stumble across it and try to use it.

**Comment by seanb80** [comment]
I've tried to push an update a few times, but it doesn't seem to be properly updating at the page, will have to delete and re-upload I believe.
