### ISSUE TITLE
Error using demultiplexing command in MSConvert CLI from DIA wiki

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#561]
I mentioned this in lab meeting, but I get an error about Window boundary tolerances being set too low when I use the exact command in the DIA wiki. Any ideas on what it might mean/what to do to fix it?

![msconverterror](https://cloud.githubusercontent.com/assets/10619258/24724477/1ff6934e-1a00-11e7-8428-6fdd3210883e.PNG)

**Comment by kubu4** [comment]
May or may not be related. Came across this little note:

![proteowizard___mailing_lists](https://cloud.githubusercontent.com/assets/4514104/24725097/6cd1a0f8-1a02-11e7-8d14-222dec6a0e88.png)

From [this thread](https://sourceforge.net/p/proteowizard/mailman/message/35555511/)

Might be worth changing that aspect of the command?

**Comment by seanb80** [comment]
That was it! Will update the wiki.

**Comment by yaaminiv** [comment]
Is there a difference between using the code directly and using a .config file? When I converted some files using the command line converter the [Evernote](https://www.evernote.com/shard/s347/sh/edcb06ab-d008-418f-b28f-52f6614f1c39/2984ab55f427fcfe) said to use a .config file:

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/2017-03-07-Reconvert-mzML-Files.ipynb

**Comment by yaaminiv** [comment]
![image](https://cloud.githubusercontent.com/assets/22335838/24970216/5af5e6f8-1f68-11e7-9543-8693299b4804.png)

I got the config file to work and it recognizes the demultiplexing option.......but then promptly ignores it.

jupyter notebook: https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/2017-04-12-Demultiplex-Raw-Files.ipynb

**Comment by yaaminiv** [comment]
I tried having the demultiplexing option as the only filter option to see if it was a multiline issue, but it wasn't.

![image](https://cloud.githubusercontent.com/assets/22335838/24971067/75e346f6-1f6b-11e7-9ea0-a9e8f8aed074.png)
![image-2](https://cloud.githubusercontent.com/assets/22335838/24971069/7860cffc-1f6b-11e7-9066-f316a228cf08.png)

@seanb80 @emmats  @sr320 @kubu4   Any advice on how to get the program not to ignore a wrapper?

**Comment by yaaminiv** [comment]
Sidenote @seanb80 I think I have different arguments in the .config file that your command line code does not have. I ran the code you used and compared it to my file:

![image](https://cloud.githubusercontent.com/assets/22335838/24971912/6e490a68-1f6e-11e7-8b9e-19b98a4793a6.png)

The simAsSpectra may be different?

**Comment by kubu4** [comment]
To add more info to this issue, the "demultiplex" filter is not listed as a filter in [ProteoWizard](http://proteowizard.sourceforge.net/tools/filters.html) (which msconvert is part of).

**Comment by emmats** [comment]
I've emailed our local msconvert expert to see what he has to say about this. I'm not sure where he is today, but I'll let you know what I hear. If I haven't heard anything soonish, I will try someone else. Sorry that I've never done this myself!

**Comment by emmats** [comment]
Can you try this without using the config file?

**Comment by kubu4** [comment]
Run w/o config file is what triggered this issue.

**Comment by emmats** [comment]
No one here has used a config file before. Lindsay has successfully demultiplexed raw files using the command I provided just in command line. She said she navigates to her directory containing all her raw files and executes the command from there.

**Comment by emmats** [comment]
Demultiplexing is disabled in the current MSConvert for 32-bit computers. Any chance you are running this on a 32-bit?

**Comment by emmats** [comment]
Austin found that there were some "extra" windows on either end of the range of window masses. He is going to write a script to get rid of those, which should allow MSConvert to run smoothly.
