### ISSUE TITLE
New Titrator pH probe for Micah

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#562]
Finally heard back from Micah regarding replacing the pH probe at DNR for doing TA samples, he's fine with it. 

Please order https://www.amazon.com/Mettler-Toledo-51109504-DGi115-SC-Electrode/dp/B01LWTXHAU

**Comment by sr320** [comment]
Does it make sense to go through Fisher / other scientific vendor?

63-4279

**Comment by kubu4** [comment]
Probably. I always check Fisher for these types of things prior to pulling the trigger on Amazon.

**Comment by sr320** [comment]
Thanks
