### ISSUE TITLE
Help getting samples from Rhonda's experiment in -80C

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#563]
I am hoping to get some help from @grace-ac @kubu4 @sr320 to get some samples out of the -80C for Emma and Brooke tomorrow. They will be running the mass spec and we want to rerun some of our samples form the 2016 experiment. The sample numbers are 35 and 43. Each tube is labeled with a sample number but there are 3-4 sets of tubes with the same sample numbers. I left a note in the box indicating  the contents of each sample set. We want the tubes that are ready for MS. If someone can decipher it or take a photo of it I should be able to point them out.

**Comment by kubu4** [comment]
Label to look for on box?

[-80C inventory is here](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit). Look in the "Racks" sheet and tell us where to find the box.

**Comment by sr320** [comment]
Here are 7 boxes with "Rhonda" noted

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Banners_and_Alerts_and_-80_Inventory_Map_-_Google_Sheets_1E959EA7.png" alt="Banners_and_Alerts_and_-80_Inventory_Map_-_Google_Sheets_1E959EA7.png"/>

**Comment by sr320** [comment]
@Ellior2 - should @kubu4 check the four boxes that have "oyster" and "2016" to see if samples 35 and 43 are present? and if so, set out in for @emmats ?

**Comment by emmats** [comment]
I also need 1-2 good samples. @Ellior2 will need to identify those for me.

**Comment by emmats** [comment]
I'm heading out because I have an outreach event this evening. I'll be leaving for UWPR at noon tomorrow so I hope the samples are found by then!

**Comment by Ellior2** [comment]
I left a handwritten note distinguishing the different sets of samples within one box (the note was placed inside the box). It was the ones labeled 12/5/2016 since that was the day we started the mass spec. This is location Rack_number 12, Column 4, Row 1. These samples should have about ~70ul. Please grab 35, 36, 43, 44.

Thank you!

**Comment by kubu4** [comment]
@emmats Are you grabbing these or do you need/want me to do something with them?

**Comment by emmats** [comment]
I will come by shortly after noon to pick them up. Can you put them in an obvious place?

**Comment by kubu4** [comment]
I'll put them in a box -80C. The box will be in freezer Rack_number 12, Column 4, Row 1

**Comment by kubu4** [comment]
@emmats - I've put them in an orange rack on the top shelf of the -80C.

![img_20170406_101550](https://cloud.githubusercontent.com/assets/4514104/24766992/4bf81fd2-1ab2-11e7-87ab-9a22d99a0147.jpg)

**Comment by kubu4** [comment]
Email from Emma:
> I picked up the samples just fine, thanks, Sam!
