### ISSUE TITLE
website link on Roberts lab site

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#566]
Could someone please update the link to my website from the Roberts Lab page?

My website: http://emmatimminsschiffman.weebly.com/
Place where link needs to be fixed: http://faculty.washington.edu/sr320/?page_id=505

Thanks!

**Comment by sr320** [comment]
@grace-ac could you edit https://github.com/sr320/LabDocs/blob/master/web/People.md accordingly?

**Comment by kubu4** [comment]
I feel like you should make Emma submit a pull request. :)

**Comment by emmats** [comment]
Not nice Sam

**Comment by kubu4** [comment]
Ha! The link would've been updated by now if you had submitted a pull request...
