### ISSUE TITLE
Oly pop structure follow-up

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#570]
![screen shot 2017-04-10 at 2 06 52 pm](https://cloud.githubusercontent.com/assets/14934314/24882760/140e4e64-1df7-11e7-8a06-a490cdc83bc9.png)

**Comment by sr320** [comment]
Do you have contact info ?

**Comment by grace-ac** [comment]
Looks like it's-->  marine.ecology@szn.it
Name: Dr. Giuseppina Gargano
![screen shot 2017-04-11 at 11 45 01 am](https://cloud.githubusercontent.com/assets/14934314/24925258/8784aeaa-1eac-11e7-82cb-d94b568c97af.png)

**Comment by sr320** [comment]
Email sent
