### ISSUE TITLE
Oly Anestesia paper - Email Sandy

### ISSUE THREAD

**Issue by MeganHintz** [sr320/LabDocs#571]
@sr320 email Sandy for an update on the Oly anesthesia paper

**Comment by sr320** [comment]
@MeganHintz would be a correct assumption that you have already made all the revisions indicated in the December 20 email?

**Comment by MeganHintz** [comment]
@sr320 most revisions have been made, I referenced you in the remaining comments for input. Thanks! 
https://docs.google.com/document/d/1AyY6LKe9PRfMd6eplD_c-JDqcoZlj_IdOZ5FGLp5NmI/edit?usp=sharing

**Comment by sr320** [comment]
Thanks
Go ahead and draft response letter where you indicate what you revised- and
generate Word version with changes highlighted.
