### ISSUE TITLE
Additional storage needed for Hyak ($10/mo/TB)?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#573]
Default storage size is 500GB. It's very likely this would be quickly consumed.

Should we consider purchasing additional storage? Should we wait until we have Hyak functioning?

**Comment by sr320** [comment]
Can go ahead and get more

**Comment by kubu4** [comment]
How much more? Which budget(s) to charge?

**Comment by sr320** [comment]
61-0221

Amount would depend on real need - for example how much space to run Pecan?

**Comment by kubu4** [comment]
@seanb80 - Please see @sr320's question above.

**Comment by kubu4** [comment]
For a bit of reference, @seanb80 currently has the most recent Oly PacBio data on Hyak and it occupies ~25GB (~5% of the total storage space).

**Comment by sr320** [comment]
Sorry did not see price in issue name - how about start with one TB?

**Comment by kubu4** [comment]
Done. We now have 1500GB of space allocated on Hyak.
