### ISSUE TITLE
blast pacificoysterdata

### ISSUE THREAD

**Issue by kaitlynrm** [sr320/LabDocs#575]
I understand how to blast a file through jupyter notebook now but I used a different file I downloaded from the internet for practice. I spoke with Sean a bit and neither of us were entirely sure on how to blast this file through:

https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417NSAF.tsv

Was this the file I should blast or is there a separate file I don't have yet?

**Comment by sr320** [comment]
You would blast this file

https://github.com/sr320/nb-2017/blob/master/C_gigas/data/Cg_Gigaton_proteins.fa

then compare the output of that to the table you indicate above.

also attached as zip
[Cg_Gigaton_proteins.fa.zip](https://github.com/sr320/LabDocs/files/917748/Cg_Gigaton_proteins.fa.zip)
