### ISSUE TITLE
Software to install on Hyak

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#576]
Some software that would be great to have on Hyak

- [x] Trinity
- [x] Blast
- [x] Burrows-Wheeler Aligner
- [ ] GATK

Burrows-Wheeler Aligner
Website: http://bio-bwa.sourceforge.net/
Download: https://sourceforge.net/projects/bio-bwa/files/bwa-0.7.15.tar.bz2/download

GATK
Website: https://software.broadinstitute.org/gatk/
Download: https://software.broadinstitute.org/gatk/download/ (need login)

**Comment by seanb80** [comment]
GATK Download page is down, but the rest is installed and the Lab Software wiki updated appropriately for Hyak.
