### ISSUE TITLE
confirm Lat longs on Map

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#581]
Plot coordinates on map to confirm they are correct.
Found in Methods of https://www.overleaf.com/read/mqbbvmwxhncg
Post map here.

**Comment by kubu4** [comment]
![dabob_map](https://cloud.githubusercontent.com/assets/4514104/25137612/2a0d5e3c-240d-11e7-9e67-9c6fb97be775.png)

![fidalgo_map](https://cloud.githubusercontent.com/assets/4514104/25137619/2e3b3c90-240d-11e7-8c84-a59268d23e27.png)

![oysterbay_map](https://cloud.githubusercontent.com/assets/4514104/25137627/31e9f37c-240d-11e7-90b8-49e8661019f2.png)

**Comment by kubu4** [comment]
Oops! I just noticed this was assigned to @grace-ac!

**Comment by kubu4** [comment]
And, not to mention, I did it incorrectly. Didn't realize the lat/long formatting in the manuscript had changed.

**Comment by grace-ac** [comment]
![fidalgobay_coordinates](https://cloud.githubusercontent.com/assets/14934314/25146654/81bce12c-2429-11e7-9ee9-9fe0d78ba024.png)
![dabobbay_coordinates](https://cloud.githubusercontent.com/assets/14934314/25146656/81be4ce2-2429-11e7-8f67-a5d8179ceb2a.png)
![oysterbay_coordinates](https://cloud.githubusercontent.com/assets/14934314/25146655/81bcfdce-2429-11e7-9900-e7b9082d2dbc.png)
I just searched the coordinates as they are in the manuscript.

**Comment by sr320** [comment]
There should be one more that is oyster bay and a bit different than first mention.

**Comment by sr320** [comment]
In manuscript there should be two lat longs for oyster bay, collection and
deployment- I want to see both

**Comment by kubu4** [comment]
Hmmm, I only see one set of lat/long in manuscript.

**Comment by sr320** [comment]
I am sure grace can find it :)

**Comment by kubu4** [comment]
Ah! Tricky! I see the second set of lat/long. @grace-ac - read carefully and it will be revealed!

**Comment by sr320** [comment]
Please cross reference with
https://peerj.com/preprints/704/

**Comment by grace-ac** [comment]
![coordinates_oysterbay_deployment](https://cloud.githubusercontent.com/assets/14934314/25286687/79d201d0-2673-11e7-83b1-fd54aa630018.png)

**Comment by grace-ac** [comment]
Coordinates match those from the peerj preprint!
