### ISSUE TITLE
can't sync repo with desktop version?

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#582]
On genefish, I cloned my metaanalysis paper repo: https://github.com/RobertsLab/paper-gigas-metaanalysis

I added a Jupyter notebook and an excel file on my machine, but it's not letting me sync the repo with the online version. Plus, the screen looks different

![screen shot 2017-04-18 at 2 31 11 pm](https://cloud.githubusercontent.com/assets/22335838/25154031/b5e845ee-2443-11e7-829e-26d62457efc1.png)

Did I make a mistake when cloning the repo?

**Comment by sr320** [comment]
And "not letting me" means ????

**Comment by yaaminiv** [comment]
1) It's not recognizing the changes I made to the repo (adding files), so there's nothing to sync with the online version
2) If I try pressing "Publish" just to see what happens, I get this error

![screen shot 2017-04-18 at 2 36 16 pm](https://cloud.githubusercontent.com/assets/22335838/25154179/70ba1ea6-2444-11e7-83d6-c11c4040dc5f.png)

**Comment by sr320** [comment]
I would have to be at computer to diagnose- but I would suggest using web
upload for a temporary solution.

**Comment by yaaminiv** [comment]
I uploaded my files, deleted the cloned repo and then recloned it. Now it's letting me sync files. Problem solved (although I don't know what went wrong in the first place)!
