### ISSUE TITLE
Update People page

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#583]
Move persons to alumni etc.
https://github.com/sr320/LabDocs/blob/master/web/People.md

Add Marcos
Add Kaitlyn

**Comment by grace-ac** [comment]
added marcos (visiting research scientist...?) and kaitlyn. added sean to research scientist list.

created alumni list for "research scientists" and added giles, crystal, and andy. 

moved hollie to alumni visiting research scientist.

moved mrunmayee and added link to her notebook.
