### ISSUE TITLE
Photo all oyster histo slides

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#586]
Please take two photos (hi magnification, low magnification) of each oyster gonad section such that one could sex.

Upload photos to new sub directory @ https://github.com/RobertsLab/project-oyster-oa/tree/master/images

**Comment by laurahspencer** [comment]
@grace-ac here's a key that you can use when you photography the Olympia oyster slides: https://github.com/laurahspencer/O.lurida_Stress/blob/master/Data/2017-February-HistoKey.docx

Samples in blue were dotted with blue histology ink to help you orient the slides correctly. 

Also, here's a Paperpile folder with a few resources for identifying male/female gonads in bivalves: https://paperpile.com/shared/QemtOZ

**Comment by grace-ac** [comment]
by "each gonad section" do you mean every gonad part of a single oyster tissue sample? @sr320 
as in, for one oyster sample, there will be multiple images (at hi and lo) of gonad tissue?

**Comment by grace-ac** [comment]
I have two slides left of Laura's @laurahspencer 
@yaaminiv - your slides are labeled as notches. is there a way that you'd like me to label the images?

**Comment by yaaminiv** [comment]
@grace-ac the number of notches + location in the original histology cassette would be great! (ex. 3-UL, where UL = upper left of original cassette)

**Comment by grace-ac** [comment]
@laurahspencer This is how K6 10-15 is labeled in your key: 
![screen shot 2017-04-28 at 9 35 50 am](https://cloud.githubusercontent.com/assets/14934314/25538135/4c342680-2bf6-11e7-8ab2-8fdec9d9da0d.png)

However, this is how the slide looks (the hinge of the cassette is on top):
![img_3194](https://cloud.githubusercontent.com/assets/14934314/25538192/8da4859c-2bf6-11e7-9073-18b024645312.JPG)

Any ideas on how you'd like me to label this one?

**Comment by grace-ac** [comment]
I guess in this image, hinge is on left of cassette ^

**Comment by laurahspencer** [comment]
Ah yes - the samples go:
10 , 11
12 , 13
14 , 15

With blue ink on #10. Have you had any issue figuring out orientation?

**Comment by grace-ac** [comment]
@laurahspencer similar issue with HL6 2-6:
![screen shot 2017-04-28 at 9 42 20 am](https://cloud.githubusercontent.com/assets/14934314/25538362/43d59612-2bf7-11e7-8289-96ee9ed8b645.png)

![img_3195](https://cloud.githubusercontent.com/assets/14934314/25538376/51b8ae54-2bf7-11e7-99df-af6fd2488f69.JPG)

**Comment by grace-ac** [comment]
I'm not sure what you mean by orientation. So far it's just been these couple slides that I'm unsure of which is which based on your key and how they look in the slide. Otherwise, everything makes sense! The blue one is always at the top left of the slide when looking at it with the label at the top.

**Comment by yaaminiv** [comment]
@grace-ac actually, use the information here!

https://github.com/RobertsLab/project-oyster-oa/blob/master/data/20170204-GigasTissueSamplingInformation.csv

**Comment by laurahspencer** [comment]
I'm referring to where the blue dot is- i labeled all the top left tissues-
and how that corresponds to orientation on the slide. It sounds like you
haven't had any issue figuring that out, but let me know if you do.
