### ISSUE TITLE
Add NSA posters to figshare 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#587]
And drop url here

**Comment by yaaminiv** [comment]
https://doi.org/10.6084/m9.figshare.4892033.v1

**Comment by laurahspencer** [comment]
https://doi.org/10.6084/m9.figshare.4892126

**Comment by sr320** [comment]
Are these the same exact files provided to printer?

**Comment by laurahspencer** [comment]
For me, yes.
