### ISSUE TITLE
Send Histology Cassettes for processing

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#589]
Yaamini & I have another round of histology samples in 9 "jars" the fridge, bottom shelf, ready to be sent for processing. Sam, I believe you prepped the last batch to be sent off? Here's the submission form: 

[2017-04-19_HistoSubmission.pdf](https://github.com/sr320/LabDocs/files/945125/2017-04-19_HistoSubmission.pdf)

**Comment by kubu4** [comment]
@grace-ac handles this stuff. I've changed the assignment over to her.

**Comment by grace-ac** [comment]
@kubu4 didn't you have to fill out a special form last time because of the chemicals involved? or am i mixing that up with something else....

**Comment by kubu4** [comment]
@laurahspencer - Before we send this stuff out, can you please verify how you prepared the samples for histology? That information is missing from your notebook entries (so, add the info there as well, please).

**Comment by kubu4** [comment]
@laurahspencer - Specifically, what solution are the cassettes currently stored in? The containers have a label and checkbox to indicate the date that they were switched from the FIX solution to the STABILIZER solution. However, the box is not checked and no date is provided, suggesting that these are still in the FIX solution.

**Comment by laurahspencer** [comment]
@kubu4 all cassettes are currently in the STABILIZER solution, and here's [my write-up](https://github.com/laurahspencer/LabNotebook/blob/master/_posts/2017-04-20-Prepping-Histology-Samples.md) of our sample prep.

**Comment by kubu4** [comment]
Thanks! When you have a chance, could you please indicate this on the labels of the jars? I know it's a pain, but that info is good for the histology place to have, as well as for shipping purposes (i.e. no special shipping requirements for the dilute STABILIZER solution).

**Comment by laurahspencer** [comment]
Certainly! Will take care of that tomorrow.

**Comment by yaaminiv** [comment]
I labelled each jar with the date tissue was placed in FIX solution and the date it was transferred to the STABILIZER solution.

**Comment by kubu4** [comment]
@grace-ac you can ship these without any special shipping requirements. The order form is printed out, to the left of my computer (partially hidden under another piece of paper). Still put in some adsorbent material (e.g. the bench top covers we discussed the other day and ship them in a styrofoam cooler. You can use a box from underneath my computer area. Thanks!
