### ISSUE TITLE
BGI Sample Parameters

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#59]
What are the DNA sample requirements for sending BGI samples for GBS or RADseq?

**Comment by kubu4** [comment]
GBS - 300ng
RAD - 1000ng

**Comment by sr320** [comment]
Anyone have quantity values for Plate 1 of Oly DNA?

**Comment by jheare** [comment]
I don't have volumes for each well but I do have concentrations and
calculations to get 500 ng from each well.

https://docs.google.com/spreadsheets/d/1ikRj2DEvkgIyogSGpl2V_6a64XDUyCSlwdQFO8Qv1no/edit?usp=sharing

**Comment by sr320** [comment]
@jheare thanks - and these were originally solubilized in what volume?

**Comment by kubu4** [comment]
Elution volume was 200uL.
