### ISSUE TITLE
Analyze C. virginica BS samples

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#590]
Take our own C. virginica Bisulfite samples and run "Methylation" pipeline to identify DMRs.

getting raw files will be test of our DMP :)

Genome is at https://www.ncbi.nlm.nih.gov/nuccore/MWPT00000000.1/

**Comment by sr320** [comment]
I get about 20% mapping with bsmap
https://github.com/sr320/nb-2017/blob/master/C_virginica/04-Cvirg-BS-Cvirg-NCBI.ipynb

**Comment by seanb80** [comment]
I'm re-running Bismark with some better trimmed data, will also try it with BSMap to see if we can get at least similar results, if not better.
