### ISSUE TITLE
Annotation of Qspec results

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#591]
@emmats @sr320 What are the next steps after Qspec? I have a couple output files from Qspec where I have compared two of my samples on a given day. Since paired t-tests confirmed no difference between any of my technical reps I added the total spectral counts for the duplicate MS runs. I have a list of proteins sorted by z-statistic and log fold change with the most differentially expressed proteins between the two samples at the top.

**Comment by emmats** [comment]
Think about how you would like to visualize your results! There isn't one correct thing for you to do now. You should look at your differentially abundant proteins and figure out what they are, what they do, and why you think they might be different (with the caveat of your small sample size...). But I think one of the best things you can do is brainstorm data visualizations and figure out how to make them happen.

**Comment by sr320** [comment]
See comments in paper
