### ISSUE TITLE
Determine Manchester Avtech needs

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#592]
We now have control of the OA avtech- 
See data @ https://gotomydevices.com/public/faf2b6c1-6a48-42a0-ba1f-3840a2796c66?temperatureScale=C

Please list all needs and wants associated with this.

**Comment by laurahspencer** [comment]
Not sure what it's capable of, but in an ideal situation I'd like:
  * New/clearer labels
  * The ability to see a time series (e.g. a visualization of the past 24 hrs) 
  * Temperature-triggered alarm via email (or something like that)
  * Temperature displayed on the Durafet sensor read-out (I believe it's capable of that)
  * Can we download data via this site?

**Comment by sr320** [comment]
* New/clearer labels  --- YES
  * The ability to see a time series (e.g. a visualization of the past 24 hrs)  ---- YES 
  * Temperature-triggered alarm via email (or something like that)  ---- YES
  * Temperature displayed on the Durafet sensor read-out (I believe it's capable of that)  --- not sure what you mean but likely?
  * Can we download data via this site?  ----- YES
