### ISSUE TITLE
Determine # Samples for Protein Extraction

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#595]
Thought I'd open an issue for the DNR project to determine the # of samples that @yaaminiv and I will process for preteomics. 

I have 180 geoduck samples total, so to run all remaining on Lumos I'll need to extract 171 this month (one of my samples from the previous run jumped out of the tube). Not all treatment/site/trial has the same number of samples (primarily due to mortality @ the site, likely caused by predation):

![image](https://cloud.githubusercontent.com/assets/17264765/25513650/9b2a5ad6-2b8b-11e7-95a9-012ae6fd21c7.png)

**Comment by sr320** [comment]
A primary factor is the protocol, bottlenecks, and how it can be improved.

**Comment by yaaminiv** [comment]
The major time sinks:

1. Speed vacuuming: took us about 10 hours for our samples to evaporate. Not sure if there's anything we can do about this
2. Desalting: Like Rhonda mentioned, the columns we use don't fit in the mini centrifuges we currently have. This could be solved by getting a new centrifuge that would accommodate

I don't think there are places for other parts in the protocol to be improved (it just depends on how quickly we can pipet reagents into our samples).

**Comment by sr320** [comment]
Lets see the entire protocol to get context.

**Comment by yaaminiv** [comment]
https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md
