### ISSUE TITLE
Larval Samples for Proteomics (DNR)?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#596]
I can vaguely recall DNR (Micah) also provided larval samples from pumping.
Does anyone else recall this?
They should be in -80 so maybe @grace-ac has an idea?

**Comment by laurahspencer** [comment]
I know that they collected samples at each site via pumping water through a
screen. I can't confirm that they gave these to you, though.

**Comment by sr320** [comment]
Notes I have

In the freezer we now have:
-- 5 pump samples for larvae in 50mL vials (P1CI, P1PG, P1SK, P1FB, and P1WB signify 'Pump 1' and 'Case Inlet,' 'Port Gamble,' 'Skokomish', 'Fidalgo Bay,' and 'Willapa Bay')
