### ISSUE TITLE
Sneak peak at possible proteins indicative of mortality

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#598]
I am starting down the rabbit hole of figuring out which proteins are indicative of mass mortality events. [Here](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DDA_2016/Qspec27.32DiffProteins_annotated.tabular) is my first annotated comparison of sample 27  (Silo 2-23C at Day 9) and sample 32 (Silo 9-29C at Day 9). We saw a large divergence occurring between the samples in the [NMDS](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DDA_2016/NMDSplot.JPG) plot.  These proteins are sorted from largest to smallest absolute values of z statistic and logfoldchange values (Most differentially abundant proteins are located on top!) Exciting stuff here. Anyone care to take a look and let me know what you think?@sr320 @emmats @kubu4 

Here are some of the [questions](https://ellior2.github.io/Asking-Questions-To-Guide-Exploration/) I plan on tackling in the coming days/weeks...

**Comment by emmats** [comment]
I see a lot of cytoskeletal proteins and cell adhesion proteins. You should definitely try to figure out if these pathways are showing greater or lesser abundance. Ubiquitin is interesting because it can be sign of protein degradation (among other things).
Maybe make two lists of differentially abundant proteins (zstat > |2|, log fold change > |0.5|): proteins that are at higher or lower abundance.
Your questions should keep you busy for a while!

**Comment by Ellior2** [comment]
Good idea. Here are ones highly expressed in dying seed [Silo 2-23C](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DDA_2016/Qspec27.32Silo2.23C.highexp.tabular.txt) and surviving seed [Silo 9-29C](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DDA_2016/Qspec27.32Silo9.29C.highexp.tabular.txt)

**Comment by Ellior2** [comment]
Highly expressed proteins in 23C (high mortality) compared to 29C (low mortality)
![image](https://cloud.githubusercontent.com/assets/20071030/25566706/96f26abc-2d93-11e7-9edc-6a93bf32027e.png)

VIRUS??

**Comment by emmats** [comment]
Before you make any assumptions, look at what those proteins actually are and think about whether or not you think they come from a virus. It would be odd to pick up that many viral proteins using DDA.
