### ISSUE TITLE
What to do with oyster shells

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#599]
@laurahspencer and @yaaminiv 

What are your plans with these oyster shells? If you'd like to keep them, where? 
![img_3240](https://cloud.githubusercontent.com/assets/14934314/25589876/1a59ed06-2e63-11e7-8573-953d7b316c4f.JPG)

**Comment by laurahspencer** [comment]
Good question. I'll get back to you!

**Comment by kubu4** [comment]
This issue was moved to RobertsLab/resources#9
