### ISSUE TITLE
Double check references

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#600]
Confirm all references in paper are listed in bibliography
for
https://docs.google.com/document/d/1sd-ziA7ZpxLXzLGe4TwXBfRFQYsCOfWlGQy679SiFCM/edit

also read for any spelling / grammar mistakes

**Comment by grace-ac** [comment]
is there a specific reference style you're aiming for? there are several different styles used.

**Comment by sr320** [comment]
supposedly @mgavery has it under control with paperpile - but it is not clear to me she is using it correctly :)

Do not worry about style now - just make sure each citation has a match...
