### ISSUE TITLE
Oyster seed enrichment analysis

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#601]
@Ellior2 , Mike Riffle put together a website for enrichment analysis so you don't have to rely on DAVID's crappiness. 
http://www.yeastrc.org/compgo_oyster/pages/goAnalysisForm.jsp
This works essentially as DAVID does. The background is already there so this will only work for this particular project. You can upload 1 or 2 gene lists at a time (the enriched processes will show up as red or blue).
Here is how it works:
1. copy your CHOYP protein name list into protein list 1 or protein list 2 box
2. select your GO aspect
3. set your p-value cut-off (I usually use 1E-1)
4. You can set the output to image (a tree of GO terms with enriched terms shaded with intensity proportional to significance), report, or download report. The report lists the GO terms and associated proteins. I usually create images that I save and I download the report.
5. click "submit" and wait for your results to pop up on the screen.

Let me know if you have any questions.

**Comment by sr320** [comment]
Awesome! Also valuable for @yaaminiv !

**Comment by emmats** [comment]
Not necessarily. The background for this enrichment tool consists of all the proteins Rhonda detected in her experiment. @yaaminiv probably detected a different subset of proteins from the oyster proteome. We'll need to make a new one for Yammini (and for Laura, too!).

**Comment by sr320** [comment]
Gotcha - thanks

**Comment by Ellior2** [comment]
So I put all of the proteins identified in one sample in box 1 (regardless of expression level?) and all of the proteins identified in another sample in box 2? This is what I did and got this image... not really sure what to make of it..

![image](https://cloud.githubusercontent.com/assets/20071030/25731807/83cbadcc-30fe-11e7-9be6-f63744d22937.png)

Or do I use the information gathered from QSpec and look at the proteins that were highly expressed (statistically) in one sample over another? And then use the log fold change or Z-statistic? It doesn't say to include any p-values.

**Comment by emmats** [comment]
That is up to you. You should think about the question you want to answer and figure out how the enrichment analysis will help you answer it.
Right now, you are looking at cellular component proteins that are enriched when your silo- and day-specific proteomes are compared to all proteins detected across your experiment. Is this something you care about? Darker boxes are more significantly enriched than lighter colored boxes. Gray boxes are not enriched but are included in the hierarchical chain of cell components.
You can play around with submitting one list to see if red or blue corresponds to list 1. I'm not sure if he made it so that terms enriched in both are purple, but I will ask.
I'm not sure what you don't understand, so feel free to ask more questions, or we can talk on the phone about it.

**Comment by emmats** [comment]
confirmed that purple = enriched in both protein lists

**Comment by Ellior2** [comment]
I guess I am unclear as to how expression level plays into this enrichment tool. It doesn't account for how many times a peptide matched that protein which I think is important. It just prompts you to put the list of proteins in from a sample which will then tell you how that sample compares to the pooled proteins from your whole experiment. Did Mike Riffle use any expression level information in creating the enrichment tool?

**Comment by sr320** [comment]
Enrichment analysis characterizes a list of genes.

How you ID the list of genes (proteins) might depend on expression, but not
the enrichment analysis itself.
