### ISSUE TITLE
Run Cod Stuff on Hyak

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#606]
When jobs allow 

Here are the files..
http://de.cyverse.org/dl/d/43679678-89E5-479B-B4AB-7B2641C518DC/ACAGCTGT_6.1_trimmed.fastq
http://de.cyverse.org/dl/d/EA916154-503E-4D0A-B99C-C436B9D7CE20/ACAGCTGT_6.2_trimmed.fastq
http://de.cyverse.org/dl/d/EC35A828-1A13-4B61-9CE7-67939C4E648B/GGTCAGTT_6.1_trimmed.fastq
http://de.cyverse.org/dl/d/42562C62-8D23-408A-992D-60284776343A/GGTCAGTT_6.2_trimmed.fastq
http://de.cyverse.org/dl/d/97FC2529-F319-4D89-B0AD-2055C02454E0/Gadus_morhua.gadMor1.dna.toplevel.fa

Here are some commands:

Create genome (and additional supporting files) from FASTA file
bwa index -p atl_cod_4_2017 -a bwtsw Gadus_morhua.gadMor1.dna.toplevel.fa # BWA

samtools faidx Gadus_morhua.gadMor1.dna.toplevel.fa #

java -jar picard.jar CreateSequenceDictionary \
             REFERENCE=Gadus_morhua.gadMor1.dna.toplevel.fa \
             OUTPUT=Gadus_morhua.gadMor1.dna.toplevel.dict

Make alignments
bwa mem -R "@RG\tID:Pcod1\tSM:WA\tPL:illumina\tLB:lib1\tPU:unit1" \
      -p ./atl_cod_4_2017 ACAGCTGT_6.1_trimmed.fastq.gz > WA_6.1_bp.sam

bwa mem -R "@RG\tID:Pcod1\tSM:WA\tPL:illumina\tLB:lib1\tPU:unit2" \
      -p ./atl_cod_4_2017 ACAGCTGT_6.2_trimmed.fastq.gz > WA_6.2_bp.sam

bwa mem -R "@RG\tID:Pcod1\tSM:AD\tPL:illumina\tLB:lib1\tPU:unit1" \
      -p ./atl_cod_4_2017 GGTCAGTT_6.1_trimmed.fastq.gz > AD_6.1_bp.sam

bwa mem -R "@RG\tID:Pcod1\tSM:AD\tPL:illumina\tLB:lib1\tPU:unit2" \
      -p ./atl_cod_4_2017 GGTCAGTT_6.2_trimmed.fastq.gz > AD_6.2_bp.sam

**Comment by seanb80** [comment]
Finished this while I was getting Redundans to work, output sam files are currently uploading to http://owl.fish.washington.edu/scaphapoda/Sean/CodOutput/
