### ISSUE TITLE
Spot-checking peptides in Skyline

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#608]
@emmats how does spot-checking about 100 peptides relate to the overall quality of our data? I haven't checked the tutorials so there might be an answer in there. For example, how will fixing the peak width for a handful of peptides affect the rest of the peaks? Wouldn't it make sense to fix the peak with for all peptides? Did I misinterpret the protocol?

**Comment by sr320** [comment]
FYI - I kind of pushed this question as I could not grasp rationale in the bigger picture :thinking:

**Comment by emmats** [comment]
You are not going to fix those peptides, you are just going to assess how poorly skyline did. You are doing this to estimate an overall error rate.

As you go through and pick peaks, feel free to post pictures if you are unsure about anything.

**Comment by sr320** [comment]
Ok - that makes a bit more sense.

Can a single spot check for a peptide be captured in a single screen shot / image?

**Comment by emmats** [comment]
Yes. @yaaminiv or @laurahspencer should be able to provide that.
