### ISSUE TITLE
2016 oyster seed morphology-throughout exp

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#609]
Hi Grace,

When you have time can you please analyze some more samples for morphology from the 2016 experiment? These were the samples taken every other day throughout the experiment. We would like to get survival information as the experiment progressed. In these samples you will have a large range of sizes as they are unscreened samples. Can you please look at Silo 2, 3, and 9 and count 100 oysters from each day? Of these 100 oysters, please record size (length should be enough) and whether alive or dead.

These are the days:
7/10/16 (Day 3)
7/12/16 (Day 5)
7/14/16 (Day 7)
7/16/16 (Day 9)
7/18/16 (Day 11)
7/20/16 (Day 13)

@sr320 Please confirm that this is warranted. I decided to not include Day 15 since we had the temperature failure on Day 14.

Thank you!

**Comment by sr320** [comment]
@grace-ac what is the status of this?

**Comment by grace-ac** [comment]
less than halfway done - not in lab much these days :( .
but my plan is for today to just take all the pictures I'll need to finish, and just measure whenever I have the time.

**Comment by grace-ac** [comment]
Finished! 
However, Silo 9 Day 13, after several imaging attempts, I was only able to count/image 65 oyster seed. 

Image is summary statistics. 
![screen shot 2017-07-05 at 12 54 45 pm](https://user-images.githubusercontent.com/14934314/27882345-2a880a22-6181-11e7-9a63-fbd98fe4702d.png)

Link to google doc spreadsheet: [here](https://docs.google.com/a/uw.edu/spreadsheets/d/1PS_-GUlnSuXMcfpp3Z91tiusy2YLXJKn022I17Y8Xes/edit?usp=sharing) (these measurements are under "Cryotubes" tab)
Link to google folder of images: [here](https://drive.google.com/drive/folders/0B_Kednl1tNImN0ZvM0FYLWxXYVk?usp=sharing)

**Comment by grace-ac** [comment]
@Ellior2 ^^
