### ISSUE TITLE
Purchase supplies for protein extractions

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#611]
@laurahspencer and I looked through the lab today and we need the following:

- 5 Disposable microplates
- pH test strips
- Pipet tips (1000 µL, 200 µL, 10 µL, at least 3-4 boxes of each)
- Macrospin columns: The Nest Group (macrospin c18 columns, #SMM SS18V)
- Trypsin: Life Technologies (20ug x 5 cat. 90057)
- Tris(hydroxymethyl)aminomethane hydrochloride: Fisher Scientific (500g)
- 2-Iodoacetamide: Sigma (IAA, cat: I1149-5G)
- TCEP: Sigma (cat. C4706-2G)

**Comment by Ellior2** [comment]
Really? I thought we got a TON of pH test strips when I started the extractions, in fact I don't even know if I broke into the new pack. Are the IAA and TCEP I made in the -80C used up or no good?

**Comment by yaaminiv** [comment]
@Ellior2 if there are extra pH strips, we definitely can't find them! There isn't a listing for pH strips on the lab inventory/location spreadsheet, last I checked.

The IAA and TCEP aren't all used up, but we're not sure if they're no good. @emmats would we be able to use IAA and TCEP made in November for our upcoming extractions? Either way, we may need more reagent because we're planning on doing more extractions in the future.

**Comment by emmats** [comment]
How were the IAA and TCEP stored? If both were frozen and IAA has been kept in the dark, then they should be fine.

**Comment by Ellior2** [comment]
Just wanted to make sure you wouldn't be buying more when we still have a bunch. I also remember a little bit went a long way with those ones, so I am not sure if we still have the original bottle that would be good too. When I made the November batch of IAA for example, I only used 186mg to make 5ml and we bought 5g....

**Comment by yaaminiv** [comment]
In that case, here's our revised list:

- 5 Disposable microplates
- pH test strips
- Pipet tips (1000 µL, 200 µL, 10 µL, at least 3-4 boxes of each)
- Macrospin columns: The Nest Group (macrospin c18 columns, #SMM SS18V)
- Trypsin: Life Technologies (20ug x 5 cat. 90057)
- Tris(hydroxymethyl)aminomethane hydrochloride: Fisher Scientific (500g)

**Comment by Ellior2** [comment]
For pH test strips check out the upper counter behind that pH meter set up... in the office where Sam hangs out maybe 6 steps in on the right.

**Comment by yaaminiv** [comment]
We checked that spot and there are no more there!

**Comment by sr320** [comment]
Budget: 63-4279

**Comment by kubu4** [comment]
@yaaminiv and @laurahspencer - Please clarify the following:

- need example of desired microplates (preferably with a Vendor and Catalog number)
- Tris: We have this (i.e. >500g). Do you actually need more?

**Comment by laurahspencer** [comment]
The Tris container in the chem locker is low- figured we needed more
regardless (we use for OA projects too).

**Comment by kubu4** [comment]
There are two containers (I believe the other one is unopened).

**Comment by kubu4** [comment]
Gah! Never mind! They are both open. Sorry!! I'll just order more.

**Comment by yaaminiv** [comment]
![img_7355](https://cloud.githubusercontent.com/assets/22335838/25921371/fbefe98c-3589-11e7-8985-c030a8529714.JPG)

Hopefully this will be the information you need for the microplates!

**Comment by sr320** [comment]
Curious- what are these used for?

**Comment by yaaminiv** [comment]
@sr320 we use them in BCA assay to quantify the amount of protein in our sonicated samples. that number is then used to calculate the amount of a reagent we need to add for trypsin digestion

**Comment by sr320** [comment]
Would something like this not be more appropriate?
https://www.thermofisher.com/order/catalog/product/15045

**Comment by yaaminiv** [comment]
Probably! I just looked at what we used previously/what was already in the lab.

**Comment by kubu4** [comment]
What type of 96-well plates does @emmats use for the BCA assay?

**Comment by emmats** [comment]
I'm not in the lab now, but will try to get you that info soon.

**Comment by emmats** [comment]
Brook ignored my request for this the other day, but here it is. Sorry for the delay.
![img_3243](https://cloud.githubusercontent.com/assets/4564812/26009368/5ca43692-36fd-11e7-8b1f-bd54af103d15.JPG)

**Comment by kubu4** [comment]
Thanks.

**Comment by laurahspencer** [comment]
@kubu4 are there tracking numbers for any of these items? I'm particularly interested in the well plates. Thanks!

**Comment by kubu4** [comment]
All items, with the exception of the pH strips have been received.

Plates were delivered today, so are likely still in the main office waiting for me to pick them up.

**Comment by sr320** [comment]
Plates are not here- just confirmed with Laurie

**Comment by kubu4** [comment]
Sorry. They get delivered tomorrow. Whoops!

**Comment by kubu4** [comment]
>@Ellior2 if there are extra pH strips, we definitely can't find them! There isn't a listing for pH strips on the lab inventory/location spreadsheet, last I checked.

For anyone who's still interested, I found the previously purchased pH strips that @Ellior2 referenced on the bench in front of the NanoPure in FTR 213, along with a few bottles of miscellaneous solutions (Solvent A, Solvent B, and some acetonitrile solution). I've left them all there, since it seems as though someone has placed them there intentionally.

**Comment by laurahspencer** [comment]
Yes, that was me who found everything and placed them there, as we will use
them this week. The pH strips had been hiding under a towel.
