### ISSUE TITLE
Import demultiplexed or .raw files into Skyline?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#613]
I'd like to confirm with @emmats that, since we demultiplexed our .raw files, we must import the converted files into Skyline and **not** the .raw files.  It's stated as such in our [DIA Wiki](https://github.com/sr320/LabDocs/wiki/DIA-data-Analyses), but I'm not sure of its source:

![image](https://cloud.githubusercontent.com/assets/17264765/25829243/d7855f36-3409-11e7-8f73-8aa267b309b0.png)

**Comment by emmats** [comment]
I believe that is correct. Good catch.
