### ISSUE TITLE
Platanus error with PacBio data due to sequence read length.

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#614]
I left Platanus running on Hyak over the weekend and it churned through the Illumina data, but when it got to the PacBio data it threw a `DNA read seq length is too long.` error. 

Poking around the source code, it looks like Platanus maxes out at a sequence length of 5kbp and the PacBio stuff is much longer. 

It looks like we may have a few options from here. 

1. We can try a hierarchical approach where we first run [Canu](http://canu.readthedocs.io) (fork of the deprecated Celera assembler) on the PacBio data and then polish using the Illumina with something like [Pilon](https://github.com/broadinstitute/pilon/wiki).

2. We can correct for errors in the PacBio data with the short-read data using [ProovRead](https://github.com/BioInf-Wuerzburg/proovread) and then assemble with [Canu](http://canu.readthedocs.io). 

3. Assemble the Illumina data with Platanus or [SparseAssemble](https://github.com/yechengxi/SparseAssembler) and then overlap the PacBio data with [DBG2OLC](https://github.com/yechengxi/DBG2OLC) using the Illumina contigs as anchors. 

Anyone have any familiarity with any of the routes? 

We've still got PBJelly running on RoadRunner, so barring any catastrophes, we should have something when that completes.

**Comment by ksil91** [comment]
From [this guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjNjYCuoOfTAhVBwiYKHXElC3gQFggxMAE&url=http%3A%2F%2Fbiorxiv.org%2Fcontent%2Fbiorxiv%2Fearly%2F2015%2F10%2F16%2F029306.full.pdf&usg=AFQjCNFfBpoOa3WBuqxL0QUnlFjR0peitg&sig2=oLEJHYXJD6POaiTP0tRDzw): "We used the pipeline recommended by DBG2OLC(Ye, et al. 2014) to perform hybrid assemblies.  In this pipeline, we used Platanus  to perform De Bruijn graph assembly on the Illumina reads.  We used 8.36 Gb (64.3X) of Illumina sequence data of the ISO1 D. melanogaster inbred line generated by the DPGP project (Langley, et al. 2012) to generate a De Bruijn graph assembly using Platanus.  We used DBG2OLC to align our PacBio reads to the De Bruijn graph assembly to produce a ‘backbone’, then, according to the DBG2OLC standard pipeline, used the backbone generate the consensus using the programs Blasr (Chaisson and Tesler 2012) and PBDagCon. As with the PB only assemblies above, we evaluated assembly quality using the Quast package." So basically the 3rd option you suggested. I also found [this recent paper](http://www.pacb.com/publications/an-improved-genome-assembly-of-azadirachta-indica-a-juss/) that uses PacBio and Illumina reads with platanus (didn't read past the abstract though to see how they did it). I'm not familiar with Canu, but did find this [Github issue ](https://github.com/marbl/canu/issues/88) with recommendations for using it for highly heterozygous data that might be helpful if you decide to go that route.
