### ISSUE TITLE
Exporting report on Skyline

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#615]
I want to export my data from Skyline into a spreadsheet. The settings I have are below:

![image](https://cloud.githubusercontent.com/assets/22335838/25925989/0501085a-35a1-11e7-9344-ff88936028c1.png)

I didn't export the spreadsheets last time and I can't find any documentation in lab notebooks/issues that have the settings we used! @emmats / @laurahspencer do you have the notes somewhere/do you know what settings I should use?

**Comment by laurahspencer** [comment]
You'll need to make your own report by selecting "Edit List" then creating
a new report, and selecting whichever metrics you're interested in.  You
could look at the excel from last time to see what parameters we used, but
I do know that "Area" was the primary metric (which I believe is in the
"Transitions" category).  I generated a report on Monday and it's enormous
- 690 MB - so I'd recommend limiting your report to only the parameters
you're interested in.

Laura
