### ISSUE TITLE
Improve Manchester Alarm Situation

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#616]
Alarm notifications need to be improved such that this does not happen..

Oyster were not hugely impacted, but this would have wiped out larvae.

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/AVTECH_-_GoToMyDevices_com_-_Manage_Room_Alert_Devices____Anywhere____Anytime__1ECA645A.png" alt="AVTECH_-_GoToMyDevices_com_-_Manage_Room_Alert_Devices____Anywhere____Anytime__1ECA645A.png"/>

https://laurahspencer.github.io/LabNotebook/Weekend-Update-with-L.Spencer/

**Comment by laurahspencer** [comment]
I increased the alarm temp to 20degC on all temp probes.

**Comment by laurahspencer** [comment]
The Avtech subscription we have allows for 1 "action," aka one person to be notified: 

![image](https://cloud.githubusercontent.com/assets/17264765/26082653/efcaf458-3985-11e7-9041-aa49691de5bf.png)

We could change that to me for the time being, if you'd like, or you can continue to forward me the emails/notify me.

**Comment by sr320** [comment]
You are welcome to change the person, but should also set up alarm
notification in Device Manager (a lot more flexible) and are recurring
(unlike cloud).

**Comment by laurahspencer** [comment]
I believe I successfully added myself on the device manager; I received an email alert this evening @ ~5:30pm - @sr320 did you too?

**Comment by sr320** [comment]
I believe the last one I got was around midnight - though not sure given date is wrong. 

![img_0261](https://cloud.githubusercontent.com/assets/4442039/26110791/300eb2de-3a08-11e7-9792-42e4282a569e.PNG)

What is the high level plan (independent of mechanism)? 
What is an ideal set-up?
