### ISSUE TITLE
Connecting to hummingbird

### ISSUE THREAD

**Issue by jldimond** [sr320/LabDocs#617]
Anyone know what might be keeping me from connecting via mac screen share with hummingbird (128.95.149.36)? It doesn't even make it to the password/username prompt.

**Comment by kubu4** [comment]
It seems to be locked up. Probably will require a physical restart, but should make sure someone isn't using it heavily. @seanb80 , are you using Hummingbird?

**Comment by seanb80** [comment]
I am not!

**Comment by sr320** [comment]
I will restart

**Comment by sr320** [comment]
It has been restarted

**Comment by jldimond** [comment]
OK Thank you! I am able to log on now.
