### ISSUE TITLE
Outreach ideas

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#62]
March 02, 2015 at 06:51PM<br>
created via Do Button

**Comment by sr320** [comment]
Oysterfest - Shelton - Education

Geoduckfest - Education

Aquarium ---

Tumblr Pictures - tag IFFTT -> Facebook.

**Comment by jldimond** [comment]
We've been reading lots of other people's broader impact statements in FISH 521, and one that I thought sounded interesting was [this one](http://datanuggets.org/) used by Ryan Waples.

**Comment by jheare** [comment]
We could have the 310 Students produce a website or blog that details their research into olympia oysters.
