### ISSUE TITLE
Analyzing BS-Seq and MeDIP data together

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#620]
Is there a way to analyze both BS-Seq and MeDIP data by using the exact same pipeline? From what I understand, I would analyze BS-Seq data in Bismark and MeDIP data with a Bayesian method (like Batman). After running two separate pipelines, I could compare the outputs. I have both BS-Seq and MeDIP data aggregated for my metaanalysis. If the intention is analyze the data as similarly as possible and compare results, I'm wondering if running two separate pipelines is still reasonable for the questions I want to answer (I think it is?).

**Comment by kubu4** [comment]
> for the questions I want to answer (I think it is?).

What are these? That might help us provide some feedback.

**Comment by sr320** [comment]
There are different first steps - BS you get CG data, whereas MeDIP is read mapping to count. 

You compare later with something like Bedtools, etc, depending on questions.

>If the intention is analyze the data as similarly as possible and compare results, I'm wondering if running two separate pipelines is still reasonable?

yes.
