### ISSUE TITLE
Roberts Lab methylation data not on SRA?

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#621]
@sr320 you mentioned that we have methylation data that might not be on SRA...where can I find it?

**Comment by sr320** [comment]
All of lab NGS data is suppose to be organized via 
https://github.com/sr320/LabDocs/wiki/Data-Management#ngs-data-management-plan

thus you can search https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0

**Comment by yaaminiv** [comment]
All of the primary taxa listed in that spreadsheet are O. lurida. Is there no gigas data, or is it misclassified?

**Comment by seanb80** [comment]
It's there, it was just filtered for O. lurida.

**Comment by yaaminiv** [comment]
perfect, thank you!
