### ISSUE TITLE
ID Highly Expressed Proteins

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#623]
This is for @katiedavidson5

ID 100 proteins that are expressed at the highest level in this file
https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_Skyline_20170511/2017-05-11-normalized-peak-areas.csv

**Comment by katiedavidson5** [comment]
Excel was able to process data better today. I sorted and summed the data by protein and field site using a pivot table, and then found the sum of each protein across sites to get the top 100 proteins. Is this the right approach?

**Comment by sr320** [comment]
Sounds good - just be sure to post the results and how you got them in your notebook (genefish.wordpress.com) then we can go over next steps..
