### ISSUE TITLE
Add sonication details to ProteinprepforMSMS.md

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#624]
@yaaminiv, @laurahspencer, and/or @Ellior2 - Please update [ProteinprepforMSMS.md](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) with info on sonicator settings to be used.

**Comment by yaaminiv** [comment]
Updated protocol with Step 4 under "Sonication" (rough wording, I welcome edits/will edit at a later time)

> Adjust sonicatior settings. Pipet an amount of water equal to that of the samples to be sonicated into a new centrifuge tube. Test sonication intensity by sonicating the water in that tube. Ideal intensity is the highest intensity at which no water sprays out of the centrifuge tube (ex. for Roberts Lab sonicator, use amplitude of 50% when sonicating samples that have a volume of 100 µL).
