### ISSUE TITLE
Live/Dead stain for oyster larvae

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#625]
Does anyone have experience using a stain to decipher live vs. dead larvae?  I'd like to add a stain and fixative to well plates with larval samples so I can count live/dead oysters a day or two after collecting.  This [2009 paper](http://onlinelibrary.wiley.com/store/10.4319/lom.2009.7.585/asset/lom320097585.pdf;jsessionid=417844735CED4DA81DE45EF9C80422BA.f01t02?v=1&t=j34p87dn&s=4ddadc8233dd6b7d06a506f818497912f88cb9c1) for zooplankton describes using "neutral red" - and [this paper](http://www.tandfonline.com/doi/abs/10.3109/10520297409116949?journalCode=ibih19) compares that to Evans Blue for a variety of zooplankton (not bivalve, though). Any suggestions?

**Comment by kubu4** [comment]
We have Trypan blue in the lab; suggesting we've used/tried it for live/dead staining in the past. Looks like Mac did this, but only on hemocytes. Not sure how/if it would work on whole larvae. Easy to test, though...

**Comment by kubu4** [comment]
Also, your first link gives me a 403 error, so I can't see it.

**Comment by laurahspencer** [comment]
The paper is, "Simple staining method for differentiating live and dead marine
zooplankton in field samples" by David T Elliott.

I'll look into the Trypan Blue stain.  Also, @Ellior2 - does Taylor use anything for what I'm describing?

**Comment by Ellior2** [comment]
No but I often put larvae in the fridge to measure/assess survival the next day. If you are just looking for empty shells, I think you might be able to push it two days. Measurements get challenging after two days as the shell seems to start degrading, but you can surely tell there is still an oyster inside.

**Comment by Ellior2** [comment]
Also if you happen to see invasive ciliates/ameobas inside your oyster shells, the oysters could be gone in hours leaving behind a bunch of empty shells. You will know it when you see it though. If you keep them alive during the interim, it's worth taking a peak to make sure you don't see this. I however have never seen this in oyster larvae, only geoduck larvae and oyster seed. I also rarely grow Olys though.
