### ISSUE TITLE
Opinion on RNA-Seq Quality for library preps

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#627]
Marco is doing his next set of libraries.

His samples seem to have DNA contamination (after DNAse treatment). 

See MACROGEN reports and email:

We carried out the sample QC again with DNase treatment.

http://lims.macrogen.com/admin/ngs2/manage/qc_tmp/2017/05/Original%20Sample%20QC_1703QHP-0090_170523B-004.pdf replacement

http://lims.macrogen.com/admin/ngs2/manage/qc_tmp/2017/05/Original%20Sample%20QC_1703QHP-0090_170525B-026.pdf replacement + DNase treatment

Sample amount is not shrink luckily. But, we still captured DNA, even we did DNase treatment. This seems to be a sample nature.

Please take you time and let me know your idea of this order.
----

Any opinions on whether he should proceed?

**Comment by sr320** [comment]
More....

Dear Giovanna,

 

When we make library, we would be using the OligoDT for captured mRNA, but in this time, DNA could be possible captured together. Especially, your sample have some uniqueness that DNA was not removed to DNase treatment. There might be LQC could be possible luckily. However, it’s not easy to estimate the quality of final report. Please take your time and let us know your decision of this issue.

Thank you for using the Macrogen.

**Comment by kubu4** [comment]
The second link appears to have way more high molecular weight junk than the first link. If I were to look at those two links w/o knowing what they were, I would think the first link was the DNase-treated sample set.

My recommendation would be to proceed, but I would use whatever samples are in the FIRST link above, as those have less high molecular weight junk AND have higher quantities of RNA, relative to the high molecular weight junk.
