### ISSUE TITLE
Platereader

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#628]
What is an example of a Platereader that would make sense for us to get?

**Comment by hputnam** [comment]
I am looking into getting this one for ~$18K... not sure if it does everything you need.

https://www.biotek.com/products/detection-multi-mode-microplate-readers/synergy-htx-multi-mode-reader/

Biotek Synergy HTX with luminescence, top/bottom fluorescence and UV-Vis absorbance, incubation to 50°C and shaking. Includes Gen5 software, and two filter sets for fluorescence intensity

**Comment by kubu4** [comment]
I'd counter with, does it make sense for us to get a plate reader? 

What do we want to use it for?

@hputnam's suggestion is a very, very nice model with many features that we'd probably never use.

The Seebs have a plate reader they allow us to use. Is that an option?
