### ISSUE TITLE
Mapping oly larvae transcriptome to genome

### ISSUE THREAD

**Issue by ksil91** [sr320/LabDocs#632]
Have you mapped the larvae transcriptome (Olurida_transcriptome_v3.fasta) against the draft genome? In particular, I want to identify any transcripts that map multiple times. I checked the CoGe browser but the only transcriptomes on there were some Male and Female samples.

**Comment by sr320** [comment]
see https://sr320.github.io/student-fish546-2016/First-Aggregate/
for some stuff, but 

Pretty sure v3 includes gonad data.

Normally we would not map contigs to genome, but rather use blast (intron issue)

I suggest blastn and setting a evalue threshold to estimate multiple occurrences. 

What is your end goal / reason?

**Comment by ksil91** [comment]
For designing capture array probes, they recommend excluding sequences that map to two different places. But you're right, blastn would be better than "mapping".

**Comment by sr320** [comment]
Given the status of the genome, I would probably compare genes (v3) blast against itself to find putative homologous transcripts. Either way, there is will be a lot of finger crossing. I would probably say all in all - such efforts would be futile 😺 - I would probably base list solely on putative gene function
