### ISSUE TITLE
Table of Contents Graphic for Geoduck Paper

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#633]
We need a Table of Contents graphic for the Journal of Proteome Research for our Geoduck reproductive maturation paper. Brook and I have a basic idea - is anyone interested in trying to make it reality? Or make something different and better? @grace-ac ?

You can see some examples on their homepage here: http://pubs.acs.org/journal/jprobs
Detailed instructions for creating graphic: http://pubs.acs.org/paragonplus/submission/toc_abstract_graphics_guidelines.pdf

The idea we had was to have a geoduck being sucked into a mass spectrometer and then peptide spectra somehow shown to be diagnostic of geoduck sex and maturation stage (maybe with histo pictures?) coming out.

**Comment by sr320** [comment]
Illustrator in Health Science will handle
