### ISSUE TITLE
Minor Revisions: Oly pop structure paper

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#634]
Due: June 26, 2017

Trying to find a word-doc version of the paper so that I can add the reviewers' comments and make the edits that I can make.

**Comment by grace-ac** [comment]
Reviewer 1: 
[Reviewer1.pdf](https://github.com/sr320/LabDocs/files/1064785/Reviewer1.pdf)
Reviewer 2:
[Reviewer2.pdf](https://github.com/sr320/LabDocs/files/1064797/Reviewer2.pdf)

**Comment by grace-ac** [comment]
Thoughts on where to find a word doc/google doc on Jake's paper? @sr320 

Title: Evidence of Ostrea lurida (Carpenter 1864) population
         structure in Puget Sound, WA

I searched through his old notebook and GitHub repo and only found links to the PeerJ preprint which I can only download as a PDF.

**Comment by sr320** [comment]
https://github.com/sr320/LabDocs/wiki/Pub-a-thon-2017

?

**Comment by sr320** [comment]
How about this: http://d.pr/f/kfZFUB

**Comment by grace-ac** [comment]
PDF that Marine Ecology has: 
[s1-ln25384436629117789-1939656818Hwf-967832818IdV205748631425384436PDF_HI0001.pdf](https://github.com/sr320/LabDocs/files/1075709/s1-ln25384436629117789-1939656818Hwf-967832818IdV205748631425384436PDF_HI0001.pdf)

**Comment by sr320** [comment]
Yep I think the link I provided is it.

**Comment by sr320** [comment]
Brent is looking at this week.
