### ISSUE TITLE
JPR Fasta File as Supplement

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#635]
@grace-ac 
I presume you tried submitting proteome fasta file as supplement to the journal? And they rejected it due to size? 
Is this correct, and if so what was the size limit?
Thanks

**Comment by grace-ac** [comment]
I wasn't the submitter- emma was. It was easier for emma to be the one! I submitted to bioRxiv.

No, I've never seen fasta on their acceptable file type list. What is listed on their acceptable file types is .pdb. 
![screen shot 2017-06-07 at 5 38 44 pm](https://user-images.githubusercontent.com/14934314/26907397-5c80466e-4ba8-11e7-903f-afdc952c042c.png)

Link to full page of acceptable file types: [here](http://pubs.acs.org/page/4authors/submission/software.html).

**Comment by sr320** [comment]
@emmats 
Go ahead and add fasta to supplemental - it is fine to zip. 

Here is the file.
https://github.com/sr320/supp-geoduck-proteomics/blob/master/S1-Pgenerosa-gonad-protein-v3.fasta

**Comment by emmats** [comment]
Thanks. I have a copy since I used it for the Comet searches :)
They did respond and say that they had forwarded my email to our editor.
