### ISSUE TITLE
Photo of adult geoduck

### ISSUE THREAD

**Issue by emmats** [sr320/LabDocs#636]
We have someone working on a geoduck graphical abstract and he would like a better picture of a geoduck than what I have. Does anyone have a clear, direct (taken at 90° to geoduck) photo of a geoduck?
Thanks!

**Comment by sr320** [comment]
Something he can use in artwork or just to see what one looks like?

**Comment by emmats** [comment]
something he can use in artwork that we will publish

**Comment by sr320** [comment]
nice juvenile pics 
https://twitter.com/HolliePutnam/status/859200180712878080
https://twitter.com/HolliePutnam/status/795807155815231488
https://twitter.com/HolliePutnam/status/786356712177491968
