### ISSUE TITLE
Purchasing for Laura's protein desalting

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#638]
Based on my desalting today, @laurahspencer will require the following when she desalts:

- 1 set of macrospin columns (Macrospin columns: The Nest Group (macrospin c18 columns, #SMM SS18V)
- pH strips (Grace and I searched and we think we're actually out this time...we checked on the counters in 209 as well as in all of the drawers/shelves, including drawer 45 where the spreadsheet said they were. We think we used them all up over the course of extractions)

**Comment by kubu4** [comment]
@sr320 - 61-0221?

**Comment by sr320** [comment]
Yes - thanks!

**Comment by kubu4** [comment]
@yaaminiv and @grace-ac, if you used up all of the pH strips (and/or anything else), please be sure to update the inventory sheet.
