### ISSUE TITLE
Check if Steven can log on to Hyak

### ISSUE THREAD

**Issue by seanb80** [sr320/LabDocs#640]
via terminal `ssh sr320@mox.hyak.uw.edu`

should first prompt for password, then prompt for password then show

```
Enter passcode or select one of the following options:

 1. Duo Push to iOS (XXX-XXX-1239)
 2. Phone call to iOS (XXX-XXX-1239)

Duo passcode or option [1-2]: 
```

Choose 1 to have it push an authentication notice to the Duo App.

**Comment by sr320** [comment]
Done
