### ISSUE TITLE
Submit Fasta to PRIDE

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#641]
@seanb80  can you upload this fasta to the respective ftp directory?
will text pw.

https://github.com/sr320/supp-geoduck-proteomics/blob/master/S1-Pgenerosa-gonad-protein-v3.fasta

From: Attila Csordas via RT <px-submission@ebi.ac.uk>
Date: Tue, Jun 13, 2017 at 1:32 PM
Subject: [px-submission #65329] ProteomeXchange Submission
To: emsie25@gmail.com

Hi Emma,

You can upload the fasta file into the PRIDE FTP area and then I will go
through the exceptional process of making the dataset private again in order to
add the fasta file and then make it public again.
Here are the login details:

FTP server: ftp-private.ebi.ac.uk
User name : pride-drop-006
Password : *********************
directory : etimmins_PX

For security reasons, we do not allow directory listings at the top level so
you will need to manually navigate to the proper directory (either by typing
the command:
cd etimmins_PX
if using a command-line FTP or using the corresponding "go to directory" option
of whatever graphical tool you are using).

Let me know once the file has arrived.

Cheers,
Attila
Submission Coordinator
PRIDE team

**Comment by sr320** [comment]
And once complete, please do email Attilla (and cc Emma and me) 
with subject
`RE:  [px-submission #65329] ProteomeXchange Submission `

that fasta has been uploaded

**Comment by seanb80** [comment]
Uploaded and emailed!
