### ISSUE TITLE
2b-RAD files named incorrectly in nightingales

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#643]
While arguably this might should go https://github.com/RobertsLab/project-olympia.oyster-genomic/issues

I include here as it gets to larger DMP checks and balances...

Files in  http://owl.fish.washington.edu/nightingales/O_lurida/2bRAD_Dec2015/

Appear to be `.gz` but are in fact `.fastq`

see also 
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Nightingales_-_Google_Sheets_1EF883CC.png" alt="Nightingales_-_Google_Sheets_1EF883CC.png"/>

**Comment by kubu4** [comment]
To clarify, are you saying the files are not actually gzipped (and, thus, the ```.gz``` extension is incorrect)?

**Comment by sr320** [comment]
Correct

**Comment by kubu4** [comment]
Are you getting an error from somewhere? When I run the ```file``` command on those 2bRAD files, they are all showing as gzipped:

![screenshot 2017-06-21 07 44 59](https://user-images.githubusercontent.com/4514104/27390261-b807340e-5655-11e7-99e5-72bf11946070.png)


To demonstrate that the ```file``` command works as intended, here's an example of me creating a text file, but named using the ```.gz``` extension, and it does <em>not</em> show as being compressed (which it isn't, of course):

![screenshot 2017-06-21 07 47 27](https://user-images.githubusercontent.com/4514104/27390371-eb9819aa-5655-11e7-8588-4f80efa898af.png)

**Comment by sr320** [comment]
Might be artifact of download.
I realized when using bowtie.

recreated...

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Untitled_and_17-06-19_and_17-06-19_and_17-06-19_—_bash_—_80×27_1EFAC537.png" alt="Untitled_and_17-06-19_and_17-06-19_and_17-06-19_—_bash_—_80×27_1EFAC537.png"/>

Mac OS must uncompress but leave `.gz` extension.
