### ISSUE TITLE
Tubewriter

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#644]
I think we should seriously consider getting one of these (probably the first one listed below). As is often the case, hindsight is 20/20 and if we had gotten this 10yrs ago, I can't even imagine how much time we'd have saved. Additionally, writing would be legible, regardless of who was labeling tubes!

Anyway, it would free up so much time to be able to have tube labeling become automated.

Here's the [Tubewriter website](http://tubewriter.com/).

They have two products:
1. Tubewriter standard ($4500) - This uses an Excel spreadsheet, a marker, and tube holders to automate tube labeling. Here's video:

https://www.youtube.com/watch?v=GN0tFMU30LY

100 - 200 tubes/hr.

2. Tubewriter 360 - ($39,000!!) - This uses an Excel spreadsheet and industrial inkjet printing to print on tubes. Can even print on histology cassettes! 

Here's video: 

https://www.youtube.com/watch?v=EvXKynChCF8

1000 - 2500 tubes/hr!

The Tubewriter 360 is, obviously, outrageously expensive. However, any possible way to get creative with some sort of cost sharing with some other labs and/or the department?

**Comment by sr320** [comment]
Given our current equipment needs I would like to wait on something like this. 
thanks
