### ISSUE TITLE
Microbiome filtering pump

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#647]
Here are some ideas for the microbiome filtering pump.

PUMPS
Masterflex L/S Precision Variable-Speed Console Drive 6-600 rpm Catalog #: GH-07528-10  $1130.00
Accepts 2 pumps heads
Allows for several different tubing types allowing for different flow rates of 0.36-3400ml/min (I have been using L/S 35 which would deliver 23-2300ml/min)
Displays rpms instead of ml/min

The pump that I have which displays ml/min is $1980.00. I guess my question for you is what else might you use this pump for in the future? Feeding larval cultures? Would you want to spend the extra money for the fancy other features?

PUMP HEADS
I looked into the pump heads that allow two channels but they only allow really small types of tubing. I think to stay versatile we should just get to pump heads that we can stack. 

This would be: Easy-Load II pump heads of high performance precision pump tubing. I recommend stainless steel rotor. $249.00 (Qty.2) Catalog #: GH-77200-62

TUBING
What we use is the Norprene Food L/S 35 (50ft/pack) for $154.00 Catalog #: GH-06402-35

**Comment by sr320** [comment]
Company?

**Comment by Ellior2** [comment]
Cole Palmer

**Comment by sr320** [comment]
@kubu4 
Please order 

PUMP
Masterflex L/S Precision Variable-Speed Console Drive 6-600 rpm Catalog #: GH-07528-10  $1130.00


PUMP HEADS (**2**)
Easy-Load II pump heads of high performance precision pump tubing. stainless steel rotor. $249.00 (Qty.2) Catalog #: GH-77200-62

TUBING
 Norprene Food L/S 35 (50ft/pack) for $154.00 Catalog #: GH-06402-35


On 61-0221

Thanks

**Comment by kubu4** [comment]
Well, these came in. Not thinking, I had them shipped here. I suppose they're needed at the hatchery?

**Comment by sr320** [comment]
In the lab is fine - no immediate need.

**Comment by kubu4** [comment]
Whew!
