### ISSUE TITLE
Extract RNA from embedded Olys

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#648]
For Katherine's libraries..

(Paxgene kit is here)

Samples are by scope in lab.

---
SN low pH
male - SN-10-20
female - SN-10-16
hermaphrodite - SN-10-17
 
SN ambient pH
4. male - SN-10-25
5. female - TBD; still need images from SN-10-27 through 33
6. hermaphrodite - SN-10-26

NF low pH
7. male - NF-10-24
8. female - NF-10-23
9. hermaphrodite - NF-10 22

NF ambient pH - (missing image for NF-10-25)
10. male - NF-10-28 (not 100% male, a few oocytes)
11. female - NF-10-30
12. hermaphrodite - NF-10-26

**Comment by laurahspencer** [comment]
Final list: 

SN low pH
1. male - SN-10-20
2. female - SN-10-16
3. hermaphrodite - SN-10-17

SN ambient pH
4. male - SN-10-25
5. female - SN-10-31
6. hermaphrodite - SN-10-26

NF low pH
7. male - NF-10-24
8. female - NF-10-23
9. hermaphrodite - NF-10 22

NF ambient pH
10. male - NF-10-28 (not 100% male, a few oocytes)
11. female - NF-10-30
12. hermaphrodite - NF-10-26

@kubu4, you'll probably want to work with Katie to make sure that you're extracting from the same sample as the one she imaged. The histology folks did not keep the samples in the same formation. Katie used my [images of the prepared cassettes](https://github.com/laurahspencer/LabNotebook/blob/master/_posts/2017-04-20-Prepping-Histology-Samples.md) and my [histology "map"](https://github.com/laurahspencer/O.lurida_Stress/blob/master/Data/2017-April-HistoKey.pdf) to ID each sample.

**Comment by kubu4** [comment]
Apparently, I can't tag Katherine in this repo. 

Any idea how much RNA she needs from each sample?

**Comment by kubu4** [comment]
@katiedavidson5 - I saw in your notebook that you indicated you uploaded your labeled images to "the google drive", but there's no link (and, I don't know what Google Drive you're referring to). Could you please drop a link here (and in your notebook)?

**Comment by sr320** [comment]
See https://genefish.wordpress.com/2017/06/28/katies-notebook-imaging-627/

**Comment by kubu4** [comment]
Thanks! Didn't go back that far in time.

**Comment by kubu4** [comment]
OK, I'm definitely going to need some help with these. Here's one example (Oly 5 block) looks like this:

![img_20170705_082211](https://user-images.githubusercontent.com/4514104/27871684-47a63fa0-615b-11e7-9ce7-82fd93d34b69.jpg)


But, the original cassette looks like this:

![2017-04-20_histo-samples8](https://user-images.githubusercontent.com/4514104/27871735-6c57e132-615b-11e7-87c5-11fb4f5accca.JPG)

**Comment by sr320** [comment]
@katiedavidson5 has mapped most of these back and ID -

She has certainly documented which ones she cannot ID 
https://genefish.wordpress.com/author/katiedavidson5/

But I presume the list (picked by @laurahspencer) could be ID'd by the fact she provided info based on @katiedavidson5 pics

**Comment by kubu4** [comment]
Agreed. I am using @laurahspencer's list. The example posted above should contain NF-10-22 and NF-10-23 (which are listed as Samples 9 & 8 in @laurahspencer's post above).

I'm also not seeing any images of the histology blocks being mapped to the original cassette layouts. This is important, as it seems that the histo blocks are <em>not</em> in the same layout as they were in the cassette (looks like most of them have been flipped 180 degrees on the vertical axis; i.e. "mirrored" layout).

I think all of @katiedavidson5's images are only of slides - not mapping blocks to cassettes.

**Comment by kubu4** [comment]
OK, I think I'm getting things figured out. Some of these cassettes were split into two different histo blocks (I'm guessing by the histology facility). I figured this out when looking at the slide labels. See images below of the Oly 5 block for an example:

![img_20170705_101456](https://user-images.githubusercontent.com/4514104/27876505-34eddd44-616c-11e7-83bc-b1150006128a.png)



![img_20170705_101548](https://user-images.githubusercontent.com/4514104/27876392-c75891fc-616b-11e7-86e4-7c192f0f1b8b.jpg)

**Comment by laurahspencer** [comment]
@kubu4 sorry for the delay; did you see these?:

[images of the prepared cassettes prior to sending to histology](https://github.com/laurahspencer/LabNotebook/blob/master/_posts/2017-04-20-Prepping-Histology-Samples.md) and my [histology "map" of the prepared cassettes](https://github.com/laurahspencer/O.lurida_Stress/blob/master/Data/2017-April-HistoKey.pdf).

It's confusing, as the histology folks move these around. I applied blue ink on the top left tissue sample in each cassette (see images for location). Katie used my images to compare the share of each tissue in the cassettes to the slides.

**Comment by kubu4** [comment]
@laurahspencer, yes, I have been looking at those. Did you see my post above, documenting some of the confusion/difficulty involved with getting this stuff figured out?

**Comment by laurahspencer** [comment]
Katie compared the shape of each tissue in the blocks/slides to my imaged slides. @katiedavidson5, did you keep record of how you assigned the tissues their record numbers?  If not, you'll have to do the same image comparison, for example, this is how I would assign NF-10 22 & 23:

![snip20170705_27](https://user-images.githubusercontent.com/17264765/27877652-5977dfb2-6170-11e7-9bee-cc5775ca9376.png)
![snip20170705_26](https://user-images.githubusercontent.com/17264765/27877653-597df69a-6170-11e7-92b0-0745f114376d.png)
![snip20170705_24](https://user-images.githubusercontent.com/17264765/27877654-598556f6-6170-11e7-931c-bbad85aca397.png)

For some back story (probably TMI)- I selected the samples based on their sex/maturation targeting a male, female, and hermaphrodite from each of the following groups: NF-10-low, NF-10-ambient, SN-10-low, & SN-10-ambient.
![image](https://user-images.githubusercontent.com/17264765/27877754-c5f9cd08-6170-11e7-802e-cadc36ece82c.png)

**Comment by kubu4** [comment]
Thanks. I figured this out already (see my post above).

I was hoping that these had all been mapped out already, just like your example above.

**Comment by kubu4** [comment]
@laurahspencer - Do you have an image of the Oly 14 cassette (I'm not seeing it in your notebook with the rest of the cassettes)? I don't need it to figure out the samples, but would be nice to have for my notebook.

**Comment by kubu4** [comment]
@laurahspencer  - Actually, I can't determine Oly 14 samples without the original cassette image. Sorry!

**Comment by kubu4** [comment]
@laurahspencer - I've annotated the set of histology blocks that contain the samples in your list (except for blocks Oly 14, due to missing tissue cassette image). Please review my annotations and confirm (or disconfirm) they are correct:

http://onsnetwork.org/kubu4/2017/07/05/sample-annotation-olympia-oyster-histology-blocks-from-laura-spencer/

Thanks!

**Comment by laurahspencer** [comment]
FYI I found an image of block 14 (along with 12 and 13), and updated the images on my notebook post. 

I started to go through the annotations, and it's super hard for me to confidently ID them from images; I'll need to do it in person on Friday when I'm in.  Will that work for you? I do think there are a couple that you swapped, for example:

![image](https://user-images.githubusercontent.com/17264765/27889871-20b2b4fc-61a4-11e7-8ab3-39d5ee47e0ec.png)

And in the "Oly 10" block the blue ink leads me to believe things need to be swapped. 
NOTE: I just checked the slide images that Katie took and it looks like she ID'd the pink tissue SN-10-21. 

![image](https://user-images.githubusercontent.com/17264765/27890379-1e3beb64-61a7-11e7-94f4-ecc1fe107fb4.png)

**Comment by kubu4** [comment]
Friday is fine. All the slides and blocks are at my computer. I won't be in. Just provide me with annotated images of the blocks and I'll get the RNA isolated.

**Comment by laurahspencer** [comment]
Will do!

**Comment by katiedavidson5** [comment]
Sorry for the late response! I will be in on Friday around 1pm and can help as well! I did not record the new locations of the oysters on all of the slides. I did for cassettes 24-31, and a few other confusing ones but that is it. Shouldn't be too hard for me to go through and label them as I imaged them though if there is any confusion!

**Comment by kubu4** [comment]
Not that the histology place can help us with this particular set, but I've emailed them about the fact that a subset of the blocks have had the tissue re-arranged from how it was submitted to them. In fact, tissue rearrangement only occurred on a subset of blocks - all blocks with a "YL" sticker on them did not retain the tissue arrangement as it was submitted to them.

**Comment by katiedavidson5** [comment]
Okay here are the labeled slides as imaged! If they're positioned in the same orientation as the cassettes (like they are set up now on @kubu4 's desk) it'll be easy to tell which is which.
![histology slides 1](https://user-images.githubusercontent.com/28788663/27976866-2fe3842c-631d-11e7-9993-f754090a2822.JPG)
![histology slides 2](https://user-images.githubusercontent.com/28788663/27976869-318bb524-631d-11e7-9484-23d463a0076c.jpg)

**Comment by laurahspencer** [comment]
I double checked Katie's annotations and I concur with the above images.  You should be all set for Monday - but please call me if you run into issues. I'll be @ the hatchery but can step away if needed. For example, if you run into an issue with one specimen and need me to quickly ID a replacement, I can do so. 

Out of curiosity, have you extracted RNA from histology blocks before, and in doing so do you target only the tissue in question, for this situation gonad?  I'm curious, since the slides show that some specimens have other tissue types amongst the gonad, but I did my best to select samples that had very well developed gonad, so hopefully it won't be too difficult if that's your aim.

**Comment by kubu4** [comment]
Yes I've done this before. I will not be reviewing the slides prior to extractions. So, I will isolate from a random area within each designated tissue. If there's a specific region within each tissue that you'd like me to target, you'll need to annotate images of the blocks, with the desired region circled within each tissue.

**Comment by sr320** [comment]
Curious... 
did @laurahspencer indicate where gonad was in each sample or were samples random?

**Comment by kubu4** [comment]
Samples were "random" (i.e. in the center of each designated tissue, in order to avoid accidental cross contamination from neighboring tissue).

**Comment by laurahspencer** [comment]
Just saw this- I assume it's too late for me to indicate gonad locations?

**Comment by kubu4** [comment]
Yep.

**Comment by laurahspencer** [comment]
Shoot- I was in the weeds and just now came up for air. Is it feasible for me to see which area you sampled, aka is it obvious when looking at the histology block? I'll be in tomorrow and can check it out.

**Comment by kubu4** [comment]
http://onsnetwork.org/kubu4/2017/07/10/rna-isolation-olympia-oyster-gonad-tissue-in-paraffin-histology-blocks/

**Comment by laurahspencer** [comment]
I took a look at the images - these tissue samples are of whole visceral mass, so on a couple of the samples you probably got more digestive gland than gonad; gonad is more prevalent on the perimeter of the samples.  I will be in tomorrow and can take a closer look, and we can discuss.

**Comment by sr320** [comment]
@laurahspencer determine which ones are gonad (if any) 

Mark embedded samples where gonad tissue can be obtained.
Maybe circle with pencil?

**Comment by kubu4** [comment]
Annotating the blocks digitally would be sufficient, however, I think the wax in the blocks is to soft for a pencil. Could you use thin tip marker on blocks?

**Comment by sr320** [comment]
@laurahspencer - was this done?

**Comment by laurahspencer** [comment]
Grace is on it today!

**Comment by grace-ac** [comment]
Notebook entry link comparing the histology block extraction sites with the actual locations of gonad tissue : [here](https://wordpress.com/post/genefish.wordpress.com/2667)

Samples were taken from the center, whereas gonad tissue is found around the edges. Gonad tissue locations (determined through use of microscope) are indicated by arrows.

**Comment by laurahspencer** [comment]
More direct link: https://genefish.wordpress.com/author/graceac9/

**Comment by laurahspencer** [comment]
@grace-ac i see that you have a couple comments on wrong Oly ID- did you see Katie's map posted on this thread 5 days ago?

**Comment by grace-ac** [comment]
@laurahspencer about to add final solution to your samples - will look at katie's map after!

**Comment by grace-ac** [comment]
fixed it!
