### ISSUE TITLE
New cover letter

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#650]
For "Evidence of Ostrea lurida Carpenter, 1864 population structure in Puget Sound, WA"

**Comment by sr320** [comment]
Here you go!
[ME_R-Roberts-2017.pdf](https://github.com/sr320/LabDocs/files/1132020/ME_R-Roberts-2017.pdf)

**Comment by grace-ac** [comment]
It's saying pdf is not a good file type. Can you send doc form? @sr320 
![screen shot 2017-07-07 at 12 39 49 pm](https://user-images.githubusercontent.com/14934314/27974137-76a9e1aa-6311-11e7-9900-76a12b782ff9.png)

**Comment by sr320** [comment]
Word Doc - 
[ME-Roberts-2017.docx](https://github.com/sr320/LabDocs/files/1132131/ME-Roberts-2017.docx)

**Comment by grace-ac** [comment]
re-submitted the revisions! 
[ScholarOne Manuscripts.pdf](https://github.com/sr320/LabDocs/files/1132169/ScholarOne.Manuscripts.pdf)
