### ISSUE TITLE
Confirming reagents for desalting peptides

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#651]
Hi folks, particularly @Ellior2 and @kubu4.  I'm making the following reagents for desalting my geoduck peptides: 
![image](https://user-images.githubusercontent.com/17264765/27982460-7ffa9728-6356-11e7-94d5-bcc5096bcdea.png)
 
Following the [Protein Prep Protocol](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) and these reagents: 

![file_000](https://user-images.githubusercontent.com/17264765/27982487-1c1324e0-6357-11e7-8650-fa39c7b38957.jpeg)
![file_001](https://user-images.githubusercontent.com/17264765/27982488-1c1528d0-6357-11e7-82e9-e14a87f8cb61.jpeg)

As the protocol does not specify reagent concentrations, I'm confirming that the chems I have are appropriate. Here are my calcs: 
![image](https://user-images.githubusercontent.com/17264765/27982456-705c0374-6356-11e7-8eb3-f5938616224f.png)

Everything checks out except for the %formic acid in the _Final Solvent_.  Am I correct that the formic acid we have is 50% (see image), or am I reading this incorrectly and it is in fact 100%?  Perhaps a more pertinent question is, @Ellior2 did you use this formic acid for your Final Solvent preparation? 

Thanks!

**Comment by sr320** [comment]
Would not Yaamini and Jose have just done this?

**Comment by laurahspencer** [comment]
I think Jose did; I'm emailing him as well.

**Comment by kubu4** [comment]
@laurahspencer, I believe your calculation is correct. Should confirm with @emmats about the vendor/catalog number of the formic avid she uses.

**Comment by sr320** [comment]
Yaamini did not desalt her samples that are going on MS Monday?

**Comment by sr320** [comment]
https://genefish.wordpress.com/2017/06/10/yaaminis-notebook-dnr-desalting-round-2/

**Comment by kubu4** [comment]
Looks like she desalted, following the link you provided. 

A counter argument is, if this has been done this way before & worked, no reason to change. Maybe?

**Comment by emmats** [comment]
I just responded to @laurahspencer via email, but you really want your final formic acid concentration to be at 0.1%. We achieve this buy buying optima grade water and acetonitrile with 0.1% formic acid (from Fisher).

**Comment by kubu4** [comment]
Thanks. When someone has a chance, it would be good to get a catalog number from @emmats.

**Comment by laurahspencer** [comment]
From Emma: https://www.fishersci.com/shop/products/0-1-formic-acid-water-optima-lc-ms-solvent-blends-fisher-chemical-4/p-3850185

It sounds like i should double the volume of formic acid in my final solution to achieve 0.1%.

the solution Yaamini used was made by Jose, who I believe followed the protocol as written (I had an email out to him, to double check). Last winter we used solution made by Rhonda. As such, the solutions used to date have likely been only 0.5% formic.

**Comment by kubu4** [comment]
Yes, adjust your calculation appropriately.

However, I'm confused by the product link. That product doesn't contain acetonitrile, but is already at 0.1% formic acid (which is what the final formic acid concentration is supposed to be). Thus, when adding acetonitrile, the formic acid concentration would end up <0.1%.

**Comment by emmats** [comment]
See above comment. We buy acetonitrile with 0.1% formic acid as well. So FA is always at 0.1%. I don't do any ordering in my lab, but what you are looking for is optima grade reagents with 0.1% FA like this https://www.fishersci.com/shop/products/0-1-formic-acid-acetonitrile-optima-lc-ms-solvent-blends-fisher-chemical-4/p-3850274.
You don't need large volumes because you use this only for reconstituting the peptides after desalting. Before that, you are adding trifluoracetic acid at 0.1% to your ACN mixtures.

**Comment by kubu4** [comment]
@emmats is that the actual product you use in lab? I'm confused by your usage of "products like." That suggests that's not actually what you use.
