### ISSUE TITLE
Mass spec supplies

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#652]
This is for Laura and Jose's upcoming mass spec runs

- 200 µL Peptide Retention Time Calibration Mixture [ThermoFisher #88321](https://www.thermofisher.com/order/catalog/product/88321)
  - Quantity: 1
- 11 mm Snap-It Autosampler Vial Caps, 6mm hole (Thermo Scientific C4011-54G)
  - Quantity: 2 packs of 100 each
- Autosampler Vials (Thermo Scientific C4011-13)
  - Quantity: 2 packs of 100 each
- [Microtube tough spots](http://www.usascientific.com/tough-spots-roll-0.375-dia-white.aspx) (for labelling autosampler vials)
  - Quantity: 1

**Comment by sr320** [comment]
61-0221

**Comment by laurahspencer** [comment]
Thank you!

**Comment by yaaminiv** [comment]
@kubu4 is there a tracking number for the PRTC?

**Comment by kubu4** [comment]
No tracking info. Order confirmation says estimated delivery is July 13th.

**Comment by laurahspencer** [comment]
Thanks- if anyone sees these come in tomorrow could you alert me?  I'm
hoping to have Grace use them on Friday.

**Comment by laurahspencer** [comment]
@kubu4 or @grace-ac - if either of you are in the lab today could you check to see if there are any packages at the office? I'm looking for the Peptide Retention Time Calibration Mixture, specifically.  Thanks!

**Comment by sr320** [comment]
Grace got all the packages. No sign of PRTC.
