### ISSUE TITLE
Determine Geoduck Illumina Data status 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#658]

**Comment by kubu4** [comment]
>Hi Sam,
Thanks for checking in.
I found out from Jon that in checking the data from the first run on the NovaSeq that we had conflicting indexes between the MP libraries and a couple of the RNASeq libraries.
That meant we could not de-convolute some of the RNA output from the MP output.  A bit of a “genome in a box” unanticipated “good to know”.
This means we had to redo the NovaSeq run after removing a couple of the RNASeq libraries.
I don’t have details on which of the RNAseq samples needed to be removed and am cc’ing Jon on this.
I talked to Jon yesterday and he is transferring data and can update us once it is ready to ship out.
So sorry for the delay (I am saying that a lot to you and for that I apologize).
I am still working on the 10x library effort and will let you know when and if I have some traction there.
Cindy

**Comment by kubu4** [comment]
My very rough notes from meeting:

Sequencing saturates diversity of libraries
- mate pair targeting biggest insert size = smallest distribution of genome = over-representation of sequences (same sequence seen repeatedly)

No paired-end libraries.

Coverage depends on diversity of of mate-pair libraries.

Different sizes of mate pair libraries.

More DNA needed for 10x sequencing.

HDD structure:

HiSeq - mate pair and RNAseq
MiSeq - RNAseq
NovaSeq - RNAseq and mate pair? (mention of index collision)

**Comment by kubu4** [comment]
Cindy's recap from meeting:

>Hello all,
Thank you so much for your
HiSeq folders for RNASeq and Mate Pair libraries
NovaSeq run for all combined.  The MP libraries have a 800 bp insert and the RNA Seq libraries have a 300bp insert so they were loaded in a 10:1 MP:RNA into the NovaSeq.
There is a sample sheet loaded on the hard drive that should indicate sample identifiers.  Those identifiers are in the sequence files.
Next steps:
Cindy to reach out to 10xGenomics regarding how to complete the geoduck sequencing project with a 10xG library.
Recommended kit from 10x is a magnetic bead kit that I will get details for.
Next run we plan to include all preps (MP, RNASeq, 10xG) into a single run.
Sam to have a look at data, follow up with questions and share any interesting observations.
Let’s plan to get this into a coherent story by PAG 2018.
C
 
 
Cindy Taylor Lawley, PhD
