### ISSUE TITLE
Reason for Modifying EZNA Kit?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#661]
Question from the webs

> I am a Masters student at the University of Calgary who is working on a project to answer some population structure and adaptive divergence questions involving two species of fresh-water, air breathing snails located in the Canadian Rockies.
 
> I am beginning my DNA extractions (with the E.Z.N.A Mollusc kit) to do PoolSeq and ddRADseq on them. I am getting good yields, decent DNA integrity and good 260/280 ratios, however my 260/230 ratios are a bit low according sequencing service I intend to use for PoolSeq. Upon trawling the web on how to perfect DNA extractions for the cleanest, nicest DNA possible I stumbled upon Sam White’s lab book. I noticed he had made some adjustments (crushing in ML1 buffer, three rounds of chloroform etc.). If it isn’t too much to ask would it be possible to talk to him or yourself briefly about the process in which you optimized and the reasons you did the modifications you did?

**Comment by kubu4** [comment]
Homogenization in Buffer ML1
- No LN2 and/or mortar/pestle for powdering sample, so homogenized directly in buffer.

Multiple chloroform treatments
- It's related to the "Note:" afer Step 6 in the manufacturer's protocol[](https://github.com/sr320/LabDocs/blob/master/protocols/Commercial_Protocols/Omega_Mollusc-DNA-Kit-Combo-May-2013-D3373.pdf). I think this is actually a typo in my notebook. I characterized it as three rounds of the 24:1 chloroform:IAA treatment, but it's actually three sequential additions of ML1 Buffer.
