### ISSUE TITLE
Re-order PRTC ASAP

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#662]
Please order PRTC again- this time catalog [#88320](https://www.thermofisher.com/order/catalog/product/88320), which is a 50ul aliquot @ $75. Please order 4 vials, and if ship as quickly as possible. The other PRTC item was apparently out of stock with no ETA, and we have borrowed a ton from Emma who is now getting low. 

I've requested compensation from Fischer Scientific, but they are being very slow to respond. I'll forward you an email I sent them last night. 

Thanks!

**Comment by laurahspencer** [comment]
Better make it 4 vials- we need to return 3 to McCoss Lab and we should keep one for ourselves. I'll update the above comment to reflect this change.

**Comment by laurahspencer** [comment]
Thanks- can you send me the order info so I can keep an eye on it?

**Comment by kubu4** [comment]
Well, I still don't have any order deets from Fisher. However, I toss in the UW eProcurement order number: EI789958

You might be able to use that, if you want to contact them.

**Comment by laurahspencer** [comment]
Great, thanks. The vendor is sending me some "sample" vials (aka free), which will ship tomorrow and get here likely early next week, hopefully Monday morning.

**Comment by kubu4** [comment]
Rec'd what we ordered, as well as the free samples. Drawer #1 in 209 -20C.

**Comment by laurahspencer** [comment]
Wow! Melissa at Lifewise Technologies gets a gold star. Thanks!
