### ISSUE TITLE
Materials for gigas spawning/larval rearing

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#665]
All of these are prime eligible and should arrive by Wednesday/Thursday.

Cut resistant gloves + shucking knives set (Quantity: 3): https://www.amazon.com/Rockland-Guard-Shucking-Resistant-Stainless/dp/B01N98YKYZ/ref=sr_1_5?ie=UTF8&qid=1500961741&sr=8-5&keywords=oyster+shucking+knives

Paper serving boats (to separate oysters and prevent contamination): https://www.amazon.com/Brown-Paper-Food-Trays-Count/dp/B00T5HWYFI/ref=pd_sbs_79_1?_encoding=UTF8&pd_rd_i=B00T5HWYFI&pd_rd_r=0YZ86Z3DNJMFZ6XNHD68&pd_rd_w=pr4h0&pd_rd_wg=HbpCn&psc=1&refRID=0YZ86Z3DNJMFZ6XNHD68

Tripours (to strip gonads into) (Quantity: 2): https://www.amazon.com/dp/B003H4QRYO/ref=twister_B004PLMCRE?_encoding=UTF8&psc=1

Labeling stickers to separate males and females visually (no need to order if we already have some sort of alternative in the lab): https://www.amazon.com/Avery-Permanent-Coding-Labels-Inches/dp/B000RNHZAI/ref=sr_1_1?rps=1&ie=UTF8&qid=1500962936&sr=8-1&keywords=red+dot+sticker&refinements=p_85%3A2470955011 (Red, Quantity: 1)

AND

https://www.amazon.com/Avery-Permanent-Coding-Labels-Inches/dp/B00007LVEX/ref=sr_1_1?rps=1&ie=UTF8&qid=1500962936&sr=8-1&keywords=red%2Bdot%2Bsticker&refinements=p_85%3A2470955011&th=1 (Blue, Quantity: 1)

Glass capillary tubes (to pull gonad tissue and sex oysters easily): https://www.amazon.com/Capillary-Tubes-Plain-Glass-Vial/dp/B001DB93E4/ref=sr_1_3?rps=1&ie=UTF8&qid=1500963072&sr=8-3&keywords=glass+capillary+tube&refinements=p_85%3A2470955011

Immersion heaters (to keep water at desired temperature in each tote, spares in case they melt or malfunction) (Quantity: 8): https://www.amazon.com/gp/product/B003GVT0V0/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

Thank you!!

**Comment by kubu4** [comment]
@sr320 - which budget(s)?

**Comment by sr320** [comment]
61-0221

**Comment by kubu4** [comment]
Also, @yaaminiv, please be sure to open packages before taking to Manchester to verify contents. I have some personal Amazon packages waiting for me in the office and I'd prefer they not end up over there. Thanks.

Additionally, please be sure to check for packing slips. If packing slips are present, please sign and date, and leave on my keyboard. Thanks.
