### ISSUE TITLE
!head command not working in Jupyter

### ISSUE THREAD

**Issue by Ellior2** [sr320/LabDocs#666]
The Jupyter struggle is real! In this notebook I am simply trying to use the `!head` command and I get `'head' is not recognized as an internal or external command,
operable program or batch file.`

[See notebook](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/Jupyter/GotoGOslim.ipynb)

I have used it successfully many times before:

![image](https://user-images.githubusercontent.com/20071030/28584387-67100332-7121-11e7-979d-a721803106b0.png)

And here I am using it in git bash terminal:

![image](https://user-images.githubusercontent.com/20071030/28584936-684ae990-7123-11e7-85d7-fbf5ff43eb3d.png)

Now why is Jupyter not recogonizing this command, any ideas? Sorry to bug you for these seemingly elementary issues I am having :/

**Comment by sr320** [comment]
Indeed frustrating - it has something to do with windows and bash. 
You can try this format in Jupyter..
```
%%bash
head fileIwanttosee.txt
```

Otherwise it is not worth spending too much time troubleshooting. These commands are not critical for completion of notebook, but rather will indicate issues (which indeed are likely to show up).

I would maybe just have git bash terminal up at same time as notebook to check files

**Comment by sr320** [comment]
Big picture comment -

That notebook and commands are meant for blast output, and you will likely not get too far assuming the skyline output is in different format. 
Feel free to just submit an issue describing what file you have and what you want in the end.

**Comment by kubu4** [comment]
This is related to Issue #664. You're running the Jupyter Notebook from the Anaconda application. Anaconda is a Python distribution and package manager. It does not have Bash and, in turn, any Bash programs (e.g.```head```).

If the solution posted in Issue #664 allows you to launch Jupyter Notebook from Git Bash again, then you'll have access to Bash programs in your Jupyter Notebook.

If you're sticking with using Anaconda to launch your Jupyter Notebook, I'm fairly certain there's a way to configure your Jupyter Notebook settings to tell it where to find Bash. If that's what you'd like to do, and you need help, create a new issue for that.
