### ISSUE TITLE
Wanted: Nice Oly Hermaphroditism Image

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#667]
Mac is considering photos for her latest pub-a-thon product.

Which is the best Oly gonad image that shows both male and female tissues?

**Comment by laurahspencer** [comment]
Hi magnification, this one is good: https://drive.google.com/file/d/0B6vcfZRVqdYHVTYxc3RrWTJMZUE/view?usp=sharing

Low magnification, this sample is good but the image would likely need to be retaken with different lighting for publication: https://drive.google.com/file/d/0B6vcfZRVqdYHN0xNRDZKdWJhaVE/view?usp=sharing

**Comment by katiedavidson5** [comment]
I agree with Laura those are the best examples I could find!
