### ISSUE TITLE
Temperature control in FTR 134

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#668]
While having windows is great for morale, it's not the best for temperature control. Because optimal temperature promotes optimal productivity, @MeganHintz and I have found the following cost-effective options:

1) Fan for warmer months: https://www.amazon.com/Westinghouse-Oscilating-Stand-Fan-Black/dp/B071R4TN35/ref=sr_1_6?s=home-garden&rps=1&ie=UTF8&qid=1501107049&sr=1-6&keywords=fan&refinements=p_n_condition-type%3A6358196011%2Cp_85%3A2470955011

2) Heater for colder months: https://www.amazon.com/Lasko-754200-Ceramic-Adjustable-Thermostat/dp/B000TKDQ5C/ref=sr_1_2?s=home-garden&ie=UTF8&qid=1501107357&sr=1-2&keywords=space+heater

We looked at heater/fan combinations but they seemed to be ineffective and expensive. Is this okay?

**Comment by sr320** [comment]
Sure

**Comment by kubu4** [comment]
Which budget(s) should I use?

**Comment by sr320** [comment]
65-2861
