### ISSUE TITLE
High Quality Oyster Larvae Pics

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#670]
Mac is looking for any high quality oyster larvae pics for her chapter.
Does anyone have some? - photo credit will be given.

**Comment by kubu4** [comment]
These two posts have some (they're Oly's, though and the cleanest pics are of dead ones [i.e. empty shells]):

http://onsnetwork.org/sjwfriedmanlab/2015/06/19/morphometrics-olympia-oyster-oa-larvae-completed/

http://onsnetwork.org/sjwfriedmanlab/2015/06/18/morphometrics-olympia-oyster-oa-larvae-3/

**Comment by sr320** [comment]
Eggs and larvae (gigas)
https://genefish.wordpress.com/2017/07/31/yaaminis-notebook-gigas-spawn/

**Comment by sr320** [comment]
Movies
http://d.pr/v/Nkh6Gb
http://d.pr/v/nKtWUV
http://d.pr/v/epx0Q

screenshot
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/2017-06-05_15_39_34_mov_1F2FD892.png" alt="2017-06-05_15_39_34_mov_1F2FD892.png"/>

**Comment by sr320** [comment]
via Megan
https://drive.google.com/drive/folders/0B1K316CGUQPiNW51Tzl0N2JvUXM
