### ISSUE TITLE
New computer for Sam

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#674]
Mac Pro is too old and all browsers are losing functionality. For example, as of today, I get a notice about browser incompatibility on GitHub and I can no longer set "Assignees" or "Labels" for GitHub issues now.

Haven't bother searching much, but here's a relatively (non-Mac) cheap option: https://smile.amazon.com/gp/offer-listing/B00T50QY1K/ref=dp_olp_refurbished_mbc?ie=UTF8&condition=refurbished

**Comment by kubu4** [comment]
OK, I purchased the computer linked above.

Thanks!

Which budget(s)?

**Comment by sr320** [comment]
61-0221
