### ISSUE TITLE
Even more gigas larvae stuff!

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#675]
[New totes](https://www.amazon.com/Rubbermaid-FG2550CPCYLND-Roughneck-Storage-50-Gallon/dp/B0030O6Z20/ref=pd_sbs_201_1?_encoding=UTF8&pd_rd_i=B0030O6Z20&pd_rd_r=DE9N7MNTDKZ901JZ2XQ3&pd_rd_w=qM7Ni&pd_rd_wg=Pny1y&psc=1&refRID=DE9N7MNTDKZ901JZ2XQ3) to replace the ones that cracked. I already checked a few hardware stores and they didn't have anything this big. (Quantity: 2-3)

[Immersion heaters](https://www.amazon.com/gp/product/B003GVT0V0/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1) to replace one that melted today + have a spare in case that happens again (Quantity: 2)

If possible, can we have these shipped to Manchester? I have PSRF's address:

7305 Beach Drive E
Port Orchard, WA 98366

**Comment by kubu4** [comment]
How many totes: 2 or 3?

**Comment by yaaminiv** [comment]
3 please!

**Comment by kubu4** [comment]
This is shipping directly to Manchester.

Also, please check the exterior and interior of the packages for packing slips.

If present, SIGN and DATE the packing slips, and then put the packing slips on my chair.
