### ISSUE TITLE
Geoduck Transcriptome plan

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#71]

**Comment by sr320** [comment]
Need to pick make and female samples

**Comment by sr320** [comment]
Sam is processing

**Comment by sr320** [comment]
just need to review and send..

**Comment by sr320** [comment]
@kubu4 is there a sheet with samples that are good to go and their stage?

**Comment by kubu4** [comment]
No sheet beyond what's in my notebook (and the Shellfish RNA Boxes Google Sheet). Having them run on Bioanalyzer this week to check quality.

**Comment by sr320** [comment]
![pic](http://eagle.fish.washington.edu/cnidarian/skitch/Shellfish_RNA_Boxes_-_Google_Sheets_1B151E2F.png)

**Comment by sr320** [comment]
Samples have been selected and @kubu4 will send off Monday to genewiz
see also 
http://onsnetwork.org/kubu4/2015/05/28/bioanalyzer-geoduck-gonad-rna-quality-assessment/
