### ISSUE TITLE
GBS Oly

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#79]

**Comment by sr320** [comment]
@kubu4 will check and see if 'risk factor' still in play

**Comment by sr320** [comment]
@kubu4 confirmed 'risk assessment' will be performed.

**Comment by kubu4** [comment]
Have PO number. Sample requirements for submission:
- >300ng per sample
- >25ng/uL per sample
- send at least 120 samples to compensate for potential low-quality (i.e. unusable) samples

**Comment by sr320** [comment]
Can we double what we send? - 2 120 samples?



—
Steven Roberts

**Comment by kubu4** [comment]
Yep!

**Comment by sr320** [comment]
So do we have plate + ready to go?

**Comment by sr320** [comment]
@jheare is compiling plates

**Comment by kubu4** [comment]
@jheare if you have these plates ready, could you please remind me where they are? If they aren't ready, could you please put them together sometime this week so I can send out on Monday (or sooner)?

**Comment by jheare** [comment]
@kubu4 I'll get them together and let you know where they are at.

**Comment by kubu4** [comment]
Thanks!

**Comment by sr320** [comment]
And just to confirm- We are doing 1 plate of sequencing, but providing extra in case samples are of poor quality.

**Comment by jheare** [comment]
I'm going to put the best quality samples in the sequencing plate and then
the second best in the extras plate.

**Comment by sr320** [comment]
thanks - provide a url to the plate layout here once its set-up

**Comment by jheare** [comment]
You can see the plate layout [here](https://github.com/jheare/Resilience-Project/blob/master/sequence-data/GBSSeqPlate.csv). There is a plate for sequencing and a back up samples plate that's about half the size. There's a couple fewer samples in the back up plate due to some errors in the spreadsheet that I didn't notice until I had already worked up the plate.

**Comment by kubu4** [comment]
Plates sent.

**Comment by sr320** [comment]
Curious if all DNA was sent or if we could do BS on these oyster too?

**Comment by jheare** [comment]
We should have over 100 ul of the DNA for each sample.

**Comment by sr320** [comment]
Report came back from BGI- My initial take was that nothing was good enough quality?

**Comment by kubu4** [comment]
They said that 61 samples (half of what was submitted) were seriously degraded. Since they didn't comment on the remaining sample qualities, I am interpretting this as meaning the remaining samples are useable.

**Comment by jheare** [comment]
Did they specify which samples?

**Comment by kubu4** [comment]
Yes.

**Comment by jheare** [comment]
I got your message. I'll look through the samples. @sr320 Should I make up
new aliquots of the low concentration DNA to send off?
