### ISSUE TITLE
List of all "Products" from Oly Grant....

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#84]
We need to come up with all "Products" from Oly Grant 
From beginning of grant ....

Heare JE, Blake B, Davis JP, Vadopalas B, Roberts SB. (2014) Evidence of Ostrea lurida (Carpenter 1894) population structure in Puget Sound, WA. PeerJ PrePrints 2:e704 http://dx.doi.org/10.7287/peerj.preprints.704

Jake Heare et al.. (2014). O. lurida Survey 2014. Zenodo. 10.5281/zenodo.13201

what else? - slides, videos, anything,......

**Comment by sr320** [comment]
@jheare - a reminder to list anything else - websites, videos, slides- anything. Your hands on workshop..

**Comment by jheare** [comment]
heareresearch.blogspot.com 
The Oly wiki Workshop -- [video](https://youtu.be/2a4LfaCV4ng) Thanks to Bonnie for the vid.

**Comment by jheare** [comment]
[PCSGA Annual Conference Presentation](https://docs.google.com/presentation/d/1bgM_sHAcKEWETDYKcnEH12y8QfWQhu9Jk73bpsDDB9s/edit?usp=sharing)

[Western Society for Naturalists Presentation](https://docs.google.com/presentation/d/1BeAZ2BbPNIahI6wvq3A4WCaQpyBcRIrRmE-2NsrITgo/edit?usp=sharing)

**Comment by jheare** [comment]
Heare, Jake; Roberts, Steven (2015): Ostrea lurida genome browser. figshare.
http://dx.doi.org/10.6084/m9.figshare.990143


Heare, Jake (2015): Ostrea lurida RADSeq Process. figshare.
http://dx.doi.org/10.6084/m9.figshare.1336051

Heare, Jake; Roberts, Steven (2014): Temperature Data from 4 sites in Puget Sound, WA (August 2013 to October 2014). figshare.
http://dx.doi.org/10.6084/m9.figshare.1252249

**Comment by jheare** [comment]
This [pic](https://lh6.googleusercontent.com/-dfdWIC8yFFs/U-VjVZtidaI/AAAAAAAAKMs/wqjNwaifcZM/w1460-h821-no/20140808_130447.jpg) of an oly brooding full of late development larvae gets a lot of traction as well. People like the visual for it.

**Comment by sr320** [comment]
Great point about pic! How about uploading to Figshare as media, with any description you can provide.

**Comment by jheare** [comment]
Definitely. I've got a lot of Oly brooding pics and several good field work pics. Would you like them all as a figshare repository?

**Comment by sr320** [comment]
might as well upload into single figshare
