### ISSUE TITLE
Wikispaces is full

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#86]
Storage
You are currently 1.41 GB over your plan's limit of 5 GB. You are out of space, take a look at our Private Label service, or contact us about getting more.

**Comment by kubu4** [comment]
I also noticed this a couple of months ago. Oddly, I think this is related to the Wiki Backup exports. Each export seems to count against the Wikispaces storage quota:

https://www.dropbox.com/s/d6dblzev5fmhk58/Screenshot%202015-04-07%2012.04.24.png?dl=0

**Comment by sr320** [comment]
We can delete these exports?

**Comment by kubu4** [comment]
Yes and no. Yes, we can delete them. However, Wikispaces always seems to retain the 10 most recent exports. As such, when I delete the oldest export, the next oldest replaces that one. Since we have weekly backups for the past n years, we'll never be able to delete them all..

**Comment by sr320** [comment]
Solution is to just ignore - but continue to not place any critical document on wikispaces (particulary if not visualized on page where it can be pdf'd)
