### ISSUE TITLE
310 Primer Orders

### ISSUE THREAD

**Issue by jheare** [sr320/LabDocs#94]
I'm going to list primers that need to be ordered for the 310 lab. Sam if you order them, please mention it as a comment and I'll close out this issue when they've all been added/ordered. 

First is Superoxide dismutase 
 EcSODfw, 5′ AGAGAATCCTGAGCTACAGC 3′ and EcSODrev, 5′ TGAGCAAAACTCTCTACAAGC 3′

**Comment by kubu4** [comment]
@jheare, please put in a spreadsheet. One column with primer name, the other column with sequence.
Remove "5'" and "3'" from sequence.
Thanks.

**Comment by jheare** [comment]
Can do. Do we have a primer order sheet on genefish or should I just go ahead and build one?

**Comment by kubu4** [comment]
Thanks for asking. Since these are for class, just make a new one.

**Comment by jheare** [comment]
The primer order sheet is [here](https://docs.google.com/spreadsheets/d/1_-FSgBnbkz6ufYDB7tDkPRrW33xzI6GIxl-oLJ0dIZw/edit?usp=sharing). I will be updating it this afternoon as I find the rest of the primer sequences.

**Comment by kubu4** [comment]
Let me know when you're finished updating it and I'll get them ordered.

**Comment by jheare** [comment]
The primers are good to go. I'll use the HSP70 and Actin I have upstairs since I know they work.

**Comment by sr320** [comment]
Reminder we need these by Friday






—
Steven Roberts

**Comment by kubu4** [comment]
@jheare primers are at Biochem Stores under Roberts Lab. Budget number to use is 751210.

**Comment by jheare** [comment]
Excellent. I'll pick them up today or tomorrow.
