### ISSUE TITLE
Oly Genome Sequencing

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#99]
We got the go ahead to request PO with out budget

**Comment by kubu4** [comment]
Cool. Does this also apply to geoduck genome sequencing project?

**Comment by sr320** [comment]
Yep - be sure to cc Kate and me on any requests

**Comment by sr320** [comment]
Stalled as BGI will not respond.

**Comment by sr320** [comment]
Ready and waiting on quality DNA

**Comment by sr320** [comment]
Quantity issues
